import Papa from 'papaparse';
export const sampleCSV='region,item,value\nEast,A,12\nWest,B,9\nEast,C,18\nWest,D,7\nNorth,E,11';
export function textLimit(value,limit=1048576){const s=String(value??'');if(new TextEncoder().encode(s).length>limit)throw Error('输入超过大小限制');return s;}
export function dataset(value){const p=Papa.parse(textLimit(value),{skipEmptyLines:'greedy',preview:5002});if(p.errors.length||p.meta.truncated||p.data.length>5001)throw Error('CSV 格式错误或超过 5000 行');const [header,...rows]=p.data;if(!header?.length||header.length>64||header.some(h=>!h.trim())||new Set(header).size!==header.length)throw Error('列名须非空且唯一，最多 64 列');if(rows.some(r=>r.length!==header.length))throw Error('CSV 列数不一致');return{header,rows};}
export function pivot(source,key,value,metric='sum'){
 const {header,rows}=dataset(source),ki=header.indexOf(key),vi=header.indexOf(value);if(ki<0||vi<0)throw Error('列名不存在');if(!['sum','mean','median','min','max','count'].includes(metric))throw Error('未知统计方式');const bins=new Map();
 for(const row of rows){const n=Number(row[vi]);if(metric!=='count'&&(!row[vi].trim()||!Number.isFinite(n)))throw Error('统计列包含非数值');const k=row[ki];if(!bins.has(k))bins.set(k,[]);bins.get(k).push(n);}
 const table=[[key,metric,'count'],...[...bins].map(([k,values])=>{const sorted=[...values].sort((a,b)=>a-b),sum=values.reduce((a,b)=>a+b,0),mid=Math.floor(values.length/2);const n={sum,mean:sum/values.length,median:values.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2,min:sorted[0],max:sorted.at(-1),count:values.length}[metric];if(!Number.isFinite(n))throw Error('统计值超出范围');return[k,n,values.length];})];return table;
}
export function pageSelection(value,count){const source=String(value).trim();if(!source)return Array.from({length:count},(_,i)=>i);const result=[];for(const part of source.split(',')){if(!/^\s*\d+(?:\s*-\s*\d+)?\s*$/.test(part))throw Error('页码格式：1,3,5-7');const [a,b=a]=part.trim().split('-').map(Number);if(a<1||b<1||a>count||b>count||Math.abs(a-b)>50)throw Error('页码越界');for(let n=a;a<=b?n<=b:n>=b;n+=a<=b?1:-1)result.push(n-1);if(result.length>50)throw Error('最多编排 50 页');}return result;}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function chartSVG(source,label,value,kind='bar'){
 const {header,rows}=dataset(source),li=header.indexOf(label),vi=header.indexOf(value);if(li<0||vi<0||!rows.length||rows.length>200)throw Error('请选择有效列；图表限 1–200 行');if(!['bar','line','scatter'].includes(kind))throw Error('未知图表类型');const values=rows.map(r=>{const n=Number(r[vi]);if(!r[vi].trim()||!Number.isFinite(n)||Math.abs(n)>1e15)throw Error('图表值须为有限数值');return n;});const min=Math.min(0,...values),max=Math.max(1,...values),span=max-min,x=i=>70+(i+.5)*740/rows.length,y=v=>380-(v-min)/span*300,zero=y(0),pts=values.map((v,i)=>`${x(i)},${y(v)}`).join(' ');
 const marks=values.map((v,i)=>kind==='bar'?`<rect x="${x(i)-Math.max(1,300/rows.length)}" y="${Math.min(zero,y(v))}" width="${Math.max(2,600/rows.length)}" height="${Math.max(.5,Math.abs(zero-y(v)))}" fill="#164dff"/>`:`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#164dff"/>`).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 460" width="900" height="460" role="img"><title>${escape(value)} / ${escape(label)}</title><rect width="900" height="460" fill="#f8fbff"/><path d="M60 60V390H830M60 ${zero}H830" fill="none" stroke="#56719a"/><text x="60" y="30" font-family="sans-serif" font-size="17" fill="#132345">${escape(value)}</text>${kind==='line'?`<polyline points="${pts}" fill="none" stroke="#164dff" stroke-width="2"/>`:''}${marks}${rows.filter((_,i)=>i%Math.max(1,Math.ceil(rows.length/12))===0).map(r=>{const i=rows.indexOf(r);return `<text x="${x(i)}" y="420" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#132345">${escape(r[li].slice(0,18))}</text>`;}).join('')}<text x="12" y="${y(max)}" font-size="10">${escape(max)}</text><text x="12" y="${y(min)}" font-size="10">${escape(min)}</text></svg>`;
}
export async function pipeline(source,recipe,signal){let output=textLimit(source);const steps=String(recipe).trim().split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!steps.length||steps.length>12)throw Error('流程须为 1–12 步');const trace=[];for(const name of steps){signal?.throwIfAborted();const before=new TextEncoder().encode(output).length;
 if(name==='trim')output=output.trim();else if(name==='uppercase')output=output.toUpperCase();else if(name==='lowercase')output=output.toLowerCase();else if(name==='sort')output=output.split(/\r?\n/).sort().join('\n');else if(name==='dedupe')output=[...new Set(output.split(/\r?\n/))].join('\n');else if(name==='json')output=JSON.stringify(JSON.parse(output),null,2);else if(name==='base64'){const {encodeBase64}=await import('../text/1.mjs');output=encodeBase64(output);}else if(name==='sha256')output=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(output)))].map(x=>x.toString(16).padStart(2,'0')).join('');else throw Error('未知步骤：'+name);output=textLimit(output,4194304);trace.push([name,before,new TextEncoder().encode(output).length]);}return{output,trace};}
export function shortestPath(points,edges,start=0,end=points.length-1){const d=points.map(()=>Infinity),prev=points.map(()=>-1),todo=new Set(points.map((_,i)=>i));d[start]=0;while(todo.size){const u=[...todo].sort((a,b)=>d[a]-d[b])[0];todo.delete(u);if(!Number.isFinite(d[u])||u===end)break;for(const [a,b]of edges){const v=a===u?b:b===u?a:-1;if(v<0||!todo.has(v))continue;const alt=d[u]+Math.hypot(points[u][0]-points[v][0],points[u][1]-points[v][1]);if(alt<d[v]){d[v]=alt;prev[v]=u;}}}if(!Number.isFinite(d[end]))return{distance:null,path:[]};const route=[];for(let p=end;p!==-1;p=prev[p])route.unshift(p);return{distance:d[end],path:route};}
