import {sampleCSV,textLimit,pivot,pageSelection,chartSVG,pipeline} from './model.mjs';
import Papa from 'papaparse';
const field=(key,label,value,type='textarea')=>({key,label,type,default:value}),file=(key,label,accept,multiple=false)=>({key,label,type:'file',accept,multiple});
const select=(key,label,options,value)=>({key,label,type:'select',default:value,options:options.map(([value,label])=>({value,label}))});
const result=(text,extra={})=>({text,extension:'txt',mime:'text/plain;charset=utf-8',...extra});
const json=x=>result(JSON.stringify(x,null,2),{extension:'json',mime:'application/json;charset=utf-8'});
const descriptor=(id,title,group,fields,run,note='')=>({id,title,group,fields,run,note,requirements:[],revision:'expand-1'});
async function bytes(file,signal,limit=16777216,allowEmpty=false){if(!file||!allowEmpty&&file.size<1||file.size>limit)throw Error('请选择文件，单文件限 16 MiB');signal?.throwIfAborted();const value=new Uint8Array(await file.arrayBuffer());signal?.throwIfAborted();return value;}
export const tools=[
 descriptor('sqlite','SQL 工作台','开发',[field('source','CSV / data',sampleCSV),field('sql','SQL','SELECT region, SUM(value) AS total FROM data GROUP BY region ORDER BY total DESC;')],async(input,context)=>{textLimit(input.sql);const {query}=await import('./sql.mjs');const value=await query(input,context),last=value.result.at(-1);return{...json(value.result),table:last?[last.columns,...last.values]:[]};},'浏览器内 SQLite；每次从 CSV 重建 data 表。'),
 descriptor('pivot','数据透视','计算',[field('source','CSV',sampleCSV),field('key','分组列','region','text'),field('value','数值列','value','text'),select('metric','统计',[['sum','求和'],['mean','均值'],['median','中位数'],['min','最小值'],['max','最大值'],['count','计数']],'sum')],async input=>{const table=pivot(input.source,input.key,input.value,input.metric);return result(Papa.unparse(table),{table,extension:'csv',mime:'text/csv;charset=utf-8'});}),
 descriptor('json-patch','JSON 补丁','开发',[field('left','原文','{"name":"OCV","items":[1,2]}'),field('right','目标 / Patch','{"name":"OCV","items":[1,3],"ready":true}'),select('action','操作',[['diff','生成 RFC 6902'],['apply','应用 Patch']],'diff')],async input=>{const mod=await import('fast-json-patch'),patch=mod.default||mod,source=JSON.parse(textLimit(input.left)),other=JSON.parse(textLimit(input.right));if(input.action==='apply'){if(!Array.isArray(other)||other.length>1000)throw Error('Patch 须为最多 1000 个操作的数组');return json(patch.applyPatch(source,other,true,false,true).newDocument);}if(input.action!=='diff')throw Error('未知操作');return json(source!==null&&other!==null&&typeof source==='object'&&typeof other==='object'?patch.compare(source,other):source===other?[]:[{op:'replace',path:'',value:other}]);}),
 descriptor('pdf-arrange','PDF 编排','文件',[file('first','PDF 1','.pdf,application/pdf'),field('pages','页码','1','text'),file('second','PDF 2（可选）','.pdf,application/pdf'),field('pages2','追加页码','','text')],async(input,{signal}={})=>{const {PDFDocument}=await import('pdf-lib'),output=await PDFDocument.create();for(const [f,order]of [[input.first,input.pages],[input.second,input.pages2]]){if(!f&&f===input.second)continue;const original=await PDFDocument.load(await bytes(f,signal));if(original.getPageCount()>500)throw Error('源 PDF 限 500 页');const indices=pageSelection(order,original.getPageCount());if(indices.length+output.getPageCount()>50)throw Error('输出最多 50 页');for(const page of await output.copyPages(original,indices))output.addPage(page);signal?.throwIfAborted();}if(!output.getPageCount())throw Error('没有输出页面');const blob=new Blob([await output.save()],{type:'application/pdf'});return result(`${output.getPageCount()} 页\n${blob.size} 字节`,{blob,extension:'pdf',mime:'application/pdf'});}),
 descriptor('contact-sheet','图片拼版','图片',[file('images','图片','image/png,image/jpeg,image/webp',true),field('columns','列数','3','number'),field('size','格宽','240','number'),select('fit','适配',[['contain','完整'],['cover','填满']],'contain')],async(input,{signal}={})=>{const files=input.images||[],cols=Number(input.columns),size=Number(input.size);if(!files.length||files.length>12||!Number.isInteger(cols)||cols<1||cols>6||!Number.isInteger(size)||size<64||size>800||!['contain','cover'].includes(input.fit))throw Error('1–12 张图片；1–6 列；格宽 64–800');if(files.reduce((n,f)=>n+f.size,0)>33554432)throw Error('图片总量限 32 MiB');const canvas=document.createElement('canvas');canvas.width=cols*size;canvas.height=Math.ceil(files.length/cols)*size;const c=canvas.getContext('2d');if(!c)throw Error('Canvas 不可用');c.fillStyle='#f6f9ff';c.fillRect(0,0,canvas.width,canvas.height);for(const [i,f]of files.entries()){if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('仅支持 PNG/JPEG/WebP');const raw=await bytes(f,signal);const {imageHeader}=await import('../img/size.mjs');const header=imageHeader(raw);if(header.mime!==f.type)throw Error('图片格式不一致');const bitmap=await createImageBitmap(f);try{if(bitmap.width>8192||bitmap.height>8192||bitmap.width*bitmap.height>16777216)throw Error('图片尺寸过大');const scale=(input.fit==='cover'?Math.max:Math.min)(size/bitmap.width,size/bitmap.height),x=(i%cols)*size,y=Math.floor(i/cols)*size;c.save();c.beginPath();c.rect(x,y,size,size);c.clip();c.drawImage(bitmap,x+(size-bitmap.width*scale)/2,y+(size-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);c.restore();}finally{bitmap.close();}signal?.throwIfAborted();}const blob=await new Promise((ok,no)=>canvas.toBlob(b=>b?ok(b):no(Error('导出失败')),'image/png'));return result(`${files.length} 张 · ${canvas.width} × ${canvas.height}`,{blob,previewBlob:blob,extension:'png',mime:'image/png'});}),
 descriptor('file-manifest','文件校验清单','检测',[file('files','文件','',true),select('action','操作',[['generate','生成 SHA-256'],['verify','核验清单']],'generate'),field('manifest','待核验清单','')],async(input,{signal}={})=>{const files=input.files||[];if(!files.length||files.length>24||files.reduce((n,f)=>n+f.size,0)>67108864||new Set(files.map(f=>f.name)).size!==files.length)throw Error('1–24 个不同名文件，总量限 64 MiB');const entries=[];for(const f of [...files].sort((a,b)=>a.name.localeCompare(b.name))){const data=await bytes(f,signal,16777216,true);entries.push({name:f.name,bytes:data.length,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(n=>n.toString(16).padStart(2,'0')).join('')});}if(input.action==='generate')return json({schema:'ocv.manifest.v1',algorithm:'SHA-256',files:entries});if(input.action!=='verify')throw Error('未知操作');const expected=JSON.parse(textLimit(input.manifest));if(!expected||expected.schema!=='ocv.manifest.v1'||expected.algorithm!=='SHA-256'||!Array.isArray(expected.files)||expected.files.length>24||expected.files.some(f=>!f||typeof f.name!=='string'||!Number.isSafeInteger(f.bytes)||f.bytes<0||typeof f.sha256!=='string'||!/^[a-f0-9]{64}$/.test(f.sha256))||new Set(expected.files.map(f=>f.name)).size!==expected.files.length)throw Error('清单格式错误');const names=new Set([...entries,...expected.files].map(f=>f.name)),check=[...names].map(name=>{const a=entries.find(f=>f.name===name),b=expected.files.find(f=>f.name===name);return{name,match:!!a&&!!b&&a.bytes===b.bytes&&a.sha256===b.sha256};});return json({match:check.every(x=>x.match),files:check});}),
 descriptor('pipeline','处理流程','文本',[field('source','输入','  Civilisation\ncivilisation\nCivilisation  '),field('recipe','步骤','trim\nlowercase\ndedupe\nsort\nsha256')],async(input,{signal}={})=>{const value=await pipeline(input.source,input.recipe,signal);return result(value.output,{table:[['步骤','输入字节','输出字节'],...value.trace]});},'trim · uppercase · lowercase · sort · dedupe · json · base64 · sha256'),
 descriptor('svg-chart','矢量图表','科学',[field('source','CSV',sampleCSV),field('label','标签列','item','text'),field('value','数值列','value','text'),select('kind','图形',[['bar','柱状'],['line','折线'],['scatter','散点']],'bar')],async input=>{const svg=chartSVG(input.source,input.label,input.value,input.kind);return result(svg,{html:svg,blob:new Blob([svg],{type:'image/svg+xml'}),extension:'svg',mime:'image/svg+xml'});})
];
