<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../config/parts/1.cs" Link="Inventory.cs" /><Compile Include="../../config/2/1.cs" Link="old/Stock.cs" /><Compile Include="../../pcakage/report2/old.cs" Link="config/2.cs" /></ItemGroup></Project>
