(in-package #:printshop/common2)

(defun reservation-key (order-id paper-id)
  (format nil "~A@~A" order-id paper-id))

(defun reserved-sheets (shop paper-id)
  (let ((sum 0))
    (maphash (lambda (key reservation)
               (declare (ignore key))
               (when (equal paper-id (first reservation))
                 (incf sum (second reservation))))
             (shop-order-items shop))
    sum))

(defun reserve-paper (shop order-id paper-id quantity)
  (require-positive-integer quantity 'reserved-sheets)
  (let* ((p (or (gethash paper-id (shop-papers shop)) (error "Unknown paper")))
         (key (reservation-key order-id paper-id))
         (previous (gethash key (shop-order-items shop)))
         (already (if previous (second previous) 0))
         (free (+ (- (paper-available p) (reserved-sheets shop paper-id)) already)))
    (unless (<= quantity free) (error "Insufficient unreserved paper"))
    (setf (gethash key (shop-order-items shop)) (list paper-id quantity order-id))
    quantity))

(defun consume-reservation (shop order-id paper-id actual)
  (let* ((key (reservation-key order-id paper-id))
         (reservation (or (gethash key (shop-order-items shop)) (error "Reservation absent")))
         (p (gethash paper-id (shop-papers shop))))
    (unless (<= 0 actual (second reservation)) (error "Consumption exceeds reserved paper"))
    (decf (paper-available p) actual)
    (remhash key (shop-order-items shop))
    (list :consumed actual :released (- (second reservation) actual))))

(defun stock-audit (shop)
  (let ((issues nil))
    (maphash (lambda (id p)
               (when (> (reserved-sheets shop id) (paper-available p))
                 (push (list id :over-reserved) issues)))
             (shop-papers shop))
    (nreverse issues)))
