import {testDeps} from '../runtime-location.mjs';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as sleep} from 'node:timers/promises';
import {docker,composeArguments,dockerEnvironment} from '../../scripts/docker-child.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
try{process.loadEnvFile(join(root,'.env'))}catch(error){if(error.code!=='ENOENT')throw error}
const base=new URL(process.env.OCV_SHARED_BASE_URL||`http://127.0.0.1:${process.env.OCV_WEB_PORT||8080}`);
if(base.protocol!=='http:'||base.username||base.password||!['localhost','127.0.0.1','[::1]'].includes(base.hostname))throw Error('The AMQP proof uses a private loopback entrance');
const deps=testDeps,stateRoot=join(deps,'runtime/after-runner'),reportFile=join(deps,'runtime/reports/phase12-sh1-amqp.json');
const stamp=new Date().toISOString().replace(/[:.]/g,'-'),deadline=Date.now()+180000;
const report={schema:'ocv.sh1/amqp-proof/1',startedAt:new Date().toISOString(),passed:false,checks:[],maximumJobs:1,maximumHostWorkers:1,maximumPollMs:180000,sqlMutations:false,manualServerActions:false,privateCapabilitiesPrinted:false,limitations:['This proves one confirmed RabbitMQ handoff with PostgreSQL inbox readback; it does not inject broker partitions or claim exactly-once delivery.','Broker management is not enabled on the existing alpine service; no queue-management evidence is fabricated.','The private saved project snapshot remains under the existing bounded project retention policy.']};
let cap,saved,owned,beforeServices=new Set(),cleaning=false;
const project=process.env.COMPOSE_PROJECT_NAME||'omnicivitas',compose=composeArguments([]);
const dockerEnv=dockerEnvironment();
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
const hash=value=>createHash('sha256').update(canonical(value)).digest('hex');
const fixture={schema:'ocv.signals-project/1',name:'amqp-'+randomUUID().slice(0,8),drawing:{components:[{id:'V1',kind:'V',x:230,y:260,rotation:90,value:5},{id:'R1',kind:'R',x:450,y:150,rotation:0,value:1000},{id:'R2',kind:'R',x:670,y:260,rotation:90,value:1000},{id:'G1',kind:'GND',x:230,y:390,rotation:0,value:0}],wires:[{id:'w1',from:{component:'V1',pin:'a'},to:{component:'R1',pin:'a'}},{id:'w2',from:{component:'V1',pin:'b'},to:{component:'G1',pin:'a'}},{id:'w3',from:{component:'R1',pin:'b'},to:{component:'R2',pin:'a'}},{id:'w4',from:{component:'R2',pin:'b'},to:{component:'G1',pin:'a'}}]},analysis:{kind:'dc',fStart:10,fStop:100000,points:64,durationS:.01,stepS:.000025},communication:{bits:'0100111001100101',seed:1234,ebN0Db:0,samplesPerSymbol:4,sampleRateHz:8000},instruments:{probe:'out',cursor:0}};

async function command(args,input,useCompose=true){
 return new Promise((done,fail)=>{const child=spawn(docker,[...(useCompose?compose:[]),...args],{cwd:root,env:{...process.env,...dockerEnv,COMPOSE_PARALLEL_LIMIT:'1',COMPOSE_PROFILES:''},windowsHide:true,stdio:['pipe','pipe','pipe']});let text='',bytes=0,problem='',settled=false;const timer=setTimeout(()=>{problem='The read-only AMQP evidence helper timed out';child.kill()},12000);child.stdin.on('error',()=>{});child.stdin.end(input);child.stdout.on('data',chunk=>{bytes+=chunk.length;if(bytes>65536){problem='AMQP evidence exceeded 64 KiB';child.kill()}else text+=chunk.toString('utf8')});child.stderr.on('data',()=>{});child.once('error',()=>{clearTimeout(timer);settled=true;fail(Error('The AMQP evidence helper could not start'))});child.once('close',code=>{clearTimeout(timer);if(settled)return;settled=true;if(code!==0||problem)fail(Error(problem||'The read-only AMQP evidence helper failed'));else done(text)});});
}
async function services(){return new Set((await command(['ps','--filter','label=com.docker.compose.project='+project,'--format','{{.Label "com.docker.compose.service"}}'],undefined,false)).trim().split(/\s+/).filter(Boolean))}
const captureCode=`const {Client}=require('pg');let raw='';process.stdin.on('data',b=>raw+=b);process.stdin.on('end',async()=>{const p=JSON.parse(raw),db=new Client({connectionString:process.env.DATABASE_URL,connectionTimeoutMillis:1200,statement_timeout:2000});try{await db.connect();const state=(await db.query("SELECT count(*) FILTER(WHERE state='queued')::int AS queued,count(*) FILTER(WHERE state IN('starting','running'))::int AS active FROM ocv_after.jobs")).rows[0],lease=(await db.query('SELECT owner,lease_until>now() AS leased FROM ocv_after.worker WHERE id=1')).rows[0];if(p.id){if(!/^[-a-f0-9]{36}$/.test(p.id))throw Error('id');const job=(await db.query('SELECT id,state,family,phase,result FROM ocv_after.jobs WHERE id=$1',[p.id])).rows[0],outbox=(await db.query('SELECT seq,event_key,kind,payload_sha,attempts,delivery FROM ocv_shared1.dispatch_outbox WHERE job_id=$1 ORDER BY seq',[p.id])).rows,inbox=(await db.query('SELECT event_seq,payload_sha,transport FROM ocv_shared1.delivery_inbox WHERE job_id=$1 ORDER BY event_seq',[p.id])).rows;console.log(JSON.stringify({...state,lease,job,outbox,inbox}));}else console.log(JSON.stringify({...state,lease}));}catch{process.exitCode=1}finally{await db.end().catch(()=>{})}});`;
const capture=async()=>JSON.parse(await command(['exec','-T','-w','/workspace/services/gateway','gateway','node','-e',captureCode],JSON.stringify(cap?{id:cap.id}:{})));
async function post(path,body){assert.ok(cleaning||Date.now()<deadline,'AMQP proof has a three-minute overall deadline');const response=await fetch(new URL(path,base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});assert.ok(response.ok,`Test-owned public HTTP ${response.status}`);const text=await response.text();assert.ok(Buffer.byteLength(text)<=65536,'Test-owned public JSON is bounded');return JSON.parse(text)}
const read=()=>post(`/api/shared/jobs/${cap.id}/read`,{ticket:cap.ticket});
async function check(name,fn){const started=Date.now();try{const evidence=await fn();report.checks.push({name,passed:true,elapsedMs:Date.now()-started,...evidence})}catch(error){report.checks.push({name,passed:false,elapsedMs:Date.now()-started,error:String(error.message).slice(0,220)});throw error}}
async function until(fn,message,maximumMs=150000){const end=cleaning?Date.now()+maximumMs:Math.min(deadline,Date.now()+maximumMs);while(Date.now()<end){const value=await fn();if(value)return value;await sleep(250)}throw Error(message)}
async function preservePrevious(path,label){try{const previous=await readFile(path),backup=join(deps,`runtime/reports/phase12-sh1-amqp-${label}-${stamp}.json`);assert.ok(previous.length<=1048576,'Prior report backup is bounded');await writeFile(backup,previous,{mode:0o600,flag:'wx'});return backup}catch(error){if(error.code==='ENOENT')return null;throw error}}
async function startWorker(){
 assert.ok(!owned,'Only one test-owned host worker');report.previousWorkerReport=await preservePrevious(join(stateRoot,'latest-report.json'),'previous-worker');
 const child=spawn(process.execPath,['--max-old-space-size=192',join(root,'scripts/after-runner.mjs'),'--drain'],{cwd:root,env:{...process.env,OCV_SHARED_AMQP:'1',OCV_RUNNER_MAX_CONCURRENCY:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']});
 owned={child,pid:child.pid,exit:null,log:''};const state=owned;state.closed=new Promise(done=>{child.once('error',()=>{state.exit={code:null,error:'The owned AMQP worker could not start'};done(state.exit)});child.once('close',(code,signal)=>{state.exit={code,signal};done(state.exit)})});const append=chunk=>{state.log=(state.log+chunk.toString('utf8')).slice(-16384)};child.stdout.on('data',append);child.stderr.on('data',append);report.ownedWorker={pid:child.pid};await writeFile(join(stateRoot,'phase12-amqp-owned-pid.json'),JSON.stringify({pid:child.pid,job:cap.id}),{mode:0o600});
}
async function saveWorker(){if(!owned)return;const logFile=join(deps,'runtime/logs/phase12-sh1-amqp-worker.log');await mkdir(dirname(logFile),{recursive:true});await writeFile(logFile,owned.log,{mode:0o600});Object.assign(report.ownedWorker,{exit:owned.exit,log:logFile})}
async function stopOwned(){if(!owned||owned.exit)return;await writeFile(join(stateRoot,'stop'),'stop\n',{mode:0o600});await until(()=>owned.exit,'The owned AMQP worker did not finish its ordinary stop path',45000);await owned.closed}

try{
 await mkdir(dirname(reportFile),{recursive:true});await mkdir(stateRoot,{recursive:true});report.previousAmqpReport=await preservePrevious(reportFile,'previous-proof');
 await check('Core is idle and Spring is stopped before the explicitly enabled AMQP worker',async()=>{const state=await capture();assert.equal(state.queued,0);assert.equal(state.active,0);assert.equal(state.lease.leased,false);beforeServices=await services();assert.equal(beforeServices.has('spring'),false,'A running Spring instance could retain AMQP=0');for(const service of ['edge','gateway','portal','next','postgres','redis'])assert.ok(beforeServices.has(service),'The six core services must already be running');return{queued:0,active:0,leased:false,springStopped:true}});
 await check('One canonical signals snapshot queues only one public Go versions operation',async()=>{saved=await post('/api/signals/projects',{project:fixture});assert.equal(saved.revision,1);assert.equal(saved.digest,hash(fixture));const accepted=await post('/api/shared/operations',{action:'versions',domain:'signals',project:saved.id,ticket:saved.ticket,operationId:randomUUID()});assert.ok(accepted.id&&accepted.ticket);assert.equal(accepted.state,'queued');cap={id:accepted.id,ticket:accepted.ticket};report.job=cap.id;report.project={id:saved.id,digest:saved.digest,revision:1};await startWorker();return{id:cap.id,oneJob:true,projectDigest:saved.digest}});
 await check('The sole host worker completes the real operation with a confirmed RabbitMQ handoff',async()=>{const done=await until(async()=>{const row=await read();if(row.state==='failed'||row.state==='cancelled')throw Error('The AMQP operation became terminal without successful handoff');if(owned.exit&&row.state!=='done')throw Error('The owned AMQP worker exited before canonical completion');return row.state==='done'?row:false},'The bounded AMQP versions operation did not complete');assert.equal(done.family,'shared');assert.equal(done.shared.operationResult.headRevision,1);assert.equal(done.shared.operationResult.versions[0].digest,saved.digest);const outbox=done.result.shared.outbox;assert.equal(outbox.transport,'rabbitmq-confirmed');assert.equal(outbox.brokerConfirmed,true);assert.equal(outbox.pending,0);assert.ok(outbox.delivered>=3);report.publicReceipt={transport:outbox.transport,brokerConfirmed:outbox.brokerConfirmed,pending:outbox.pending,delivered:outbox.delivered};return{headRevision:1,sourceDigest:saved.digest,transport:outbox.transport,brokerConfirmed:true,pending:0}});
 await check('PostgreSQL proves all three published task events arrived through the confirmed inbox',async()=>{const state=await capture();assert.equal(state.job.state,'done');assert.equal(state.outbox.length,3);assert.equal(state.inbox.length,3);assert.ok(state.outbox.every(row=>row.delivery==='delivered'&&row.attempts>=1));assert.equal(new Set(state.inbox.map(row=>row.event_seq)).size,3);for(const row of state.inbox){const event=state.outbox.find(item=>item.seq===row.event_seq);assert.ok(event);assert.equal(row.payload_sha,event.payload_sha);assert.equal(row.transport,'rabbitmq-confirmed');assert.match(row.payload_sha,/^[a-f0-9]{64}$/)}report.inboxEvidence=state.inbox.map(row=>({seq:row.event_seq,sha:row.payload_sha,transport:row.transport}));return{outboxRows:3,inboxRows:3,publishAttemptsObserved:true,checksumsEqual:true}});
 await check('The bounded drain exits and releases its lease and newly owned optional containers',async()=>{await until(()=>owned.exit,'The owned AMQP drain did not exit',45000);await owned.closed;assert.equal(owned.exit.code,0);await saveWorker();const bytes=await readFile(join(stateRoot,'latest-report.json'));assert.ok(bytes.length<=1048576);const host=JSON.parse(bytes);assert.equal(host.effectiveConcurrency,1);assert.ok(host.completed.some(row=>row.id===cap.id&&row.shared?.outbox?.brokerConfirmed===true));assert.equal(host.failed.length,0);report.ownedWorker.worker=host.worker;const state=await capture();assert.equal(state.lease.leased,false);assert.equal(state.active,0);assert.equal(state.queued,0);const after=await services(),newOptional=[...after].filter(name=>!beforeServices.has(name));assert.deepEqual(newOptional,[]);return{effectiveConcurrency:1,leaseReleased:true,newOptionalRunning:[]}});
 report.passed=true;
}catch(error){report.error=String(error.message).slice(0,300);process.exitCode=1}
finally{
 cleaning=true;
 if(cap&&!report.passed){try{if(['queued','starting','running'].includes((await read()).state))await post(`/api/shared/jobs/${cap.id}/cancel`,{ticket:cap.ticket})}catch{report.cleanupIncomplete=true}}
 try{await stopOwned()}catch{report.cleanupIncomplete=true;if(owned&&!owned.exit){owned.child.kill();await Promise.race([owned.closed,sleep(5000)])}}
 await saveWorker().catch(()=>{report.cleanupIncomplete=true});
 if(owned&&!owned.exit)report.cleanupIncomplete=true;
 if(cap){try{const state=await capture();report.cleanup={state:state.job?.state,leased:state.lease.leased,ownLease:state.lease.owner===report.ownedWorker?.worker&&state.lease.leased,liveOwnedWorker:!!owned&&!owned.exit};if(['queued','starting','running'].includes(state.job?.state)||state.lease.leased)report.cleanupIncomplete=true}catch{report.cleanupIncomplete=true}}
 if(report.cleanupIncomplete){report.passed=false;process.exitCode=1}report.finishedAt=new Date().toISOString();await writeFile(reportFile,JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,file:reportFile}));
}
