import {testDeps} from '../runtime-location.mjs';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as sleep} from 'node:timers/promises';
import {docker,composeArguments,dockerEnvironment} from '../../scripts/docker-child.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
try{process.loadEnvFile(join(root,'.env'))}catch(error){if(error.code!=='ENOENT')throw error}
const base=new URL(process.env.OCV_SHARED_BASE_URL||`http://127.0.0.1:${process.env.OCV_WEB_PORT||8080}`);
if(base.protocol!=='http:'||base.username||base.password||!['localhost','127.0.0.1','[::1]'].includes(base.hostname))throw Error('The SH1 control proof uses a private loopback entrance');
const deps=testDeps;
const reportFile=join(deps,'runtime/reports/phase12-sh1-controls.json'),worker=randomUUID(),deadline=Date.now()+180000;
const report={schema:'ocv.sh1/control-proof/1',startedAt:new Date().toISOString(),passed:false,checks:[],jobs:[],worker,maximumFixtures:3,maximumHostRunnerProcesses:0,startsServices:false,sqlMutations:false,privateCapabilitiesPrinted:false,scope:'Finite synthetic metadata task plan over explicitly submitted real note fixtures; no claim that a full music report, solver or artifact pipeline ran.',limitations:['Priority is read at its real default zero. There is no public priority mutation API, so higher-priority selection is not tested.','Transient faults are explicitly injected through the task failure/retry APIs; real process interruption is covered separately by recovery.mjs.','Optional RabbitMQ publisher confirmations are outside this database-outbox control proof.']};
const owned=new Map(),sessionA=randomUUID(),sessionB=randomUUID();let a1,a2,b1,successfulSha,leaseOwned=false,cleaning=false;
const plan=[{key:'s0',phase:0,depends:[]},{key:'s1',phase:1,depends:['s0']},{key:'s2',phase:2,depends:['s1']}];
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
const digest=value=>createHash('sha256').update(canonical(value)).digest('hex');
const compose=composeArguments([]);
const dockerEnv=dockerEnvironment();

// The fixed container helper reads its runner credential from its environment; it never serializes it.
const helper=`const {Client}=require('pg');let raw='';process.stdin.on('data',b=>raw+=b);process.stdin.on('end',async()=>{let db;try{const p=JSON.parse(raw);if(p.op==='capture'){if(!Array.isArray(p.ids)||p.ids.length>3||p.ids.some(id=>!/^[-a-f0-9]{36}$/.test(id)))throw Error('ids');db=new Client({connectionString:process.env.DATABASE_URL,connectionTimeoutMillis:1200,statement_timeout:2000});await db.connect();const state=(await db.query("SELECT count(*) FILTER(WHERE state='queued')::int AS queued,count(*) FILTER(WHERE state IN('starting','running'))::int AS active FROM ocv_after.jobs")).rows[0];const lease=(await db.query('SELECT owner,lease_until>now() AS leased FROM ocv_after.worker WHERE id=1')).rows[0];const jobs=p.ids.length?(await db.query('SELECT j.id,j.seq,j.state,j.phase,j.result,b.owner_bucket,b.priority,b.attempts,b.max_attempts,b.plan_sha,b.available_at FROM ocv_after.jobs j JOIN ocv_shared1.task_books b ON b.job_id=j.id WHERE j.id=ANY($1::uuid[]) ORDER BY j.seq',[p.ids])).rows:[];const steps=p.ids.length?(await db.query('SELECT job_id,key2.step_key AS key,key2.ordinal AS phase,key2.status,key2.attempts,key2.result_sha AS sha,key2.result FROM ocv_shared1.cash_book key2 WHERE job_id=ANY($1::uuid[]) ORDER BY job_id,ordinal',[p.ids])).rows:[];const events=p.ids.length?(await db.query('SELECT job_id,seq,event_key,kind,payload_sha,delivery FROM ocv_shared1.dispatch_outbox WHERE job_id=ANY($1::uuid[]) ORDER BY seq',[p.ids])).rows:[];const inbox=p.ids.length?(await db.query('SELECT job_id,event_seq,payload_sha,transport FROM ocv_shared1.delivery_inbox WHERE job_id=ANY($1::uuid[]) ORDER BY event_seq',[p.ids])).rows:[];console.log(JSON.stringify({...state,lease,jobs,steps,events,inbox}));}else if(p.op==='http'){const urls={worker:'http://gateway:3000/api/a2/worker.cgi',task:'http://spring:8081/shared/invoice.php',outbox:'http://spring:8081/shared/outbox.asm',shared:'http://gateway:3000/api/shared/internal',health:'http://spring:8081/shared/tasks/health'};if(!urls[p.target])throw Error('target');const headers={'Content-Type':'application/json'},configured=process.env.OCV_RUNNER_KEY||'';if(p.keyMode!=='none')headers['X-Ocv-Runner']=p.keyMode==='wrong'?configured.slice(0,-1)+(configured.endsWith('0')?'1':'0'):configured;const response=await fetch(urls[p.target],{method:p.target==='health'?'GET':'POST',headers,body:p.target==='health'?undefined:JSON.stringify(p.body),signal:AbortSignal.timeout(8000)});let text='',bytes=0;const decoder=new TextDecoder();for await(const chunk of response.body){bytes+=chunk.length;if(bytes>65536)throw Error('bound');text+=decoder.decode(chunk,{stream:true})}text+=decoder.decode();let body;try{body=JSON.parse(text)}catch{body=null}console.log(JSON.stringify({status:response.status,body}));}else throw Error('op');}catch{process.exitCode=1}finally{if(db)await db.end().catch(()=>{})}});`;
async function internal(input){
 assert.ok(cleaning||Date.now()<deadline,'The control proof has a three-minute overall deadline');
 return new Promise((done,fail)=>{const child=spawn(docker,[...compose,'exec','-T','-w','/workspace/services/gateway','gateway','node','-e',helper],{cwd:root,env:{...process.env,...dockerEnv,COMPOSE_PARALLEL_LIMIT:'1',COMPOSE_PROFILES:''},windowsHide:true,stdio:['pipe','pipe','pipe']});let text='',bytes=0,problem='',settled=false;const timer=setTimeout(()=>{problem='The bounded private evidence helper timed out';child.kill()},12000);child.stdin.on('error',()=>{});child.stdin.end(JSON.stringify(input));child.stdout.on('data',chunk=>{bytes+=chunk.length;if(bytes>65536){problem='Private evidence exceeded 64 KiB';child.kill()}else text+=chunk.toString('utf8')});child.stderr.on('data',()=>{});child.once('error',()=>{clearTimeout(timer);settled=true;fail(Error('The private evidence helper could not start'))});child.once('close',code=>{clearTimeout(timer);if(settled)return;settled=true;if(code!==0||problem)fail(Error(problem||'The private evidence helper failed; ensure core and Spring are already running'));else{try{done(JSON.parse(text))}catch{fail(Error('The private evidence helper returned invalid bounded JSON'))}}});});
}
const capture=()=>internal({op:'capture',ids:[...owned.keys()]});
async function privateCall(target,body,statuses=[200,201],keyMode){const response=await internal({op:'http',target,body,keyMode});assert.ok(statuses.includes(response.status),`Unexpected ${target} HTTP ${response.status}`);return response.body}
const control=(action,extra={},statuses=[200,201])=>privateCall('worker',{worker,action,...extra},statuses);
const task=(action,extra={},statuses=[200,201],who=worker,keyMode)=>privateCall('task',{job:a1.id,worker:who,action,...extra},statuses,keyMode);
async function post(path,body){assert.ok(cleaning||Date.now()<deadline,'Bounded control proof deadline');const response=await fetch(new URL(path,base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});assert.ok(response.ok,`Public fixture HTTP ${response.status}`);const text=await response.text();assert.ok(Buffer.byteLength(text)<=65536,'Fixture response is bounded');return JSON.parse(text)}
const read=cap=>post(`/api/shared/jobs/${cap.id}/read`,{ticket:cap.ticket});
async function submit(session,pitch){assert.ok(owned.size<3,'At most three private fixtures');const response=await post('/api/q8/music',{session,tempo:100,events:[{n:pitch,t:0,d:120,v:.6},{n:pitch+2,t:60,d:150,v:.7},{n:pitch+4,t:160,d:100,v:.5}]});assert.ok(response.job?.id&&response.ticket);assert.equal(response.job.family,'music-report');assert.equal(response.storage,'postgresql');const cap={id:response.job.id,ticket:response.ticket};owned.set(cap.id,cap);report.jobs.push({id:cap.id,sourceDigest:response.sha});return cap}
async function check(name,fn){const started=Date.now();try{const evidence=await fn();report.checks.push({name,passed:true,elapsedMs:Date.now()-started,...evidence})}catch(error){report.checks.push({name,passed:false,elapsedMs:Date.now()-started,error:String(error.message).slice(0,220)});throw error}}
async function claimOnly(cap){const end=Math.min(deadline,Date.now()+40000);while(Date.now()<end){const response=await control('claim');if(response.job){assert.equal(response.job.id,cap.id,'Claim must remain on the expected test-owned fixture');return response.job}assert.ok(response.queuedPending>0,'The delayed fixture must remain queued');const remaining=Date.parse(response.nextAvailableAt||'')-Date.now();await sleep(Number.isFinite(remaining)?Math.max(100,Math.min(1000,remaining)):250)}throw Error('The bounded delayed fixture did not become eligible')}
async function cancel(cap){const reply=await post(`/api/shared/jobs/${cap.id}/cancel`,{ticket:cap.ticket});assert.equal(reply.cancelled,true);assert.equal((await read(cap)).state,'cancelled')}

try{
 await mkdir(dirname(reportFile),{recursive:true});
 await check('Core is idle, the canonical lease is expired, and Java is already available',async()=>{const before=await capture();assert.equal(before.queued,0);assert.equal(before.active,0);assert.equal(before.lease.leased,false);assert.equal((await privateCall('health',undefined)).contract,'ocv.shared-task/1');return{queued:0,active:0,leased:false,noServicesStarted:true}});
 await check('Incorrect or absent private credentials do not acquire a worker lease',async()=>{await privateCall('worker',{worker,action:'heartbeat'},[404],'wrong');await privateCall('worker',{worker,action:'heartbeat'},[404],'none');assert.equal((await capture()).lease.leased,false);return{wrongHeader:404,missingHeader:404,leaseUnchanged:true}});
 await check('Three explicit recordings create two real owner groups and one canonical lease',async()=>{a1=await submit(sessionA,60);a2=await submit(sessionA,62);b1=await submit(sessionB,64);const state=await capture();assert.equal(state.jobs.length,3);assert.ok(state.jobs.every(row=>row.state==='queued'&&row.attempts===0&&row.priority===0));assert.equal(state.jobs.find(row=>row.id===a1.id).owner_bucket,sessionA);assert.equal(state.jobs.find(row=>row.id===a2.id).owner_bucket,sessionA);assert.equal(state.jobs.find(row=>row.id===b1.id).owner_bucket,sessionB);const hello=await control('heartbeat');leaseOwned=true;assert.equal(hello.canContinue,true);const claimed=await control('claim');assert.equal(claimed.job.id,a1.id);await privateCall('worker',{worker:randomUUID(),action:'heartbeat'},[409]);return{fixtures:3,ownerGroups:2,claimed:a1.id,competingUuid:409}});
 await check('Java rejects wrong credentials and a nonowner UUID without changing the claimed task',async()=>{await task('prepare',{steps:plan},[404],worker,'wrong');await task('prepare',{steps:plan},[404],worker,'none');await task('prepare',{steps:plan},[409],randomUUID());const state=await capture(),row=state.jobs.find(item=>item.id===a1.id);assert.equal(row.state,'starting');assert.equal(row.attempts,1);assert.equal(row.plan_sha,null);assert.equal(state.steps.length,0);return{wrongHeader:404,missingHeader:404,wrongLease:409,planNotCreated:true}});
 await check('Prepare is idempotent, changed plans conflict, and prerequisites gate real step start',async()=>{const first=await task('prepare',{steps:plan});assert.equal(first.ok,true);assert.equal(first.duplicate,false);assert.equal((await task('prepare',{steps:plan})).duplicate,true);const changed=structuredClone(plan);changed[1].depends=[];await task('prepare',{steps:changed},[409]);await task('stepbegin',{step:'s1'},[409]);const started=await task('stepbegin',{step:'s0'});assert.equal(started.alreadyStarted,false);assert.equal((await task('stepbegin',{step:'s0'})).alreadyStarted,true);return{planSha:first.planSha,duplicatePlan:true,changedPlan:409,blockedStep:409,duplicateBegin:true}});
 await check('A checkpoint comes from real frozen notes and exact replay preserves its checksum',async()=>{const frozen=await privateCall('shared',{id:a1.id,worker,action:'input',view:'dataset'});assert.equal(frozen.dataset.kind,'music');assert.equal(frozen.dataset.submitted,true);assert.equal(frozen.dataset.notes.length,3);const result={schema:'ocv.test.task-control/1',sourceDigest:frozen.source.digest,noteCount:frozen.dataset.notes.length,scope:'finite note metadata only'};const first=await task('checkpoint',{step:'s0',result});successfulSha=first.resultSha;assert.equal(successfulSha,digest(result));assert.equal(first.duplicate,false);const duplicate=await task('checkpoint',{step:'s0',result});assert.equal(duplicate.duplicate,true);assert.equal(duplicate.resultSha,successfulSha);await task('checkpoint',{step:'s0',result:{...result,noteCount:4}},[409]);const state=await capture(),row=state.steps.find(item=>item.job_id===a1.id&&item.key==='s0');assert.equal(row.sha,successfulSha);assert.deepEqual(row.result,result);assert.equal(row.attempts,1);assert.equal(state.events.filter(item=>item.job_id===a1.id).length,2);return{sourceDigest:frozen.source.digest,resultSha:successfulSha,duplicateCheckpoint:true,changedCheckpoint:409,events:2}});
 await check('Only an explicitly transient failure requeues the same job; owner fairness selects B before A2',async()=>{await task('stepbegin',{step:'s1'});const failure=await task('failure',{step:'s1',code:'service_unavailable'});assert.equal(failure.retry.retryable,true);assert.equal(failure.canonicalStateMutated,false);await control('retry',{job:a1.id,phase:1,result:{code:'version_conflict',scope:'rejected permanent retry probe'},code:'version_conflict',delaySeconds:1},[400]);assert.equal((await read(a1)).state,'starting');const scheduled=await control('retry',{job:a1.id,phase:1,result:{code:'service_unavailable',scope:'explicit injected transient control probe'},code:'service_unavailable',delaySeconds:1});assert.equal(scheduled.retried,true);assert.equal(scheduled.attempts,1);assert.equal((await read(a1)).state,'queued');const fair=await control('claim');assert.equal(fair.job.id,b1.id,'An owner without a recent claim must precede the second already-claimed owner fixture');return{sameJob:a1.id,requeued:true,permanentRetryRejected:400,nextOwner:sessionB,earlierA2StillQueued:(await read(a2)).state==='queued'}});
 await check('Queued and active fixture cancellation uses owner tickets without a running host dispatcher',async()=>{assert.equal((await read(a2)).state,'queued');await cancel(a2);await cancel(b1);const state=await capture();assert.equal(state.active,0);assert.equal(state.queued,1);assert.ok(state.jobs.filter(row=>row.id!==a1.id).every(row=>row.state==='cancelled'));return{queuedCancelled:a2.id,activeCancelled:b1.id,noHostRunner:true}});
 await check('A later canonical attempt reuses completed bytes and observes real retry availability',async()=>{await claimOnly(a1);let recovered=await task('recover');assert.equal(recovered.attempt,2);assert.equal(recovered.recovered,true);assert.equal(recovered.steps.find(row=>row.key==='s0').resultSha,successfulSha);await task('stepbegin',{step:'s1'});const failure=await task('failure',{step:'s1',code:'transport_timeout'});assert.equal(failure.retry.retryable,true);const scheduled=await control('retry',{job:a1.id,phase:1,result:{code:'transport_timeout',scope:'explicit injected transient control probe'},code:'transport_timeout',delaySeconds:30});assert.equal(scheduled.retried,true);assert.equal(scheduled.attempts,2);const waiting=await control('claim');assert.equal(waiting.job,null,'A retry cannot be claimed before its real availability timestamp');assert.equal(waiting.queuedPending,1);assert.ok(waiting.nextAvailableAt);await claimOnly(a1);recovered=await task('recover');assert.equal(recovered.attempt,3);assert.equal(recovered.steps.find(row=>row.key==='s0').resultSha,successfulSha);return{secondAttempt:2,thirdAttempt:3,retainedSha:successfulSha,delayedClaimExcluded:true}});
 await check('The third temporary failure exhausts the bounded budget without another job or fabricated completion',async()=>{await task('stepbegin',{step:'s1'});const failure=await task('failure',{step:'s1',code:'resource_wait'});assert.equal(failure.retry.retryable,false);assert.equal(failure.retry.exhausted,true);const retry=await control('retry',{job:a1.id,phase:1,result:{code:'resource_wait',scope:'explicit injected final transient control probe'},code:'resource_wait',delaySeconds:1});assert.equal(retry.retried,false);assert.equal(retry.attempts,3);const state=await capture(),job=state.jobs.find(row=>row.id===a1.id);assert.equal(job.state,'failed');assert.equal(job.attempts,3);assert.equal(state.jobs.length,3);const first=state.steps.find(row=>row.job_id===a1.id&&row.key==='s0'),failed=state.steps.find(row=>row.job_id===a1.id&&row.key==='s1');assert.equal(first.sha,successfulSha);assert.equal(first.attempts,1);assert.equal(failed.status,'failed');assert.equal(failed.attempts,3);assert.equal(state.events.filter(row=>row.job_id===a1.id).length,5);return{state:'failed',canonicalAttempts:3,stepAttempts:3,originalCheckpointAttempts:1,events:5}});
 await check('The real database outbox delivers five unique receipts and duplicate acknowledgement deduplicates',async()=>{const rows=await privateCall('outbox',{job:a1.id,worker,action:'read',limit:8});assert.equal(rows.items.length,5);const relay=await privateCall('outbox',{job:a1.id,worker,action:'relay',limit:8,transport:'database-outbox'});assert.equal(relay.transport,'database-outbox');assert.equal(relay.brokerConfirmed,false);assert.equal(relay.pending,0);assert.equal(new Set(relay.delivered).size,5);const first=rows.items[0],ack=await privateCall('outbox',{job:a1.id,worker,action:'ack',seq:first.seq,payloadSha:first.payloadSha,transport:'database-outbox'});assert.equal(ack.duplicate,true);await privateCall('outbox',{job:a1.id,worker,action:'ack',seq:first.seq,payloadSha:'0'.repeat(64),transport:'database-outbox'},[409]);await privateCall('outbox',{job:a1.id,worker,action:'ack',seq:first.seq,payloadSha:first.payloadSha,transport:'rabbitmq'},[400]);const state=await capture(),events=state.events.filter(row=>row.job_id===a1.id),inbox=state.inbox.filter(row=>row.job_id===a1.id);assert.ok(events.every(row=>row.delivery==='delivered'));assert.equal(inbox.length,5);for(const row of inbox){const event=events.find(item=>item.seq===row.event_seq);assert.equal(row.payload_sha,event.payload_sha);assert.equal(row.transport,'database-outbox')}return{receipts:5,inboxRows:5,pending:0,duplicateAck:true,changedAck:409,fakeAmqpAck:400,amqpClaimed:false}});
 await check('Ordinary release invalidates the same Java UUID lease',async()=>{await control('release');leaseOwned=false;assert.equal((await capture()).lease.leased,false);await task('inspect',{},[409]);return{leaseReleased:true,expiredUuidRejected:409}});
 report.passed=true;
}catch(error){report.error=String(error.message).slice(0,300);process.exitCode=1}
finally{
 cleaning=true;
 for(const cap of owned.values()){try{const row=await read(cap);if(['queued','starting','running'].includes(row.state))await cancel(cap)}catch{report.cleanupIncomplete=true}}
 try{const state=await capture();if(state.lease.owner===worker&&state.lease.leased){await control('release');leaseOwned=false}const after=await capture();report.cleanup={ownedActive:after.jobs.filter(row=>['queued','starting','running'].includes(row.state)).length,ownedLease:after.lease.owner===worker&&after.lease.leased};if(report.cleanup.ownedActive||report.cleanup.ownedLease)report.cleanupIncomplete=true;for(const row of after.jobs){const entry=report.jobs.find(item=>item.id===row.id);if(entry)Object.assign(entry,{state:row.state,attempts:row.attempts})}}catch{report.cleanupIncomplete=true}
 if(report.cleanupIncomplete){report.passed=false;process.exitCode=1}report.finishedAt=new Date().toISOString();await mkdir(dirname(reportFile),{recursive:true});await writeFile(reportFile,JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,file:reportFile}));
}
