import {testDeps} from '../runtime-location.mjs';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as sleep} from 'node:timers/promises';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
try{process.loadEnvFile(join(root,'.env'))}catch(error){if(error.code!=='ENOENT')throw error}
const base=new URL(process.env.OCV_SHARED_BASE_URL||`http://127.0.0.1:${process.env.OCV_WEB_PORT||8080}`);
if(base.protocol!=='http:'||base.username||base.password||!['localhost','127.0.0.1','[::1]'].includes(base.hostname))throw Error('The SH2 mutation proof uses a private loopback entrance');
const deps=testDeps,reportFile=join(deps,'runtime/reports/phase12-sh2.json');
const report={schema:'ocv.sh2/http-proof/1',startedAt:new Date().toISOString(),passed:false,checks:[],jobs:[],maximumJobs:30,maximumPollMs:600000,serviceClaims:[],privateCapabilitiesPrinted:false};
const owned=new Map(),seen=new Set(),overallDeadline=Date.now()+600000;
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const fixture={schema:'ocv.signals-project/1',name:'sh2-'+randomUUID().slice(0,8),drawing:{components:[
 {id:'V1',kind:'V',x:230,y:260,rotation:90,value:5},{id:'R1',kind:'R',x:450,y:150,rotation:0,value:1000},{id:'R2',kind:'R',x:670,y:260,rotation:90,value:1000},{id:'G1',kind:'GND',x:230,y:390,rotation:0,value:0}
 ],wires:[{id:'w1',from:{component:'V1',pin:'a'},to:{component:'R1',pin:'a'}},{id:'w2',from:{component:'V1',pin:'b'},to:{component:'G1',pin:'a'}},{id:'w3',from:{component:'R1',pin:'b'},to:{component:'R2',pin:'a'}},{id:'w4',from:{component:'R2',pin:'b'},to:{component:'G1',pin:'a'}}]},analysis:{kind:'dc',fStart:10,fStop:100000,points:64,durationS:.01,stepS:.000025},communication:{bits:'0100111001100101',seed:1234,ebN0Db:0,samplesPerSymbol:4,sampleRateHz:8000},instruments:{probe:'out',cursor:0}};
let saved,first,second,branch,opened,joined,upload;

async function post(path,body,statuses=[200,201]){
 const response=await fetch(new URL(path,base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const raw=await response.text();assert.ok(Buffer.byteLength(raw)<=6291456,'SH2 response must remain bounded');let data;try{data=JSON.parse(raw)}catch{throw Error(`Non-JSON SH2 response (HTTP ${response.status})`)};assert.ok(statuses.includes(response.status),`Unexpected HTTP ${response.status}`);return data;
}
async function check(name,fn){const started=Date.now();try{const evidence=await fn();report.checks.push({name,passed:true,elapsedMs:Date.now()-started,...evidence})}catch(error){report.checks.push({name,passed:false,elapsedMs:Date.now()-started,error:String(error.message).slice(0,240)});throw error}}
async function read(job){return post(`/api/shared/jobs/${job.id}/read`,{ticket:job.ticket})}
async function wait(job){
 const transitions=[];
 while(Date.now()<overallDeadline){const record=await read(job);if(transitions.at(-1)?.state!==record.state||transitions.at(-1)?.phase!==record.phase)transitions.push({state:record.state,phase:record.phase});if(['done','failed','cancelled'].includes(record.state)){owned.delete(job.id);report.jobs.push({id:job.id,state:record.state,phase:record.phase,transitions});return record}await sleep(1200)}
 throw Error('The SH2 proof reached its ten-minute overall deadline');
}
async function operation(action,extra={},expectFailure=false){
 assert.ok(saved,'The original project must exist');assert.ok(Date.now()<overallDeadline,'Bounded overall proof deadline');const ack=await post('/api/shared/operations',{action,project:saved.id,ticket:saved.ticket,domain:'signals',...extra});assert.ok(ack.id&&ack.ticket,'Persistent operation acknowledgement required');
 if(!seen.has(ack.id)){assert.ok(seen.size<30,'At most thirty test-owned shared jobs');seen.add(ack.id)}owned.set(ack.id,ack.ticket);
 const record=await wait(ack);if(!expectFailure)assert.equal(record.state,'done','An actual shared task must complete without frontend fallback');
 return {ack,record,result:record.shared?.operationResult};
}
async function current(cap=saved){return post(`/api/signals/projects/${cap.id}/read`,{ticket:cap.ticket})}
const member=cap=>({room:cap.room,client:cap.client,clientTicket:cap.clientTicket});

try{
 await check('Two canonical snapshots are saved with a checked head',async()=>{
  first=await post('/api/signals/projects',{project:fixture});assert.equal(first.revision,1);assert.equal(first.digest,hash(canonical(fixture)));saved={...first};const next=structuredClone(fixture);next.drawing.components.find(part=>part.id==='R2').value=3000;second=await post('/api/signals/projects',{project:next,id:saved.id,ticket:saved.ticket,expectedRevision:1});assert.equal(second.revision,2);saved.revision=2;return {firstRevision:1,secondRevision:2,firstDigest:first.digest,secondDigest:second.digest,storage:first.storage};
 });
 await check('Go lists the same canonical version head and immutable digests',async()=>{const{result}=await operation('versions');assert.equal(result.headRevision,2);assert.equal(result.versions.find(v=>v.revision===1).digest,first.digest);assert.equal(result.versions.find(v=>v.revision===2).digest,second.digest);assert.equal(result.storage,'PostgreSQL');return {head:result.headRevision,retained:result.versions.length}});
 await check('Retained snapshots produce a structural JSON-pointer difference',async()=>{const{result}=await operation('diff',{beforeRevision:1,afterRevision:2});assert.equal(result.before.digest,first.digest);assert.equal(result.after.digest,second.digest);const value=result.difference.changes.find(c=>c.path==='/drawing/components/2/value');assert.equal(value.before,1000);assert.equal(value.after,3000);assert.equal(value.kind,'replace');return {changed:result.difference.totalChanges,granularity:result.difference.granularity}});
 await check('A branch comes from the selected old snapshot and has an independent head',async()=>{const operationId=randomUUID(),body={operationId,sourceRevision:1,name:fixture.name+'-fork'},out=await operation('branch',body);branch={id:out.ack.capability.project,ticket:out.ack.capability.ticket};assert.equal(out.result.project.sourceSnapshot,first.snapshot);const reread=await current(branch);assert.equal(reread.project.drawing.components.find(p=>p.id==='R2').value,1000);assert.equal(reread.revision,1);assert.notEqual(branch.id,saved.id);const duplicate=await operation('branch',body);assert.equal(duplicate.ack.id,out.ack.id);assert.equal(duplicate.ack.duplicate,true);return {revision:reread.revision,sourceSnapshot:first.snapshot,duplicateJob:true}});
 await check('Rollback appends a new immutable revision and submission retries deduplicate',async()=>{const body={operationId:randomUUID(),sourceRevision:1,expectedRevision:2},out=await operation('rollback',body);assert.equal(out.result.project.revision,3);assert.equal(out.result.project.digest,first.digest);assert.equal(out.result.appended,true);const duplicate=await operation('rollback',body);assert.equal(duplicate.ack.id,out.ack.id);assert.equal(duplicate.ack.duplicate,true);const reread=await current();assert.equal(reread.revision,3);assert.equal(reread.project.drawing.components.find(p=>p.id==='R2').value,1000);saved.revision=3;return {appendedRevision:3,originalDigestPreserved:true,duplicateJob:true}});
 await check('A new stale rollback fails with a non-retryable real revision conflict',async()=>{const{record}=await operation('rollback',{operationId:randomUUID(),sourceRevision:1,expectedRevision:2},true);assert.equal(record.state,'failed');assert.match(String(record.result?.reason),/HTTP 409/);assert.equal(record.result?.code,'version_conflict','A real revision conflict must not become a storage failure');assert.equal((await current()).revision,3);return {state:record.state,code:record.result.code,http409:true,headUnchanged:true}});
 await check('Two capability-checked participants open and join one room',async()=>{const firstRoom=await operation('room-open',{operationId:randomUUID()});opened=firstRoom.ack.capability;const secondRoom=await operation('room-join',{room:opened.room});joined=secondRoom.ack.capability;assert.equal(firstRoom.result.room,secondRoom.result.room);assert.notEqual(opened.client,joined.client);assert.equal(firstRoom.result.crdt,false);return {participants:2,wholeSnapshotCAS:true,crdt:false}});
 await check('A confirmed collaboration commit appends one head and duplicate requests acknowledge it',async()=>{const project=structuredClone(fixture);project.drawing.components.find(p=>p.id==='R2').value=7500;const body={...member(opened),operationId:randomUUID(),expectedRevision:3,projectData:project},out=await operation('room-commit',body);assert.equal(out.result.revision,4);assert.equal(out.result.sequence,1);const duplicate=await operation('room-commit',body);assert.equal(duplicate.ack.id,out.ack.id);assert.equal((await current()).revision,4);saved.revision=4;return {revision:4,sequence:1,duplicateJob:true}});
 await check('The second participant cannot silently overwrite a changed head',async()=>{const project=structuredClone(fixture);project.drawing.components.find(p=>p.id==='R1').value=1500;const{record}=await operation('room-commit',{...member(joined),operationId:randomUUID(),expectedRevision:3,projectData:project},true);assert.equal(record.state,'failed');assert.match(String(record.result?.reason),/HTTP 409/);assert.equal(record.result?.code,'version_conflict');assert.equal((await current()).revision,4);return {state:record.state,code:record.result.code,http409:true,headUnchanged:true}});
 await check('Reconnect replays a contiguous confirmed sequence and presence',async()=>{const{result}=await operation('room-read',{...member(opened),cursor:0});assert.equal(result.cursor,1);assert.equal(result.operations.length,1);assert.equal(result.operations[0].sequence,1);assert.equal(result.operations[0].revision,4);assert.equal(result.participants.length,2);assert.equal(result.hasMore,false);return {cursor:result.cursor,presence:2}});
 await check('Rebased second-participant input commits without losing the first edit',async()=>{const head=await current();const project=structuredClone(head.project);project.drawing.components.find(p=>p.id==='R1').value=1500;const{result}=await operation('room-commit',{...member(joined),operationId:randomUUID(),expectedRevision:4,projectData:project});assert.equal(result.revision,5);assert.equal(result.sequence,2);const replay=await operation('room-read',{...member(opened),cursor:1});assert.equal(replay.result.operations.length,1);assert.equal(replay.result.operations[0].sequence,2);const verified=await current();assert.equal(verified.project.drawing.components.find(p=>p.id==='R1').value,1500);assert.equal(verified.project.drawing.components.find(p=>p.id==='R2').value,7500);saved.revision=5;return {revision:5,reconnectCursor:2,bothEditsRetained:true}});
 const artifact=Buffer.alloc(90117);for(let i=0;i<artifact.length;i++)artifact[i]=(i*37+19)%256;const artifactDigest=hash(artifact),chunks=[artifact.subarray(0,65536),artifact.subarray(65536)];
 await check('A bounded two-chunk upload starts against the same canonical project',async()=>{upload=randomUUID();const{result}=await operation('upload-start',{upload,size:artifact.length,digest:artifactDigest});assert.equal(result.upload,upload);assert.equal(result.chunkSize,65536);assert.equal(result.totalParts,2);assert.equal(result.state,'uploading');return {bytes:artifact.length,parts:2,chunkBytes:65536}});
 await check('Out-of-order chunks survive a resume/status read without replacing data',async()=>{await operation('upload-put',{upload,part:1,digest:hash(chunks[1]),data:chunks[1].toString('base64')});const{result}=await operation('upload-status',{upload});assert.deepEqual(result.receivedParts.map(p=>p.part),[1]);assert.equal(result.receivedBytes,chunks[1].length);assert.equal(result.receivedParts[0].digest,hash(chunks[1]));await operation('upload-put',{upload,part:0,digest:hash(chunks[0]),data:chunks[0].toString('base64')});const duplicate=await operation('upload-put',{upload,part:1,digest:hash(chunks[1]),data:chunks[1].toString('base64')});assert.equal(duplicate.result.duplicate,true);return {resumeMissingOnly:true,outOfOrderIndex:1,duplicateChunk:true}});
 await check('Full commit verifies the actual MinIO readback and clears PostgreSQL staging',async()=>{const{result}=await operation('upload-commit',{upload});assert.equal(result.verified,true);assert.equal(result.digest,artifactDigest);assert.equal(result.size,artifact.length);assert.equal(result.storage,'MinIO + PostgreSQL');const status=await operation('upload-status',{upload});assert.equal(status.result.state,'ready');assert.equal(status.result.receivedParts.length,0);report.serviceClaims.push({service:'MinIO',proof:'Go SHA-256-verified PUT and GET',digest:artifactDigest});return {sha256:artifactDigest,readbackVerified:true,stagingReleased:true}});
 await check('Downloaded chunks reconstruct the identical artifact and full content hash',async()=>{const collected=[];for(let part=0;part<2;part++){const{result}=await operation('upload-download',{upload,part});const chunk=Buffer.from(result.data,'base64');assert.equal(result.part,part);assert.equal(result.parts,2);assert.equal(result.verified,true);assert.equal(result.chunkDigest,hash(chunk));assert.equal(result.digest,artifactDigest);collected.push(chunk)}const complete=Buffer.concat(collected);assert.equal(hash(complete),artifactDigest);assert.equal(complete.length,artifact.length);return {bytes:complete.length,sha256:artifactDigest,chunksVerified:2}});
 await check('Test-owned artifact and participant cleanup uses the public bounded paths',async()=>{const cleared=await operation('upload-abort',{upload});assert.equal(cleared.result.cancelled,true);const a=await operation('room-leave',member(opened)),b=await operation('room-leave',member(joined));assert.equal(a.result.left,true);assert.equal(b.result.left,true);return {artifactCleared:true,participantsLeft:2}});
 report.passed=true;
 // This fixture is private runtime data for a subsequent, focused browser check.
 const fixtureFile=join(deps,'tmp/phase12-sh2-private.json');await mkdir(dirname(fixtureFile),{recursive:true});await writeFile(fixtureFile,JSON.stringify({project:saved,branch,projectData:(await current()).project},null,2),{mode:0o600});
}catch(error){report.error=String(error.message).slice(0,300);process.exitCode=1}
finally{
 for(const[id,ticket]of owned){try{const cancelled=await post(`/api/shared/jobs/${id}/cancel`,{ticket});if(cancelled.cancelled||['done','failed','cancelled'].includes((await read({id,ticket})).state))owned.delete(id);else report.cleanupIncomplete=true}catch{report.cleanupIncomplete=true}}
 report.finishedAt=new Date().toISOString();report.uniqueJobs=seen.size;report.liveOwnedAfterCleanup=owned.size;await mkdir(dirname(reportFile),{recursive:true});await writeFile(reportFile,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,jobs:seen.size,file:reportFile}));
}
