import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import {reports} from './report-location.mjs';
import {tools} from '../../config/apps/portal/src/tool/data.mjs';
import {SAVE_KEY} from '../../config/apps/portal/src/3d/save.mjs';

const route='/functions/3d-world/';
const snapshot=page=>page.evaluate(()=>window.__ocv3D?.snapshot());
const activate=async locator=>{await locator.focus();await locator.press('Enter');};
const proof=(name,value)=>fs.writeFileSync(path.join(reports,`3d-${name}.json`),JSON.stringify(value,null,2));
function expectNearTerrainCoverage(state){
 const mask=state.world.farMask;expect(mask.materialCompiled).toBe(true);expect(mask.retainedTriangles).toBeGreaterThan(0);expect(mask.retainedTriangles).toBeLessThan(mask.totalTriangles);
 expect(state.player.x).toBeGreaterThanOrEqual(mask.minX);expect(state.player.x).toBeLessThanOrEqual(mask.maxX);expect(state.player.z).toBeGreaterThanOrEqual(mask.minZ);expect(state.player.z).toBeLessThanOrEqual(mask.maxZ);
}
async function ready(page){await expect.poll(async()=> (await snapshot(page))?.mode,{timeout:45000}).toBe('webgl');await expect.poll(async()=> (await snapshot(page)).frames,{timeout:30000}).toBeGreaterThan(2);await page.locator('#world').focus();}
async function enter(page){await page.goto(route);await ready(page);}
async function settledView(page){await expect.poll(()=>page.locator('.aero-iris').evaluate(node=>Number(getComputedStyle(node).opacity)),{timeout:30000}).toBeLessThan(.02);}
async function walkUntil(page,code,predicate,timeout=45000){await page.keyboard.down(code);try{await expect.poll(async()=>predicate(await snapshot(page)),{timeout,intervals:[100]}).toBe(true);}finally{await page.keyboard.up(code);}}
function aimAngles(state,point){const x=point.x-state.position.x,y=point.y-state.position.y,z=point.z-state.position.z;return{yaw:Math.atan2(-x,-z),pitch:Math.atan2(y,Math.hypot(x,z))};}
const angularDifference=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
async function nativeAim(page,getPoint){
 // Reading every building/road into the trace can move a small wandering body
 // beyond the reticle before a native click. Read only live aiming coordinates.
 const tracking=()=>page.evaluate(()=>window.__ocv3D.tracking());
 const turnUntil=async(code,predicate)=>{await page.keyboard.down(code);try{await expect.poll(async()=>predicate(await tracking()),{timeout:15000,intervals:[32,50]}).toBe(true);}finally{await page.keyboard.up(code);}};
 let state=await tracking(),angle=aimAngles(state,getPoint(state)),difference=angularDifference(angle.yaw,state.yaw);
 if(Math.abs(difference)>.45)await turnUntil(difference>0?'ArrowLeft':'ArrowRight',s=>Math.abs(angularDifference(aimAngles(s,getPoint(s)).yaw,s.yaw))<.35);
 state=await tracking();angle=aimAngles(state,getPoint(state));if(Math.abs(angle.pitch-state.pitch)>.3)await turnUntil(angle.pitch>state.pitch?'ArrowUp':'ArrowDown',s=>Math.abs(aimAngles(s,getPoint(s)).pitch-s.pitch)<.22);
 const bounds=await page.locator('#world').boundingBox(),center={x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2};await page.mouse.move(center.x,center.y);await page.mouse.down({button:'right'});
 try{state=await tracking();angle=aimAngles(state,getPoint(state));const dx=-angularDifference(angle.yaw,state.yaw)/.0021,dy=-(angle.pitch-state.pitch)/.0021;expect(Math.abs(dx)).toBeLessThan(bounds.width/2);expect(Math.abs(dy)).toBeLessThan(bounds.height/2);await page.mouse.move(center.x+dx,center.y+dy);}finally{await page.mouse.up({button:'right'});}
 await expect.poll(()=>page.evaluate(()=>window.__ocv3D.tracking().frames),{timeout:10000,intervals:[16,32,50]}).toBeGreaterThan(state.frames);
}
async function walkToInitialStation(page){
 const state=await snapshot(page),station=[...state.checkpoint.stations].sort((a,b)=>Math.hypot(a.x,a.z-180)-Math.hypot(b.x,b.z-180))[0];expect(Math.hypot(station.x,station.z-180)).toBeLessThan(40);expect(Math.abs(state.yaw)).toBeLessThan(.01);await page.locator('#world').focus();
 if(state.player.z>station.z+1)await walkUntil(page,'KeyW',s=>s.player.z<station.z+1);else if(state.player.z<station.z-1)await walkUntil(page,'KeyS',s=>s.player.z>station.z-1);
 const advanced=await snapshot(page);if(advanced.player.x>station.x+1)await walkUntil(page,'KeyA',s=>s.player.x<station.x+1);else if(advanced.player.x<station.x-1)await walkUntil(page,'KeyD',s=>s.player.x>station.x-1);
 await expect.poll(async()=> (await snapshot(page)).checkpoint.resting).toBe(station.id);await expect(page.locator('[data-save]')).toBeEnabled();return station;
}
async function installAudioProbe(page){
 await page.addInitScript(()=>{
  const Context=window.AudioContext||window.webkitAudioContext;
  window.__aeroNativeAudio={contexts:[],gains:[],started:0,ended:0};
  if(!Context)return;
  const createGain=Context.prototype.createGain;
  Context.prototype.createGain=function(...args){if(!window.__aeroNativeAudio.contexts.includes(this))window.__aeroNativeAudio.contexts.push(this);const node=createGain.apply(this,args);window.__aeroNativeAudio.gains.push(node);return node;};
  for(const name of ['createOscillator','createBufferSource']){
   const create=Context.prototype[name];Context.prototype[name]=function(...args){const source=create.apply(this,args),start=source.start;source.start=function(...values){const result=start.apply(this,values);window.__aeroNativeAudio.started++;return result;};source.addEventListener('ended',()=>window.__aeroNativeAudio.ended++);return source;};
  }
 });
}

test('3D game is a real entry in both game directories and site search',async({page})=>{
 expect(tools).toHaveLength(111);expect(tools.filter(t=>t.group==='游戏')).toHaveLength(11);
 await page.goto('/functions/games/');await expect(page.getByRole('link',{name:/3D游戏/})).toHaveAttribute('href',route);
 await page.goto('/functions/');const games=page.locator('.tool-group').filter({has:page.locator('h2').filter({hasText:/^游戏$/})});await expect(games.locator(`a[href="${route}"]`)).toHaveCount(1);
 await page.goto('/search/?q='+encodeURIComponent('3D游戏'));await expect(page.locator(`a[href="${route}"]`).filter({hasText:'3D游戏'})).toBeVisible();
});

test('Text-free first-person page renders actual terrain, settlements, water and a bounded twelve-kilometre world',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Shader Error|VALIDATE_STATUS|initialization failed/.test(m.text()))errors.push(m.text());});
 await enter(page);expect((await page.locator('body').innerText()).trim()).toBe('');await expect(page.locator('h1:visible,header,nav,[role=menu]')).toHaveCount(0);await expect(page).toHaveTitle('');
 await expect(page.locator('.aero-energy')).toHaveCount(0);const canvas=await page.locator('#world').boundingBox(),viewport=await page.evaluate(()=>({width:innerWidth,height:innerHeight}));expect(canvas.width).toBeGreaterThan(400);expect(canvas.height).toBeGreaterThan(300);expect(canvas.width).toBeLessThan(viewport.width);expect(canvas.height).toBeLessThan(viewport.height);expect(canvas.x).toBeGreaterThanOrEqual(0);expect(canvas.y).toBeGreaterThanOrEqual(0);expect(canvas.x+canvas.width).toBeLessThanOrEqual(viewport.width);expect(canvas.y+canvas.height).toBeLessThanOrEqual(viewport.height);
 const gpu=await page.locator('#world').evaluate(node=>{const gl=node.getContext('webgl2'),debug=gl.getExtension('WEBGL_debug_renderer_info');return{renderer:gl.getParameter(debug?debug.UNMASKED_RENDERER_WEBGL:gl.RENDERER),vendor:gl.getParameter(debug?debug.UNMASKED_VENDOR_WEBGL:gl.VENDOR),version:gl.getParameter(gl.VERSION),attributes:gl.getContextAttributes()};});proof('native-GPU',gpu);
 const state=await snapshot(page);expect(state.world.worldSize).toBe(12000);expect(state.world.areaKm2).toBe(144);expect(state.world.activeChunks).toBeGreaterThan(0);expect(state.world.activeChunks).toBeLessThanOrEqual(25);expect(state.world.buildings).toBeGreaterThan(100);expect(state.world.terrainVertices).toBeGreaterThan(10000);expect(state.world.rivers).toBeGreaterThan(0);expect(state.world.clouds).toBeGreaterThan(0);expect(state.renderer.triangles).toBeGreaterThan(1000);expect(state.renderer.calls).toBeGreaterThan(20);expect(state.renderer.shadows).toBe(true);expect(state.renderer.contactAO).toBe(true);expect(state.renderer.glassTransmission).toBeGreaterThan(0);expect(state.world.shadowMapReady).toBe(true);expect(state.world.shadowMapAllocated).toEqual({width:2048,height:2048});expect(state.entities.entities.length).toBeGreaterThan(12);expect(state.portals.length).toBeGreaterThan(6);expect(errors).toEqual([]);
 expect(state.entities.entities.length).toBeGreaterThanOrEqual(80);expect(Object.keys(state.entities.species)).toHaveLength(5);expect(Object.values(state.entities.species).every(count=>count>0)).toBe(true);expect(Object.values(state.entities.species).reduce((sum,count)=>sum+count,0)).toBe(state.entities.entities.length);expect(state.eyeHeight).toBe(2.2);expect(state.position.y-state.player.y).toBeCloseTo(2.2,1);expectNearTerrainCoverage(state);await settledView(page);await page.screenshot({path:path.join(reports,'3d-avenue.png')});proof('initial-world',{...state,canvas,viewport});
});

test('Native walking, arrow look, sprint, jump and recovery change the actual first-person simulation',async({page})=>{
 await enter(page);const initial=await snapshot(page);
 await walkUntil(page,'KeyW',s=>s.player.z<initial.player.z-4);const walked=await snapshot(page);expect(walked.player.y).toBeCloseTo(10,1);
 await walkUntil(page,'ArrowLeft',s=>s.yaw>.22);const turned=await snapshot(page);expect(turned.yaw).toBeGreaterThan(.22);
 await page.keyboard.press('KeyR');await expect.poll(async()=> (await snapshot(page)).respawns).toBe(1);const recovered=await snapshot(page);expect(recovered.player.x).toBe(0);expect(recovered.player.z).toBe(180);expect(recovered.yaw).toBe(0);
 await page.keyboard.press('Space');await expect.poll(async()=> (await snapshot(page)).player.grounded).toBe(false);const jumping=await snapshot(page);expect(jumping.player.y).toBeGreaterThan(10);await expect.poll(async()=> (await snapshot(page)).player.grounded,{timeout:15000}).toBe(true);
 const sprintStart=await snapshot(page);await page.keyboard.down('ShiftLeft');try{await walkUntil(page,'KeyW',s=>s.time>sprintStart.time+1);}finally{await page.keyboard.up('ShiftLeft');}
 const sprinted=await snapshot(page),walkingSpeed=(initial.player.z-walked.player.z)/(walked.time-initial.time),sprintSpeed=(sprintStart.player.z-sprinted.player.z)/(sprinted.time-sprintStart.time);expect(sprintStart.player.z-sprinted.player.z).toBeGreaterThan(45);expect(sprintSpeed).toBeGreaterThan(30);expect(sprintSpeed).toBeGreaterThan(walkingSpeed*3.5);expect(sprintSpeed).toBeLessThanOrEqual(58.1);expect(sprinted.player.energy).toBe(1);expect(sprinted.player.health).toBeGreaterThan(0);proof('native-controls',{initial,walked,turned,jumping,sprintStart,sprinted,walkingSpeed,sprintSpeed});
});

test('Visible house footprint blocks native strafing while the player remains outside its wall',async({page})=>{
 await enter(page);await walkUntil(page,'KeyW',s=>s.player.z<130);await page.keyboard.down('ShiftLeft');try{await walkUntil(page,'KeyD',s=>s.player.x>34);}finally{await page.keyboard.up('ShiftLeft');}
 await page.keyboard.down('KeyD');try{await page.waitForTimeout(1700);}finally{await page.keyboard.up('KeyD');}
 const stopped=await snapshot(page);expect(stopped.player.z).toBeLessThan(134);expect(stopped.player.z).toBeGreaterThan(114);expect(stopped.player.x).toBeGreaterThan(34);expect(stopped.player.x).toBeLessThan(35.52);proof('native-house-collision',stopped);
});

test('Three native shots hit the front entity, produce real sound, and walking collects its dropped object',async({page})=>{
 await installAudioProbe(page);await enter(page);expect(await page.evaluate(()=>window.__aeroNativeAudio.contexts.length)).toBe(0);
 const trigger=page.getByRole('button',{name:'发射',exact:true});
 for(let shot=1;shot<=3;shot++){await activate(trigger);await expect.poll(async()=> (await snapshot(page)).shots,{timeout:15000}).toBe(shot);await expect.poll(async()=> (await snapshot(page)).hits,{timeout:15000}).toBe(shot);await expect.poll(async()=> (await snapshot(page)).entities.entities[0].hp).toBe(3-shot);if(shot<3){await expect.poll(async()=> (await snapshot(page)).entities.entities[0].healthVisible).toBe(true);await page.waitForTimeout(1200);}}
 const hit=await snapshot(page);expect(hit.entities.entities[0]).toMatchObject({hp:0,state:'seed'});expect(hit.entities.kills).toBe(1);await expect.poll(()=>page.evaluate(()=>window.__aeroNativeAudio.started)).toBeGreaterThan(3);await expect.poll(()=>page.evaluate(()=>window.__aeroNativeAudio.ended)).toBeGreaterThan(0);
 await page.locator('#world').focus();await page.keyboard.down('ShiftLeft');try{await walkUntil(page,'KeyW',s=>s.entities.collected>0);}finally{await page.keyboard.up('ShiftLeft');}const collected=await snapshot(page);expect(collected.entities.entities[0]).toMatchObject({state:'sleep',visible:false});expect(collected.cycle).toBe(1);expect(collected.audio.played.shot).toBeGreaterThan(0);proof('native-shoot-collect',{hit,collected,nativeAudio:await page.evaluate(()=>({started:window.__aeroNativeAudio.started,ended:window.__aeroNativeAudio.ended,states:window.__aeroNativeAudio.contexts.map(c=>c.state)}))});
});

test('A real hostile drone damages the player, and walking into a rest station refills the visible health meter',async({page})=>{
 await enter(page);const initial=await snapshot(page);await walkUntil(page,'KeyW',s=>s.player.z<94);await expect.poll(async()=> (await snapshot(page)).checkpoint.damageTaken,{timeout:20000}).toBeGreaterThan(0);const injured=await snapshot(page);expect(injured.player.health).toBeLessThan(initial.player.health);expect(injured.player.health).toBeGreaterThan(0);expect(injured.respawns).toBe(0);expect(injured.entities.shotsAtPlayer).toBeGreaterThan(0);expect(injured.entities.projectileImpacts).toBeGreaterThan(0);expect(injured.entities.damageEvents).toBeGreaterThan(0);expect(injured.entities.entities.find(entity=>entity.id===4)).toMatchObject({kind:'drone',proactive:true});await expect.poll(async()=>Number(await page.getByRole('meter',{name:'生命值'}).getAttribute('aria-valuenow'))).toBeLessThan(100);
 const station=await walkToInitialStation(page);await expect.poll(async()=> (await snapshot(page)).checkpoint.healed,{timeout:25000}).toBeGreaterThan(0);await expect.poll(async()=> (await snapshot(page)).player.health,{timeout:25000}).toBe(1);await expect(page.getByRole('meter',{name:'生命值'})).toHaveAttribute('aria-valuenow','100');const healed=await snapshot(page);expect(healed.checkpoint.resting).toBe(station.id);expect(healed.respawns).toBe(0);proof('native-enemy-healing',{initial,injured,healed});
});

test('Native collection and station saving persist through reload, and recovery returns to the saved station',async({page})=>{
 await enter(page);await expect(page.locator('[data-save]')).toBeDisabled();await page.keyboard.press('KeyQ');expect((await snapshot(page)).checkpoint.store.writes).toBe(0);expect(await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY)).toBeNull();
 const trigger=page.getByRole('button',{name:'发射',exact:true});for(let shot=1;shot<=3;shot++){await activate(trigger);await expect.poll(async()=> (await snapshot(page)).hits).toBe(shot);if(shot<3)await page.waitForTimeout(1200);}
 await page.locator('#world').focus();await walkUntil(page,'KeyW',s=>s.entities.collected>0);expect((await snapshot(page)).cycle).toBe(1);const station=await walkToInitialStation(page);await activate(page.getByRole('button',{name:'保存进度',exact:true}));await expect.poll(async()=> (await snapshot(page)).checkpoint.store.status).toBe('saved');const saved=await snapshot(page),savedText=await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY),progress=JSON.parse(savedText);expect(Object.keys(progress).sort()).toEqual(['checkpoint','energy','found','health','version']);expect(progress).toMatchObject({version:1,checkpoint:station.id,found:[0]});expect(saved.checkpoint.store.persistent).toBe(true);
 await page.locator('#world').focus();await walkUntil(page,'KeyW',s=>s.player.z<145);await expect(page.locator('[data-save]')).toBeDisabled();await page.keyboard.press('KeyQ');expect((await snapshot(page)).checkpoint.store.writes).toBe(1);await page.keyboard.press('KeyR');await expect.poll(async()=> (await snapshot(page)).respawns).toBe(1);const recovered=await snapshot(page);expect(recovered.player.x).toBeCloseTo(station.x,6);expect(recovered.player.z).toBeCloseTo(station.z,6);
 await page.reload();await ready(page);const restored=await snapshot(page);expect(restored.checkpoint).toMatchObject({id:station.id,restores:1,store:{status:'loaded',persistent:true}});expect(restored.player.x).toBeCloseTo(station.x,6);expect(restored.player.z).toBeCloseTo(station.z,6);expect(restored.cycle).toBe(1);expect(await page.evaluate(key=>localStorage.getItem(key),SAVE_KEY)).toBe(savedText);proof('native-checkpoint-reload',{saved,recovered,restored,progress});
});

test('Refused local storage still allows a native session checkpoint and recovery without claiming persistence',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('Storage refused for the test environment','SecurityError');}}));await enter(page);const station=await walkToInitialStation(page);await page.keyboard.press('KeyQ');await expect.poll(async()=> (await snapshot(page)).checkpoint.store.writes).toBe(1);const saved=await snapshot(page);expect(saved.checkpoint.store).toMatchObject({status:'memory',persistent:false,checkpoint:station.id});
 await walkUntil(page,'KeyW',s=>s.player.z<145);await page.keyboard.press('KeyR');await expect.poll(async()=> (await snapshot(page)).respawns).toBe(1);const recovered=await snapshot(page);expect(recovered.player.x).toBeCloseTo(station.x,6);expect(recovered.player.z).toBeCloseTo(station.z,6);
 await page.reload();await ready(page);const fresh=await snapshot(page);expect(fresh.checkpoint).toMatchObject({id:null,restores:0,store:{status:'memory',persistent:false}});expect(fresh.player.x).toBe(0);expect(fresh.player.z).toBe(180);proof('refused-checkpoint-storage',{saved,recovered,fresh,claim:'The test environment throws a real SecurityError when the localStorage property is accessed; progress is produced only by native walking and save controls. This exercises the unavailable-storage path, not a real browser privacy policy.'});
});

test('Harmless NPCs wander across five cities and native shooting destroys one without an attack or discovery reward',async({page})=>{
 await enter(page);const initial=await snapshot(page);expect(initial.entities.npcCount).toBe(initial.world.cityDistricts*8);expect(initial.entities.npcs).toHaveLength(initial.entities.npcCount);expect(Object.keys(initial.entities.npcKinds)).toHaveLength(5);expect(Object.values(initial.entities.npcKinds).every(count=>count>0)).toBe(true);expect(new Set(initial.entities.npcs.map(npc=>npc.city)).size).toBe(initial.world.cityDistricts);expect(initial.entities.npcs.every(npc=>npc.id>=1000&&!npc.proactive&&!npc.hostile&&npc.attacks===0&&npc.damageEvents===0)).toBe(true);
 await walkUntil(page,'KeyW',s=>Math.abs(s.player.z-166)<7.5);await page.keyboard.press('KeyE');await expect.poll(async()=> (await snapshot(page)).warps).toBe(1);const arrived=await snapshot(page),candidate=[...arrived.entities.npcs].filter(npc=>npc.city==='city'&&npc.hp>0).sort((a,b)=>Math.hypot(a.x-arrived.player.x,a.z-arrived.player.z)-Math.hypot(b.x-arrived.player.x,b.z-arrived.player.z))[0],id=candidate.id,npcIn=s=>s.entities.npcs.find(npc=>npc.id===id);expect(Math.hypot(candidate.x-arrived.player.x,candidate.z-arrived.player.z)).toBeLessThan(45);
 await expect.poll(async()=>npcIn(await snapshot(page)).walked,{timeout:10000}).toBeGreaterThan(candidate.walked+.5);const wandered=await snapshot(page);expect(Math.hypot(npcIn(wandered).x-candidate.x,npcIn(wandered).z-candidate.z)).toBeGreaterThan(.1);
 await nativeAim(page,npcIn);await page.locator('#world').focus();await page.keyboard.down('KeyW');
 try{await expect.poll(async()=>{const s=await page.evaluate(()=>window.__ocv3D.tracking()),npc=npcIn(s);return Math.hypot(npc.x-s.player.x,npc.z-s.player.z);},{timeout:12000,intervals:[32,50]}).toBeLessThan(10);}finally{await page.keyboard.up('KeyW');}
 const approached=await snapshot(page);expect(Math.hypot(npcIn(approached).x-approached.player.x,npcIn(approached).z-approached.player.z)).toBeLessThan(11);let wounded=null;
 for(let attempt=0;attempt<16&&npcIn(await snapshot(page)).hp>0;attempt++){await nativeAim(page,npcIn);await page.locator('[data-fire]').press('Enter');await page.waitForTimeout(260);const s=await snapshot(page);if(!wounded&&npcIn(s).hp<candidate.hp){wounded=s;if(npcIn(s).hp>0)await expect.poll(async()=>npcIn(await snapshot(page)).healthVisible).toBe(true);await page.screenshot({path:path.join(reports,'3d-city-NPC-wounded.png')});}}
 expect(wounded).not.toBeNull();const destroyed=await snapshot(page);expect(npcIn(destroyed)).toMatchObject({hp:0,state:'seed',proactive:false,hostile:false,attacks:0,damageEvents:0,damageTotal:0});expect(destroyed.entities.npcKills).toBeGreaterThan(0);
 await nativeAim(page,npcIn);await page.locator('#world').focus();await walkUntil(page,'KeyW',s=>s.entities.npcCollected>0,20000);const collected=await snapshot(page);expect(npcIn(collected)).toMatchObject({state:'sleep',visible:false,attacks:0,damageEvents:0});expect(collected.cycle).toBe(initial.cycle);expect(collected.entities.collected).toBe(0);proof('native-city-NPC',{initial,arrived,wandered,approached,wounded,destroyed,collected,id,claim:'Actual arrow turns, right-button pointer dragging, a native walk to the moving NPC and native Enter fire damage, destroy and collect it. Lightweight tracking only reads coordinates and frames; no camera setter, injected hit or raycast replacement.'});
});

test('Native walking and portal action travel into city and river regions, replacing streamed terrain',async({page})=>{
 await enter(page);const initial=await snapshot(page);await walkUntil(page,'KeyW',s=>Math.abs(s.player.z-166)<7.5);await expect(page.locator('[data-travel]')).toHaveAttribute('data-ready','true');await page.keyboard.press('KeyE');await expect.poll(async()=> (await snapshot(page)).warps,{timeout:30000}).toBe(1);
 const city=await snapshot(page);expect(Math.hypot(city.player.x-initial.player.x,city.player.z-initial.player.z)).toBeGreaterThan(1000);expect(city.world.activeChunks).toBeLessThanOrEqual(25);expect(city.world.streamedTiles).toBeGreaterThan(initial.world.streamedTiles);expect(city.world.streamedDisposed).toBeGreaterThan(initial.world.streamedDisposed);expect(city.world.currentTile).not.toBe(initial.world.currentTile);expect(city.world.activeChunkKeys).not.toEqual(initial.world.activeChunkKeys);expect(city.player.grounded).toBe(true);expectNearTerrainCoverage(city);expect(city.world.farMask.minX).not.toBe(initial.world.farMask.minX);await settledView(page);await walkUntil(page,'ArrowLeft',s=>s.yaw>.45);await page.screenshot({path:path.join(reports,'3d-city.png')});const cityView=await snapshot(page);
 await expect.poll(async()=> (await snapshot(page)).time,{timeout:30000}).toBeGreaterThan(city.time+1.3);await page.keyboard.press('KeyE');await expect.poll(async()=> (await snapshot(page)).warps,{timeout:30000}).toBe(2);const river=await snapshot(page);expect(Math.hypot(river.player.x-city.player.x,river.player.z-city.player.z)).toBeGreaterThan(1000);expect(river.world.activeChunks).toBeLessThanOrEqual(25);expectNearTerrainCoverage(river);expect(river.world.farMask.minX).not.toBe(city.world.farMask.minX);await settledView(page);await walkUntil(page,'ArrowRight',s=>s.yaw<-.4);await walkUntil(page,'ArrowDown',s=>s.pitch<-.15);await page.screenshot({path:path.join(reports,'3d-river.png')});proof('native-portal-streaming',{initial,city,cityView,river,riverView:await snapshot(page)});
});

test('The native portal chain reaches all nine expanded cities and renders their distinct districts',async({page})=>{
 test.setTimeout(240000);await enter(page);const initial=await snapshot(page),cities=new Map(initial.world.cityRecords.map(city=>[city.id,city])),visited=[];expect(initial.world.cityDistricts).toBe(9);expect(cities.size).toBe(9);expect([...cities.keys()].sort()).toEqual(['city','north-city','white-plaza','arcade','spires','terrace-city','lagoon-city','horizon-city','capital'].sort());expect([...cities.values()].every(city=>city.buildings>=10)).toBe(true);expect(new Set([...cities.values()].map(city=>city.style)).size).toBe(9);expect(initial.world.buildings).toBeGreaterThan(900);expect(initial.world.buildings).toBeGreaterThan([...cities.values()].reduce((sum,city)=>sum+city.buildings,0));expect(initial.portals.map(p=>p.id)).toEqual(expect.arrayContaining([...cities.keys()]));
 await walkUntil(page,'KeyW',s=>Math.abs(s.player.z-166)<7.5);await activate(page.getByRole('button',{name:'切换全屏',exact:true}));await expect.poll(async()=> (await snapshot(page)).viewport.fullscreen).toBe(true);await page.locator('#world').focus();
 for(let step=1;step<initial.portals.length&&visited.length<cities.size;step++){
  if(step>1)await page.waitForTimeout(1300);await page.keyboard.press('KeyE');await expect.poll(async()=> (await snapshot(page)).warps,{timeout:30000}).toBe(step);const state=await snapshot(page),destination=initial.portals[step];expect(Math.hypot(state.player.x-destination.x,state.player.z-destination.z)).toBeLessThan(8);expect(state.world.activeChunks).toBeLessThanOrEqual(25);expectNearTerrainCoverage(state);
  if(!cities.has(destination.id))continue;expect(state.world.colliderSamples.some(collider=>collider.id.startsWith('tower-'))).toBe(true);await settledView(page);
  if(['white-plaza','arcade','spires'].includes(destination.id)){
   const center=cities.get(destination.id),targetYaw=Math.atan2(-(center.x-state.player.x),-(center.z-state.player.z));if(targetYaw>.06)await walkUntil(page,'ArrowLeft',s=>s.yaw>targetYaw-.06);else if(targetYaw<-.06)await walkUntil(page,'ArrowRight',s=>s.yaw<targetYaw+.06);await walkUntil(page,'ArrowUp',s=>s.pitch>(destination.id==='spires'?.3:.18));await page.screenshot({path:path.join(reports,`3d-${destination.id}.png`)});
  }
  visited.push({id:destination.id,state:await snapshot(page)});
 }
 expect(visited.map(city=>city.id).sort()).toEqual([...cities.keys()].sort());proof('native-nine-cities',{initial,visited,claim:'All nine arrivals and camera turns use native keyboard controls and the actual sequential portal chain; district views are captured in native fullscreen.'});
});

test('Sixteen varied meadow artifacts are real meshes and a new native portal reaches their giant landscape',async({page})=>{
 test.setTimeout(120000);await enter(page);const initial=await snapshot(page),artifacts=initial.world.meadowArtifacts;expect(artifacts.length).toBeGreaterThan(14);expect(artifacts.length).toBeLessThanOrEqual(18);expect(initial.world.meadowArtifactCount).toBe(artifacts.length);expect(new Set(artifacts.map(artifact=>artifact.kind)).size).toBeGreaterThanOrEqual(10);expect(new Set(artifacts.map(artifact=>artifact.placement)).size).toBe(4);expect(artifacts.every(artifact=>artifact.meshCount>0&&artifact.size>25&&Number.isFinite(artifact.x)&&Number.isFinite(artifact.y)&&Number.isFinite(artifact.z))).toBe(true);expect(initial.world.meadowArtifactMeshes).toBeGreaterThan(50);expect(artifacts.some(artifact=>artifact.grounded)).toBe(true);expect(artifacts.some(artifact=>artifact.floating)).toBe(true);
 const index=initial.portals.findIndex(portal=>portal.id==='m01');expect(index).toBeGreaterThan(initial.portals.findIndex(portal=>portal.id==='spires'));expect(initial.portals.map(portal=>portal.id)).toEqual(expect.arrayContaining(['m01','m02','m07','m09','m12','m15']));await walkUntil(page,'KeyW',s=>Math.abs(s.player.z-166)<7.5);
 for(let step=1;step<=index;step++){if(step>1)await page.waitForTimeout(1300);await page.keyboard.press('KeyE');await expect.poll(async()=> (await snapshot(page)).warps,{timeout:30000}).toBe(step);}
 const arrived=await snapshot(page);expect(Math.hypot(arrived.player.x-initial.portals[index].x,arrived.player.z-initial.portals[index].z)).toBeLessThan(8);expect(arrived.player.grounded).toBe(true);expectNearTerrainCoverage(arrived);await settledView(page);await activate(page.getByRole('button',{name:'切换全屏',exact:true}));await expect.poll(async()=> (await snapshot(page)).viewport.fullscreen).toBe(true);const artifact=artifacts.find(item=>item.id==='m01');await nativeAim(page,()=>({x:artifact.x,y:arrived.position.y+12,z:artifact.z}));await page.screenshot({path:path.join(reports,'3d-meadow-artifact.png')});const closeView=await snapshot(page);
 await nativeAim(page,s=>({x:s.position.x,y:s.position.y,z:s.position.z-20}));const retreatStart=await snapshot(page);await page.keyboard.down('ShiftLeft');try{await walkUntil(page,'KeyS',s=>s.player.z>retreatStart.player.z+135,12000);}finally{await page.keyboard.up('ShiftLeft');}await nativeAim(page,()=>({x:artifact.x,y:(artifact.bounds.minY+artifact.bounds.maxY)/2,z:artifact.z}));await page.screenshot({path:path.join(reports,'3d-meadow-artifact-overview.png')});proof('native-meadow-artifacts',{initial,arrived,closeView,retreatStart,overview:await snapshot(page),claim:'Generated mesh/placement records are combined with a real sequential portal journey, native fullscreen, a native sprint retreat and mouse/arrow camera input. No forced position or game-state setters.'});
});

test('Native pointer gesture locks or preserves drag fallback, and Escape leaves the fixed exit accessible',async({page})=>{
 await enter(page);const bounds=await page.locator('#world').boundingBox();await page.locator('#world').click({position:{x:bounds.width/2,y:bounds.height/2}});await page.waitForTimeout(250);const before=await snapshot(page);
 if(before.locked){await page.mouse.move(bounds.x+bounds.width*.65,bounds.y+bounds.height*.53,{steps:5});await expect.poll(async()=> Math.abs((await snapshot(page)).yaw-before.yaw)).toBeGreaterThan(.04);}else{await page.mouse.move(bounds.x+bounds.width*.4,bounds.y+bounds.height*.45);await page.mouse.down({button:'right'});await page.mouse.move(bounds.x+bounds.width*.65,bounds.y+bounds.height*.5,{steps:5});await page.mouse.up({button:'right'});await expect.poll(async()=> Math.abs((await snapshot(page)).yaw-before.yaw)).toBeGreaterThan(.04);}
 const turned=await snapshot(page);await page.keyboard.press('Escape');await expect.poll(()=>page.evaluate(()=>document.pointerLockElement===null)).toBe(true);await expect(page.getByRole('link',{name:'退出游戏',exact:true})).toBeVisible();expect(turned.mode).toBe('webgl');proof('native-pointer',{before,turned,claim:before.locked?'Native browser pointer lock and movement.':'Native right-button drag fallback because the browser did not grant pointer lock.'});
});

test('Native fullscreen enters and exits, and mute zeros the actual sound graph gain',async({page})=>{
 await installAudioProbe(page);await enter(page);const windowed=await page.locator('#world').boundingBox();await activate(page.getByRole('button',{name:'切换全屏',exact:true}));await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement)),{timeout:10000}).toBe(true);
 await expect.poll(()=>page.locator('#world').evaluate(node=>node.clientWidth===innerWidth&&node.clientHeight===innerHeight),{timeout:10000}).toBe(true);const fullscreen=await page.locator('#world').boundingBox();expect(fullscreen.width).toBeGreaterThan(windowed.width);expect(fullscreen.height).toBeGreaterThan(windowed.height);
 await page.keyboard.press('Escape');await expect.poll(()=>page.evaluate(()=>document.fullscreenElement===null),{timeout:10000}).toBe(true);await expect.poll(()=>page.locator('#world').boundingBox(),{timeout:10000}).toEqual(windowed);
 await activate(page.getByRole('button',{name:'静音',exact:true}));await expect(page.locator('[data-mute]')).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.evaluate(()=>window.__aeroNativeAudio.gains[0]?.gain.value)).toBe(0);expect((await snapshot(page)).audio.muted).toBe(true);
 await activate(page.getByRole('button',{name:'取消静音',exact:true}));await expect.poll(()=>page.evaluate(()=>window.__aeroNativeAudio.gains[0]?.gain.value)).toBeGreaterThan(.3);await expect(page.getByRole('link',{name:'退出游戏',exact:true})).toBeVisible();proof('native-fullscreen-sound',{state:await snapshot(page),windowed,fullscreen});
});

test('Hidden and persisted lifecycle hooks stop frames, movement and sound and resume without delayed travel',async({page})=>{
 await enter(page);await activate(page.getByRole('button',{name:'发射',exact:true}));await expect.poll(async()=> (await snapshot(page)).audio.state).toBe('running');
 await page.keyboard.down('KeyW');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await page.keyboard.up('KeyW');await expect.poll(async()=> (await snapshot(page)).audio.state).toBe('suspended');const hidden=await snapshot(page);await page.waitForTimeout(350);const resting=await snapshot(page);expect(resting.frames).toBe(hidden.frames);expect(resting.player).toEqual(hidden.player);
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await expect.poll(async()=> (await snapshot(page)).frames).toBeGreaterThan(hidden.frames);const resumed=await snapshot(page);expect(resumed.player.x).toBe(hidden.player.x);expect(resumed.player.z).toBe(hidden.player.z);
 await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));const suspended=await snapshot(page);await page.waitForTimeout(250);expect((await snapshot(page)).frames).toBe(suspended.frames);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect.poll(async()=> (await snapshot(page)).frames).toBeGreaterThan(suspended.frames);proof('lifecycle-hooks',{hidden,resumed,suspended,claim:'Synthetic document.hidden and persisted PageTransitionEvent exercise actual hooks; not evidence of a real BFCache hit or OS suspension.'});
});

test('Native exit navigates back to games and actual pagehide disposes the streamed world',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));await enter(page);const storageKey='__ocv.test.3d.departure',originalValue=await page.evaluate(key=>sessionStorage.getItem(key),storageKey);
 try{
  await page.evaluate(key=>{sessionStorage.setItem(key,JSON.stringify({event:'armed'}));window.addEventListener('pagehide',event=>{try{sessionStorage.setItem(key,JSON.stringify({event:'pagehide',persisted:event.persisted,state:window.__ocv3D.snapshot()}));}catch(error){sessionStorage.setItem(key,JSON.stringify({event:'error',error:error.stack}));}},{once:true});},storageKey);
  await page.getByRole('link',{name:'退出游戏',exact:true}).click();await expect(page).toHaveURL(/\/functions\/games\/$/);await expect(page.locator('#world')).toHaveCount(0);const saved=JSON.parse(await page.evaluate(key=>sessionStorage.getItem(key),storageKey));expect(saved.event).toBe('pagehide');expect(saved.persisted).toBe(false);const departed=saved.state;expect(departed.disposed).toBe(true);expect(departed.world.activeChunks).toBe(0);expect(departed.audio.state).toBe('disposed');expect(errors).toEqual([]);proof('native-disposal',{...departed,persisted:saved.persisted,claim:'A temporary test-only sessionStorage key transports a read-only snapshot from the real pagehide; the key is restored or removed immediately. No synthetic pagehide or game-state mutation.'});
 }finally{await page.evaluate(({key,value})=>{if(value===null)sessionStorage.removeItem(key);else sessionStorage.setItem(key,value);},{key:storageKey,value:originalValue}).catch(()=>{});}
});
