import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {reports} from './report-location.mjs';
const keyboard=async(page,control,key='Enter')=>{await control.focus();await page.keyboard.press(key);};
const save=(info,name,proof)=>fs.writeFileSync(path.join(reports,`interaction-${info.project.name}-${name}.json`),JSON.stringify(proof,null,2));
async function ready(page,url){await page.goto(url);await expect.poll(()=>page.evaluate(()=>window.__ocvLoose?.windows||0)).toBeGreaterThan(0);}
const position=node=>({x:node.getBoundingClientRect().left,y:node.getBoundingClientRect().top,offsetX:node.style.getPropertyValue('--loose-x'),offsetY:node.style.getPropertyValue('--loose-y')});

test('Original windows really move, twitch, close and restore without losing functional island state',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,'/maze/offices/settings/');
 await keyboard(page,page.getByRole('button',{name:'功能窗口置顶'}));await expect(page.locator('.feature-panel astro-island')).not.toHaveAttribute('ssr','');await page.getByRole('button',{name:'领票',exact:true}).click();await expect(page.getByTestId('pinia-count')).toContainText('1 张');
 const panel=page.locator('.feature-panel'),before=await panel.evaluate(position);
 await keyboard(page,panel.locator('[data-loose-drag]'),'ArrowRight');await keyboard(page,panel.locator('[data-loose-drag]'),'ArrowDown');const shifted=await panel.evaluate(position);
 expect(shifted.offsetX).toBe('24px');expect(shifted.offsetY).toBe('24px');expect(shifted.x-before.x).toBeCloseTo(24,0);expect(shifted.y-before.y).toBeCloseTo(24,0);
 if(info.project.name==='desktop'){const b=await panel.locator('[data-loose-drag]').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+68,b.y+b.height/2-35,{steps:4});await page.mouse.up();await expect.poll(()=>panel.evaluate(el=>Number.parseFloat(el.style.getPropertyValue('--loose-x')))).toBeCloseTo(92,0);}
 const shiver=page.locator('.result-container');await keyboard(page,shiver.locator('[data-loose-shake]'));const twitch=await shiver.evaluate(el=>el.getAnimations().filter(a=>a.effect?.target===el).map(a=>({duration:a.effect.getTiming().duration,keyframes:a.effect.getKeyframes().map(k=>k.transform)})));expect(twitch.some(a=>a.keyframes.includes('translate(19px, 2px)')||a.keyframes.some(k=>k?.includes('19px')))).toBe(true);
 await page.waitForTimeout(650);await keyboard(page,panel.locator('[data-loose-close]'));await expect(panel).toBeHidden();
 await page.getByRole('button',{name:'恢复所有窗口',exact:true}).click();await expect(panel).toBeVisible();await expect(page.getByTestId('pinia-count')).toContainText('1 张');const restored=await panel.evaluate(position);expect(restored.offsetX).toBe('0px');expect(restored.offsetY).toBe('0px');
 expect(await page.locator('.loose-wire').count()).toBe(4);expect(await page.locator('.loose-spark').count()).toBe(8);await expect.poll(()=>page.locator('.loose-wire').first().getAttribute('d')).toMatch(/^M.+C/);expect(errors).toEqual([]);
 save(info,'windows',{before,shifted,twitch,restored,state:await page.evaluate(()=>({...window.__ocvLoose})),errors});await page.screenshot({path:path.join(reports,`interaction-${info.project.name}-windows.png`)});
});

test('Teleport evasion uses a genuine 5–30 limit and the next activation closes it; reset permits another round',async({page},info)=>{
 await ready(page,'/maze/window/');const panel=page.locator('.floating-panel'),confirm=panel.locator('.fake-actions button').nth(1);
 if(info.project.name==='desktop'){await keyboard(page,panel.locator('.maze-title'),'ArrowLeft');const b=await confirm.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await expect.poll(async()=>Number(await panel.getAttribute('data-escapes'))).toBeGreaterThan(0);await page.mouse.move(-10,-10);await page.waitForTimeout(50);}else await keyboard(page,confirm);
 const limit=Number(await panel.getAttribute('data-escape-limit'));expect(Number.isInteger(limit)).toBe(true);expect(limit).toBeGreaterThanOrEqual(5);expect(limit).toBeLessThanOrEqual(30);
 for(let i=0;Number(await panel.getAttribute('data-escapes'))<limit;i++){expect(i).toBeLessThan(30);await keyboard(page,confirm);}expect(Number(await panel.getAttribute('data-escapes'))).toBe(limit);await expect(panel).not.toHaveAttribute('hidden','');
 const proof={limit,escapes:Number(await panel.getAttribute('data-escapes')),position:await panel.evaluate(position)};await keyboard(page,confirm);await expect(panel).toBeHidden();await page.getByRole('button',{name:'恢复所有窗口',exact:true}).click();await expect(panel).not.toHaveAttribute('hidden','');await keyboard(page,confirm);const nextLimit=Number(await panel.getAttribute('data-escape-limit'));expect(nextLimit).toBeGreaterThanOrEqual(5);expect(nextLimit).toBeLessThanOrEqual(30);expect(Number(await panel.getAttribute('data-escapes'))).toBe(1);save(info,'teleport',{...proof,nextLimit,state:await page.evaluate(()=>({...window.__ocvLoose}))});
});

test('Continuous evasion keeps varying speed and direction, pauses only for background/reduced motion and resumes after restore',async({page},info)=>{
 await ready(page,'/maze/window/');const panel=page.locator('.floating-panel');await keyboard(page,panel.locator('[data-loose-run]'));const samples=[];
 for(let i=0;i<4;i++){await page.waitForTimeout(1000);samples.push({position:await panel.evaluate(position),velocity:await panel.evaluate(el=>[Number(el.dataset.velocityX),Number(el.dataset.velocityY)]),state:await page.evaluate(()=>({...window.__ocvLoose}))});}
 expect(new Set(samples.map(s=>s.position.offsetX+','+s.position.offsetY)).size).toBe(4);expect(samples.at(-1).state.runningFrames).toBeGreaterThan(samples[0].state.runningFrames);expect(samples.at(-1).state.directionChanges-samples[0].state.directionChanges).toBeGreaterThanOrEqual(2);await expect(panel).toHaveAttribute('data-running','true');
 expect(new Set(samples.map(s=>Math.hypot(...s.velocity).toFixed(2))).size).toBeGreaterThan(1);expect(new Set(samples.map(s=>Math.atan2(s.velocity[1],s.velocity[0]).toFixed(2))).size).toBeGreaterThan(1);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const paused=await panel.evaluate(position);await page.waitForTimeout(350);expect(await panel.evaluate(position)).toEqual(paused);expect(await page.evaluate(()=>window.__ocvLoose.suspended)).toBe(true);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await expect.poll(()=>panel.evaluate(el=>el.style.getPropertyValue('--loose-x'))).not.toBe(paused.offsetX);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(150);const reduced=await panel.evaluate(position);await page.waitForTimeout(350);expect(await panel.evaluate(position)).toEqual(reduced);await expect(panel).toHaveAttribute('data-running','true');expect(await page.locator('.loose-wire').first().evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
 await page.emulateMedia({reducedMotion:'no-preference'});await expect.poll(()=>panel.evaluate(el=>el.style.getPropertyValue('--loose-x'))).not.toBe(reduced.offsetX);await keyboard(page,panel.locator('[data-loose-close]'));await expect(panel).toBeHidden();
 await page.getByRole('button',{name:'恢复所有窗口',exact:true}).click();await expect(panel).not.toHaveAttribute('hidden','');const resetPosition=await panel.evaluate(position);await expect.poll(()=>panel.evaluate(el=>el.style.getPropertyValue('--loose-x'))).not.toBe(resetPosition.offsetX);await expect(panel).toHaveAttribute('data-running','true');await keyboard(page,panel.locator('[data-loose-close]'));await page.getByRole('link',{name:'退出迷宫返回主页'}).click();await expect(page).toHaveURL(/\/#systems$/);
 save(info,'continuous',{samples,paused,reduced,resumesAfterRestore:true,onlyClosedByExplicitAction:true});
});

test('Optical gestures actually turn Three objects, emit a GPU wave, ray-pick geometry and command the light renderer',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'reduce'});await ready(page,'/#systems');await expect.poll(()=>page.evaluate(()=>window.__ocvReactor?.renderer),{timeout:30000}).toBe('three-webgl2');await expect(page.locator('[data-optical-lens]')).not.toHaveAttribute('inert','');
 const before=await page.evaluate(()=>({...window.__ocvReactor}));await keyboard(page,page.locator('[data-orbit]'),'ArrowRight');await keyboard(page,page.locator('[data-orbit]'),'ArrowDown');await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.turns)).toBeGreaterThan(before.turns);await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.spin.x)).not.toBe(before.spin.x);
 await keyboard(page,page.locator('[data-optical-pulse]'));await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.pulses)).toBeGreaterThan(0);await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.waveScale)).toBeGreaterThan(0);expect(await page.evaluate(()=>window.__ocvReactor.gpuError)).toBe(0);
 const matrixBit=page.locator('.bit-matrix i').first(),bit=await matrixBit.getAttribute('aria-pressed');await keyboard(page,matrixBit);await expect(matrixBit).toHaveAttribute('aria-pressed',String(bit!=='true'));
 const lensBefore=await page.locator('[data-optical-lens]').evaluate(position);await keyboard(page,page.locator('[data-lens-grip]'),'ArrowLeft');expect((await page.locator('[data-optical-lens]').evaluate(position)).x-lensBefore.x).toBeCloseTo(-24,0);
 // Clear obstructing old windows through their real close buttons, then pick the projected real core.
 for(let i=0;i<30;i++){const covering=await page.evaluate(()=>{const p=window.__ocvReactor.pickPoint,el=document.elementFromPoint(p.x,p.y)?.closest('[data-loose-window]');return el?.dataset.looseWindow??null;});if(covering===null)break;const pane=page.locator(`[data-loose-window="${covering}"]`),close=pane.locator('[data-loose-close]').first();if(await close.count())await keyboard(page,close);else for(let n=0;n<6;n++)await keyboard(page,pane.locator('.loose-handle').first(),'ArrowRight');}
 const hit=await page.evaluate(()=>window.__ocvReactor.pickPoint);await page.mouse.move(hit.x,hit.y);await page.mouse.down();await page.mouse.move(hit.x+48,hit.y+20,{steps:3});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.picks)).toBeGreaterThan(0);await expect.poll(()=>page.evaluate(()=>window.__ocvReactor.turns)).toBeGreaterThan(before.turns+2);
 const main=await page.evaluate(()=>({...window.__ocvReactor}));await page.screenshot({path:path.join(reports,`interaction-${info.project.name}-gpu.png`)});
 await ready(page,'/portals/light/');await expect.poll(()=>page.evaluate(()=>window.__ocvLight?.frames||0)).toBeGreaterThan(0);await keyboard(page,page.locator('[data-orbit]'),'ArrowRight');await keyboard(page,page.locator('[data-orbit]'),'ArrowDown');await keyboard(page,page.locator('[data-optical-pulse]'));await expect.poll(()=>page.evaluate(()=>window.__ocvLight.pulses)).toBeGreaterThan(0);const light=await page.evaluate(()=>({...window.__ocvLight}));expect(light.spin.x).not.toBe(0);expect(light.scale).toBeGreaterThan(1);expect(light.gpuError).toBe(0);expect(errors).toEqual([]);save(info,'gpu',{before,main,light,errors});
});

test('Exactly two upright small original memes are hidden behind the deep-route button and fetched only on activation',async({page,request},info)=>{
 const images=[];page.on('request',r=>{const pathname=new URL(r.url()).pathname;if(['/forgotten-cache/03.avif','/forgotten-cache/04.jpg'].includes(pathname))images.push(pathname);});await ready(page,'/maze/cache/l1/l2/');await expect(page.locator('#forgotten-drawer')).toBeHidden();await expect(page.locator('#forgotten-drawer img')).toHaveCount(0);expect(images).toEqual([]);
 await page.getByRole('button',{name:'功能窗口置顶'}).click();await keyboard(page,page.locator('[data-attachment-toggle]'));await expect(page.locator('#forgotten-drawer')).toBeVisible();await expect(page.locator('#forgotten-drawer img')).toHaveCount(2);await expect.poll(()=>page.locator('#forgotten-drawer img').evaluateAll(els=>els.every(el=>el.complete&&el.naturalWidth>0))).toBe(true);
 const sizes=await page.locator('#forgotten-drawer img').evaluateAll(els=>els.map(el=>({src:new URL(el.src).pathname,natural:[el.naturalWidth,el.naturalHeight],display:[el.getBoundingClientRect().width,el.getBoundingClientRect().height],transform:getComputedStyle(el).transform,rotate:getComputedStyle(el).rotate})));for(const s of sizes){expect(s.display[0]).toBeLessThanOrEqual(132.1);expect(s.display[1]).toBeLessThanOrEqual(164.1);expect(['none','matrix(1, 0, 0, 1, 0, 0)']).toContain(s.transform);expect(['none','0deg']).toContain(s.rotate);}
 const hashes=[];for(const [url,expected] of [['/forgotten-cache/03.avif','203528bdad8433cfae591b738c3735911d9e2f64ed62ecac8e39f5dcf9b494d1'],['/forgotten-cache/04.jpg','2a20947007080740983e6d20981984b3b428d8d63065a6f1cbc31690bb04293f']]){const r=await request.get(url);expect(r.status()).toBe(200);const hash=createHash('sha256').update(await r.body()).digest('hex');expect(hash).toBe(expected);hashes.push({url,hash});}
 await page.screenshot({path:path.join(reports,`interaction-${info.project.name}-attachments.png`)});await keyboard(page,page.locator('[data-attachment-close]'));await expect(page.locator('#forgotten-drawer')).toBeHidden();await keyboard(page,page.locator('[data-attachment-toggle]'));await expect(page.locator('#forgotten-drawer')).toBeVisible();await expect(page.locator('#forgotten-drawer img')).toHaveCount(2);expect(images.length).toBe(2);
 await page.goto('/maze/cache/');await expect(page.locator('[data-attachment-toggle],#forgotten-drawer')).toHaveCount(0);const attachmentRequests=images.slice();await page.goto('/');await expect(page.locator('img')).toHaveCount(1);await expect(page.locator('#forgotten-drawer,[data-attachment-toggle]')).toHaveCount(0);save(info,'attachments',{sizes,hashes,requestsBeforeActivation:0,requestsAfterActivation:attachmentRequests,otherRoutesDoNotMount:true});
});

test('老吴 opens the original animated GIF large and centered, has no dismiss control and expires after 12 seconds without renewal',async({page,request},info)=>{
 const requests=[];page.on('request',r=>{if(r.url().includes('/forgotten-cache/laowu.gif'))requests.push(r.url());});await ready(page,'/maze/empty/');const trigger=page.getByRole('button',{name:'老吴',exact:true}),visit=page.locator('.laowu-visit');await expect(trigger).toBeVisible();await expect(visit).toBeHidden();expect(requests).toEqual([]);
 await trigger.click();await expect(visit.locator('img')).toBeVisible();await expect.poll(()=>visit.locator('img').evaluate(el=>el.complete&&el.naturalWidth>0)).toBe(true);
 const activated=await page.evaluate(()=>({...window.__ocvLaowu}));const dimensions=await visit.locator('img').evaluate(el=>{const b=el.getBoundingClientRect();return{size:[b.width,b.height],center:[b.left+b.width/2,b.top+b.height/2],viewport:[innerWidth,innerHeight]};});expect(dimensions.size[1]).toBeGreaterThan(350);expect(dimensions.center[0]).toBeCloseTo(dimensions.viewport[0]/2,0);expect(dimensions.center[1]).toBeCloseTo(dimensions.viewport[1]/2,0);
 await expect(visit.locator('button,[data-loose-close]')).toHaveCount(0);await page.keyboard.press('Escape');await expect(visit).toBeVisible();
 await trigger.click();expect(await page.evaluate(()=>window.__ocvLaowu.expiresAt)).toBe(activated.expiresAt);expect(await page.evaluate(()=>window.__ocvLaowu.opens)).toBe(1);
 await page.screenshot({path:path.join(reports,`interaction-${info.project.name}-laowu.png`)});
 // Canvas drawImage uses an animated image's default frame. Capture the actually displayed GIF instead.
 const frames=[];for(let i=0;i<2;i++){await page.waitForTimeout(550);const shot=await visit.locator('img').screenshot({path:path.join(reports,`interaction-${info.project.name}-laowu-frame-${i}.png`)});frames.push(createHash('sha256').update(shot).digest('hex'));}expect(new Set(frames).size).toBeGreaterThan(1);
 const remaining=activated.expiresAt-Date.now();if(remaining>2200){await page.waitForTimeout(remaining-1700);await expect(visit).toBeVisible();}await expect(visit).toBeHidden({timeout:3500});const endedAt=Date.now();expect(endedAt).toBeGreaterThanOrEqual(activated.expiresAt);expect(await page.evaluate(()=>window.__ocvLaowu.opens)).toBe(1);
 const response=await request.get('/forgotten-cache/laowu.gif');expect(response.status()).toBe(200);const hash=createHash('sha256').update(await response.body()).digest('hex');expect(hash).toBe('07a15512be22e86c9315a310cc91c1605aacdd4ce3b3689dd31b99fce36f6c89');
 await page.emulateMedia({reducedMotion:'reduce'});await trigger.click();await expect(visit.locator('canvas')).toBeVisible();await expect(visit.locator('img')).toHaveCount(0);const still=await visit.locator('canvas').evaluate(el=>el.toDataURL());await page.waitForTimeout(350);expect(await visit.locator('canvas').evaluate(el=>el.toDataURL())).toBe(still);await page.getByRole('link',{name:'退出迷宫返回主页'}).click();await expect(page).toHaveURL(/\/#systems$/);save(info,'laowu',{activated,dimensions,observedAnimatedFrames:new Set(frames).size,endedAt,hash,repeatClickDoesNotRenew:true,reducedMotionIsStill:true,exitRemainsOperable:true});
});

test('Window controls differ and selected panes move and shiver by themselves while the cover stays quiet',async({page},info)=>{
 await ready(page,'/');await expect(page.locator('.loose-lens')).toBeHidden();await page.waitForTimeout(500);expect(await page.evaluate(()=>window.__ocvLoose.autoJolts)).toBe(0);expect(await page.evaluate(()=>window.__ocvLoose.runningFrames)).toBe(0);
 await ready(page,'/portals/unified/');const weather=page.locator('.portal-weather'),before=await weather.evaluate(position);await page.waitForTimeout(950);const after=await weather.evaluate(position);expect(after.offsetX+after.offsetY).not.toBe(before.offsetX+before.offsetY);const automatic=await page.evaluate(()=>({...window.__ocvLoose}));expect(automatic.autoMoving).toBeGreaterThan(0);expect(automatic.dragCount).toBe(0);expect(automatic.runaways).toBe(0);expect(automatic.pulses).toBe(0);
 const toolsets=automatic.toolsets;expect(new Set(toolsets.map(s=>s.buttons.join(','))).size).toBeGreaterThanOrEqual(3);expect(Math.max(...toolsets.map(s=>s.buttons.length))).toBeLessThanOrEqual(2);expect(toolsets.some(s=>s.buttons.length===0)).toBe(true);
 await ready(page,'/maze/window/');const pane=page.locator('.panel_v2');await expect.poll(()=>pane.evaluate(el=>el.getAnimations().some(a=>a.effect?.target===el)),{intervals:[50,100],timeout:5000}).toBe(true);const twitch=await pane.evaluate(el=>el.getAnimations().filter(a=>a.effect?.target===el).map(a=>({duration:a.effect.getTiming().duration,keyframes:a.effect.getKeyframes().map(k=>k.transform)})));const untouched=await page.evaluate(()=>({...window.__ocvLoose}));expect(untouched.autoJolts).toBeGreaterThan(0);expect(untouched.dragCount).toBe(0);expect(untouched.pulses).toBe(0);expect(twitch.length).toBeGreaterThan(0);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(200);const quiet=await page.evaluate(()=>window.__ocvLoose.autoJolts);await page.waitForTimeout(300);expect(await page.evaluate(()=>window.__ocvLoose.autoJolts)).toBe(quiet);expect(await pane.evaluate(el=>el.getAnimations().filter(a=>a.effect?.target===el).length)).toBe(0);await page.getByRole('link',{name:'退出迷宫返回主页'}).click();await expect(page).toHaveURL(/\/#systems$/);save(info,'personalities',{before,after,toolsets,automatic,untouched,twitch,reducedMotionStopsAutomaticJolts:true});
});

test('The supplied home meme is in a new small upright frame after entry, with native dragging and closing',async({page,request},info)=>{
 await page.emulateMedia({reducedMotion:'reduce'});await ready(page,'/');
 const pane=page.locator('.home-image-note'),image=pane.locator('img');await expect(image).toHaveCount(1);expect(await pane.evaluate(el=>el.closest('.wrong-windows').inert&&getComputedStyle(el.closest('.wrong-windows')).opacity==='0')).toBe(true);
 // Keep the same deadline, but let one in-page assertion observe the native attribute.
 // Repeated locator.evaluate adds selector/handle round trips behind the first GPU draw.
 await page.getByRole('link',{name:'进入主页',exact:true}).click();await expect(page.locator('.wrong-windows')).not.toHaveAttribute('inert','');await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(el=>el.complete&&el.naturalWidth>0)).toBe(true);
 const display=await image.evaluate(el=>({size:[el.getBoundingClientRect().width,el.getBoundingClientRect().height],natural:[el.naturalWidth,el.naturalHeight],rotate:getComputedStyle(el).rotate,transform:getComputedStyle(el).transform}));expect(display.size[0]).toBeLessThanOrEqual(120.1);expect(display.size[1]).toBeLessThanOrEqual(132.1);expect(['none','0deg']).toContain(display.rotate);expect(['none','matrix(1, 0, 0, 1, 0, 0)']).toContain(display.transform);await expect(pane.locator('.loose-tools')).toHaveCount(0);
 const before=await pane.evaluate(position);await keyboard(page,pane.locator('.wrong-title'),'ArrowRight');const moved=await pane.evaluate(position);expect(moved.x-before.x).toBeCloseTo(24,0);await page.screenshot({path:path.join(reports,`interaction-${info.project.name}-home-image.png`)});
 await keyboard(page,pane.getByRole('button',{name:'关闭图片',exact:true}));await expect(pane).toBeHidden();await page.getByRole('button',{name:'恢复所有窗口',exact:true}).click();await expect(image).toBeVisible();expect((await pane.evaluate(position)).offsetX).toBe('0px');
 const response=await request.get('/forgotten-cache/home-04.avif');expect(response.status()).toBe(200);const hash=createHash('sha256').update(await response.body()).digest('hex');expect(hash).toBe('a742ff427a19e9e6f2975de0e398dc2075a40cde916a964824c70ed6a94e32cb');await page.goto('/portals/unified/');await expect(page.locator('.home-image-note')).toHaveCount(0);
 save(info,'home-image',{display,before,moved,hash,quietCover:true,nativeDragCloseRestore:true,onlyClassicHome:true});
});
