import {testDeps} from '../runtime-location.mjs';
import {test,expect} from '@playwright/test';import path from 'node:path';
const reports=path.join(testDeps,'runtime/reports');
test('White identity scene, no former memes or gimmick forms, real dense bounded WebGL and responsive layout',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'OMNICIVITAS',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>window.__ocvOptics?.frames||0)).toBeGreaterThan(4);expect(await page.evaluate(()=>window.__ocvOptics.renderer)).toBe('webgl');expect(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor)).toBe('rgb(248, 251, 253)');await expect(page.locator('img,form,input,iframe')).toHaveCount(0);await expect(page.locator('.identity-scene .instrument')).toHaveCount(0);expect(await page.evaluate(()=>window.__ocvOptics.cover)).toBe(true);await expect(page.getByText(/System loading|饭还没好|临时管理员|保洁|NO COMMON/)).toHaveCount(0);
 const scene=await page.evaluate(()=>({...window.__ocvOptics,canvas:[document.querySelector('canvas').width,document.querySelector('canvas').height],overflow:document.documentElement.scrollWidth-innerWidth}));expect(scene.lineSegments).toBeGreaterThan(10000);expect(scene.pointCount).toBeGreaterThan(5000);expect(Math.max(...scene.canvas)).toBeLessThanOrEqual(1600);expect(scene.overflow).toBeLessThan(3);await page.waitForTimeout(1500);await page.screenshot({path:path.join(reports,`luminous-${info.project.name}-hero.png`)});expect(errors).toEqual([]);
});
test('Geometry buttons actually morph the GPU field, gallery advances and selected figures remain keyboard operable',async({page},info)=>{
 await page.goto('/');await page.locator('.geometry-controls').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'流线',exact:true}).click();await expect(page.getByRole('button',{name:'流线',exact:true})).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.evaluate(()=>window.__ocvOptics.activeGeometry)).toBe(2);await expect.poll(()=>page.evaluate(()=>window.__ocvOptics.morph)).toBeGreaterThan(1.9);
 await page.locator('#gallery-next').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'下一组图形'}).click();await expect.poll(()=>page.locator('#geometry-gallery').evaluate(el=>el.scrollLeft)).toBeGreaterThan(100);await page.getByRole('button',{name:'上一组图形'}).click();await expect.poll(()=>page.locator('#geometry-gallery').evaluate(el=>el.scrollLeft)).toBeLessThan(15);const specimen=page.locator('.specimen').first();await specimen.focus();await page.keyboard.press('Enter');await expect(specimen).toHaveAttribute('aria-pressed','true');await page.waitForTimeout(450);await page.screenshot({path:path.join(reports,`luminous-${info.project.name}-collection.png`)});
});
test('Scrolling crosses coherent scenes, progress moves and reduced motion draws once while navigation works',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await expect.poll(()=>page.evaluate(()=>window.__ocvOptics?.frames||0)).toBeGreaterThan(0);const frames=await page.evaluate(()=>window.__ocvOptics.frames);await page.waitForTimeout(180);expect(await page.evaluate(()=>window.__ocvOptics.frames)).toBe(frames);expect(await page.evaluate(()=>getComputedStyle(document.querySelector('.orbit-a')).animationName)).toBe('none');await page.getByRole('link',{name:'进入主页',exact:true}).click();await expect(page.locator('.systems-sticky')).toBeInViewport();await page.getByRole('button',{name:'阵列',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.__ocvOptics.activeGeometry)).toBe(3);await page.getByRole('link',{name:'图形',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Number(getComputedStyle(document.documentElement).getPropertyValue('--progress')))).toBeGreaterThan(.4);await page.getByRole('link',{name:'返回顶部'}).click();await expect(page.getByRole('heading',{name:'OMNICIVITAS',exact:true})).toBeInViewport();
});
test('Without WebGL the identity and controls remain accessible; status is real and old public assets are absent',async({page,request})=>{
 await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:get.call(this,type,...args);};});await page.goto('/');await expect(page.locator('.css-fallback')).toBeVisible();expect(await page.evaluate(()=>window.__ocvOptics.renderer)).toBe('css');await page.getByRole('link',{name:'进入主页',exact:true}).click();await page.getByRole('link',{name:'运行状态',exact:true}).click();await expect(page.locator('#status')).toContainText('accountSystem');await expect(page.locator('#refresh')).toBeEnabled();const meme=await request.get('/memes/m01.webp');expect(meme.status()).toBe(404);await page.goto('/borrowed');await expect(page).toHaveURL(/\/#systems$/);await expect(page.locator('form,iframe')).toHaveCount(0);await page.goto('/corridors/error/another-floor/tape');await expect(page).toHaveURL(/\/#home$/);
});

