import {testDeps} from '../runtime-location.mjs';
import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
const reports=path.join(testDeps,'runtime/reports');
async function home(page){await page.goto('/');await expect(page.locator('#storage-note')).toHaveText('抽屉已打开');}
test('Vue Pinia vee-validate Element Plus, Svelte Store, Solid, Lit Shadow DOM, Alpine, htmx, jQuery and mixed styles really interact',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await home(page);
 await page.getByLabel('票名').fill('晚饭');await page.getByRole('button',{name:'领票',exact:true}).click();await expect(page.getByTestId('pinia-count')).toContainText('1 张 · 晚饭');
 await page.getByLabel('票名').fill('');await page.getByRole('button',{name:'领票',exact:true}).click();await expect(page.locator('[data-framework="vue"]')).toContainText('写 1—40 个字');await expect(page.getByTestId('pinia-count')).toContainText('1 张');
 await page.getByRole('button',{name:'再停一次',exact:true}).click();await expect(page.getByTestId('svelte-count')).toHaveText('1');
 await page.getByRole('button',{name:'翻面',exact:true}).click();await expect(page.getByTestId('solid-word')).toHaveText('不在。');
 await page.locator('stamp-of-stamp').getByRole('button',{name:'盖章'}).click();await expect(page.locator('stamp-of-stamp').locator('p')).toHaveText('1 次');
 await page.getByRole('button',{name:'展开 / 收起'}).click();await expect(page.getByText('食堂把财务科借走了。')).toBeVisible();await page.getByRole('button',{name:'展开 / 收起'}).click();await expect(page.getByText('食堂把财务科借走了。')).toBeHidden();
 await page.getByRole('button',{name:'取一小块公告'}).click();await expect(page.locator('#htmx-output [data-fragment="pantry"]')).toHaveText('今日公告饭已凉。窗口未凉。');
 await page.getByRole('button',{name:'老电话接通'}).click();await expect(page.locator('#jquery-output')).toContainText('NestJS');
 await page.getByRole('button',{name:'擦 Vue 的字'}).click();await expect(page.locator('[data-jquery-display="vue"]')).toHaveClass(/ocv-jquery-painted/);await expect(page.locator('[data-jquery-display="vue"]')).toHaveText('保洁经过：这句只管显示');
 await page.getByLabel('票名').fill('早餐');await page.getByRole('button',{name:'领票',exact:true}).click();await expect(page.getByTestId('pinia-count')).toContainText('2 张 · 早餐');
 await expect(page.locator('#jquery-extra')).toBeVisible();await page.getByRole('button',{name:'藏附件'}).click();await expect(page.locator('#jquery-extra')).toBeHidden();
 expect(await page.evaluate(()=>new Set(['[data-framework="vue"]','[data-framework="svelte"]','[data-framework="solid"]','.history-patch'].map(s=>getComputedStyle(document.querySelector(s)).backgroundColor)).size)).toBe(4);
 await expect(page.getByRole('button',{name:'停止乱动'})).toHaveCount(0);await page.emulateMedia({reducedMotion:'reduce'});expect(await page.evaluate(()=>getComputedStyle(document.querySelector('.jitter-piece')).animationName)).toBe('none');
 await page.screenshot({path:path.join(reports,(process.env.OCV_SCREENSHOT_PREFIX||'phase3')+'-'+info.project.name+'-home.png'),fullPage:true});expect(errors).toEqual([]);
});
test('IndexedDB-only split object, CSV Cache Storage CSS SVG DOM hash, session and local storage restore; exported JSON and deterministic rebuild',async({page})=>{
 const sent=[];page.on('request',r=>sent.push(r.url()+' '+(r.postData()||'')));await home(page);
 const privateBody='仅留抽屉-本机专用-'+Date.now();await page.locator('#cabinet-body').fill(privateBody);await page.getByRole('button',{name:'存入抽屉'}).click();await expect(page.locator('#object-output')).toContainText(privateBody);
 expect(await page.evaluate(()=>window.__ocvFront.validation)).toEqual({joi:true,yup:true,zod:true,validator:true,manualIfCount:23});
 await page.getByRole('button',{name:'换标签',exact:true}).click();await expect(page.locator('#object-output')).toContainText('冷饭');await page.getByRole('button',{name:'改状态',exact:true}).click();await expect(page.locator('#object-output')).toContainText('已归档');
 const record=await page.evaluate(()=>window.__ocvFront.object);expect(record.prefix).toBe('第零号-');expect(record.description).toBe('原件在锅底，影印件也在锅底');expect(record.source.body).toBe('IndexedDB only');expect(record.id).not.toBe('temporary');
 await page.locator('#local-value').fill('77');await page.getByRole('button',{name:'保存',exact:true}).click();await page.evaluate(()=>sessionStorage.setItem('ocv_plastic_delegate','塑料勺代表'));
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'数据库迁移 ↓'}).click()]);const file=path.join(reports,'phase3-browser-export-'+Date.now()+'.json');await download.saveAs(file);const exported=JSON.parse(fs.readFileSync(file));expect(exported.version).toBe(1);expect(exported.record.body).toBe(privateBody);expect(exported.record.statusAlias).toBe('已归档');
 await page.reload();await expect(page.locator('#storage-note')).toHaveText('抽屉已打开');await expect(page.locator('#cabinet-body')).toHaveValue(privateBody);await expect(page.locator('#local-value')).toHaveValue('77');await expect(page.locator('#session-badge')).toHaveText('塑料勺代表');await expect(page.locator('#object-output')).toContainText('已归档');
 const local=await page.evaluate(()=>({keys:Object.keys(localStorage).map(k=>localStorage.getItem(k)).join(' '),cookie:document.cookie,cache:'caches'in window}));expect(local.keys).not.toContain(privateBody);expect(local.cookie).toContain('ocv_pebble=43');expect(local.cache).toBe(true);expect(sent.join('\n')).not.toContain(privateBody);
 await page.getByRole('button',{name:'清除本模块存储并重建'}).click();await expect(page.locator('#cabinet-body')).toHaveValue('未初始化');await expect(page.locator('#object-output')).toContainText('热锅');await expect(page.locator('#object-output')).toContainText('待盖章');
});
test('BroadcastChannel horizontal expansion, bounded WorkerManagerFactory, Math Lodash Ramda IDs and five date libraries',async({page,context})=>{
 await home(page);const second=await context.newPage();await second.goto('/?expanded=1');await expect(second.locator('#storage-note')).toHaveText('抽屉已打开');await page.getByRole('button',{name:'敲隔壁标签'}).click();await expect(second.locator('#channel-output')).toHaveText('隔壁标签：1');
 await page.getByRole('button',{name:'计算 2 + 2'}).click();await expect(page.locator('#worker-output')).toContainText('workerAnswer');const u=await page.evaluate(()=>window.__ocvFront.utilities);expect(u.workerAnswer).toBe(4);expect(u.mathAnswer).toBe(4);expect(u.empty).toBe(true);expect(u.normalized).toBe('OCV');expect(u.ids.native).toMatch(/^[\da-f-]{36}$/);expect(u.ids.package).toMatch(/^[\da-f-]{36}$/);expect(u.ids.short.length).toBeGreaterThan(10);
 const dates=await page.evaluate(()=>window.__ocvFront.dates);expect(dates.native).toBe('2026-10-01T19:14:00.000Z');expect(dates.moment).toBe('2026/10/02 03:14');expect(dates.dayjs).toBe(dates.native);expect(dates.luxon).toBe(dates.moment);expect(dates.dateFns).toMatch(/^2026-10-0[12]$/);
 const [third]=await Promise.all([context.waitForEvent('page'),page.getByRole('button',{name:'横向扩容 ↗'}).click()]);await third.waitForLoadState();expect(new URL(third.url()).searchParams.get('expanded')).toBe('1');await third.close();await second.close();
});
test('Next React Redux URL/local restoration, Zustand MobX Jotai XState RxJS, RHF/Formik and Ant MUI Tailwind Bootstrap styled Emotion',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/borrowed?invoiceMood=7&role=勺代表');await expect(page.getByTestId('redux-count')).toHaveText('7');
 await page.getByRole('button',{name:'领一个号',exact:true}).click();await expect(page.getByTestId('redux-count')).toHaveText('8');expect(await page.evaluate(()=>localStorage.getItem('ocv_goods_delivery'))).toBe('8');expect(new URL(page.url()).searchParams.get('invoiceMood')).toBe('8');
 await page.getByRole('button',{name:'折收据',exact:true}).click();await expect(page.getByTestId('zustand-state')).toHaveText('收据折了');await page.getByRole('button',{name:'补记',exact:true}).click();await expect(page.getByTestId('mobx-count')).toHaveText('1');
 await page.getByRole('button',{name:'看附件',exact:true}).click();await expect(page.getByRole('dialog',{name:'空附件'})).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'翻审批',exact:true}).click();await expect(page.getByTestId('xstate')).toHaveText('已盖章');for(let i=0;i<3;i++)await page.getByRole('button',{name:'连敲几下'}).click();await expect(page.getByTestId('rxjs-count')).toHaveText('收到 1 次');
 await page.getByLabel('另一张表的备注').fill('锅已洗');await page.getByRole('button',{name:'附上',exact:true}).click();await expect(page.getByTestId('formik-result')).toHaveText('备注：锅已洗');
 await page.getByRole('button',{name:'问窗口怎么叫我'}).click();await expect(page.getByTestId('role-result')).toContainText('勺代表 · 无权限作用');
 const mixed=await page.getByTestId('mixed-style').evaluate(el=>({layout:getComputedStyle(el).display,button:getComputedStyle(el.querySelector('.btn')).backgroundColor,ridge:getComputedStyle(el.parentElement).borderTopStyle,oil:getComputedStyle(el.querySelector('[data-testid="redux-count"]')).borderTopRightRadius}));expect(mixed.layout).toBe('flex');expect(mixed.ridge).toBe('ridge');expect(mixed.button).not.toBe('rgba(0, 0, 0, 0)');expect(mixed.oil).toBe('22px');
 await page.getByRole('button',{name:'领一个号',exact:true}).hover();await expect(page.getByRole('tooltip')).toContainText('只存一个显示数字');
 await page.reload();await expect(page.getByTestId('redux-count')).toHaveText('8');await page.goto('/borrowed');await expect(page.getByTestId('redux-count')).toHaveText('8');
 await page.screenshot({path:path.join(reports,(process.env.OCV_SCREENSHOT_PREFIX||'phase3')+'-'+info.project.name+'-next.png'),fullPage:true});expect(errors).toEqual([]);
});
test('Real Next API to Nest/PostgreSQL, Redis to localStorage to TanStack memory; failures allow retry and password-shaped fields are refused',async({page,request})=>{
 await page.goto('/borrowed');let cacheRequests=0;page.on('request',r=>{if(r.url().includes('/api/browser-cache.php/'))cacheRequests++;});
 await page.getByLabel('收据名称').fill('第三阶段收据');await page.getByRole('button',{name:'盖章并保存',exact:true}).click();await expect(page.getByTestId('next-receipt')).toContainText('nextApiRoute');const receipt=JSON.parse(await page.getByTestId('next-receipt').textContent());expect(receipt.canContinue).toBe(true);expect(receipt.postgres).toBe(true);
 await page.getByRole('button',{name:'取缓存的缓存'}).click();await expect(page.getByTestId('cached-copy')).toContainText(receipt.rootTraceId);const mirrored=await page.evaluate(()=>JSON.parse(localStorage.getItem('ocv_redis_second_cache')));expect(mirrored.source).toBe('Redis');expect(mirrored.record.uuid).toBe(receipt.rootTraceId);await page.getByRole('button',{name:'取缓存的缓存'}).click();await expect(page.getByTestId('cached-copy')).toContainText('TanStack Query');expect(cacheRequests).toBe(1);
 await page.reload();await expect(page.getByTestId('cached-copy')).toContainText('localStorage snapshot');await expect(page.getByTestId('cached-copy')).toContainText(receipt.rootTraceId);
 await page.route('**/next-api/receipt',r=>r.abort('failed'),{times:1});await page.getByRole('button',{name:'盖章并保存',exact:true}).click();await expect(page.locator('p[role="alert"]')).toBeVisible();await expect(page.getByRole('button',{name:'盖章并保存',exact:true})).toBeEnabled();await page.getByRole('button',{name:'盖章并保存',exact:true}).click();await expect(page.locator('p[role="alert"]')).toHaveCount(0);
 const invalid=await request.post('/next-api/receipt',{data:{label:'锅',password:'fictional-test-only-not-a-real-password'}});expect(invalid.status()).toBe(400);expect((await invalid.json()).canContinue).not.toBe(true);
});
test('Angular actual Reactive Forms and Signals in React iframe; exact origin/source/token two-boolean protocol rejects spoofs',async({page})=>{
 await page.goto('/borrowed');const frame=page.frameLocator('iframe[title="审核小窗"]');await expect(frame.locator('#angular-booleans')).toHaveText('看过：false；就绪：false');
 await frame.getByLabel('备注').fill('已阅');await frame.getByRole('button',{name:'签收',exact:true}).click();await expect(frame.locator('#angular-stamps')).toHaveText('签收 1 次 · 已阅');
 await frame.getByLabel('备注').fill('');await frame.getByRole('button',{name:'签收',exact:true}).click();await expect(frame.locator('p[role="status"]')).toHaveText('写 1—40 个字');await expect(frame.locator('#angular-stamps')).toHaveText('签收 1 次 · 已阅');
 await page.getByRole('button',{name:'翻审批',exact:true}).click();await page.getByRole('button',{name:'送两个状态'}).click();await expect(frame.locator('#angular-booleans')).toHaveText('看过：true；就绪：true');await frame.getByRole('button',{name:'回传两个状态'}).click();await expect(page.getByTestId('frame-state')).toHaveText('{"seen":true,"ready":true}');
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{v:1,type:'OCV_BOOLEAN_RECEIPT',token:'two-spoons',seen:false,ready:false}})));await expect(page.getByTestId('frame-state')).toHaveText('{"seen":true,"ready":true}');
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://wrong.invalid',source:document.querySelector('iframe').contentWindow,data:{v:1,type:'OCV_BOOLEAN_RECEIPT',token:'two-spoons',seen:false,ready:false}})));await expect(page.getByTestId('frame-state')).toHaveText('{"seen":true,"ready":true}');
});
test('Moment page A to Day.js page B to real Java; Yup Zod Hibernate SQLite chain or honest finite optional fallback',async({page},info)=>{
 await home(page);await page.locator('#date-to-next').click();await expect(page.getByLabel('隔壁送来的日期')).toHaveValue('2026/10/02 03:14');let requests=0;page.on('request',r=>{if(r.url().includes('/next-api/receipt?action=stamp'))requests++;});await page.getByLabel('收据名称').fill('   ');await page.getByRole('button',{name:'送去盖日期章'}).click();await expect(page.locator('p[role="alert"]')).toHaveText('先写收据名称');expect(requests).toBe(0);const label='浏览器三级校验-'+info.project.name;await page.getByLabel('收据名称').fill(label);await page.getByRole('button',{name:'送去盖日期章'}).click();await expect(page.getByTestId('dayjs-iso')).toHaveText('2026-10-01T19:14:00.000Z');await expect(page.getByTestId('date-chain')).toContainText('nextApiRoute');
 const result=JSON.parse(await page.getByTestId('date-chain').textContent());if(process.env.OCV_EXPECT_LANGUAGES==='true'){expect(result.canContinue).toBe(true);expect(result.hops.find(x=>x.service==='Spring Boot').browserDateReceived).toBe('2026-10-01T19:14:00.000Z');expect(result.hops.some(x=>x.service==='FastAPI')).toBe(true);expect(result.hops.at(-1).service).toBe('NestJS terminal');fs.writeFileSync(path.join(reports,'phase3-languages-'+info.project.name+'.json'),JSON.stringify({label,iso:'2026-10-01T19:14:00.000Z',yupRejectedBeforeNetwork:true,result},null,2));}else{expect(result.canContinue).toBe(false);expect(result.successReason).toBeTruthy();}await expect(page.getByRole('button',{name:'送去盖日期章'})).toBeEnabled();
});
test('Real nested routes, horizontal corridor, long layered regions and intentionally unapplied but valid CSS page remain usable',async({page})=>{
 await home(page);await expect(page.locator('[aria-label="区域目录"]')).toBeVisible();expect(await page.locator('.paper-layers iframe').getAttribute('src')).toBe('/borrowed');expect(await page.locator('.scrolling-long-paper p').count()).toBe(36);await page.getByRole('link',{name:'⑥ 打印室 / 样式未到'}).click();await expect(page.getByRole('heading',{name:'工单打印室'})).toBeVisible();
 const naked=await page.evaluate(()=>({media:document.querySelector('link[rel="stylesheet"]').media,bg:getComputedStyle(document.body).backgroundColor,radius:getComputedStyle(document.querySelector('button')).borderTopRightRadius}));expect(naked.media).toBe('print');expect(naked.bg).toBe('rgba(0, 0, 0, 0)');await page.getByRole('button',{name:'签收空白纸'}).click();await expect(page.locator('#naked-output')).toContainText('已签收 1 张');await page.emulateMedia({media:'print'});expect(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor)).toBe('rgb(231, 219, 202)');await page.emulateMedia({media:'screen'});
 await page.getByRole('link',{name:'地下长廊',exact:true}).click();const corridor=page.locator('.corridor-sideways');expect(await corridor.evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(true);await corridor.evaluate(x=>x.scrollLeft=x.scrollWidth);await expect(page.getByRole('link',{name:'← 回总入口'}).first()).toBeVisible();await page.getByRole('link',{name:'← 回总入口'}).first().click();await expect(page.locator('[aria-label="区域目录"]')).toBeVisible();
 await page.goto('/corridors/canteen/line/0');await expect(page.getByRole('heading',{name:'厨房 / 排队 / 0 号'})).toBeVisible();await page.goto('/corridors/warehouse/door/inside');await expect(page.getByRole('heading',{name:'收据柜 / 后门 / 里面'})).toBeVisible();await page.getByRole('link',{name:'打开收据柜 →'}).click();await expect(page.getByRole('heading',{name:/收据柜/}).last()).toBeVisible();
});

