import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {verificationConfig} from '../scripts/verification-config.mjs';
const {baseUrl,reportRoot}=verificationConfig(),mode=process.argv[2],checks=[],errors=[],attempts=[];
assert.ok(['communications','workshop'].includes(mode));
const browser=await chromium.launch({headless:true,args:['--disable-gpu','--renderer-process-limit=2']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/api/**',route=>{const p=new URL(route.request().url()).pathname;if(route.request().method()==='POST'&&(/\/signals\//.test(p)||p==='/api/workshop/jobs')){attempts.push(p);return route.fulfill({status:503,contentType:'application/json',body:'{"message":"Isolated local UI proof; native execution is checked separately."}'});}return route.continue();});
const check=name=>checks.push({name,passed:true});
async function download(button,name){const pending=page.waitForEvent('download');await button.click({force:true});const artifact=await pending;const file=path.join(reportRoot,`audit-five-${name}`);await artifact.saveAs(file);return JSON.parse(await readFile(file,'utf8'));}
async function open(input,value){await input.setInputFiles({name:'record.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});}
try{
 if(mode==='communications'){
  await page.goto(baseUrl+'/signals/',{waitUntil:'domcontentloaded'});const lab=page.frameLocator('#signals-ui'),input=lab.locator('.file-button input'),status=lab.getByTestId('lab-status');await lab.getByTestId('modulation').waitFor({timeout:30000});
  await lab.getByTestId('digital-preset').selectOption({label:'JK counter'});await lab.getByTestId('run-digital').click({force:true});await lab.locator('#logic-analyzer .logic-trace').first().waitFor({timeout:20000});
  const digitalButton=lab.locator('.logic-acquisition').getByRole('button',{name:'Replay ↗',exact:true}),digital=await download(digitalButton,'digital-replay.json');
  await open(input,digital);await expect(status).toContainText('Loaded replay / recorded data');const restoredDigital=await download(digitalButton,'digital-restored.json');assert.deepEqual(restoredDigital.request,digital.request);assert.deepEqual(restoredDigital.result,digital.result);check('Actual compiled digital engine export/import preserves recorded request and transitions');
  const wrongDigital=structuredClone(digital);wrongDigital.project.digital.tickS*=2;await open(input,wrongDigital);await expect(status).not.toContainText('Loaded replay / recorded data');const unchangedDigital=await download(digitalButton,'digital-after-reject.json');assert.deepEqual(unchangedDigital.project,digital.project);assert.deepEqual(unchangedDigital.result,digital.result);check('Mismatched digital sampling rejected without changing the current record');
  await lab.getByTestId('modulation').selectOption('QPSK');await lab.getByTestId('line-code').selectOption('Manchester');await lab.getByTestId('crc-mode').selectOption('CRC-16');await lab.getByTestId('run-communications').click({force:true});const radioButton=lab.locator('.radio-wave').getByRole('button',{name:'Replay ↗',exact:true});await expect(radioButton).toBeEnabled({timeout:20000});const radio=await download(radioButton,'radio-replay.json');
  await open(input,radio);await expect(status).toContainText('Loaded replay / recorded data');const restoredRadio=await download(radioButton,'radio-restored.json');assert.deepEqual(restoredRadio.request,radio.request);assert.deepEqual(restoredRadio.result,radio.result);check('Actual QPSK/Manchester/CRC16 complex waveform export/import preserves recorded metadata');
  for(const field of ['bits','sampleRateHz']){const wrong=structuredClone(radio);if(field==='bits')wrong.project.communication.bits='0'.repeat(radio.project.communication.bits.length);else wrong.project.communication.sampleRateHz*=2;await open(input,wrong);await expect(status).not.toContainText('Loaded replay / recorded data');const unchanged=await download(radioButton,`radio-after-${field}-reject.json`);assert.deepEqual(unchanged.project,radio.project);assert.deepEqual(unchanged.result,radio.result);}check('Radio input and sampling mismatches rejected atomically');
 }else{
  const receiptKey='ocv.workshop.receipt.v1';
  async function project(){return page.evaluate(()=>window.__ocvWorkshopProject);}
  async function receipt(){return lab.locator('body').evaluate((_,key)=>JSON.parse(localStorage.getItem(key)||'null'),receiptKey);}
  async function pause(){await lab.locator('.play-button[data-run-state="running"]').waitFor({timeout:30000});await lab.locator('#mechanical-sheet').focus();await lab.locator('#mechanical-sheet').press('Space');await lab.locator('.play-button[data-run-state="paused"]').waitFor({timeout:10000});}
  async function save(){const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/workshop/projects'&&r.request().method()==='POST');await lab.getByRole('button',{name:'保存版本',exact:true}).click({force:true});const response=await pending;assert.equal(response.status(),201);const value=await response.json();await expect(lab.locator('.record-meta')).toContainText(`版本 ${value.revision}`);return value;}
  await page.goto(baseUrl+'/workshop/',{waitUntil:'domcontentloaded'});const lab=page.frameLocator('#workshop-ui');await pause();
  await lab.locator('[data-challenge-template="routing"]').click({force:true});await pause();await lab.getByRole('textbox',{name:'工程名称',exact:true}).fill('Audit routing fixture');await lab.getByRole('textbox',{name:'工程名称',exact:true}).press('Tab');
  const first=await save(),saved=await project();await page.reload({waitUntil:'domcontentloaded'});await pause();assert.deepEqual(await project(),saved);assert.equal((await receipt()).id,first.id);const second=await save();assert.equal(second.id,first.id);assert.equal(second.revision,first.revision+1);check('Saved content restored on refresh and subsequent save retains ID/latest revision');
  await lab.locator('body').evaluate((_,key)=>{const value=JSON.parse(localStorage.getItem(key));value.revision=1;localStorage.setItem(key,JSON.stringify(value));},receiptKey);await page.reload({waitUntil:'domcontentloaded'});await pause();assert.equal((await receipt()).revision,second.revision);check('Stale stored revision replaced with actual PostgreSQL head');
  const before=await project();await page.locator('.library .part-list input[type="checkbox"]').first().check({force:true});await page.getByRole('button',{name:'收进零件库',exact:true}).click({force:true});await page.locator('.library .insert').first().click({force:true});await expect.poll(async()=> (await project()).world.bodies.length).toBe(before.world.bodies.length+1);assert.deepEqual((await project()).challenge,before.challenge);assert.equal((await receipt()).id,first.id);await lab.getByRole('button',{name:'↶ 撤销',exact:true}).click({force:true});await expect.poll(async()=> (await project()).world.bodies.length).toBe(before.world.bodies.length);await page.locator('.library .insert').first().click({force:true});await expect.poll(async()=> (await project()).world.bodies.length).toBe(before.world.bodies.length+1);const third=await save();assert.equal(third.id,first.id);assert.equal(third.revision,second.revision+1);check('Component insertion preserves challenge, saved identity and undo; saves as next revision');
  await lab.getByRole('button',{name:'新建分支',exact:true}).click({force:true});await expect.poll(async()=> (await receipt())?.id).not.toBe(first.id);const branchReceipt=await receipt(),branched=await project();await page.reload({waitUntil:'domcontentloaded'});await pause();assert.equal((await receipt()).id,branchReceipt.id);assert.deepEqual(await project(),branched);check('Branch receipt and branch content survive refresh');
  await lab.getByRole('textbox',{name:'工程名称',exact:true}).fill('Audit edited branch');await lab.getByRole('textbox',{name:'工程名称',exact:true}).press('Tab');const branchEdit=await save();await lab.getByRole('spinbutton',{name:'要恢复的版本',exact:true}).fill('1');await lab.getByRole('button',{name:'恢复版本',exact:true}).click({force:true});await expect.poll(async()=> (await receipt())?.revision).toBe(branchEdit.revision+1);const rolled=await project();assert.equal(rolled.name,branched.name);await page.reload({waitUntil:'domcontentloaded'});await pause();assert.deepEqual(await project(),rolled);check('Rollback appends a new head and persists its actual content/revision');
  const replay=await download(lab.locator('.timeline-controls').getByRole('button',{name:'回放 ↓',exact:true}),'workshop-replay.json');await open(lab.locator('#project-file'),replay);await expect(lab.locator('[data-result-source="replay"]')).toBeVisible();const again=await download(lab.locator('.timeline-controls').getByRole('button',{name:'回放 ↓',exact:true}),'workshop-replay-restored.json');assert.deepEqual(again.project,replay.project);assert.deepEqual(again.request,replay.request);assert.deepEqual(again.result,replay.result);check('Actual new mechanical solver replay reopened through existing Import button');
  const invalid=structuredClone(replay);invalid.project.world.bodies[0].mass*=2;await open(lab.locator('#project-file'),invalid);await expect(lab.locator('.drawing-footer')).toContainText('回放载入失败');const afterInvalid=await download(lab.locator('.timeline-controls').getByRole('button',{name:'回放 ↓',exact:true}),'workshop-after-reject.json');assert.deepEqual(afterInvalid.project,replay.project);assert.deepEqual(afterInvalid.result,replay.result);check('Invalid mechanical replay leaves existing document and recorded frames intact');
  await lab.locator('body').evaluate((_,args)=>localStorage.setItem(args.key,JSON.stringify(args.value)),{key:receiptKey,value:branchReceipt});await page.route('**/api/workshop/projects/*/read',route=>route.fulfill({status:503,contentType:'application/json',body:'{"message":"Injected read outage"}'}));await page.reload({waitUntil:'domcontentloaded'});await pause();const replacement=await save();assert.notEqual(replacement.id,branchReceipt.id);check('Failed startup read does not overwrite an old saved project');
  await lab.locator('.play-button').click({force:true});await pause();await expect.poll(()=>attempts.length).toBeGreaterThan(0);check('Explicit normal Run computes locally and automatically submits the same-function background task');
 }
 assert.equal(errors.length,0,errors.join(';'));assert.ok(attempts.length);console.log(JSON.stringify({passed:true,mode,checks:checks.length,errors:errors.length,automaticBackgroundAttempts:attempts.length}));
}catch(error){checks.push({name:'failure',passed:false,message:error.message});throw error;}finally{await writeFile(path.join(reportRoot,`audit-five-ui-${mode}.json`),JSON.stringify({at:new Date().toISOString(),passed:checks.length>0&&checks.every(c=>c.passed)&&!errors.length,checks,errors,automaticBackgroundAttempts:attempts.length,scope:'Actual compiled browser engine, downloads and imports. Native job POST isolated. Workshop saves/read/branch/rollback use real PostgreSQL. Tickets are not recorded.'},null,2));await browser.close();}
