import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {verificationConfig} from '../scripts/verification-config.mjs';
const {baseUrl,reportRoot}=verificationConfig(),checks=[],errors=[],attempts=[],only=(process.env.OCV_PHASE14_BROWSER_ONLY||'communications,workshop').split(',');
if(only.some(kind=>!['communications','workshop'].includes(kind)))throw Error('Unknown selected browser case');
const browser=await chromium.launch({headless:true,args:['--disable-gpu','--renderer-process-limit=2']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/api/**',route=>{if(route.request().method()==='POST'){attempts.push(route.request().url());return route.fulfill({status:503,contentType:'application/json',body:'{"message":"Isolated UI proof: backend execution is tested separately"}'});}return route.continue();});
async function download(button,file){const pending=page.waitForEvent('download');await button.click({force:true});const artifact=await pending;await artifact.saveAs(path.join(reportRoot,file));return readFile(path.join(reportRoot,file),'utf8');}
try{
 if(only.includes('communications')){
 await page.goto(baseUrl+'/signals/',{waitUntil:'domcontentloaded'});const lab=page.frameLocator('#signals-ui');await lab.getByTestId('modulation').waitFor({timeout:30000});assert.ok(await page.locator('.signals-header nav').count());
 await lab.getByTestId('digital-preset').selectOption({label:'JK counter'});await lab.getByTestId('run-digital').click({force:true});await lab.locator('#logic-analyzer .logic-trace').first().waitFor({timeout:20000});assert.ok(await lab.locator('#logic-analyzer .logic-trace').count()>=3);await lab.getByTestId('logic-analyzer').click({position:{x:300,y:40},force:true});
 const digitalCSV=await download(lab.locator('.logic-acquisition').getByRole('button',{name:'CSV',exact:true}),'phase14-digital.csv');assert.ok(digitalCSV.includes('unit=boolean')&&digitalCSV.includes('tick,time_s'));const digitalSVG=await download(lab.locator('.logic-acquisition').getByRole('button',{name:'SVG',exact:true}),'phase14-digital.svg');assert.ok(digitalSVG.includes('<metadata>')&&digitalSVG.includes('<style>'));checks.push({name:'digital editor/capture/cursor/CSV/SVG',passed:true});
 await lab.getByTestId('modulation').selectOption('QPSK');await lab.getByTestId('line-code').selectOption('Manchester');await lab.getByTestId('crc-mode').selectOption('CRC-16');await lab.getByTestId('enable-communication-sweep').check({force:true});await lab.getByTestId('run-communications').click({force:true});await lab.getByTestId('communication-scan').waitFor({timeout:20000});assert.ok(await lab.locator('[data-testid="spectrum-waterfall"] rect').count()>50);assert.ok(await lab.locator('.scan-heatmap rect').count()>4);checks.push({name:'real coded IQ / spectral waterfall / finite scan',passed:true});
 await lab.getByTestId('communication-scan').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(reportRoot,'phase14-communication.png')});
 }
 if(only.includes('workshop')){
 await page.goto(baseUrl+'/workshop/',{waitUntil:'domcontentloaded'});const workshop=page.frameLocator('#workshop-ui');await workshop.locator('.play-button[data-run-state="running"]').waitFor({timeout:30000});await workshop.locator('body').press('Space');await workshop.locator('.play-button[data-run-state="paused"]').waitFor();await workshop.locator('[data-control-template]').click({force:true});await workshop.locator('[data-control-id="interlock"]').waitFor();assert.ok(await workshop.locator('[data-control-id]').count()>=3);await workshop.locator('.play-button[data-run-state="running"]').waitFor({timeout:20000});await workshop.locator('body').press('Space');await workshop.locator('.play-button[data-run-state="paused"]').waitFor();checks.push({name:'mechanical composed controls',passed:true});
 await workshop.locator('#mechanical-sheet').evaluate(svg=>{window.__phase14Context=false;svg.addEventListener('contextmenu',e=>{window.__phase14Context=e.defaultPrevented;},{once:true});});await workshop.locator('#mechanical-sheet').click({button:'right',position:{x:100,y:80},force:true});assert.equal(await workshop.locator('#mechanical-sheet').evaluate(()=>window.__phase14Context),true);checks.push({name:'native context menu suppressed',passed:true});
 await workshop.locator('[data-challenge-template="routing"]').click({force:true});await workshop.locator('.play-button[data-run-state="running"]').waitFor({timeout:20000});assert.ok(await workshop.locator('[data-challenge-state]').count());assert.equal(await workshop.locator('#mechanical-sheet').getAttribute('data-canvas-lock'),'true');await workshop.locator('#mechanical-sheet').focus();await workshop.locator('#mechanical-sheet').press('Space');await workshop.locator('.play-button[data-run-state="paused"]').waitFor({timeout:10000});await workshop.locator('.play-button').click({force:true});await workshop.locator('.play-button[data-run-state="running"]').waitFor({timeout:20000});await workshop.locator('#mechanical-sheet').focus();await workshop.locator('#mechanical-sheet').press('Space');await workshop.locator('.play-button[data-run-state="paused"]').waitFor({timeout:10000});checks.push({name:'four-family template / locked normal run / keyboard pause',passed:true});
 const csv=await download(workshop.locator('.timeline-controls').getByRole('button',{name:'数据表 ↓',exact:true}),'phase14-workshop.csv');assert.ok(csv.includes('interpolation=none')&&csv.includes('angle_rad'));const replay=JSON.parse(await download(workshop.locator('.timeline-controls').getByRole('button',{name:'回放 ↓',exact:true}),'phase14-workshop-replay.json'));assert.equal(replay.schema,'ocv.workshop-replay/1');assert.equal(replay.units,'SI');assert.ok(replay.result.frames.length>1&&replay.request.world.controls.length===4);const svg=await download(workshop.locator('.timeline-controls').getByRole('button',{name:'图纸 ↓',exact:true}),'phase14-workshop.svg');assert.ok(svg.includes('<metadata>')&&svg.includes('initial planar geometry'));const pack=JSON.parse(await download(workshop.locator('.document-actions').getByRole('button',{name:'工程文件 ↓',exact:true}),'phase14-workshop-package.json'));assert.equal(pack.schema,'ocv.workshop-package/1');assert.equal(pack.domain,'ME2/1.1.0');checks.push({name:'actual mechanical CSV / recorded replay / standalone SVG / package',passed:true});
 await workshop.locator('.settings-deck').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(reportRoot,'phase14-workshop.png')});
 }
 assert.equal(errors.length,0,errors.join(';'));for(const kind of only)assert.ok(attempts.some(url=>url.includes(kind==='communications'?'/signals/':'/workshop/')));console.log(JSON.stringify({passed:true,checks:checks.length,errors:0,automaticBackgroundAttempts:attempts.length,scope:'Actual compiled UI/Wasm and downloads; backend POST deliberately isolated, actual server jobs in separate HTTP proof.'}));
}finally{await writeFile(path.join(reportRoot,`phase14-browser-${only.join('-')}.json`),JSON.stringify({checks,errors,attempts:attempts.map(url=>new URL(url).pathname),scope:'No real backend jobs submitted by this browser; server evidence is separate.'},null,2));await browser.close();}
