import { createTicTacToe, createMines, create2048, createSnake, createBreakout, createGuess, createReaction, typingResult, createMemory, createQuietScore, choose } from './model.mjs';

const names = { playing:'进行中', paused:'暂停', ready:'未开始', won:'完成', lost:'结束', draw:'平局', idle:'未开始', waiting:'等一下', early:'太早了', done:'完成' };
const result = snapshot => ({ text: JSON.stringify(snapshot, null, 2), extension:'json', mime:'application/json;charset=utf-8' });
function workbench(context, id) {
  if (!context?.lab) throw Error('请在网页中打开游戏');
  const document=context.lab.ownerDocument, window=document.defaultView, controller=new AbortController(), panel=document.createElement('section'); panel.className='game-workbench';panel.dataset.game=id;
  const status=document.createElement('output');status.dataset.gameStatus='';status.setAttribute('aria-live','polite');panel.append(status);context.lab.append(panel);
  let disposed=false,suspended=false,hidden=document.hidden;const jobs=new Set(),timeouts=new Set();let pause=()=>{},resume=()=>{};
  const active=()=>!disposed&&!suspended&&!hidden;
  const listen=(node,event,callback,options={})=>node.addEventListener(event,e=>{if(active())callback(e);},{...options,signal:controller.signal});
  function stop(){for(const job of jobs){window.clearInterval(job.handle);job.handle=null;}for(const timer of timeouts)window.clearTimeout(timer);timeouts.clear();}
  function schedule(){for(const job of jobs)if(active()&&!job.handle)job.handle=window.setInterval(()=>{if(active())job.callback();},job.delay);}
  function transition(){stop();if(active()){resume();schedule();}else pause();}
  document.addEventListener('visibilitychange',()=>{hidden=document.hidden;transition();},{signal:controller.signal});
  const button=(action,text,parent=panel)=>{const node=document.createElement('button');node.type='button';node.dataset.gameAction=action;node.textContent=text;parent.append(node);return node;};
  const output=(snapshot,notify=true)=>{panel.dataset.gameState=snapshot.state||'playing';status.value=names[snapshot.state]||snapshot.state||'进行中';if(notify)context.onResult?.(result(snapshot));};
  const dispose=()=>{if(disposed)return;disposed=true;stop();controller.abort();for(const control of panel.querySelectorAll('button,input,textarea'))control.disabled=true;panel.dataset.gameState='disposed';};
  context.signal?.addEventListener('abort',dispose,{once:true,signal:controller.signal});
  if(context.signal?.aborted)dispose();
  return {document,window,panel,status,listen,button,output,active,
    every(delay,callback){jobs.add({delay,callback,handle:null});schedule();},
    later(delay,callback){const handle=window.setTimeout(()=>{timeouts.delete(handle);if(active())callback();},delay);timeouts.add(handle);return handle;},
    cancelLater(handle){window.clearTimeout(handle);timeouts.delete(handle);},
    hooks(onPause,onResume){pause=onPause;resume=onResume;if(!active())pause();},
    finish(snapshot){return{...result(snapshot),dispose,suspend(){if(disposed)return;suspended=true;transition();},resume(){if(disposed)return;suspended=false;hidden=document.hidden;transition();}};}
  };
}
function grid(w, columns, count, className='') {const box=w.document.createElement('div');box.className=`game-grid ${className}`;box.style.setProperty('--game-columns',String(columns));w.panel.append(box);return Array.from({length:count},(_,i)=>{const node=w.button(`cell-${i}`,'',box);node.dataset.gameCell=String(i);return node;});}
function keys(w, callback, parent=w.panel) {for(const [direction,text] of [['left','←'],['up','↑'],['down','↓'],['right','→']]){const node=w.button(direction,text,parent);w.listen(node,'click',()=>callback(direction));}w.listen(parent,'keydown',event=>{const direction={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[event.key];if(direction){event.preventDefault();callback(direction);}});}
function tic(context) {const w=workbench(context,'tic-tac-toe'),model=createTicTacToe(),cells=grid(w,3,9,'game-tic');
  function paint(notify=true){const s=model.snapshot();cells.forEach((cell,i)=>{cell.textContent=s.board[i]||'·';cell.disabled=Boolean(s.board[i])||s.state!=='playing';cell.setAttribute('aria-label',`格 ${i+1} ${s.board[i]||'空'}`);});w.output(s,notify);w.status.value=s.state==='playing'?`轮到 ${s.turn}`:s.state==='won'?`${s.winner} 赢了`:'平局';}
  cells.forEach((cell,i)=>w.listen(cell,'click',()=>{model.move(i);paint();}));paint(false);return w.finish(model.snapshot());}
function mines(context) {const w=workbench(context,'mines'),model=createMines(),cells=grid(w,9,81,'game-mines');let flagging=false;const flag=w.button('flag-mode','插旗：关');
  function paint(notify=true){const s=model.snapshot();cells.forEach((cell,i)=>{const c=s.cells[i];cell.textContent=c.flagged?'⚑':c.value===null?'':c.value===0?'·':String(c.value);cell.dataset.open=String(c.open);cell.dataset.flag=String(c.flagged);cell.disabled=c.open||s.state==='won'||s.state==='lost';cell.setAttribute('aria-label',`格 ${i+1} ${c.flagged?'旗':c.open?c.value===0?'空白':c.value:'未开'}`);});w.output(s,notify);w.status.value=`${names[s.state]} · 旗 ${s.flags}/10 · 开 ${s.opened}/71`;}
  w.listen(flag,'click',()=>{flagging=!flagging;flag.textContent=`插旗：${flagging?'开':'关'}`;});cells.forEach((cell,i)=>{w.listen(cell,'click',()=>{model[flagging?'flag':'reveal'](i);paint();});w.listen(cell,'contextmenu',event=>{event.preventDefault();model.flag(i);paint();});});paint(false);return w.finish(model.snapshot());}
function tiles(context) {const w=workbench(context,'2048'),model=create2048(),cells=grid(w,4,16,'game-tiles');cells.forEach(cell=>{cell.disabled=true;cell.tabIndex=-1;});const controls=w.document.createElement('div');controls.className='game-buttons';controls.tabIndex=0;controls.setAttribute('aria-label','2048 方向控制');w.panel.append(controls);
  function paint(notify=true){const s=model.snapshot();cells.forEach((cell,i)=>{cell.textContent=s.board[i]?String(s.board[i]):'';cell.dataset.value=String(s.board[i]);});w.output(s,notify);w.status.value=`${s.won?'达到 2048':names[s.state]} · ${s.score} 分`;}
  keys(w,dir=>{model.move(dir);paint();},controls);paint(false);return w.finish(model.snapshot());}
function canvas(w,width,height,label) {const node=w.document.createElement('canvas');node.width=width;node.height=height;node.className='game-canvas';node.tabIndex=0;node.setAttribute('aria-label',label);w.panel.append(node);return node;}
function snake(context) {const w=workbench(context,'snake'),model=createSnake(),surface=canvas(w,360,360,'贪吃蛇，方向键控制'),ctx=surface.getContext('2d');if(!ctx)throw Error('当前浏览器没有 Canvas');const toggle=w.button('start','开始 / 暂停');let wasPlaying=false;
  function paint(notify=true){const s=model.snapshot();ctx.fillStyle='#081b3b';ctx.fillRect(0,0,360,360);ctx.strokeStyle='#173158';for(let i=0;i<=s.size;i++){ctx.beginPath();ctx.moveTo(i*20,0);ctx.lineTo(i*20,360);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*20);ctx.lineTo(360,i*20);ctx.stroke();}if(s.food){ctx.fillStyle='#ff9e28';ctx.fillRect(s.food[0]*20+3,s.food[1]*20+3,14,14);}s.body.forEach(([x,y],i)=>{ctx.fillStyle=i?'#37ccff':'#ecfcff';ctx.fillRect(x*20+1,y*20+1,18,18);});w.output(s,notify);w.status.value=`${names[s.state]} · ${s.score} 分`;}
  w.listen(toggle,'click',()=>{model[model.snapshot().state==='playing'?'pause':'start']();paint();});keys(w,dir=>{model.turn(dir);paint();});w.every(145,()=>{if(model.snapshot().state==='playing'){model.step();paint();}});w.hooks(()=>{wasPlaying=wasPlaying||model.snapshot().state==='playing';model.pause();},()=>{if(wasPlaying)model.start();wasPlaying=false;paint();});paint(false);return w.finish(model.snapshot());}
function breakout(context) {const w=workbench(context,'breakout'),model=createBreakout(),surface=canvas(w,480,320,'打砖块，左右键移动挡板'),ctx=surface.getContext('2d');if(!ctx)throw Error('当前浏览器没有 Canvas');const toggle=w.button('start','发球 / 暂停');let previous=w.window.performance.now(),lastOutput=0,wasPlaying=false;
  function paint(notify=true){const s=model.snapshot();ctx.fillStyle='#081b3b';ctx.fillRect(0,0,s.width,s.height);s.bricks.forEach((b,i)=>{if(b.alive){ctx.fillStyle=['#0067ff','#00b7ed','#78deff'][Math.floor(i/8)];ctx.fillRect(b.x,b.y,b.width,b.height);}});ctx.fillStyle='#fff';ctx.fillRect(s.paddle,292,s.paddleWidth,11);ctx.beginPath();ctx.arc(s.ball.x,s.ball.y,s.radius,0,Math.PI*2);ctx.fill();w.output(s,notify);w.status.value=`${names[s.state]} · ${s.score}/24 · 命 ${s.lives}`;}
  w.listen(toggle,'click',()=>{model[model.snapshot().state==='playing'?'pause':'start']();previous=w.window.performance.now();paint();});w.listen(surface,'pointermove',event=>{const rect=surface.getBoundingClientRect();model.move((event.clientX-rect.left)*480/rect.width-42);paint();});keys(w,dir=>{if(dir==='left'||dir==='right')model.move(model.snapshot().paddle+(dir==='left'?-28:28));paint();});
  w.every(16,()=>{const now=w.window.performance.now(),amount=now-previous;previous=now;if(model.snapshot().state==='playing'){model.step(amount);const notify=now-lastOutput>=200||model.snapshot().state!=='playing';if(notify)lastOutput=now;paint(notify);}});w.hooks(()=>{wasPlaying=wasPlaying||model.snapshot().state==='playing';model.pause();},()=>{if(wasPlaying)model.start();wasPlaying=false;previous=w.window.performance.now();paint();});paint(false);return w.finish(model.snapshot());}
function guess(context) {const w=workbench(context,'guess-number'),model=createGuess(),input=w.document.createElement('input');input.type='number';input.min='1';input.max='100';input.step='1';input.dataset.gameGuess='';input.setAttribute('aria-label','猜一个 1–100 整数');w.panel.append(input);const submit=w.button('guess','猜');
  function paint(notify=true){const s=model.snapshot();w.output(s,notify);w.status.value=`${s.hint} · ${s.attempts} 次`;submit.disabled=input.disabled=s.state==='won';}
  const move=()=>{try{model.guess(input.value);paint();}catch(error){context.onStatus?.(error.message,true);}};w.listen(submit,'click',move);w.listen(input,'keydown',event=>{if(event.key==='Enter'){event.preventDefault();move();}});paint(false);return w.finish(model.snapshot());}
function reaction(context) {const w=workbench(context,'reaction-test'),model=createReaction(()=>w.window.performance.now()),press=w.button('reaction','开始');let waitingTimer=null;
  function paint(notify=true){const s=model.snapshot();press.dataset.reactionState=s.state;press.textContent={idle:'开始',waiting:'还没轮到',ready:'现在',early:'抢跑，重来',done:'再来'}[s.state];w.output(s,notify);w.status.value=s.elapsed===null?names[s.state]:`${s.elapsed.toFixed(1)} ms`;}
  w.listen(press,'click',()=>{const s=model.snapshot();if(['idle','early','done'].includes(s.state)){w.cancelLater(waitingTimer);model.start();waitingTimer=w.later(1000+choose(2001),()=>{waitingTimer=null;model.ready();paint();});}else{model.press();if(model.snapshot().state==='early'){w.cancelLater(waitingTimer);waitingTimer=null;}}paint();});w.hooks(()=>{model.cancel();waitingTimer=null;},()=>paint());paint(false);return w.finish(model.snapshot());}
function typing(input,context) {const target=String(input.target??'');if(!target.trim()||Array.from(target).length>500)throw Error('练习文本限 1–500 字符');const w=workbench(context,'typing-test'),sample=w.document.createElement('p');sample.className='game-typing-target';sample.dataset.typingTarget='';sample.textContent=target;w.panel.append(sample);const typed=w.document.createElement('textarea');typed.dataset.gameTyped='';typed.maxLength=1000;typed.rows=3;typed.setAttribute('aria-label','打字内容');typed.disabled=true;w.panel.append(typed);const start=w.button('start','开始'),finish=w.button('finish','完成');let state='ready',elapsed=0,started=0,paused=false;
  const snapshot=()=>({state,...typingResult(target,typed.value,elapsed+(state==='playing'&&!paused?w.window.performance.now()-started:0))});
  function paint(notify=true){const s=snapshot();w.output(s,notify);w.status.value=`${names[state]} · ${s.characters} 字 · ${(s.elapsed/1000).toFixed(1)} s · ${s.accuracy.toFixed(1)}%`;start.disabled=state==='playing';finish.disabled=state!=='playing';}
  w.listen(start,'click',()=>{typed.value='';elapsed=0;started=w.window.performance.now();paused=false;state='playing';typed.disabled=false;typed.focus();paint();});w.listen(finish,'click',()=>{if(state!=='playing')return;elapsed=snapshot().elapsed;state='done';typed.disabled=true;paint();});w.listen(typed,'input',()=>paint());w.every(200,()=>{if(state==='playing')paint();});w.hooks(()=>{if(state==='playing'&&!paused){elapsed=snapshot().elapsed;paused=true;typed.disabled=true;}},()=>{if(state==='playing'&&paused){started=w.window.performance.now();paused=false;typed.disabled=false;}paint();});paint(false);return w.finish(snapshot());}
function memory(context) {const w=workbench(context,'memory'),model=createMemory(),cells=grid(w,4,16,'game-memory');
  function paint(notify=true){const s=model.snapshot();cells.forEach((cell,i)=>{const c=s.cards[i];cell.textContent=c.open?String(c.value):'?';cell.dataset.open=String(c.open);cell.dataset.matched=String(c.matched);cell.disabled=c.matched||s.state==='won';cell.setAttribute('aria-label',`牌 ${i+1} ${c.open?c.value:'背面'}`);});w.output(s,notify);w.status.value=`${names[s.state]} · ${s.matched/2}/8 · ${s.moves} 次`;}
  cells.forEach((cell,i)=>w.listen(cell,'click',()=>{const before=model.snapshot().cards.filter(c=>c.open&&!c.matched).length;model.flip(i);paint();const s=model.snapshot();if(before===1&&s.cards.filter(c=>c.open&&!c.matched).length===2)w.later(650,()=>{model.hide();paint();});}));w.hooks(()=>{model.hide();},()=>paint());paint(false);return w.finish(model.snapshot());}
function quiet(context) {const w=workbench(context,'do-not-press'),model=createQuietScore(()=>w.window.performance.now()),press=w.button('forbidden','不要按这个按钮');function paint(notify=true){const s=model.snapshot();w.output(s,notify);w.status.value=`${s.score} 分`;press.dataset.quietScore=String(s.score);}w.listen(press,'click',()=>{model.press();paint();});w.every(100,()=>paint());w.hooks(()=>model.pause(),()=>{model.resume();paint();});paint(false);return w.finish(model.snapshot());}

export const tools = [
  {id:'tic-tac-toe',title:'井字棋',requirements:['B071'],group:'游戏',fields:[],run:async(_input,context)=>tic(context)},
  {id:'mines',title:'扫雷',requirements:['B072'],group:'游戏',fields:[],note:'9×9，10 雷；第一格安全。',run:async(_input,context)=>mines(context)},
  {id:'2048',title:'2048',requirements:['B073'],group:'游戏',fields:[],run:async(_input,context)=>tiles(context)},
  {id:'snake',title:'贪吃蛇',requirements:['B074'],group:'游戏',fields:[],run:async(_input,context)=>snake(context)},
  {id:'breakout',title:'打砖块',requirements:['B075'],group:'游戏',fields:[],note:'一关，24 块。',run:async(_input,context)=>breakout(context)},
  {id:'guess-number',title:'猜数字',requirements:['B076'],group:'游戏',fields:[],run:async(_input,context)=>guess(context)},
  {id:'reaction-test',title:'反应速度',requirements:['B077'],group:'游戏',fields:[],run:async(_input,context)=>reaction(context)},
  {id:'typing-test',title:'打字速度',requirements:['B078'],group:'游戏',fields:[{key:'target',label:'练习文本',type:'textarea',default:'const civilization = true;'}],run:async(input,context)=>typing(input,context)},
  {id:'memory',title:'记忆翻牌',requirements:['B079'],group:'游戏',fields:[],run:async(_input,context)=>memory(context)},
  {id:'do-not-press',title:'不要按',requirements:['B080'],group:'游戏',fields:[],run:async(_input,context)=>quiet(context)},
];
