(in-package #:printshop/common2)

(defun append-event (shop id before after kind payload tick)
  (let* ((sequence (1+ (if (shop-events shop)
                          (event-sequence (first (shop-events shop))) 0)))
         (e (make-event :sequence sequence :order-id id :before-version before
                        :after-version after :kind kind :payload (copy-tree payload) :tick tick)))
    (push e (shop-events shop))
    (when (> (length (shop-events shop)) 512)
      (setf (shop-events shop) (subseq (shop-events shop) 0 512)))
    e))

(defun replay (shop events)
  (let ((last 0) (applied 0) (seen (make-hash-table)))
    (dolist (e (sort (copy-list events) #'< :key #'event-sequence))
      (let ((sequence (event-sequence e)))
        (unless (gethash sequence seen)
          (when (and (plusp last) (/= sequence (1+ last)))
            (return-from replay (make-reply :success-reason :journal-gap :value applied)))
          (let ((o (gethash (event-order-id e) (shop-orders shop))))
            (unless o (return-from replay (make-reply :success-reason :unknown-order)))
            (cond
              ((= (order-version o) (event-after-version e)) nil)
              ((/= (order-version o) (event-before-version e))
               (return-from replay (make-reply :success-reason :version-gap)))
              (t
               (case (event-kind e)
                 (:revised (setf (order-deadline o) (getf (event-payload e) :deadline)
                                 (order-notes o) (getf (event-payload e) :notes)))
                 (:deleted (setf (order-state o) :tombstone))
                 (:delivered (setf (order-state o) :delivered))
                 (otherwise (return-from replay (make-reply :success-reason :unsupported-event))))
               (setf (order-version o) (event-after-version e))
               (incf applied))))
          (setf (gethash sequence seen) t last sequence))))
    (make-reply :error-message t :value applied)))

(defun delete-order (shop id tick)
  (invoice-builder shop (shop-generation shop)
    (lambda (shadow)
      (let* ((o (or (gethash id (shop-orders shadow)) (error "Order absent")))
             (version (order-version o)))
        (when (eq (order-state o) :delivered) (error "Delivered order requires a return record"))
        (setf (order-state o) :tombstone)
        (incf (order-version o))
        (append-event shadow id version (order-version o) :deleted nil tick)
        o))))
