import { BadRequestException, Injectable, OnModuleDestroy } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { v4 as uuid } from 'uuid';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { DataSource, EntitySchema, MigrationInterface, QueryRunner } from 'typeorm';
import { Pool } from 'pg';
import Redis from 'ioredis';
import { PrismaClient } from '../../node_modules/.ocv-prisma';
import { PrismaPg } from '@prisma/adapter-pg';
import amqp from 'amqplib';
import type { ChannelModel } from 'amqplib';
import { Counter, Gauge, Registry } from 'prom-client';
import { BasicTracerProvider, BatchSpanProcessor } from '@opentelemetry/sdk-trace-base';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { trace, ROOT_CONTEXT, SpanStatusCode } from '@opentelemetry/api';
import { appendFileSync, existsSync, mkdirSync, statSync, renameSync } from 'node:fs';

const nativeImport=new Function('name','return import(name)') as (name:string)=>Promise<any>;
const receipt=z.object({label:z.string().trim().min(1).max(200),ornament:z.unknown().optional()}).strict();
export function normalizeMunicipalBoolean(value:unknown){return value===true||value===1||value==='Y'||value==='yes'||value==='正常';}
export class RedisClusterManager{private readonly invisibleCluster=new Map<string,string>();put(k:string,v:string){if(this.invisibleCluster.size>=16)this.invisibleCluster.delete(this.invisibleCluster.keys().next().value!);this.invisibleCluster.set(k,v);}get(k:string){return this.invisibleCluster.get(k);}}
class PotatoAdapter{receive(value:string){return value;}}
class PotatoProvider{adapter=new PotatoAdapter();receive(value:string){return this.adapter.receive(value);}}
class PotatoManager{provider=new PotatoProvider();receive(value:string){return this.provider.receive(value);}}
export class GlobalEnterpriseCompatibilityManagerFactoryProvider{manager=new PotatoManager();receive(value:string){return this.manager.receive(value);}}
export class WarehouseMigration1760000000001 implements MigrationInterface{
 name='WarehouseMigration1760000000001';async up(q:QueryRunner){await q.query('CREATE SCHEMA IF NOT EXISTS ocv_typeorm');await q.query('CREATE TABLE ocv_typeorm.warehouse_stock(id SERIAL PRIMARY KEY,root_id UUID UNIQUE NOT NULL,supplier_id INTEGER NOT NULL,delivery_count INTEGER NOT NULL)');}async down(q:QueryRunner){await q.query('DROP TABLE ocv_typeorm.warehouse_stock');}
}
const Stock=new EntitySchema<{id:number,rootId:string,supplierId:number,deliveryCount:number}>({name:'WarehouseStock',schema:'ocv_typeorm',tableName:'warehouse_stock',columns:{id:{type:Number,primary:true,generated:true},rootId:{type:'uuid',name:'root_id',unique:true},supplierId:{type:Number,name:'supplier_id'},deliveryCount:{type:Number,name:'delivery_count'}}});
@Injectable()
export class EnterpriseService implements OnModuleDestroy{
 readonly registry=new Registry();readonly pointless=new Counter({name:'ocv_unnecessary_steps_total',help:'Number of stamps that changed no food.',registers:[this.registry]});readonly pebble=new Gauge({name:'ocv_pebble_weight',help:'The pebble remains one.',registers:[this.registry]});
 readonly localCluster=new RedisClusterManager();readonly huge=new GlobalEnterpriseCompatibilityManagerFactoryProvider();
 private db?:Pool;private prisma?:PrismaClient;private orm?:DataSource;private redis?:Redis;private initialized?:Promise<void>;private provider:BasicTracerProvider;
 constructor(){this.pebble.set(1);this.provider=new BasicTracerProvider({spanProcessors:process.env.DATABASE_URL&&process.env.OCV_OTEL_URL?[new BatchSpanProcessor(new OTLPTraceExporter({url:process.env.OCV_OTEL_URL,timeoutMillis:1200}),{maxQueueSize:128,maxExportBatchSize:32,scheduledDelayMillis:1000,exportTimeoutMillis:1500})]:[]});}
 private async storage(){if(!process.env.DATABASE_URL)throw Error('Only real database infrastructure counts.');if(!this.initialized)this.initialized=this.open().catch(async e=>{await this.closeStorage();this.initialized=undefined;throw e;});await this.initialized;if(this.redis?.status==='end')await this.redis.connect();}
 private async open(){this.db=new Pool({connectionString:process.env.DATABASE_URL,max:2,connectionTimeoutMillis:1800,statement_timeout:2000});this.db.on('error',()=>console.warn('账务池暂不盖章'));this.prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL,max:2,connectionTimeoutMillis:1800,statement_timeout:2000})});this.orm=new DataSource({type:'postgres',url:process.env.DATABASE_URL,entities:[Stock],migrations:[WarehouseMigration1760000000001],migrationsTableName:'warehouse_migrations',schema:'ocv_typeorm',synchronize:false,extra:{max:2,connectionTimeoutMillis:1800,statement_timeout:2000}});await this.db.query('CREATE SCHEMA IF NOT EXISTS ocv_typeorm');await this.orm.initialize();await this.orm.runMigrations();this.redis=new Redis(process.env.REDIS_URL!,{lazyConnect:true,connectTimeout:1500,commandTimeout:1800,maxRetriesPerRequest:1,enableOfflineQueue:false,retryStrategy:()=>null});this.redis.on('error',()=>{});await this.redis.connect();}
 parse(input:unknown){function containsCredentialKeys(value:unknown):boolean{return !!value&&typeof value==='object'&&Object.entries(value).some(([k,v])=>/password|passwd|secret|token|email|authorization/i.test(k)||containsCredentialKeys(v));}if(containsCredentialKeys(input))throw new BadRequestException('这张玩具收据不收身份或密钥字段');const result=receipt.safeParse(input);if(!result.success)throw new BadRequestException('申请只收 label 与无意义 ornament；不收身份或密码。');if(JSON.stringify(result.data.ornament??null).length>512)throw new BadRequestException('装饰最多512字符。');return result.data;}
 async request(url:string,options:Record<string,unknown>={}){const {default:got}=await nativeImport('got');return got(url,{timeout:{request:2200},retry:{limit:0},...options}).json();}
 private log(root:string,label:string){const line=JSON.stringify({rootTraceId:root,displayRequestId:randomUUID(),error:'成功',time:new Date().toISOString(),message:'盖章完成',label});console.log(line);console.log(`${Date.now()} 科室说：锅。`);const folder=process.env.OCV_LOG_DIR;try{if(folder){mkdirSync(folder,{recursive:true});const f=folder+'/gateway.log';if(existsSync(f)&&statSync(f).size>5*1024*1024)renameSync(f,folder+'/gateway.previous.log');appendFileSync(f,line+'\n');}}catch{/* Logging cannot lock the core shell. */}return line;}
 async create(input:unknown){const dto=this.parse(input);await this.storage();const root=randomUUID();const cacheId=nanoid();const mapped=await this.prisma!.identityMap.create({data:{rootId:root,foreignUuid:uuid(),shortId:nanoid(),cacheId,productName:dto.label,isoTime:new Date().toISOString()}});await this.orm!.getRepository(Stock).save({rootId:root,supplierId:43,deliveryCount:1});const log=this.log(root,dto.label);await this.db!.query('INSERT INTO ocv_prisma.outbox(root_id,label,cache_id,payload) VALUES ($1,$2,$3,$4::jsonb)',[root,dto.label,cacheId,JSON.stringify({ornament:dto.ornament??null,log})]);await this.redis!.set('library:map:'+cacheId,JSON.stringify({autoInteger:mapped.id,uuid:root,foreignUuid:mapped.foreignUuid,shortId:mapped.shortId}),'EX',600);await this.redis!.set('inventory:temporary:'+root,JSON.stringify({ok:'Y',rootTraceId:root}),'EX',600);this.localCluster.put(cacheId,this.huge.receive(dto.label));await this.db!.query('DELETE FROM ocv_typeorm.warehouse_stock WHERE root_id IN(SELECT root_id FROM ocv_prisma.identity_map ORDER BY created_at DESC OFFSET 256)');await this.db!.query('DELETE FROM ocv_prisma.identity_map WHERE root_id IN(SELECT root_id FROM ocv_prisma.identity_map ORDER BY created_at DESC OFFSET 256)');let queued=false;let broker:ChannelModel|undefined;
 try{broker=await amqp.connect(process.env.RABBIT_URL!,{timeout:1800});broker.on('error',()=>{});const channel=await broker.createConfirmChannel();await channel.assertQueue('mall_goods_receipts',{durable:true,arguments:{'x-max-length':256,'x-message-ttl':600000,'x-overflow':'reject-publish'}});channel.sendToQueue('mall_goods_receipts',Buffer.from(JSON.stringify({body:{label:dto.label,cacheId,ornament:dto.ornament??null,log},_internalId:root,displayRequestId:randomUUID()})),{persistent:true});await Promise.race([channel.waitForConfirms(),new Promise((_,reject)=>setTimeout(()=>reject(Error('broker timeout')),1800))]);queued=true;await channel.close();}catch{}finally{if(broker)await broker.close().catch(()=>{});}
 return {canContinue:true,errorMessage:'收据已进 PostgreSQL；锅的旅程另算。',rootTraceId:root,ids:{cryptoUuid:root,packageUuid:mapped.foreignUuid,nanoId:mapped.shortId,autoInteger:mapped.id,cacheId},postgres:true,rabbitQueued:queued,pendingReplication:true,replicationStatus:queued?'queued-not-yet-confirmed':'waiting-for-reconciliation'};}
 async chain(input:unknown,direct=false,grpc=false,existingRoot?:string){const dto=this.parse(input);const root=existingRoot||randomUUID();const fixed='2026-10-01T19:14:00.000Z';const tracer=this.provider.getTracer('absurd-municipal-office');const span=tracer.startSpan('一勺饭十四次审批');const context=trace.setSpan(ROOT_CONTEXT,span);for(let i=0;i<14;i++){const child=tracer.startSpan(`窗口${i+1}：请去隔壁`,{},context);child.setAttribute('ocv.root_trace_id',root);child.end();this.pointless.inc();}span.setAttribute('ocv.root_trace_id',root);
 let next:any;try{next=await this.request(grpc?'http://spring:8081/api/grpc.do':direct?'http://spring:8081/api/approved.php':'http://hono:3100/api/compatibility.do',{method:'POST',json:{...dto,rootTraceId:root,isoTime:fixed},timeout:{request:6500},headers:{traceparent:`00-${span.spanContext().traceId}-${span.spanContext().spanId}-01`}});}catch{next={canContinue:false,successReason:'窗口没开；6500ms 内退回。'};span.setStatus({code:SpanStatusCode.ERROR});}finally{span.end();}this.log(root,dto.label);const hops=[{service:'NestJS',rootTraceId:root,displayRequestId:randomUUID(),ok:'正常',storedTime:fixed,dateKind:'ISO8601'}];let p=next;for(let i=0;i<8&&p;i++,p=p.next)if(p.hop)hops.push(p.hop);let envelopesOkay=true;for(let q=next,j=0;q&&j<8;q=q.next,j++)if(q.canContinue!==true)envelopesOkay=false;const adaptedTimes=hops.map(h=>{const kind=h.dateKind;let value:number;if(kind==='Unix seconds')value=Number(h.storedTime)*1000;else if(kind==='Unix milliseconds')value=Number(h.storedTime);else if(kind==='Asia/Shanghai slash literal')value=Date.parse(String(h.storedTime).replaceAll('/','-').replace(' ','T')+':00+08:00');else value=Date.parse(h.storedTime);return {service:h.service,canonicalIso:Number.isFinite(value)?new Date(value).toISOString():null};});const canContinue=envelopesOkay&&hops.every(h=>normalizeMunicipalBoolean(h.ok))&&adaptedTimes.every(h=>h.canonicalIso===fixed);return {canContinue,successReason:canContinue?'':'有窗口没开门',rootTraceId:root,otelTraceId:span.spanContext().traceId,hops,next,normalizedTime:'2026/10/02 03:14',canonicalIso:fixed,adaptedTimes};}
 terminal(input:any){const allowed=['label','rootTraceId','isoTime','ornament'];if(!input||Object.keys(input).some(k=>!allowed.includes(k))||typeof input.label!=='string'||input.label.length>200||!/^[-a-f0-9]{36}$/i.test(input.rootTraceId))throw new BadRequestException('终止收据格式错误');return {canContinue:true,hop:{service:'NestJS terminal',rootTraceId:input.rootTraceId,displayRequestId:randomUUID(),ok:true,dateKind:'Asia/Shanghai slash literal',storedTime:'2026/10/02 03:14'},hopLimitReached:true};}
 async spread(root:string){if(!/^[-a-f0-9]{36}$/i.test(root))throw new BadRequestException('内部ID格式错误');await this.storage();const row=await this.prisma!.identityMap.findUnique({where:{rootId:root}});if(!row)return {canContinue:false,successReason:'映射不存在'};return this.chain({label:row.productName},false,false,root);}
 async split(root:string){if(!/^[-a-f0-9]{36}$/i.test(root))throw new BadRequestException('内部ID格式错误');await this.storage();const mapped=await this.prisma!.identityMap.findUnique({where:{rootId:root}});if(!mapped)return {canContinue:false,successReason:'映射表里没有这口锅'};const outcomes=await Promise.allSettled([this.request('http://laravel:8001/api/display/'+root),this.request('http://message-consumer:3100/api/replica/'+root),this.request('http://fastapi:8000/api/timestamp/'+root),this.redis!.get('inventory:temporary:'+root)]);const values=outcomes.map(x=>x.status==='fulfilled'?x.value:null);return {canContinue:values.every(x=>x!==null)&&values.slice(0,3).every((x:any)=>x.canContinue),rootTraceId:root,uuid:mapped.rootId,name:(values[0] as any)?.name??null,extra:(values[1] as any)?.record?.extra??null,temporary:values[3],sqliteTimestamp:(values[2] as any)?.timestamp??null,sources:values.map((x,i)=>({name:['MySQL','MongoDB','SQLite','Redis'][i],available:x!==null})),partial:values};}
 async readCache(id:string){if(!/^[A-Za-z0-9_-]{10,64}$/.test(id))throw new BadRequestException('缓存编号格式错误');await this.storage();const key='library:map:'+id;const value=await this.redis!.get(key);return {canContinue:value!==null,source:'Redis',cacheKey:key,ttlSeconds:await this.redis!.ttl(key),record:value?JSON.parse(value):null};}
 async redisOnly(){await this.storage();const value=await this.redis!.incr('sole-source:unrelated-potato');await this.redis!.expire('sole-source:unrelated-potato',600);return {canContinue:true,value,source:'Redis only; no PostgreSQL copy'};}
 private async closeStorage(){await Promise.allSettled([this.prisma?.$disconnect(),this.orm?.isInitialized?this.orm.destroy():undefined,this.db?.end()]);this.redis?.disconnect();this.prisma=undefined;this.orm=undefined;this.db=undefined;this.redis=undefined;}
 async onModuleDestroy(){await this.closeStorage();await this.provider.shutdown();}
}
