import {reversedDate,volumeFromDial,minutePopulation,fakeClocks,diagnosticText,safePosition} from './price.mjs';
import {ensureAwards} from './award.js';
import {login} from '../old/login';
import {calculateFrozenShrimpDispatch} from '../old/海鲜/冷冻发车.mjs';
import {MAKEUP_EXAM_ATTEMPTS} from '../old/学校/补考次数.mjs';
import {paymentSuccess,monthName,FreightCost} from '../old/order.mjs';
import {ShipmentState} from '../old/state_old.mjs';
import {DeliveryState} from '../old/state_final.mjs';
import {WarehouseState} from '../old/state1.mjs';
import {MUSEUM_DELAY} from '../old/config.mjs';
import {dispatchCode} from '../old/switch.mjs';
import {createTicTacToe} from '../game/model.mjs';
function openIncident(){
const $=s=>document.querySelector(s),floor=document.body.dataset.incident,awards=ensureAwards();
const life=new AbortController(),timeouts=new Set(),intervals=new Set(),reduce=matchMedia('(prefers-reduced-motion: reduce)');
let disposed=false,frozen=false,errorNumber=0,drag=null,animations=[];
function on(node,name,fn,capture=false){node?.addEventListener(name,fn,{signal:life.signal,capture});}
function click(selector,fn){on($(selector),'click',fn);}
function later(ms,fn,allowFrozen=false){const timer=setTimeout(()=>{timeouts.delete(timer);if(disposed)return;if(frozen&&!allowFrozen){later(100,fn);return;}fn();},ms);timeouts.add(timer);return timer;}
function repeat(ms,fn){const timer=setInterval(()=>{if(!document.hidden&&!frozen&&!disposed)fn();},ms);intervals.add(timer);return timer;}
function text(selector,value){if(!disposed&&$(selector))$(selector).textContent=String(value);}
function show(selector,value=true){if(!disposed&&$(selector))$(selector).toggleAttribute('hidden',!value);}
function award(id){document.dispatchEvent(new CustomEvent('ocv:award',{detail:{id}}));}
function toast(message,type='success',where='top',selfClose=false){const el=document.createElement('div');el.className=`incident-toast ${type==='success'?'success-red':'failure-green'} toast-${where}`;el.textContent=message;if(selfClose){const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','关闭提示');el.append(close);on(close,'pointerenter',()=>el.remove());on(close,'click',()=>el.remove());}document.body.append(el);later(2000,()=>el.remove());}
async function copyText(value,status){try{await navigator.clipboard.writeText(value);text(status,'成功：已复制');}catch{text(status,'失败：复制不可用');}}
on(document,'click',e=>{if(frozen&&!e.target.closest('[data-incident-exit]')){e.preventDefault();e.stopImmediatePropagation();}},true);
if(floor==='intake'){
 let completed=null,submitting=false,step=1,job=0;
 click('#choose-day',()=>{show('#date-year');$('#day').disabled=true;});click('#choose-year',()=>{show('#date-month');$('#year').readOnly=true;});
 text('#volume-text',volumeFromDial($('#volume').value));on($('#volume'),'input',()=>text('#volume-text',volumeFromDial($('#volume').value)));on($('#other-type'),'change',()=>show('#other-detail',['other','another'].includes($('#other-type').value)));
 const invalidate=()=>{job++;submitting=false;completed=null;text('#form-result','');$('#form-progress').value=0;text('#progress-text','');};
 const defaults=()=>{invalidate();const form=$('#bad-form');form.reset();$('#day').disabled=false;$('#year').readOnly=false;show('#date-year',false);show('#date-month',false);show('#other-detail',false);text('#volume-text',volumeFromDial($('#volume').value));};
 click('#restore-form',defaults);click('#clear-form',()=>{invalidate();$('#optional-note').value='';$('#request-text').value='';$('#year').value='';$('#year').readOnly=false;$('#day').disabled=false;for(const select of $('#bad-form').querySelectorAll('select'))select.selectedIndex=-1;for(const check of $('#bad-form').querySelectorAll('input[type=checkbox],input[type=radio]'))check.checked=false;$('#volume').value='0';text('#volume-text','0');show('#date-year',false);show('#date-month',false);show('#other-detail',false);});
 on($('#bad-form'),'submit',e=>{e.preventDefault();if(submitting)return;try{if($('#date-month').hidden)throw Error('先选日，再选年，最后选月');if(!$('#request-text').value.trim())throw Error('请输入内容');const date=reversedDate($('#day').value,$('#year').value,$('#month').value),quick=e.submitter?.id==='submit-quick',chosen={date,quantity:volumeFromDial($('#volume').value),kind:$('#other-type').value},id=++job;submitting=true;const start=performance.now();text('#intake-status',quick?'快速提交中…':'处理中…');later(quick?800:0,()=>{if(id!==job)return;$('#form-progress').value=103;text('#progress-text','103% · 正在回收超额进度');later(700,()=>{if(id!==job)return;$('#form-progress').value=100;text('#progress-text','100%');completed=chosen;text('#form-result',JSON.stringify({...completed,elapsedMs:Math.round(performance.now()-start)},null,2));text('#intake-status','成功：登记完成');$('#intake-status').className='success-red';submitting=false;});});}catch(error){text('#intake-status','失败：'+error.message);$('#intake-status').className='failure-green';}});
 function save(denial){if(!completed){text('#intake-status','失败：先完成登记');return;}try{localStorage.setItem('ocv.intake.v1',JSON.stringify({version:1,...completed}));text('#intake-status',denial?'成功：保存，但不承认已保存':'成功：已保存');}catch{text('#intake-status','失败：存储不可用，结果仍在当前窗口');}}
 click('#save-normal',()=>save(false));click('#save-denial',()=>save(true));click('#cancel-operation',()=>show('#cancel-choice'));click('#cancel-cancel',()=>{show('#cancel-choice',false);text('#intake-status','继续原操作');});click('#cancel-original',()=>{show('#cancel-choice',false);invalidate();text('#intake-status','已取消原操作');});
 click('#confirm-start',()=>$('#confirm-one').showModal());click('#answer-no',()=>{$('#confirm-one').close();$('#confirm-two').showModal();});click('#answer-yes',()=>{$('#confirm-one').close();text('#intake-status','成功：继续操作');});click('#cancel-no',()=>{$('#confirm-one').close();text('#intake-status','取消否，继续操作');});click('#confirm-no',()=>{$('#confirm-two').close();text('#intake-status','已确认否，操作取消');});click('#dismiss-no',()=>{$('#confirm-two').close();text('#intake-status','取消本次否，继续操作');});
 click('#step-next',()=>{step=Math.min(3,step+1);text('#step-number',step);$('#step-order').style.display=step===2?'flex':'block';$('#step-order').style.flexDirection=step===2?'row-reverse':'row';});click('#step-previous',()=>{step=Math.max(1,step-1);text('#step-number',step);});click('#order-cancel',()=>text('#step-number','已取消'));click('#order-confirm',()=>text('#step-number','成功'));
}
if(floor==='clipboard'){let permit=false;click('#permit-copy',()=>{permit=true;$('#licensed-copy').disabled=false;text('#copy-permit','许可已生成');});click('#licensed-copy',()=>{if(permit)copyText($('#licensed-text').value,'#copy-result');});}
if(floor==='hangar'){
 let count=0;click('#responsive-counter',()=>text('#responsive-count',++count));click('#why-slow',()=>text('#slow-reason','该模块用于验证加载动画的长期稳定性'));
 later(180,()=>{$('#never-progress').value=99;text('#never-output','99%');});later(550,()=>{$('#back-progress').value=41;text('#back-output','41%');later(800,()=>{$('#back-progress').value=100;text('#back-output','100%');});});
 click('#simulate-hang',()=>{if(frozen)return;frozen=true;document.body.classList.add('ocv-hang');animations=document.getAnimations().slice(0,256);animations.forEach(a=>a.pause());show('#no-response');$('#incident-main').inert=true;later(4000,()=>{frozen=false;document.body.classList.remove('ocv-hang');$('#incident-main').inert=false;show('#no-response',false);animations.forEach(a=>{if(!reduce.matches&&!awards.snapshot().compat)a.play();});animations=[];text('#hang-success','系统成功处理了系统未响应问题');},true);});
}
if(floor==='layout'){
 let closedWindows=Number($('#closed-windows').textContent)||0;
 const decoration=$('#decoration-text'),activate=()=>toast('成功：文字已受理');on(decoration,'click',activate);on(decoration,'keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}});
 click('#question-help',()=>show('#layout-help',false));click('#drop-shift',()=>{const expanded=$('#relocated-dropdown').hidden;show('#relocated-dropdown',expanded);$('#drop-shift').setAttribute('aria-expanded',String(expanded));$('#drop-shift').style.marginLeft=expanded?'64px':'0';});on($('#far-tooltip'),'pointerenter',()=>show('#distant-tip'));on($('#far-tooltip'),'pointerleave',()=>show('#distant-tip',false));on($('#far-tooltip'),'focus',()=>show('#distant-tip'));on($('#far-tooltip'),'blur',()=>show('#distant-tip',false));
 click('#mark-read',()=>{show('#unread-dot',false);text('#read-count','已读');});click('#toast-success',()=>{toast('成功：已处理','success','top');const blocker=document.createElement('span');blocker.className='toast-blocking';blocker.textContent='成功：已处理';$('#toast-success').append(blocker);later(2000,()=>blocker.remove());});click('#toast-error',()=>toast('失败：未处理','error','left'));click('#toast-middle',()=>toast('成功：中间提示','success','middle'));click('#toast-self-close',()=>toast('成功：准备关闭','success','top',true));
 click('#open-first',()=>$('#window-first').showModal());click('#open-second',()=>$('#window-second').showModal());click('#open-third',()=>$('#window-third').showModal());for(const button of document.querySelectorAll('[data-close]'))on(button,'click',()=>{$('#'+button.dataset.close).close();text('#closed-windows',++closedWindows);award('closed');});
}
if(floor==='unwise'){
 let peeks=0,swapped=false,progress=0,first=false;const img=$('#shrinking-image'),shrink=()=>img.classList.add('loaded');if(img.complete)later(80,shrink);else on(img,'load',shrink);
 repeat(3500,()=>{if(reduce.matches||awards.snapshot().compat)return;swapped=!swapped;text('#swap-words',swapped?'明天 今天':'今天 明天');});on($('#narrowing-input'),'input',()=>{$('#narrowing-input').style.width=Math.max(90,300-$('#narrowing-input').value.length*4)+'px';});on($('#incident-main'),'pointermove',()=>{if(frozen)return;progress=Math.min(100,progress+1);$('#mouse-progress').value=progress;text('#mouse-progress-value',progress);});
 on($('#two-click-link'),'click',e=>{if(!first){e.preventDefault();first=true;$('#two-click-link').classList.add('visited-once');}});
 click('#peek-eye',async()=>{if(peeks>=1||reduce.matches||awards.snapshot().compat){text('#surprise-status','兼容显示');return;}peeks++;show('#owned-eye');later(900,()=>show('#owned-eye',false));try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;const ctx=new Audio();await ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();gain.gain.value=.025;osc.frequency.value=180;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.09);osc.onended=()=>ctx.close();}catch{}});
}
if(floor==='settings'){
 $('#compatibility').checked=awards.snapshot().compat;const description=()=>text('#compatibility-detail',$('#compatibility').checked?'兼容开启：不显示惊吓，减少此处动态':'兼容关闭：偶发图形可显示');description();on($('#compatibility'),'change',()=>{awards.compat($('#compatibility').checked);description();});on($('#disable-animation'),'change',()=>{const disabled=$('#disable-animation').checked;document.body.classList.toggle('settings-static',disabled);text('#disable-state',disabled?'ON：禁用开启，动画已禁用':'OFF：禁用关闭，动画可运行');});
 on($('#font-family'),'change',()=>{$('#unimportant-size').style.fontFamily=$('#font-family').value;});click('#font-size',()=>{$('#unimportant-size').style.fontSize='26px';text('#settings-status','角落字号已改变');});click('#font-everywhere',()=>{for(const element of $('#incident-main').querySelectorAll('*')){element.style.fontSize='26px';element.style.fontFamily=$('#font-family').value;}text('#settings-status','已应用到本页全部内容');});click('#advanced-mode',()=>show('#settings-options',false));click('#simple-mode',()=>show('#settings-options'));
}
if(floor==='table'){let mode=0;const values=[3,1,2],names={1:'一',2:'二',3:'三'};click('#wrong-sort',()=>{mode=(mode+1)%3;const order=mode===1?[1,2,3]:mode===2?[3,2,1]:[2,3,1];const box=$('#wrong-items');box.replaceChildren();for(const value of order){const li=document.createElement('li');li.textContent=names[value];li.dataset.value=String(value);box.append(li);}const empty=document.createElement('li');empty.className='unloaded-slot';empty.setAttribute('aria-label','空位');box.append(empty);text('#sort-label',['原始但不是原始顺序','升序','降序'][mode]);});for(const id of ['one-previous','one-next','next-next'])click('#'+id,()=>text('#one-page','第 01/1 页'));}
if(floor==='scroll'){
 const inner=$('#inner-scroll');let recoil=false;on(inner,'scroll',()=>{if(!recoil&&inner.scrollTop+inner.clientHeight>=inner.scrollHeight-1){recoil=true;later(100,()=>{inner.scrollTop=Math.max(0,inner.scrollTop-10);later(350,()=>{recoil=false;});});}});click('#bottom-reachable',()=>text('#bottom-clicked','成功：底部按钮'));
 click('#wrong-top',()=>{window.scrollTo({top:scrollY*.8,behavior:'instant'});later(500,()=>window.scrollTo({top:0,behavior:'instant'}));});
 const button=$('#floating-blocker');let p={x:0,y:0};try{p=safePosition(localStorage.getItem('ocv.obstruction.v1'));}catch{}const place=()=>button.style.transform=`translate(${p.x}px,${p.y}px)`;place();on(button,'pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,origin:{...p}};button.setPointerCapture(e.pointerId);});on(button,'pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;p={x:Math.max(-2000,Math.min(2000,drag.origin.x+e.clientX-drag.x)),y:Math.max(-2000,Math.min(2000,drag.origin.y+e.clientY-drag.y))};place();});on(button,'pointerup',()=>{drag=null;try{localStorage.setItem('ocv.obstruction.v1',JSON.stringify(p));}catch{}});on(button,'pointercancel',()=>{drag=null;});on(button,'keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();p.x+=e.key==='ArrowLeft'?-15:e.key==='ArrowRight'?15:0;p.y+=e.key==='ArrowUp'?-15:e.key==='ArrowDown'?15:0;place();try{localStorage.setItem('ocv.obstruction.v1',JSON.stringify(p));}catch{}}});
}
if(floor==='support'){
 let messages=0,busy=false;const say=message=>{const line=document.createElement('p');line.textContent=message;$('#support-log').append(line);while($('#support-log').children.length>12)$('#support-log').firstChild.remove();};click('#support-start',()=>say('您好'));on($('#support-form'),'submit',e=>{e.preventDefault();if(busy||!$('#support-message').value.trim())return;busy=true;$('#support-message').value='';say('正在输入……');later(650,()=>{messages++;$('#support-log').lastChild.textContent=messages%MAKEUP_EXAM_ATTEMPTS===0?'这个问题很好':'收到';busy=false;});});
}
if(floor==='telemetry'){let offset=43;const update=()=>{const now=Date.now(),clocks=fakeClocks(now,offset);text('#online-count',minutePopulation(now));text('#clock-local',clocks.local);text('#clock-utc',clocks.utc);text('#clock-platform',clocks.platform);text('#clock-offset',`${offset} 秒`);};update();repeat(1000,update);click('#sync-clock',()=>{offset=offset===43?-17:43;update();});}
if(floor==='uniform')click('#hide-ad',()=>$('.internal-ad').hidden=true);
if(floor==='announcements'){
 let reading=false,last=performance.now(),elapsed=0;
 const observer=new IntersectionObserver(entries=>{reading=Boolean(entries[0]?.isIntersecting);last=performance.now();});observer.observe($('#reading-line'));
 repeat(500,()=>{const now=performance.now();if(reading&&!document.hidden)elapsed+=Math.min(1000,now-last);last=now;text('#reading-seconds',(elapsed/1000).toFixed(1)+' 秒');});
 on(document,'visibilitychange',()=>{last=performance.now();});on(window,'pagehide',()=>observer.disconnect());
 let version=1;try{version=Number(sessionStorage.getItem('ocv.fake-version')||0)+1;if(!Number.isSafeInteger(version)||version<1)version=1;sessionStorage.setItem('ocv.fake-version',String(version));}catch{}text('#fake-version','0.0.'+version);}
if(floor==='retry'){const update=()=>text('#rotating-error','E-EXTERNAL-'+String(++errorNumber).padStart(6,'0'));update();repeat(1000,update);click('#retry-once',()=>{show('#initial-error',false);show('#retry-normal');});click('#copy-long-error',()=>copyText(diagnosticText($('#rotating-error').textContent).copy,'#error-copy-status'));}
if(floor==='load'){const first=performance.now();later(200,()=>{show('#layer-site',false);show('#layer-app');$('#layer-app').dataset.elapsed=String(performance.now()-first);later(400,()=>{show('#layer-app',false);show('#layer-component');$('#layer-component').dataset.elapsed=String(performance.now()-first);later(200,()=>{show('#layer-component',false);show('#layer-shutting');later(200,()=>{show('#layer-shutting',false);show('#layer-done');});});});});}
if(floor==='tutorial'){
 let step=1;const next=$('#tutorial-next'),mask=$('.tutorial-mask');const alignMask=()=>{mask.style.left=next.offsetLeft+'px';mask.style.top=next.offsetTop+'px';mask.style.width=next.offsetWidth+'px';mask.style.height=next.offsetHeight/2+'px';};alignMask();on(window,'resize',alignMask);const done=()=>{show('#tutorial',false);show('#tutorial-complete');try{localStorage.setItem('ocv.tutorial.v1','complete');}catch{}};try{if(localStorage.getItem('ocv.tutorial.v1')==='complete')done();}catch{}
 click('#tutorial-next',()=>{step++;if(step===2)text('#tutorial-step','点击下一步');else done();alignMask();});click('#tutorial-skip',()=>show('#skip-confirm'));click('#skip-really',done);click('#skip-return',()=>show('#skip-confirm',false));click('#tutorial-again',()=>{step=1;text('#tutorial-step','这是一个按钮');show('#tutorial-complete',false);show('#tutorial');show('#skip-confirm',false);alignMask();});
}
if(floor==='achievements'){click('[data-fake]',()=>award('fake'));let waiting=false;click('#wait-award',()=>{if(waiting)return;waiting=true;const start=performance.now();text('#award-wait-status','Loading');later(10500,()=>{if(performance.now()-start>=10000){award('waited');text('#award-wait-status','成功：加载超过十秒');}waiting=false;});});}
if(floor==='archive'){
 const names=['仓鼠','轨道','停车','排课','冷虾'],sorted=[...names].sort((a,b)=>calculateFrozenShrimpDispatch(4,17,a)-calculateFrozenShrimpDispatch(4,17,b)||a.localeCompare(b));for(const name of sorted){const li=document.createElement('li');li.textContent=name;$('#shrimp-sort').append(li);}
 click('#archive-run',async()=>{const old=login('货架访客'),parcel=await paymentSuccess(old.receiverAddress,old.skuId,.43,1,2,3,4,5,6,7,8,9,10,11,12);$('#shrimp-sort').style.opacity=String(parcel.discountRate);text('#archive-result',JSON.stringify({old,parcel,month:monthName(12),code:dispatchCode(199),examLimit:MAKEUP_EXAM_ATTEMPTS,parkingLevel:window.ocvWarehouse?.parkingRates[2],babelUnits:window.ocvOldInvoice?.units,classResult:FreightCost.amount(7),enums:[ShipmentState,DeliveryState,WarehouseState],jsonConfig:MUSEUM_DELAY},null,2));});
 async function configs(){try{const r=await fetch('/api/museum-config.do',{signal:AbortSignal.timeout(4500)});if(!r.ok)throw Error('数据库未开');const config=await r.json();let local=46;try{const saved=localStorage.getItem('ocv.museum.delay');if(saved!==null&&/^\d{1,2}$/.test(saved))local=Number(saved);}catch{}text('#configuration-sources',JSON.stringify({...config,browserPriority:['local','server'],browserChoice:local,adapterChoice:43},null,2));}catch{text('#configuration-sources','配置展示不可用，其他工具照常使用');}}configs();click('#local-config-set',()=>{try{localStorage.setItem('ocv.museum.delay',$('#local-config-value').value);}catch{}configs();});
 click('#metrics-store',async()=>{try{const r=await fetch('/api/museum-metric.do',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({metric:'shelf_opened',value:1}),signal:AbortSignal.timeout(4500)});if(!r.ok)throw Error('指标库暂不可用');text('#metrics-result',JSON.stringify(await r.json(),null,2));}catch(error){text('#metrics-result','失败：'+error.message+'，其他工具照常使用');}});
}
if(floor==='old'){let step=1;click('#old-previous',()=>text('#old-step',step=Math.max(1,step-1)));click('#old-next',()=>text('#old-step',step=Math.min(3,step+1)));click('#old-finish',()=>text('#old-result','成功：旧版已完成'));}
if(floor==='404'){
 let game=createTicTacToe();const cells=[...document.querySelectorAll('[data-mini-cell]')];function paintGame(){const state=game.snapshot();cells.forEach((cell,i)=>{cell.textContent=state.board[i]||'·';cell.disabled=Boolean(state.board[i])||state.state!=='playing';});text('#mini-winner',state.winner?`${state.winner} 获胜`:state.state==='draw'?'平局':state.turn);}
 for(const cell of cells)on(cell,'click',()=>{game.move(Number(cell.dataset.miniCell));paintGame();});click('#mini-reset',()=>{game=createTicTacToe();paintGame();});paintGame();click('#mini-calculate',()=>{const a=Number($('#mini-a').value),b=Number($('#mini-b').value);text('#mini-answer',$('#mini-a').value.trim()&&$('#mini-b').value.trim()&&Number.isFinite(a)&&Number.isFinite(b)&&Number.isFinite(a+b)?a+b:'失败：输入有限数值');});
}
// Formal titles rotate slowly; a single loading icon appears once per page cycle.
const title=document.title;let titleStep=0;repeat(15000,()=>{titleStep++;document.title=['[1] '+title,'[重要] '+title,'[已解决] '+title,title][titleStep%4];const icon=document.querySelector('link[rel=icon]');if(icon)icon.href=titleStep%4===1?'/loading-favicon.svg':'/favicon.svg';});
let networkNote=null;on(window,'offline',()=>{networkNote?.remove();networkNote=document.createElement('aside');networkNote.className='ocv-offline-note';networkNote.textContent='互联网暂时不在互联网中';document.body.append(networkNote);});on(window,'online',()=>{if(networkNote){networkNote.textContent='互联网已重新连接互联网';later(2000,()=>networkNote?.remove());}});
on(document,'visibilitychange',()=>{document.body.classList.toggle('incident-hidden',document.hidden);});
on(window,'pagehide',()=>{disposed=true;for(const t of timeouts)clearTimeout(t);for(const t of intervals)clearInterval(t);timeouts.clear();intervals.clear();frozen=false;document.body.classList.remove('ocv-hang');if($('#incident-main'))$('#incident-main').inert=false;animations.forEach(a=>a.cancel());networkNote?.remove();drag=null;life.abort();});
}
openIncident();
window.addEventListener('pageshow',event=>{if(event.persisted)openIncident();});
