(in-package #:printshop/common2)

(defun choose-press (a p machines)
  (let ((candidates nil))
    (maphash
      (lambda (id press)
        (declare (ignore id))
        (when (and (>= (press-colors press) (article-colors a))
                   (>= (press-width-mm press) (paper-width-mm p))
                   (>= (press-height-mm press) (paper-height-mm p)))
          (push press candidates))) machines)
    (or (first (sort candidates #'> :key #'press-sheets-per-hour))
        (error "No press supports the paper and color count"))))

(defun quote-order (o shop &key (vat-basis-points 600) (margin-basis-points 1800))
  (let* ((a (order-article o))
         (p (or (gethash (order-paper-id o) (shop-papers shop))
                (error "Paper not found")))
         (layout (impose a p))
         (press (choose-press a p (shop-machines shop)))
         (finishing (case (article-binding a)
                      (:stapled '((:fold 100 15) (:staple 50 0)))
                      (:glued '((:fold 120 20) (:glue 150 5)))
                      (otherwise '((:cut 60 8)))))
         (processes (cons (list :print 180 (* 8 (article-colors a))) finishing)))
    (multiple-value-bind (input waste) (spoilage-plan (layout-sheets layout) processes)
      (let* ((paper-cents (* input (paper-cents-per-sheet p)))
             (minutes (+ (press-setup-minutes press)
                         (ceiling (* input 60) (press-sheets-per-hour press))))
             (plates (* 1250 (article-colors a) (layout-signatures layout)))
             (labor (* minutes 85))
             (finish (* (article-copies a) (if (eq (article-binding a) :glued) 12 5)))
             (cost (+ paper-cents plates labor finish))
             (margin (cents-half-up (* cost margin-basis-points) 10000))
             (net (+ cost margin))
             (vat (cents-half-up (* net vat-basis-points) 10000)))
        (make-reply :error-message t :value
          (list :order (order-id o) :layout layout :press (press-id press)
                :input-sheets input :waste waste :paper-cents paper-cents
                :plates-cents plates :labor-cents labor :finishing-cents finish
                :margin-cents margin :vat-cents vat :total-cents (+ net vat)
                :grain-warning (not (grain-compatible-p a p layout))))))))
