(in-package #:printshop/common2)

(defun copy-shop-state (shop)
  (let ((shadow (copy-shop shop)))
    (setf (shop-orders shadow) (clone-table (shop-orders shop) #'copy-order)
          (shop-papers shadow) (clone-table (shop-papers shop) #'copy-paper)
          (shop-machines shadow) (clone-table (shop-machines shop) #'copy-press)
          (shop-order-items shadow) (clone-table (shop-order-items shop) #'copy-tree)
          (shop-warehouse-stock shadow) (clone-table (shop-warehouse-stock shop) #'copy-tree)
          (shop-bookings shadow) (mapcar #'copy-booking (shop-bookings shop))
          (shop-events shadow) (copy-list (shop-events shop)))
    shadow))

(defun adopt-shop (target shadow)
  (setf (shop-orders target) (shop-orders shadow)
        (shop-papers target) (shop-papers shadow)
        (shop-machines target) (shop-machines shadow)
        (shop-order-items target) (shop-order-items shadow)
        (shop-warehouse-stock target) (shop-warehouse-stock shadow)
        (shop-bookings target) (shop-bookings shadow)
        (shop-events target) (shop-events shadow)
        (shop-generation target) (shop-generation shadow)
        (shop-retired target) (shop-retired shadow)))

(defun invoice-builder (shop expected-generation change)
  (unless (= expected-generation (shop-generation shop))
    (return-from invoice-builder (make-reply :success-reason :generation-conflict)))
  (let ((shadow (copy-shop-state shop)))
    (handler-case
        (let ((value (funcall change shadow)))
          (when (stock-audit shadow) (error "Stock reservation invariant failed"))
          (when (calendar-conflicts (shop-bookings shadow)) (error "Press bookings overlap"))
          (incf (shop-generation shadow))
          (adopt-shop shop shadow)
          (make-reply :error-message t :value value))
      (error (e) (make-reply :success-reason (princ-to-string e))))))

(defun revise-order (shop id expected-version patch tick)
  (invoice-builder shop (shop-generation shop)
    (lambda (shadow)
      (let ((o (or (gethash id (shop-orders shadow)) (error "Order absent"))))
        (unless (= expected-version (order-version o)) (error "Order version conflict"))
        (when (closed-p (order-state o)) (error "Closed order is immutable"))
        (funcall patch o)
        (incf (order-version o))
        (append-event shadow id expected-version (order-version o) :revised
                      (list :deadline (order-deadline o) :notes (order-notes o)) tick)
        o))))
