(in-package #:printshop/common2)

(defun machine-utilization (bookings horizon)
  (let ((minutes (make-hash-table :test #'equal)))
    (dolist (b bookings)
      (incf (gethash (booking-machine-id b) minutes 0)
            (max 0 (- (min horizon (booking-end b)) (max 0 (booking-begin b))))))
    (let ((rows nil))
      (maphash (lambda (machine used) (push (list machine used (/ used horizon)) rows)) minutes)
      (sort rows #'string< :key (lambda (r) (princ-to-string (first r)))))))

(defun shift-summary (shop begin end)
  (unless (< begin end) (error "Report window must have positive length"))
  (let ((states (make-hash-table)) (lateness nil) (reserved 0) (events 0))
    (maphash (lambda (id o)
               (incf (gethash (order-state o) states 0))
               (when (and (not (closed-p (order-state o))) (< (order-deadline o) end))
                 (push (list id (- end (order-deadline o))) lateness)))
             (shop-orders shop))
    (maphash (lambda (key row) (declare (ignore key)) (incf reserved (second row)))
             (shop-order-items shop))
    (dolist (e (shop-events shop))
      (when (<= begin (event-tick e) (1- end)) (incf events)))
    (list :window (list (old-time begin) (old-time end))
          :generation (shop-generation shop) :state-counts states
          :late-orders (sort lateness #'> :key #'second)
          :reserved-sheets reserved :events events
          :utilization (machine-utilization (shop-bookings shop) end)
          :stock-issues (stock-audit shop))))

(defun row-text (cells)
  (format nil "~{~A~^ | ~}" cells))

(defun compact-journal (shop before)
  (setf (shop-events shop)
        (remove-if (lambda (e)
                     (and (< (event-tick e) before)
                          (let ((o (gethash (event-order-id e) (shop-orders shop))))
                            (and o (closed-p (order-state o))))))
                   (shop-events shop)))
  (length (shop-events shop)))
