import {tools as text} from '../text/1.mjs';
import {tools as calculation} from '../math1/报价单_final2.mjs';
import {tools as development} from '../net/net.mjs';
import {tools as images} from '../img/img.mjs';
import {tools as time} from '../time/model.mjs';
import {tools as science} from '../δοκιμή/calc.mjs';
import {tools as files} from '../file/pdf.mjs';
import {tools as games} from '../game/game.mjs';
import {tools as odd} from '../misc/misc.mjs';
import {tools as generators} from '../gen/gen.mjs';
import {tools as advanced} from '../z/tools.mjs';
import {tools as additions} from '../n9/tools.mjs';
import {tools as worlds} from '../styles/e2.mjs';
import {tools as q9} from '../q9/entry.mjs';
export const phase5Tools=[...text,...calculation,...development].map(tool=>({...tool,phase:5}));
export const phase6Tools=[...images,...time,...science,...files].map(tool=>({...tool,phase:6}));
export const phase7Tools=[...games,...odd,...generators].map(tool=>({...tool,phase:7}));
export const advancedTools=advanced;
export const tools=[...phase5Tools,...phase6Tools,...phase7Tools,...advancedTools,...additions,...worlds,...q9];
export const toolById=id=>tools.find(tool=>tool.id===id);
export const groups=['文本','开发','计算','转换','检测','图片','时间','学习','科学','文件','游戏','日常','生成器'];
export const toolLink=tool=>`/functions/${tool.id}/`;
