// One bounded renderer; decoration never handles form data or blocks a route.
const stage=document.querySelector('[data-gravity-stage]');
const canvas=document.querySelector('#civilization-core');
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const fine=matchMedia('(pointer: fine)');
const life=new AbortController();
const on=(target,event,fn,options={})=>target?.addEventListener(event,fn,{...options,signal:life.signal});
const state={renderer:'css',frames:0,particles:42,limit:8,airborne:0,visible:true,reduced:reduce.matches,gravity:1};
window.__ocvScene=state;
const pointer={x:0,y:0};let gl,program,uniforms,raf=0,last=0,clock=0,frameTimes=[],intersecting=true,dirty=true,disposed=false;
const vertex='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';
const fragment=`precision mediump float;
uniform vec2 size;uniform vec2 mouse;uniform float tick;
mat2 rot(float a){return mat2(cos(a),-sin(a),sin(a),cos(a));}
vec3 model(vec3 p){p.xy=rot(-.45+mouse.x*.28)*p.xy;p.yz=rot(.9+sin(tick*.22)*.18+mouse.y*.25)*p.yz;p.xz=rot(tick*.16)*p.xz;return p;}
float shape(vec3 p){p=model(p);return length(vec2(length(p.xz)-.88,p.y))-.31;}
vec3 normal(vec3 p){vec2 e=vec2(.004,0.);return normalize(vec3(shape(p+e.xyy)-shape(p-e.xyy),shape(p+e.yxy)-shape(p-e.yxy),shape(p+e.yyx)-shape(p-e.yyx)));}
float noise(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.54);}
void main(){vec2 uv=(gl_FragCoord.xy-size*.5)/min(size.x,size.y);vec3 ro=vec3(0.,0.,3.8);vec3 rd=normalize(vec3(uv*2.9,-3.));float d=0.;float h=1.;for(int i=0;i<48;i++){h=shape(ro+rd*d);if(h<.002||d>6.)break;d+=h*.85;}if(d>6.||h>.02){gl_FragColor=vec4(0.);return;}vec3 p=ro+rd*d;vec3 n=normal(p);vec3 r=reflect(rd,n);float fres=pow(1.-max(0.,dot(n,-rd)),3.);float band=pow(max(0.,sin(r.y*7.+r.x*3.)),10.);float broad=pow(max(0.,dot(n,normalize(vec3(-.6,1.,1.)))),3.);float spec=pow(max(0.,dot(r,normalize(vec3(-.8,1.,.7)))),28.);vec3 color=vec3(.065,.10,.115)+vec3(.68,.74,.79)*broad+vec3(.85,.94,1.)*band+vec3(.65,1.,.78)*fres+spec; color+=vec3(.12,.15,.2)*max(r.x,0.);color+=(noise(gl_FragCoord.xy+fract(tick)*12.)-.5)*.035;gl_FragColor=vec4(color,1.);}`;
function setup(){try{gl=canvas.getContext('webgl',{alpha:true,antialias:false,powerPreference:'low-power',preserveDrawingBuffer:false});if(!gl)return;const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){gl.deleteShader(s);throw Error('shader unavailable');}return s;};const vs=compile(gl.VERTEX_SHADER,vertex),fs=compile(gl.FRAGMENT_SHADER,fragment);program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('link unavailable');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);uniforms={size:gl.getUniformLocation(program,'size'),mouse:gl.getUniformLocation(program,'mouse'),tick:gl.getUniformLocation(program,'tick')};state.renderer='webgl';stage.dataset.renderer='webgl';}catch{state.renderer='css';stage.dataset.renderer='css';gl=null;}}
setup();
const particleCanvas=document.createElement('canvas');particleCanvas.id='orbital-particles';particleCanvas.setAttribute('aria-hidden','true');stage.prepend(particleCanvas);const ctx=particleCanvas.getContext('2d');
const particles=Array.from({length:42},(_,i)=>({x:((i*73+19)%101)/101,y:((i*47+37)%103)/103,r:i%4===0?1.4:.65}));
function size(){const rect=stage.getBoundingClientRect();const scale=Math.min(1.25,640/Math.max(rect.width,rect.height));canvas.width=particleCanvas.width=Math.max(1,Math.round(rect.width*scale));canvas.height=particleCanvas.height=Math.max(1,Math.round(rect.height*scale));dirty=true;wake();}
const ro=new ResizeObserver(size);ro.observe(stage);
function draw(){if(gl){gl.viewport(0,0,canvas.width,canvas.height);gl.uniform2f(uniforms.size,canvas.width,canvas.height);gl.uniform2f(uniforms.mouse,pointer.x,pointer.y);gl.uniform1f(uniforms.tick,clock);gl.drawArrays(gl.TRIANGLES,0,6);}if(ctx){const w=particleCanvas.width,h=particleCanvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#b9fbd0';particles.forEach((p,i)=>{const x=(p.x+Math.sin(clock*.09+i)*.028)*w,y=(p.y+Math.cos(clock*.13+i)*.035)*h;ctx.globalAlpha=.2+Math.sin(clock*.4+i)*.15;ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();if(i%3===0){ctx.strokeStyle='#abd8c4';ctx.lineWidth=.4;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+22,y-12);ctx.stroke();}});ctx.globalAlpha=1;}state.frames++;}
function frame(now){raf=0;if(disposed||document.hidden)return;const elapsed=now-last;if(elapsed>33){if(intersecting&&(!reduce.matches||dirty)){clock+=Math.min(elapsed/1000,.08)*state.gravity;draw();frameTimes.push(Math.round(1000/elapsed));if(frameTimes.length>28)frameTimes.shift();if(state.frames%15===0){document.querySelector('#scene-fps').textContent=String(Math.round(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length));document.querySelector('#frame-wave').setAttribute('points',frameTimes.map((v,i)=>`${i*5},${23-Math.min(v,60)/3}`).join(' '));}}if(dirty){scrollEffects();dirty=false;}last=now;}if(!reduce.matches&&(intersecting||dirty))raf=requestAnimationFrame(frame);}
function wake(){if(!raf&&!disposed&&!document.hidden){last=performance.now()-40;raf=requestAnimationFrame(frame);}}
const visibility=new IntersectionObserver(entries=>{intersecting=entries[0].isIntersecting;state.visible=intersecting;dirty=true;wake();},{rootMargin:'80px'});visibility.observe(stage);
on(document,'visibilitychange',()=>{document.body.dataset.sceneHidden=String(document.hidden);if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{dirty=true;wake();}});
on(canvas,'webglcontextlost',e=>{e.preventDefault();state.renderer='css';stage.dataset.renderer='css';gl=null;});
on(stage,'pointermove',e=>{if(reduce.matches)return;const r=stage.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;dirty=true;wake();});
on(document.querySelector('#local-gravity'),'input',e=>{state.gravity=Number(e.target.value);document.querySelector('#gravity-value').textContent=state.gravity.toFixed(1);document.documentElement.style.setProperty('--float-time',`${12/state.gravity}s`);dirty=true;wake();});
const burstTimers=new Map();const count=document.querySelector('#airborne-count');
on(document.querySelector('#throw-civilization'),'click',()=>{if(burstTimers.size>=8)return;const chip=document.createElement('span');chip.className='thrown-civilization';chip.textContent=['fragment','批准无效','受付終了','NULL®','已转交空气'][state.frames%5];chip.style.setProperty('--throw-x',`${(Math.random()-.5)*440}px`);chip.style.setProperty('--throw-y',`${-160-Math.random()*220}px`);chip.style.setProperty('--throw-r',`${(Math.random()-.5)*150}deg`);chip.setAttribute('aria-hidden','true');stage.append(chip);const timer=setTimeout(()=>{chip.remove();burstTimers.delete(chip);state.airborne=burstTimers.size;count.textContent=String(state.airborne);},2800);burstTimers.set(chip,timer);state.airborne=burstTimers.size;count.textContent=String(state.airborne);});
const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.querySelectorAll('.has-reveal').forEach(el=>el.classList.add('is-revealed'));reveal.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.section-index h2,.receipt-intro h2,.chapter-heading h2,.stack-card h3').forEach(el=>{el.classList.add('has-reveal');reveal.observe(el.parentElement);});
const headline=document.querySelector('#launch-title>span');headline.classList.add('kinetic-word');
const odometer=document.querySelector('#depth-odometer');const columns=Array.from({length:5},()=>{const col=document.createElement('span');col.className='odometer-column';col.setAttribute('aria-hidden','true');for(let i=0;i<10;i++){const digit=document.createElement('span');digit.textContent=i;col.append(digit);}return col;});odometer.replaceChildren(...columns);
function scrollEffects(){const top=Math.round(Math.max(0,scrollY));if(!reduce.matches){headline.style.setProperty('--word-width',String(Math.max(.78,1-top/2000)));headline.style.setProperty('--word-space',`${-6+Math.min(top/100,5)}px`);}const digits=String(Math.min(top,99999)).padStart(5,'0');columns.forEach((col,i)=>col.style.transform=`translateY(${-Number(digits[i])*42}px)`);odometer.setAttribute('aria-label',`页面滚动 ${top} 像素`);const area=document.querySelector('.stacking-sector').getBoundingClientRect();const progress=Math.max(0,Math.min(1,(innerHeight-area.top)/(innerHeight+area.height*.35)));document.querySelector('#drawn-circuit').style.strokeDashoffset=String(1000*(1-progress));}
on(window,'scroll',()=>{dirty=true;wake();},{passive:true});
const track=document.querySelector('#chapter-track');on(document.querySelector('#chapter-back'),'click',()=>track.scrollBy({left:-track.clientWidth*.8,behavior:reduce.matches?'instant':'smooth'}));on(document.querySelector('#chapter-forward'),'click',()=>track.scrollBy({left:track.clientWidth*.8,behavior:reduce.matches?'instant':'smooth'}));
const light=document.createElement('div');light.className='cursor-light';light.setAttribute('aria-hidden','true');const cursor=document.createElement('div');cursor.className='cursor-civil-servant';cursor.setAttribute('aria-hidden','true');cursor.innerHTML='<b>✳</b><span>临时管理员</span>';document.body.append(light,cursor);
on(document,'pointermove',e=>{if(!fine.matches||reduce.matches)return;light.style.setProperty('--mouse-x',`${e.clientX}px`);light.style.setProperty('--mouse-y',`${e.clientY}px`);cursor.style.transform=`translate(${e.clientX+18}px,${e.clientY+20}px)`;cursor.style.opacity='1';cursor.querySelector('span').textContent=e.target.closest('a,button,input')?'正在接管 ↗':'临时管理员';},{passive:true});on(document.documentElement,'pointerleave',()=>{cursor.style.opacity='0';});
const magnet=document.querySelector('.primary-flight');on(magnet,'pointermove',e=>{if(!fine.matches||reduce.matches)return;const r=magnet.getBoundingClientRect();magnet.style.transform=`translate(${Math.max(-8,Math.min(8,(e.clientX-r.left-r.width/2)*.12))}px,${Math.max(-6,Math.min(6,(e.clientY-r.top-r.height/2)*.15))}px)`;});on(magnet,'pointerleave',()=>magnet.style.transform='');
document.querySelectorAll('.map-of-wrong-building>div:not(.map-rail)').forEach(el=>{on(el,'pointermove',e=>{if(!fine.matches||reduce.matches)return;const r=el.getBoundingClientRect();el.style.transform=`perspective(850px) rotateX(${-(e.clientY-r.top-r.height/2)/r.height*9}deg) rotateY(${(e.clientX-r.left-r.width/2)/r.width*9}deg)`;});on(el,'pointerleave',()=>el.style.transform='');});
const scrambleTimers=new Set();document.querySelectorAll('[data-scramble]').forEach(el=>{const original=el.textContent;on(el,'pointerenter',()=>{if(reduce.matches||el.dataset.busy)return;el.dataset.busy='true';let step=0;const run=()=>{step++;el.textContent=Array.from(original).map((c,i)=>i<step/10*original.length?c:'<>/?#_%'[Math.floor(Math.random()*7)]).join('');if(step<10){const t=setTimeout(()=>{scrambleTimers.delete(t);run();},40);scrambleTimers.add(t);}else{el.textContent=original;delete el.dataset.busy;}};run();});});
function freezeMedia(){document.querySelectorAll('.meme-media[data-animated]').forEach(media=>{const img=media.querySelector('img');if(!reduce.matches){media.querySelector('canvas')?.remove();delete media.dataset.frozen;return;}if(!img.complete||!img.naturalWidth||media.dataset.frozen)return;const still=document.createElement('canvas');still.width=img.naturalWidth;still.height=img.naturalHeight;still.setAttribute('role','img');still.setAttribute('aria-label',img.alt);still.getContext('2d')?.drawImage(img,0,0);media.append(still);media.dataset.frozen='true';});}
document.querySelectorAll('.meme-media[data-animated] img').forEach(img=>on(img,'load',freezeMedia));on(reduce,'change',()=>{state.reduced=reduce.matches;freezeMedia();dirty=true;wake();});freezeMedia();
on(window,'pagehide',e=>{cancelAnimationFrame(raf);raf=0;burstTimers.forEach((timer,chip)=>{clearTimeout(timer);chip.remove();});burstTimers.clear();state.airborne=0;count.textContent='0';scrambleTimers.forEach(clearTimeout);scrambleTimers.clear();if(!e.persisted){disposed=true;ro.disconnect();visibility.disconnect();reveal.disconnect();gl?.getExtension('WEBGL_lose_context')?.loseContext();life.abort();}});on(window,'pageshow',()=>{dirty=true;wake();});wake();

