import {testDeps} from '../runtime-location.mjs';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {setTimeout as sleep} from 'node:timers/promises';
const base=new URL(process.env.OCV_WORKSHOP_BASE_URL||`http://localhost:${process.env.OCV_WEB_PORT||8080}`);
if(!['http:','https:'].includes(base.protocol)||base.username||base.password)throw Error('Use an HTTP entrance without credentials');
const reportFile=join(testDeps,'runtime/reports/phase11-http.json');
const report={schema:'ocv.workshop/http-proof/1',startedAt:new Date().toISOString(),passed:false,checks:[],jobs:[]};
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
async function post(path,body,expected=[200,201],prefix='/api/workshop'){const r=await fetch(new URL(prefix+path,base),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const text=await r.text();assert.ok(Buffer.byteLength(text)<=6291456);const p=JSON.parse(text);assert.ok(expected.includes(r.status),`${path}: HTTP ${r.status} ${String(p.message||p.error||'').slice(0,160)}`);return p;}
async function check(name,fn){const start=Date.now();try{const evidence=await fn();report.checks.push({name,passed:true,elapsedMs:Date.now()-start,...evidence});}catch(e){report.checks.push({name,passed:false,error:e.message});throw e;}}
const world={gravityX:0,gravityY:-9.81,stepS:1/120,durationS:.2,sampleEvery:1,seed:1,bodies:[{id:'B1',kind:'ball',mode:'dynamic',x:0,y:20,angle:0,radius:.3,width:.6,height:.6,mass:1,friction:0,restitution:0,linearDamping:0,angularDamping:0,vx:0,vy:0,omega:0,layer:0,group:'',label:'reference',colour:'#3377dd'}],joints:[],motors:[],controls:[]};
const project={schema:'ocv.workshop-project/1',name:'HTTP reference '+randomUUID().slice(0,8),world,appearance:{depth:1,material:'alloy',background:'white',wireframe:false}};
const request={schema:'ocv.workshop-run/1',op:'simulate',world};
let saved;const own=new Map();
async function wait(job){const transitions=[],deadline=Date.now()+Math.min(240000,Math.max(30000,Number(process.env.OCV_WORKSHOP_HTTP_TIMEOUT_MS||180000)));while(Date.now()<deadline){const row=await post(`/jobs/${job.id}/read`,{ticket:job.ticket});if(transitions.at(-1)?.state!==row.state||transitions.at(-1)?.phase!==row.phase)transitions.push({state:row.state,phase:row.phase});if(['done','failed','cancelled'].includes(row.state))return{row,transitions};await sleep(800);}throw Error('Bounded HTTP task deadline reached');}
try{
 await check('Immutable PostgreSQL snapshots, conflicts, branch and append-only rollback',async()=>{saved=await post('/projects',{project});assert.equal(saved.storage,'PostgreSQL');assert.equal(saved.digest,hash(project));const first=await post(`/projects/${saved.id}/read`,{ticket:saved.ticket});assert.deepEqual(first.project,project);const changed={...project,world:{...world,gravityY:-5}};const second=await post('/projects',{id:saved.id,ticket:saved.ticket,expectedRevision:1,project:changed});assert.equal(second.revision,2);await post('/projects',{id:saved.id,ticket:saved.ticket,expectedRevision:1,project:changed},[409]);const old=await post(`/projects/${saved.id}/read`,{ticket:saved.ticket,revision:1});assert.equal(old.digest,saved.digest);const branch=await post(`/projects/${saved.id}/branch`,{ticket:saved.ticket,revision:1});assert.equal(branch.revision,1);assert.equal(branch.digest,saved.digest);assert.equal(branch.sourceSnapshot,saved.snapshot);const rolled=await post(`/projects/${saved.id}/rollback`,{ticket:saved.ticket,revision:1,expectedRevision:2});assert.equal(rolled.revision,3);assert.equal(rolled.sourceSnapshot,saved.snapshot);assert.equal(rolled.parentSnapshot,second.snapshot);const head=await post(`/projects/${saved.id}/read`,{ticket:saved.ticket});assert.equal(head.revision,3);assert.deepEqual(head.project,project);const history=await post(`/projects/${saved.id}/versions`,{ticket:saved.ticket});assert.deepEqual(history.versions.map(v=>v.revision),[3,2,1]);await post(`/projects/${saved.id}/read`,{ticket:'0'.repeat(64)},[404]);await post(`/projects/${saved.id}/read`,{ticket:saved.ticket},[404],'/api/signals');return{revisions:3,branchRevision:1,storedHashVerified:true,originalRetained:true,domainIsolation:true};});
 await check('Invalid private/account/model fields and unprivileged worker access rejected',async()=>{await post('/projects',{project:{...project,password:'do-not-store'}},[400]);await post('/jobs',{request:{...request,world:{...world,bodies:[{...world.bodies[0],mass:0}]}}},[400]);await post('/jobs',{request:{...request,world:{...world,unknown:1}}},[400]);await post('/internal',{action:'input',id:randomUUID(),worker:randomUUID()},[404]);return{privateAccountFieldsRejected:true};});
 for(const entry of [{name:'simulation',request},{name:'parameter scan',request:{...request,op:'scan',scan:{parameter:'gravityY',targetId:'',values:[-2,-9.81,-20],trials:1}}}])await check(`Actual C# → Rust → PostgreSQL → C# ${entry.name}`,async()=>{const job=await post('/jobs',{request:entry.request,project:saved.id,projectTicket:saved.ticket});own.set(job.id,job);assert.equal(job.dispatcherConfigured,true);const{row,transitions}=await wait(job);assert.equal(row.state,'done',row.error||JSON.stringify(row.result));assert.equal(row.storage,'PostgreSQL');assert.equal(row.result.engine.ok,true);assert.equal(row.result.analysis.ok,true);assert.equal(row.result.steps.length,3);assert.equal(row.result.steps[1].nativeExecution,true);assert.equal(row.result.steps[2].nativeResultReplaced,false);assert.equal(row.result.steps[2].resultReadFrom,'PostgreSQL');if(entry.request.op==='simulate')assert.ok(row.result.engine.frames.length>1);else{assert.equal(row.result.engine.scan.runs.length,3);assert.equal(row.result.engine.summary.runCount,3);assert.equal(row.result.engine.summary.failedRuns,0);}report.jobs.push({id:job.id,operation:entry.request.op,transitions,engine:row.result.engine.engine,version:row.result.engine.version});own.delete(job.id);return{operation:entry.request.op,nativeExecution:true,actualDatabaseReadback:true,manifestStored:!!row.result.manifest};});
 report.passed=true;
}finally{for(const job of own.values())await post(`/jobs/${job.id}/cancel`,{ticket:job.ticket}).catch(()=>{});report.finishedAt=new Date().toISOString();await mkdir(join(reportFile,'..'),{recursive:true});await writeFile(reportFile,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,file:reportFile}));}
