import {testDeps} from '../runtime-location.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {setTimeout as sleep} from 'node:timers/promises';
const base=process.env.OCV_WORKSHOP_BASE_URL||`http://localhost:${process.env.OCV_WEB_PORT||8080}`;
const file=join(testDeps,'runtime/reports/engineering-lifecycle.json');
const report={schema:'ocv.workshop/lifecycle-proof/2',startedAt:new Date().toISOString(),passed:false,checks:[]};let own;let sibling;
async function post(path,body,status=[200,201]){const r=await fetch(base+'/api/workshop'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const p=await r.json();assert.ok(status.includes(r.status),`HTTP ${r.status} ${p.message||p.error||''}`);return p;}
const world={gravityX:0,gravityY:-9.81,stepS:1/120,durationS:.2,sampleEvery:1,seed:1,bodies:[{id:'B1',kind:'ball',x:0,y:2,radius:.3,mass:1}],joints:[],motors:[],controls:[]};
try{own=await post('/jobs',{request:{schema:'ocv.workshop-run/1',op:'simulate',world}});sibling=await post('/jobs',{request:{schema:'ocv.workshop-run/1',op:'simulate',world}});assert.equal(sibling.state,'queued');const siblingCancelled=await post(`/jobs/${sibling.id}/cancel`,{ticket:sibling.ticket});assert.equal(siblingCancelled.cancelled,true);const transitions=[],deadline=Date.now()+120000;let row;while(Date.now()<deadline){row=await post(`/jobs/${own.id}/read`,{ticket:own.ticket});transitions.push({state:row.state,phase:row.phase});if(['starting','running'].includes(row.state))break;if(['done','failed'].includes(row.state))throw Error('Job completed before active cancellation was observed');await sleep(250);}assert.ok(['starting','running'].includes(row.state));const canceled=await post(`/jobs/${own.id}/cancel`,{ticket:own.ticket});assert.equal(canceled.cancelled,true);const terminal=await post(`/jobs/${own.id}/read`,{ticket:own.ticket});assert.equal(terminal.state,'cancelled');assert.equal(terminal.cancelled,true);await sleep(1500);const stable=await post(`/jobs/${own.id}/read`,{ticket:own.ticket});assert.equal(stable.state,'cancelled');report.checks.push({name:'Shared mechanical queue and active cancellation preserve terminal state',passed:true,id:own.id,siblingId:sibling.id,transitions,stableAfterMs:1500});report.passed=true;}finally{if(sibling)await post(`/jobs/${sibling.id}/cancel`,{ticket:sibling.ticket}).catch(()=>{});if(own)await post(`/jobs/${own.id}/cancel`,{ticket:own.ticket}).catch(()=>{});report.finishedAt=new Date().toISOString();await mkdir(join(file,'..'),{recursive:true});await writeFile(file,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,file}));}
