// A bounded GPU line/particle field. No forms, account data or remote assets.
import { desktopView } from '../q7/view.mjs';
const canvas=document.querySelector('#optical-field');
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const fine=matchMedia('(pointer: fine)');
const lifetime=new AbortController();
const on=(node,type,listener,options={})=>node?.addEventListener(type,listener,{...options,signal:lifetime.signal});
const mobile=innerWidth<700;
const pointCapacity=44000;
let desktop=desktopView(innerWidth,innerHeight);
const state={renderer:'css',frames:0,pointCount:mobile?5500:11000,lineSegments:0,activeGeometry:0,scroll:0,reduced:reduce.matches,suspended:false};
window.__ocvOptics=state;
const pointer={x:0,y:0,tx:0,ty:0};
let gl,program,lineBuffer,calmBuffer,pointBuffer,uniforms,raf=0,previous=0,time=0,morph=0,target=0,dirty=true,disposed=false,override=null,sectionIndex=0,energy=0;
const shaders={vertex:`precision highp float;
attribute vec3 a_seed;uniform vec2 u_size;uniform vec2 u_pointer;uniform float u_time;uniform float u_morph;uniform float u_points;uniform float u_energy;uniform float u_calm;uniform float u_spread;varying float v_alpha;varying float v_tint;
const float TAU=6.2831853;
mat2 spin(float a){return mat2(cos(a),-sin(a),sin(a),cos(a));}
void main(){vec3 q=a_seed;float a=q.x*TAU;float wave=sin(a*5.+q.y*17.+u_time*.55);float r=.62+q.y*1.67+.12*wave;vec3 p0=vec3(cos(a)*r,sin(a)*r*.82,sin(a*2.+q.y*13.)*.48);
if(q.z>1.5){float b=q.y*TAU+.6*sin(q.x*4.+q.y*16.+u_time*.45);float f=.55+q.x*2.9+.11*sin(q.x*16.+q.y*10.);p0=vec3(cos(b)*f,sin(b)*f*.84,sin(q.x*9.+q.y*13.+u_time*.26)*(.15+q.x*.6));}
float ph=acos(clamp(q.y*2.-1.,-.99,.99));vec3 p1=vec3(sin(ph)*cos(a),cos(ph),sin(ph)*sin(a))*1.55;
if(q.z>1.5){float ba=q.y*TAU+.8*sin(q.x*4.+q.y*7.+u_time*.24);float br=1.15+q.x*2.2;p1=vec3(cos(ba)*br,sin(ba)*br*.78,sin(q.x*9.+q.y*17.+u_time*.2)*.65);}
float w=q.x*TAU*1.6+q.y*TAU+u_time*.26;float cr=.24+q.y*.88;vec3 p2=vec3((q.x-.5)*5.4,cos(w)*cr,sin(w)*cr);
vec3 p3=vec3((q.x-.5)*5.,(q.y-.5)*3.7,sin(q.x*TAU*2.+q.y*TAU+u_time*.25)*.43);p3.xy=spin(-.4)*p3.xy;
vec3 p=mix(p0,p1,smoothstep(0.,1.,u_morph));p=mix(p,p2,smoothstep(1.,2.,u_morph));p=mix(p,p3,smoothstep(2.,3.,u_morph));
p.xy+=vec2(sin(q.y*TAU+u_time*.2),cos(q.x*TAU+u_time*.15))*.012;
p.xz=spin(.12*sin(u_time*.05)+u_pointer.x*.17)*p.xz;p.yz=spin(-.15+u_pointer.y*.13)*p.yz;p.xy=spin(u_time*.045+sin(u_time*.27)*.05)*p.xy;
float dist=length(p.xy-u_pointer*2.);p.xy+=normalize(p.xy-u_pointer*2.+.001)*exp(-dist*dist*2.)*.12;p*=1.+u_energy*.065;
float depth=4.8-p.z;vec2 projected=p.xy*2.4/depth;projected*=mix(1.,u_spread,1.-u_calm);projected.x*=u_size.y/u_size.x;gl_Position=vec4(projected,0.,1.);
float dpr=min(u_size.x/1000.,1.6);gl_PointSize=(1.2+pow(fract(q.y*913.),8.)*2.5)*max(.8,dpr)*(5./depth);
v_alpha=(.19+fract(q.y*321.)*.16)*(q.z>1.5?.68:1.)*(3.8/depth);v_tint=fract(q.y*91.+q.x*2.);if(u_points>.5)v_alpha=.32+pow(fract(q.y*119.),7.)*.6;v_alpha*=mix(1.,.34,u_calm);if(q.z>1.5)v_alpha*=1.-u_calm;
}`,fragment:`precision highp float;uniform float u_points;uniform float u_time;varying float v_alpha;varying float v_tint;
void main(){float alpha=v_alpha;if(u_points>.5){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;alpha*=exp(-d*d*3.);alpha*=.75+.25*sin(u_time*.6+v_tint*30.);}
vec3 ink=mix(vec3(.39,.57,.73),vec3(.49,.71,.81),v_tint);gl_FragColor=vec4(ink,alpha);}`};
function setup(){try{gl=canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power',preserveDrawingBuffer:false});if(!gl)throw Error('no context');const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){gl.deleteShader(s);throw Error('shader compile');}return s;};const vs=compile(gl.VERTEX_SHADER,shaders.vertex),fs=compile(gl.FRAGMENT_SHADER,shaders.fragment);program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('shader link');gl.useProgram(program);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.DEPTH_TEST);
const segments=mobile?170:280,rings=mobile?76:135,branches=mobile?24:46,branchSteps=mobile?90:150;const lines=[];for(let ring=0;ring<rings;ring++){for(let j=0;j<segments;j++)lines.push(j/segments,ring/rings,0,(j+1)/segments,ring/rings,0);}for(let branch=0;branch<branches;branch++){for(let j=0;j<branchSteps;j++)lines.push(j/branchSteps,branch/branches,2,(j+1)/branchSteps,branch/branches,2);}state.lineSegments=lines.length/6;lineBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(lines),gl.STATIC_DRAW);
const calm=[];for(let ring=0;ring<12;ring++)for(let j=0;j<240;j++)calm.push(j/240,ring/12,0,(j+1)/240,ring/12,0);calmBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,calmBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(calm),gl.STATIC_DRAW);
const points=new Float32Array(pointCapacity*3);let seed=9182;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<pointCapacity;i++){points[i*3]=random();points[i*3+1]=Math.pow(random(),.55);points[i*3+2]=1;}pointBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pointBuffer);gl.bufferData(gl.ARRAY_BUFFER,points,gl.STATIC_DRAW);uniforms={};for(const key of ['size','pointer','time','morph','points','energy','calm','spread'])uniforms[key]=gl.getUniformLocation(program,'u_'+key);uniforms.seed=gl.getAttribLocation(program,'a_seed');gl.enableVertexAttribArray(uniforms.seed);state.renderer='webgl';document.body.dataset.renderer='webgl';}catch{gl=null;const fallback=document.createElement('div');fallback.className='css-fallback';fallback.setAttribute('aria-hidden','true');document.body.prepend(fallback);state.renderer='css';document.body.dataset.renderer='css';}}
setup();
const sections=[...document.querySelectorAll('[data-optical-section]')];
const identity=document.querySelector('#main-identity');
function scrollState(){state.scroll=Math.round(scrollY);state.cover=scrollY<innerHeight*.72;document.body.dataset.cover=String(state.cover);document.querySelector('.optical-nav').inert=state.cover;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);document.documentElement.style.setProperty('--progress',String(scrollY/max));let index=0;for(let i=0;i<sections.length;i++){if(sections[i].getBoundingClientRect().top<innerHeight*.4)index=i;}if(index!==sectionIndex)sectionIndex=index;const current=sections[index];const base=Number(current.dataset.opticalSection);let progress=base;if(index===0)progress=Math.min(1,scrollY/(innerHeight*.85));if(index===2)progress=2+Math.max(0,Math.min(1,-current.getBoundingClientRect().top/current.offsetHeight));target=override??progress;state.activeGeometry=override??base;
const shift=Math.min(1,scrollY/(innerHeight*.8));if(!reduce.matches){identity.style.transform=`translateY(${-20-shift*80}px) scale(${1-shift*.18}) rotateX(${pointer.y*4}deg) rotateY(${pointer.x*7}deg)`;identity.style.opacity=String(Math.max(0,1-shift*1.8));}else{identity.style.transform='';identity.style.opacity='1';}
document.querySelectorAll('.geometry-controls button').forEach(button=>button.setAttribute('aria-pressed',String(Number(button.dataset.geometry)===state.activeGeometry)));}
function render(){if(!gl)return;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform2f(uniforms.size,canvas.width,canvas.height);gl.uniform2f(uniforms.pointer,pointer.x,pointer.y);gl.uniform1f(uniforms.time,time);gl.uniform1f(uniforms.morph,morph);gl.uniform1f(uniforms.energy,energy);gl.uniform1f(uniforms.spread,desktop.effectScale);const calmness=1.-Math.min(1,scrollY/(innerHeight*.72));gl.uniform1f(uniforms.calm,calmness);state.activePointCount=calmness>.99?1100:state.pointCount;state.activeLineSegments=calmness>.99?2880:state.lineSegments;gl.bindBuffer(gl.ARRAY_BUFFER,calmness>.99?calmBuffer:lineBuffer);gl.vertexAttribPointer(uniforms.seed,3,gl.FLOAT,false,0,0);gl.uniform1f(uniforms.points,0);gl.drawArrays(gl.LINES,0,state.activeLineSegments*2);gl.bindBuffer(gl.ARRAY_BUFFER,pointBuffer);gl.vertexAttribPointer(uniforms.seed,3,gl.FLOAT,false,0,0);gl.uniform1f(uniforms.points,1);gl.drawArrays(gl.POINTS,0,state.activePointCount);}
function frame(now){raf=0;if(disposed||document.hidden)return;const dt=now-previous;if(dt>=32){if(dirty){scrollState();dirty=false;}const duration=Math.min(dt/1000,.08);if(!reduce.matches){time+=duration;const damping=1-Math.exp(-duration*5);pointer.x+=(pointer.tx-pointer.x)*damping;pointer.y+=(pointer.ty-pointer.y)*damping;morph+=(target-morph)*damping;energy*=Math.exp(-duration*2.2);if(scrollY<innerHeight)identity.style.transform=`translateY(${-20-Math.min(1,scrollY/(innerHeight*.8))*80}px) scale(${1-Math.min(1,scrollY/(innerHeight*.8))*.18}) rotateX(${pointer.y*4}deg) rotateY(${pointer.x*7}deg)`;}else{morph=target;pointer.x=pointer.y=0;}render();state.frames++;state.morph=morph;state.pointer={x:pointer.x,y:pointer.y};previous=now;}if(!reduce.matches||dirty)raf=requestAnimationFrame(frame);}
function wake(){if(!raf&&!disposed&&!document.hidden){previous=performance.now()-40;raf=requestAnimationFrame(frame);}}
function resize(){desktop=desktopView(innerWidth,innerHeight);state.pointCount=Math.min(pointCapacity,desktop.pointCount);state.pointCapacity=pointCapacity;state.desktopScale=desktop.effectScale;const cap=desktop.bufferCap||(innerWidth<700?800:1600);const scale=Math.min(devicePixelRatio,1.4,cap/Math.max(innerWidth,innerHeight));canvas.width=Math.round(innerWidth*scale);canvas.height=Math.round(innerHeight*scale);dirty=true;wake();}
on(window,'resize',resize,{passive:true});on(window,'scroll',()=>{dirty=true;wake();},{passive:true});on(document,'visibilitychange',()=>{state.suspended=document.hidden;document.body.dataset.hidden=String(document.hidden);if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{dirty=true;wake();}});on(reduce,'change',()=>{state.reduced=reduce.matches;dirty=true;wake();});
const cursor=document.querySelector('#light-cursor');on(window,'pointermove',event=>{if(reduce.matches||!fine.matches)return;pointer.tx=event.clientX/innerWidth*2-1;pointer.ty=1-event.clientY/innerHeight*2;cursor.style.transform=`translate(${event.clientX-175}px,${event.clientY-175}px)`;},{passive:true});on(document,'pointerdown',event=>{if(!reduce.matches&&event.target.closest('.identity-scene,.systems-sticky'))energy=1;});
document.querySelectorAll('[data-geometry]').forEach(button=>on(button,'click',()=>{scrollState();override=Number(button.dataset.geometry);target=override;state.activeGeometry=override;energy=1;dirty=true;document.querySelectorAll('[data-geometry]').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.geometry)===override)));wake();}));
function automaticGeometry(){override=null;dirty=true;scrollState();wake();}
on(window,'wheel',automaticGeometry,{passive:true});on(window,'touchmove',automaticGeometry,{passive:true});
on(window,'keydown',e=>{if(['PageDown','PageUp','Home','End',' '].includes(e.key)&&!e.target.closest('input,textarea,select,button,[role=button]'))automaticGeometry();});
document.querySelectorAll('a[href^="#"],a[href^="/#"]').forEach(a=>on(a,'click',automaticGeometry));
const gallery=document.querySelector('#geometry-gallery');on(document.querySelector('#gallery-prev'),'click',()=>gallery.scrollBy({left:-gallery.clientWidth*.6,behavior:reduce.matches?'instant':'smooth'}));on(document.querySelector('#gallery-next'),'click',()=>gallery.scrollBy({left:gallery.clientWidth*.6,behavior:reduce.matches?'instant':'smooth'}));
document.querySelectorAll('.specimen').forEach(card=>{on(card,'pointermove',event=>{if(!fine.matches||reduce.matches)return;const r=card.getBoundingClientRect();card.style.transform=`perspective(1000px) rotateX(${-(event.clientY-r.top-r.height/2)/r.height*12}deg) rotateY(${(event.clientX-r.left-r.width/2)/r.width*12}deg)`;});on(card,'pointerleave',()=>card.style.transform='');});
on(canvas,'webglcontextlost',event=>{event.preventDefault();gl=null;state.renderer='css';document.body.dataset.renderer='css';if(!document.querySelector('.css-fallback')){const fallback=document.createElement('div');fallback.className='css-fallback';fallback.setAttribute('aria-hidden','true');document.body.prepend(fallback);}});
on(window,'pagehide',event=>{cancelAnimationFrame(raf);raf=0;if(!event.persisted){disposed=true;lifetime.abort();if(gl){gl.deleteBuffer(lineBuffer);gl.deleteBuffer(calmBuffer);gl.deleteBuffer(pointBuffer);gl.deleteProgram(program);gl.getExtension('WEBGL_lose_context')?.loseContext();}}});on(window,'pageshow',()=>{dirty=true;wake();});resize();





