<script>
import {onMount,onDestroy} from 'svelte';
import {interpolateFrame as present,frameAtTime as atTime} from './receipt2.mjs';
let current=null,previous=null,index=0,playing=false,speed=1,body='',compare=false,requestFrame=0,last=0,elapsed=0;
const px=x=>550+x*55,py=y=>470-y*55;
$: frames=current?.result?.frames||[];
$: frame=frames[index]||null;
$: displayed=present(frame,frames[index+1],elapsed+(frames[0]?.t||0),current?.enhanced&&playing);
$: ids=frames[0]?.bodies?.map(b=>b.id)||[];
$: path=body?frames.slice(0,index+1).map(f=>f.bodies.find(b=>b.id===body)).filter(Boolean).map((b,i)=>`${i?'L':'M'}${px(b.x)},${py(b.y)}`).join(' '):'';
$: old=compare&&displayed?atTime(previous?.result?.frames,displayed.t):null;
$: oldPath=compare&&body?(previous?.result?.frames||[]).map(f=>f.bodies.find(b=>b.id===body)).filter(Boolean).map((b,i)=>`${i?'L':'M'}${px(b.x)},${py(b.y)}`).join(' '):'';
$: measured=frame?.bodies?.find(b=>b.id===body);
$: moments=(current?.result?.keyMoments||[]).slice(0,128);
$: differences=(displayed?.bodies||[]).flatMap(b=>{const prior=old?.bodies?.find(p=>p.id===b.id);return prior?[{id:b.id,distance:Math.hypot(b.x-prior.x,b.y-prior.y),speed:Math.hypot(b.vx,b.vy)-Math.hypot(prior.vx,prior.vy),omega:b.omega-prior.omega}]:[]}).slice(0,12);
$: view=frameBounds(current,compare?previous:null);
const label=(record,id)=>record?.project?.world?.bodies?.find(p=>p.id===id)?.label||'零件';
const number=value=>Number.isFinite(value)?value.toFixed(3):'—';
function frameBounds(...records){let left=0,right=1100,top=0,bottom=600;for(const record of records){for(const f of record?.result?.frames||[])for(const b of f.bodies){const part=record?.project?.world?.bodies?.find(p=>p.id===b.id);const r=Math.max(part?.radius||0,(part?.width||0)/2,(part?.height||0)/2,.25)*55+25;left=Math.min(left,px(b.x)-r);right=Math.max(right,px(b.x)+r);top=Math.min(top,py(b.y)-r);bottom=Math.max(bottom,py(b.y)+r)}}return{x:left,y:top,width:right-left,height:bottom-top}}
function firstMovable(value){return value?.project?.world?.bodies?.find(b=>b.mode!=='fixed')?.id||value?.result?.frames?.[0]?.bodies?.[0]?.id||''}
function receive(event){const value=event.detail;if(!Array.isArray(value?.result?.frames)||!value.result.frames.length)return;previous=current;current=value;index=0;body=firstMovable(value);playing=false;elapsed=0}
function step(now){requestFrame=requestAnimationFrame(step);const dt=Math.min(.1,(now-last)/1000||0);last=now;if(!playing||document.hidden||!frames.length)return;elapsed+=dt*speed;const first=frames[0].t;while(index+1<frames.length&&frames[index+1].t-first<=elapsed)index++;if(index>=frames.length-1)playing=false}
function play(){if(index>=frames.length-1){index=0;elapsed=0}else elapsed=(frames[index]?.t||0)-(frames[0]?.t||0);playing=!playing}
function seek(event){index=Number(event.target.value);elapsed=(frames[index]?.t||0)-(frames[0]?.t||0);playing=false}
function jump(t){if(!frames.length)return;index=frames.reduce((best,f,i)=>Math.abs(f.t-t)<Math.abs(frames[best].t-t)?i:best,0);elapsed=frames[index].t-frames[0].t;playing=false}
function eventLabel(event,record){return event.kind==='challenge'?'挑战达成':event.kind==='control'?`控制触发 · ${{start:'启动',stop:'停止',reverse:'反转',signal:'信号'}[event.action]||'驱动'}`:`碰撞 · ${label(record,event.a)} / ${label(record,event.b)}`}
function exportFile(kind){if(!current)return;let text,name,mime;if(kind==='csv'){text='t_s,id,x_m,y_m,angle_rad,vx_m_s,vy_m_s,omega_rad_s,engine_version,step_s,sample_every,model_dimension\n'+frames.flatMap(f=>f.bodies.map(b=>[f.t,b.id,b.x,b.y,b.angle,b.vx,b.vy,b.omega,current.result.version||'',current.result.summary?.stepS??'',current.result.summary?.sampleEvery??'',current.result.model?.dimension??2].map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(','))).join('\n');name='mechanical-trajectory.csv';mime='text/csv'}else{text=JSON.stringify({schema:'ocv.workshop-replay/1',units:'SI',sampling:'recorded solver poses; actual result.summary.stepS/sampleEvery; display interpolation excluded',project:current.project,request:current.request,result:current.result},null,2);name='mechanical-replay.json';mime='application/json'}const url=URL.createObjectURL(new Blob([text],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
onMount(()=>{const history=window.__ocvWorkshopResults||[];previous=history[1]||null;current=history[0]||null;body=firstMovable(current);window.addEventListener('ocv:workshop-result',receive);requestFrame=requestAnimationFrame(step)});
onDestroy(()=>{if(typeof window!=='undefined'){window.removeEventListener('ocv:workshop-result',receive);cancelAnimationFrame(requestFrame)}});
</script>
<div class="replay" data-enhanced={current?.enhanced?"ready":"off"}><header><strong>回放与比较</strong><span>m · kg · s</span></header><div class="toolbar"><button on:click={play} disabled={!frames.length}>{playing?'Ⅱ':'▶'}</button><button on:click={()=>{playing=false;index=Math.min(index+1,frames.length-1);elapsed=frames[index]?.t||0}} disabled={!frames.length}>▹</button><select bind:value={speed} aria-label="回放速度"><option value={.25}>¼×</option><option value={.5}>½×</option><option value={1}>1×</option><option value={2}>2×</option></select><select bind:value={body} aria-label="轨迹零件">{#each ids as id}<option value={id}>{current?.project?.world?.bodies?.find(p=>p.id===id)?.label||'零件'}</option>{/each}</select><label><input type="checkbox" bind:checked={compare} disabled={!previous}/>对比上次运行</label><span>{(displayed?.t||0).toFixed(3)} s</span><button on:click={()=>exportFile('csv')} disabled={!frames.length}>轨迹表 ↓</button><button on:click={()=>exportFile('json')} disabled={!frames.length}>回放包 ↓</button></div><div class="stage"><svg viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} role="img" aria-label="记录的机械运动"><defs><pattern id="replay-grid" width="55" height="55" patternUnits="userSpaceOnUse"><path d="M55 0H0V55" fill="none" stroke="#d8e5f7" stroke-width="1"/></pattern></defs><rect x={view.x} y={view.y} width={view.width} height={view.height} fill="url(#replay-grid)"/><path d={`M${view.x} 470H${view.x+view.width}M550 ${view.y}V${view.y+view.height}`} stroke="#91b3e7" stroke-width="1"/>{#if oldPath}<path d={oldPath} fill="none" stroke="#c3884b" stroke-dasharray="4 4" stroke-width="1.5"/>{/if}{#if path}<path d={path} fill="none" stroke="#147aff" stroke-width="2"/>{/if}{#each old?.bodies||[] as b}<circle cx={px(b.x)} cy={py(b.y)} r="8" fill="none" stroke="#d29155" stroke-dasharray="3 3"/>{/each}{#each displayed?.bodies||[] as b}{@const part=current?.project?.world?.bodies?.find(p=>p.id===b.id)}<g transform={`translate(${px(b.x)},${py(b.y)}) rotate(${-b.angle*180/Math.PI})`}>{#if ['ball','wheel','gear','pulley'].includes(part?.kind)}<circle r={(part?.radius||.2)*55} fill={part?.colour||'#528fea'} fill-opacity=".65" stroke="#2860aa"/><path d={`M0 0H${(part?.radius||.2)*55}`} stroke="#16487c"/>{:else}<rect x={-(part?.width||.4)*27.5} y={-(part?.height||.2)*27.5} width={(part?.width||.4)*55} height={(part?.height||.2)*55} fill={part?.colour||'#528fea'} fill-opacity=".55" stroke="#2860aa"/>{/if}</g>{/each}</svg></div><div class="timeline"><input type="range" min="0" max={Math.max(0,frames.length-1)} value={index} on:input={seek} disabled={!frames.length} aria-label="记录帧"/><span>{index+1} / {frames.length}</span></div>
<div class="probe" aria-label="运动测量"><b>{label(current,body)}</b><span>x / m <strong>{number(measured?.x)}</strong></span><span>y / m <strong>{number(measured?.y)}</strong></span><span>速度 / m·s⁻¹ <strong>{number(measured?Math.hypot(measured.vx,measured.vy):NaN)}</strong></span><span>角速度 / rad·s⁻¹ <strong>{number(measured?.omega)}</strong></span></div>
{#if compare&&old}<div class="difference"><table aria-label="两次运行差值（相同时间线性插值）"><thead><tr><th>零件</th><th>位置差 / m</th><th>速度差 / m·s⁻¹</th><th>角速度差 / rad·s⁻¹</th></tr></thead><tbody>{#each differences as row}<tr><td>{label(current,row.id)}</td><td>{number(row.distance)}</td><td>{number(row.speed)}</td><td>{number(row.omega)}</td></tr>{/each}</tbody></table></div>{/if}
{#if compare&&!old}<div class="difference">无重合时间</div>{/if}
{#if moments.length}<details class="moments"><summary>关键事件 · {moments.length}</summary><div>{#each moments as event}<button on:click={()=>jump(event.t)} aria-label={`定位事件 ${event.t.toFixed(3)}秒`}>{event.t.toFixed(3)} s · {eventLabel(event,current)}</button>{/each}</div></details>{/if}
<footer><span>{current?.result?.summary?.steps||0} 步</span><span>{current?.result?.summary?.collisions||0} 次碰撞</span><span>{current?.result?.summary?.challengeComplete?'挑战完成':''}</span></footer></div>
<style>
.replay{border:1px solid #94b4ee;background:#f9fcff;color:#275698;font:12px system-ui}header{display:flex;justify-content:space-between;padding:10px;background:#e4edff;border-bottom:1px solid #9ab7e7}header span{font:10px monospace}.toolbar{display:flex;align-items:center;gap:7px;padding:8px;flex-wrap:wrap}button,select{border:1px solid #a1bcee;background:#eef5ff;color:#28589e;padding:5px 8px;font:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.toolbar>span{margin-left:auto;font:11px monospace}.stage{background:#f7fbff;border-block:1px solid #cee0f8}.stage svg{display:block;width:100%;height:285px}.timeline{display:flex;align-items:center;gap:12px;padding:8px}.timeline input{flex:1;accent-color:#397bdd}.timeline span{font:11px monospace}footer{display:flex;gap:16px;padding:8px;font:10px monospace;border-top:1px solid #d2e2f6}footer span:last-child{margin-left:auto}
.probe{display:flex;gap:14px;padding:10px;background:#edf5ff;border-top:1px solid #c5d9f5;flex-wrap:wrap;font-size:10px}.probe b{margin-right:auto}.probe strong{margin-left:5px;font:11px ui-monospace,monospace}.difference{padding:8px;border-top:1px solid #c5d9f5}.difference table{width:100%;border-collapse:collapse;font:10px ui-monospace,monospace}.difference th,.difference td{padding:5px;text-align:left;border-bottom:1px solid #d9e7fb}.difference small,.moments small{display:block;padding:5px;color:#6786ac;font-size:10px}.moments{padding:8px;border-top:1px solid #d9e7fb}.moments summary{cursor:pointer;font-size:11px}.moments>div{display:flex;flex-wrap:wrap;gap:5px;padding-top:8px}.moments button{font-size:10px;padding:4px 6px}
</style>
