import {searchFeatures,recommend} from '../main1/catalogue.mjs';
const life=new AbortController(),on=(target,type,callback,options={})=>target?.addEventListener(type,callback,{...options,signal:life.signal}),frame=document.querySelector('#workshop-ui');let timer;
const input=document.querySelector('#workshop-search'),results=document.querySelector('.workshop-search-results');
function search(){clearTimeout(timer);results.replaceChildren();results.hidden=false;for(const item of(input.value.trim()?searchFeatures(input.value):recommend()).slice(0,20)){const link=document.createElement('a');link.href=item.url;link.textContent=item.title;results.append(link)}}
function closeSearch(){clearTimeout(timer);results.hidden=true}
on(input,'input',()=>{clearTimeout(timer);if(!input.value.trim()){closeSearch();return}timer=setTimeout(search,120)});on(document.querySelector('[data-workshop-search]'),'click',search);on(input,'keydown',event=>{if(event.key==='Enter')search();if(event.key==='Escape')closeSearch()});on(input,'blur',event=>{if(!event.relatedTarget?.closest('.workshop-search'))closeSearch()});on(document,'pointerdown',event=>{if(!event.target.closest('.workshop-search'))closeSearch()});on(document,'keydown',event=>{if(event.key==='Escape')closeSearch();if((event.ctrlKey||event.metaKey)&&event.key==='k'){event.preventDefault();input.focus()}});
function measure(){frame?.contentWindow?.postMessage({type:'OCV_WORKSHOP_MEASURE'},location.origin)}on(frame,'load',measure);measure();
on(window,'message',event=>{if(event.origin!==location.origin||event.source!==frame?.contentWindow)return;const data=event.data;if(data?.type==='OCV_WORKSHOP_HEIGHT'){const height=Number(data.height);if(Number.isFinite(height)&&height>0)frame.style.height=`${Math.max(600,Math.min(200000,height+4))}px`}else if(data?.type==='OCV_WORKSHOP_PROJECT'){window.__ocvWorkshopProject=data.project;window.dispatchEvent(new CustomEvent('ocv:workshop-project',{detail:data.project}))}else if(data?.type==='OCV_WORKSHOP_RESULT'){const detail={result:data.result,project:data.project,request:data.request,enhanced:!!data.enhanced};window.__ocvWorkshopResults=[detail,...(window.__ocvWorkshopResults||[])].slice(0,2);window.dispatchEvent(new CustomEvent('ocv:workshop-result',{detail}))}else if(data?.type==='OCV_WORKSHOP_NOTICE'){const target=document.querySelector('.workshop-notice');target.hidden=false;target.textContent=String(data.message).slice(0,240)}});
const help=document.querySelector('#workshop-shortcuts'),helpToggle=document.querySelector('[data-workshop-help-toggle]');
function showHelp(open){help.hidden=!open;helpToggle?.setAttribute('aria-expanded',String(open))}
on(helpToggle,'click',()=>showHelp(help.hidden));
on(document.querySelector('[data-workshop-help-close]'),'click',()=>showHelp(false));
on(window,'pagehide',event=>{clearTimeout(timer);if(!event.persisted)life.abort()});
