import {spawn,spawnSync} from 'node:child_process';import http from 'node:http';import path from 'node:path';import {fileURLToPath} from 'node:url';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const packageCli=process.env.npm_execpath;if(!packageCli)throw Error('Start with pnpm dev so the active package manager is available.');
const ports={web:Number(process.env.OCV_WEB_PORT||8080),portal:Number(process.env.OCV_PORTAL_PORT||4321),next:Number(process.env.OCV_NEXT_PORT||3200),gateway:Number(process.env.OCV_GATEWAY_PORT||3000)};
const children=[];let stopped=false;
const server=http.createServer((req,res)=>{const url=req.url||'/';const service=/^\/(borrowed|studio|_next|next-api)(\/|\?|$)/.test(url)?'next':/^\/(api|health)\//.test(url)?'gateway':'portal';const routed=url;const timeout=/^\/api\/q8\/events\//.test(url)?70000:/^\/(api|health|next-api)\//.test(url)?10000:60000;const upstream=http.request({hostname:'127.0.0.1',port:ports[service],method:req.method,path:routed,headers:req.headers,timeout},reply=>{res.writeHead(reply.statusCode||502,reply.headers);reply.pipe(res);});upstream.on('error',()=>{if(!res.headersSent)res.writeHead(503,{'Content-Type':'text/plain; charset=utf-8'});res.end('窗口还没开；稍后重试。');});upstream.on('timeout',()=>upstream.destroy());req.pipe(upstream);res.on('close',()=>upstream.destroy());});
const sockets=new Set();
server.on('upgrade',(req,client,head)=>{const service=req.url?.startsWith('/_next/')?'next':req.url?.startsWith('/api/')?'gateway':'portal';const upstream=http.request({hostname:'127.0.0.1',port:ports[service],path:req.url,headers:req.headers,timeout:10000});upstream.on('timeout',()=>upstream.destroy());upstream.on('response',res=>{res.resume();client.destroy();});upstream.on('upgrade',(res,socket,extra)=>{client.write('HTTP/1.1 101 Switching Protocols\r\n'+Object.entries(res.headers).map(([k,v])=>k+': '+v).join('\r\n')+'\r\n\r\n');socket.write(head);client.write(extra);sockets.add(client);sockets.add(socket);client.pipe(socket).pipe(client);client.on('close',()=>{socket.destroy();sockets.delete(client);sockets.delete(socket);});socket.on('error',()=>client.destroy());});upstream.on('error',()=>client.destroy());upstream.end();});
function stop(code=0){if(stopped)return;stopped=true;server.close();for(const s of sockets)s.destroy();for(const child of children)if(child.exitCode===null&&child.pid){if(process.platform==='win32')spawnSync('taskkill',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});else{try{process.kill(-child.pid,'SIGTERM');}catch{child.kill();}}}process.exitCode=code;}
async function command(name,args,extra={},wait=false){const child=spawn(process.execPath,[packageCli,...args],{cwd:project,env:{...process.env,...extra},stdio:'inherit',windowsHide:true,detached:process.platform!=='win32'});children.push(child);child.once('error',()=>stop(1));if(wait)await new Promise((resolve,reject)=>child.once('exit',code=>code===0?resolve():reject(Error(name+' build failed'))));else child.once('exit',()=>{if(!stopped)stop(1);});}
// Builds are sequential and use each application's own build system.
await command('Angular',['--filter','@omnicivitas/ng','build'],{NG_BUILD_MAX_WORKERS:'1'},true);
await command('Gateway',['--filter','@omnicivitas/gateway','build'],{},true);
await import('./copy-angular.mjs');
await command('Legacy assets',['exec','node','scripts/phase8-build.mjs'],{},true);
await command('Research assets',['exec','node','scripts/prepare-research.mjs'],{},true);
const gateway=spawn(process.execPath,['services/gateway/dist/main.js'],{cwd:project,env:{...process.env,HOST:'127.0.0.1',PORT:String(ports.gateway),DATABASE_URL:process.env.DATABASE_URL||'',REDIS_URL:process.env.REDIS_URL||'',OCV_REQUIRE_INFRASTRUCTURE:process.env.DATABASE_URL?'true':'false',NODE_OPTIONS:'--max-old-space-size=384'},stdio:'inherit',windowsHide:true,detached:process.platform!=='win32'});children.push(gateway);gateway.on('error',()=>stop(1));gateway.on('exit',()=>{if(!stopped)stop(1);});
await command('Astro',['--filter','@omnicivitas/portal','exec','astro','dev','--host','127.0.0.1','--port',String(ports.portal)],{NODE_OPTIONS:'--max-old-space-size=1536'});
await command('Next',['--filter','@omnicivitas/web2','exec','next','dev','--webpack','--hostname','127.0.0.1','--port',String(ports.next)],{OCV_GATEWAY_URL:process.env.OCV_GATEWAY_URL||'http://127.0.0.1:'+ports.gateway,NODE_OPTIONS:'--max-old-space-size=1536'});
server.on('error',()=>stop(1));server.listen(ports.web,'127.0.0.1',()=>console.log('OmniCivitas dev: http://127.0.0.1:'+ports.web+' ; without DATABASE_URL the core save is a bounded memory demo.'));
process.on('SIGINT',()=>stop());process.on('SIGTERM',()=>stop());
