import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import { composeCall,dockerCall } from './docker-child.mjs';
import {verificationConfig} from './verification-config.mjs';
const {baseUrl:base,grafanaUrl,reportRoot}=verificationConfig();
const group=process.argv[2]||'core';const checks=[];const observations={};
await fs.mkdir(reportRoot,{recursive:true});
const pg=sql=>composeCall(['exec','-T','postgres','sh','-c','PGPASSWORD="$POSTGRES_PASSWORD" psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -At -c "$1"','ocv-query',sql]).stdout.trim();
const mysqlQuery=sql=>composeCall(['exec','-T','mysql','sh','-c','MYSQL_PWD="$MYSQL_PASSWORD" mysql --user="$MYSQL_USER" --database="$MYSQL_DATABASE" -Nse "$1"','ocv-query',sql]).stdout.trim();
let mongoDatabase;
const mongoQuery=code=>{if(!mongoDatabase){const config=JSON.parse(composeCall(['config','--format','json']).stdout),url=new URL(config.services.gateway.environment.MONGO_URL);mongoDatabase=decodeURIComponent(url.pathname.slice(1));assert.ok(mongoDatabase,'Mongo database must be declared by the actual gateway configuration');}return composeCall(['exec','-T','mongo','mongosh',mongoDatabase,'--quiet','--eval',code]);};
const req=async(route,body)=>{const r=await fetch(base+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});return {status:r.status,body:await r.json()};};
function check(name,condition){assert.ok(condition,name);checks.push(name);console.log('PASS '+name);}
let saved;
try{
 const ping=await req('/api/ping.php');check('Core Nest ping remains usable',ping.status===200&&ping.body.canContinue);
 for(const account of ['/api/login','/api/register','/api/login.do','/api/register.php'])check('Account absent: '+account,(await req(account)).status===404);
 const bad=await req('/api/civilization-enterprise.do',{label:'锅',password:'never-send-a-real-secret'});check('Zod refuses identity/password shaped fields',bad.status===400);
 if(group==='core'||group==='legacy'||group==='everything'){
  const created=await req('/api/civilization-enterprise.do',{label:'锅Phase2-'+Date.now(),ornament:{unvalidatedPotato:43}});saved=created.body;observations.initialRecord=saved;check('Prisma identity and independent TypeORM stock are real',created.status===201&&saved.canContinue&&saved.ids.autoInteger>0&&saved.ids.nanoId!==saved.ids.cacheId&&saved.ids.cryptoUuid!==saved.ids.packageUuid);
  const root=saved.rootTraceId;const rows=pg(`SELECT p.product_name,s.supplier_id,s.delivery_count FROM ocv_prisma.identity_map p JOIN ocv_typeorm.warehouse_stock s ON s.root_id=p.root_id WHERE p.root_id='${root}'`);observations.postgresJoin=rows;check('Exact PostgreSQL join exercises both ORM-owned schemas',rows.endsWith('|43|1')&&rows.startsWith('锅Phase2-'));
  const migrations=pg("SELECT migration_name FROM public._prisma_migrations WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL ORDER BY migration_name;SELECT name FROM ocv_typeorm.warehouse_migrations");check('Independent real Prisma and TypeORM migrations applied',migrations.includes('202610020001_pebble')&&migrations.includes('20261002080000_receipt_bits')&&migrations.includes('WarehouseMigration1760000000001'));observations.migrations=migrations;
  const cached=composeCall(['exec','-T','redis','redis-cli','GET','library:map:'+saved.ids.cacheId]).stdout.trim();observations.mappingCache=JSON.parse(cached);check('Mapping cache uses another ID, not its UUID',JSON.parse(cached).uuid===root);
  const empty=pg('SELECT (SELECT count(*) FROM ocv_unused.users)+(SELECT count(*) FROM ocv_unused.user_passwords)+(SELECT count(*) FROM ocv_unused.login_sessions)');check('Elaborate account tables remain empty',empty==='0');
  const potato=await req('/api/unrelated-potato.asmx');check('Redis has a harmless sole-source counter',potato.body.canContinue&&potato.body.value>0);
  const sse=await fetch(base+'/api/receipt-events.cgi',{signal:AbortSignal.timeout(2500)});const text=await sse.text();check('SSE sends three real messages and ends',sse.ok&&(text.match(/data:/g)||[]).length===3);
  const ws=await new Promise((resolve,reject)=>{const s=new WebSocket(base.replace('http','ws')+'/api/enterprise-ws.cgi');const timer=setTimeout(()=>{s.close();reject(Error('WebSocket timeout'));},2500);s.onmessage=e=>{clearTimeout(timer);s.close();resolve(JSON.parse(e.data));};s.onerror=reject;});check('Nginx upgraded real WebSocket',ws.canContinue===true);
  if(group==='core'){const absent=await req('/api/stamp-everywhere.php',{label:'饭'});observations.optionalFallback=absent.body;check('Missing optional chain has explicit finite fallback',absent.body.canContinue===false&&typeof absent.body.successReason==='string');for(const kind of ['graphql','ruby','go','analysis','minio','mysql'])check('Optional '+kind+' absent without blocking core',(await req('/api/department.do/'+kind)).body.canContinue===false);check('Optional reconciliation absent without blocking core',(await req('/api/reconcile.do')).body.canContinue===false);check('Core homepage survives optional failure',(await fetch(base)).ok);}
 }
 if(group==='legacy'||group==='everything'){
  const chain=await req('/api/stamp-everywhere.php',{label:'饭',ornament:{whatever:'该字段不做语义校验'}});observations.chain=chain.body;check('Six HTTP hops terminate without recursion',chain.body.canContinue&&chain.body.hops.length===6&&chain.body.next.next.next.next.next.hopLimitReached===true);
  check('Every hop preserves root trace and changes display ID',chain.body.hops.every(h=>h.rootTraceId===chain.body.rootTraceId)&&new Set(chain.body.hops.map(h=>h.displayRequestId)).size===6);
  check('ISO/seconds/milliseconds/Shanghai literal really adapt to one instant',chain.body.adaptedTimes.every(t=>t.canonicalIso===chain.body.canonicalIso));
  check('Direct Nest to Spring REST', (await req('/api/spring-direct.cgi',{label:'锅'})).body.canContinue);
  const validator=composeCall(['exec','-T','gateway','node','-e',`fetch('http://spring:8081/api/approved.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:'',rootTraceId:'${chain.body.rootTraceId}',isoTime:'2026-10-01T19:14:00.000Z'}),signal:AbortSignal.timeout(2000)}).then(r=>console.log(r.status))`]).stdout.trim();check('Hibernate Validator actually refuses an empty field after Zod gateway',validator==='400');
  const grpc=await req('/api/grpc.asmx',{label:'章'});observations.grpc=grpc.body;check('Spring to Python uses real gRPC',grpc.body.canContinue&&grpc.body.next.protocol==='gRPC'&&grpc.body.next.sqliteFile==='redis.sqlite'&&grpc.body.next.unixSeconds===1790882040);
  for(const kind of ['hono','graphql','ruby','go','analysis']){const x=await req('/api/department.do/'+kind);check('Active '+kind+' service really responds',x.body.canContinue);if(kind==='analysis')check('DuckDB consumes formal CSV/JSON/YAML',x.body.total===6&&x.body.csvRows===3&&x.body.sources.length===4&&x.body.meetsPolicy===true&&x.body.displayName===x.body.json.product_name&&x.body.municipality===x.body.yaml.warehouse);if(kind==='ruby')check('Sinatra serializes JSON inside JSON',JSON.parse(x.body.jsonInsideJson).service==='Ruby Sinatra');}
  const xml=await fetch(base+'/api/PotatoTaxService.asmx');check('ASP.NET returns silly SOAP XML',xml.ok&&(await xml.text()).includes('GetPotatoTaxResponse'));
  const disguised=await req('/api/foo.php');check('PHP-named public route actually reaches Hono, not PHP',disguised.body.service==='Hono'&&disguised.body.errorMessage);
  const fragment=await fetch(base+'/api/fragment.cgi');check('Hono returns real HTML fragment',fragment.ok&&(await fragment.text()).includes('data-fragment="hono"'));
  const spread=await req('/api/spread-object.do/'+saved.rootTraceId,{});check('Same PostgreSQL UUID is actually sent through MySQL and SQLite',spread.body.canContinue);
  const jpa=pg(`SELECT product_name,delivery_count FROM ocv_jpa.warehouse_stock WHERE root_trace_id='${chain.body.rootTraceId}' ORDER BY id DESC LIMIT 1`);check('Hibernate JPA really stores the chain receipt',jpa==='饭|1');observations.jpaRow=jpa;
  const sqlite=composeCall(['exec','-T','fastapi','python','-c',`import sqlite3,json;print(json.dumps({n:sqlite3.connect('/ocv-data/'+n).execute('SELECT misplaced_time FROM warehouse_stock WHERE root_id=? ORDER BY rowid DESC LIMIT 1',('${chain.body.rootTraceId}',)).fetchone()[0] for n in ['postgres.sqlite','mysql.sqlite','redis.sqlite']}))`]).stdout;const actualSqlite=JSON.parse(sqlite);check('Three actual SQLAlchemy SQLite files store different timestamp formats',actualSqlite['mysql.sqlite']==='1790882040'&&actualSqlite['redis.sqlite']==='2026/10/02 03:14'&&actualSqlite['postgres.sqlite'].includes('2026-10-01T19:14'));observations.sqlite=actualSqlite;const unconstrained=composeCall(['exec','-T','fastapi','python','-c',"import sqlite3;print(sum(x[3] for x in sqlite3.connect('/ocv-data/postgres.sqlite').execute('PRAGMA table_info(warehouse_stock)')))"]).stdout.trim();check('SQLite deliberately has no field NOT NULL constraints',unconstrained==='0');
  const ms=mysqlQuery(`SELECT misplaced_unix_ms FROM ocv_eloquent_school_student WHERE root_id='${chain.body.rootTraceId}'`);check('Eloquent really persists Unix milliseconds in MySQL',ms==='1790882040000');observations.mysqlMilliseconds=ms;
  const mysql=await req('/api/department.do/mysql?q='+encodeURIComponent(observations.postgresJoin.split('|')[0]));check('MySQL LIKE executes Eloquent query',mysql.body.canContinue&&mysql.body.rows.some(r=>r.root_id===saved.rootTraceId));
 }
 if(group==='databases'||group==='everything'){const minio=await req('/api/department.do/minio');check('MinIO tiny object put/get exact bytes',minio.body.canContinue&&minio.body.contents==='锅已经过了十四个窗口，饭还是凉的。\n');}
 if(group==='messaging'||group==='everything'){
  const event=await req('/api/civilization-enterprise.do',{label:'异步锅-'+Date.now(),ornament:{potato:43}});check('Nest RabbitMQ confirm is real',event.body.rabbitQueued===true);saved=event.body;
  let replica;for(let i=0;i<24;i++){replica=await req('/api/split-object.do/'+saved.rootTraceId);if(replica.body.partial?.[1]?.record?.source==='Kafka payload')break;await new Promise(r=>setTimeout(r,500));}
  const record=replica.body.partial?.[1]?.record;observations.kafkaMongoRecord=record;check('Rabbit body to Kafka payload to Nest Mongoose Mongo',record?.source==='Kafka payload'&&record.root_id===saved.rootTraceId&&record.error==='成功');check('Replica temporary state really in Redis',JSON.parse(replica.body.partial[1].redis).rootTraceId===saved.rootTraceId);
  if(group==='everything'){await req('/api/spread-object.do/'+saved.rootTraceId,{});const reassembled=await req('/api/split-object.do/'+saved.rootTraceId);observations.splitObject=reassembled.body;check('Five storage fragments really reassemble',reassembled.body.canContinue&&reassembled.body.uuid===saved.rootTraceId&&reassembled.body.name===record.product_name&&reassembled.body.extra.pot==='仍然在'&&reassembled.body.sqliteTimestamp==='2026/10/02 03:14');check('Spring Redis Pub/Sub reaches separate Nest Mongo log consumer',reassembled.body.partial[1].logs.some(l=>l.data?.service==='Spring'));
   check('Original unvalidated ornament really reaches Mongo',reassembled.body.extra.ornament?.potato===43);
   const identical=record.receiptLog;check('Gateway JSON log is mirrored verbatim into Mongo',typeof identical==='string'&&JSON.parse(identical).rootTraceId===saved.rootTraceId);const file=composeCall(['exec','-T','gateway','node','-e',"console.log(require('node:fs').readFileSync('/ocv-data/gateway.log','utf8'))"]).stdout;const stdout=composeCall(['logs','--tail','300','gateway']).stdout;check('Same JSON receipt log exists in stdout and actual bounded file',file.includes(identical)&&stdout.includes(identical));observations.mirroredLog=identical;
   let search;for(let i=0;i<10;i++){search=await req('/api/search-index.php?q=异步锅');if(search.body.result?.hits?.hits?.some(h=>h._id===saved.rootTraceId))break;await new Promise(r=>setTimeout(r,300));}check('Real Elasticsearch full text finds fourth copy',search.body.canContinue&&search.body.result.hits.hits.some(h=>h._id===saved.rootTraceId&&h._source.log===identical));
   const authoritative=pg(`SELECT product_name FROM ocv_prisma.identity_map WHERE root_id='${saved.rootTraceId}'`);const redisCopy=JSON.parse(composeCall(['exec','-T','redis','redis-cli','GET','school:replica:'+saved.ids.cacheId]).stdout.trim());const indexedCopy=search.body.result.hits.hits.find(h=>h._id===saved.rootTraceId)._source;check('Four actual copies have identical label and internal UUID',authoritative===record.product_name&&redisCopy.label===authoritative&&indexedCopy.label===authoritative&&redisCopy.rootTraceId===saved.rootTraceId&&indexedCopy.rootTraceId===saved.rootTraceId);observations.fourCopies={postgres:authoritative,mongo:record.product_name,redis:redisCopy,elasticsearch:indexedCopy};
   mongoQuery(`db.school_student_annex.updateOne({root_id:"${saved.rootTraceId}"},{$set:{product_name:"故意弄错"}})`);composeCall(['exec','-T','redis','redis-cli','SET','school:replica:'+saved.ids.cacheId,'{"label":"故意弄错"}']);
   composeCall(['exec','-T','gateway','node','-e',`fetch('http://elasticsearch:9200/warehouse-stock/_update/${saved.rootTraceId}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({doc:{label:'故意弄错'}})}).then(async r=>{if(!r.ok)throw Error(await r.text())})`]);
   const reconcile=await req('/api/reconcile.do');check('Reconciliation executes actual small-field comparison',reconcile.body.canContinue&&reconcile.body.count>0);const repaired=await req('/api/split-object.do/'+saved.rootTraceId);check('Reconciliation repairs deliberately corrupted Mongo replica',repaired.body.partial[1].record.product_name.startsWith('异步锅-'));check('Reconciliation preserves the original ornament and receipt log',repaired.body.extra.ornament?.potato===43&&repaired.body.partial[1].record.receiptLog===identical);const cacheFixed=composeCall(['exec','-T','redis','redis-cli','GET','school:replica:'+saved.ids.cacheId]).stdout.trim();check('Reconciliation repairs deliberately corrupted Redis',JSON.parse(cacheFixed).label===repaired.body.name);await new Promise(r=>setTimeout(r,1200));const indexFixed=await req('/api/search-index.php?q=异步锅');check('Reconciliation repairs deliberately corrupted Elasticsearch',indexFixed.body.result.hits.hits.some(h=>h._id===saved.rootTraceId&&h._source.label===repaired.body.name&&h._source.log===identical));
   mongoQuery(`db.school_student_annex.updateOne({root_id:"${saved.rootTraceId}"},{$set:{product_name:"定时任务请修锅"}})`);let automatic=false;for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,750));const r=await req('/api/split-object.do/'+saved.rootTraceId);if(r.body.partial[1]?.record?.product_name===repaired.body.name){automatic=true;break;}}check('Scheduled job repairs Mongo without manual invocation',automatic);observations.scheduledRepair=true;
  }
 }
 if(group==='monitoring'||group==='everything'){
  await req('/api/stamp-everywhere.php',{label:'OTel 饭'});await new Promise(r=>setTimeout(r,6000));const logs=composeCall(['logs','--tail','500','otel']).stdout;check('Collector receives real OpenTelemetry multi-span export',logs.includes('窗口14')&&logs.includes('Trace ID'));
  const query=composeCall(['exec','-T','prometheus','wget','-qO-','http://localhost:9090/api/v1/query?query=ocv_pebble_weight']).stdout;const data=JSON.parse(query);check('Prometheus scrapes real trivial gauge',data.status==='success'&&data.data.result.some(r=>Number(r.value[1])===1));
  const board=await fetch(grafanaUrl+'/api/dashboards/uid/ocv-cold-rice');const dashboard=await board.json();check('Grafana provisions 48 actual panels',board.ok&&dashboard.dashboard.panels.length===48);
 }
 const ids=composeCall(['ps','-q']).stdout.trim().split(/\s+/).filter(Boolean);const containers=JSON.parse(dockerCall(['inspect',...ids]).stdout);for(const c of containers)check('Actual limits and health: '+c.Config.Labels['com.docker.compose.service'],c.HostConfig.Memory>0&&c.HostConfig.MemorySwap===c.HostConfig.Memory&&c.HostConfig.NanoCpus>0&&c.HostConfig.PidsLimit>0&&c.HostConfig.LogConfig.Config['max-size']==='5m'&&c.State.Health.Status==='healthy');
 await fs.writeFile(path.join(reportRoot,(process.env.OCV_VERIFY_REPORT_PREFIX||'phase2-')+group+'.json'),JSON.stringify({status:'passed',group,updatedAt:new Date().toISOString(),checks,saved,observations,containers:containers.map(c=>({service:c.Config.Labels['com.docker.compose.service'],memory:c.HostConfig.Memory,health:c.State.Health.Status}))},null,2));
}catch(e){await fs.writeFile(path.join(reportRoot,(process.env.OCV_VERIFY_REPORT_PREFIX||'phase2-')+group+'.json'),JSON.stringify({status:'failed',group,checks,error:e.message,saved,observations},null,2));throw e;}
