import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {resolve,join,dirname,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),require=createRequire(join(root,'config/apps/ng/package.json'));
const {transpileModule,ModuleKind,ScriptTarget}=require('typescript'),temporaryRoot=resolve(process.env.OCV_DEPS_ROOT?join(process.env.OCV_DEPS_ROOT,'tmp'):tmpdir());
await mkdir(temporaryRoot,{recursive:true});const scratch=await mkdtemp(join(temporaryRoot,'signals-phase14-ui-'));
try{
 for(const module of ['clock2','stock','packet','transport','plot','replay2']){
  const source=await readFile(join(root,'config/apps/ng/config2',module+'.ts'),'utf8');const output=transpileModule(source,{compilerOptions:{module:ModuleKind.ES2022,target:ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,(_,name)=>`from './${name}.mjs'`);
  await writeFile(join(scratch,module+'.mjs'),output);
 }
 const clock=await import(pathToFileURL(join(scratch,'clock2.mjs'))),stock=await import(pathToFileURL(join(scratch,'stock.mjs'))),transport=await import(pathToFileURL(join(scratch,'transport.mjs'))),plot=await import(pathToFileURL(join(scratch,'plot.mjs'))),replay=await import(pathToFileURL(join(scratch,'replay2.mjs')));
 for(const name of ['Shift register','JK counter','Parity latch']){const template=clock.validateDigital(clock.digitalTemplate(name)),layout=clock.digitalLayout(template);assert.ok(layout.connections.length>template.gates.length);assert.equal(new Set(layout.nodes.map(node=>node.id)).size,layout.nodes.length);assert.ok(layout.height>=250)}
 const bad=clock.digitalTemplate();bad.gates[0].inputs=['missing'];assert.throws(()=>clock.validateDigital(bad),/unknown wire/);
 const project=stock.defaultProject();project.communication={...project.communication,crc:'CRC-16',modulation:'QPSK',lineCode:'Manchester',timingOffsetSymbols:.125,frequencyOffsetHz:10,sweep:{axis:'ebN0Db',values:[0,2],secondaryAxis:'timingOffsetSymbols',secondaryValues:[-.25,0,.25]}};project.digital=clock.digitalTemplate('JK counter');assert.deepEqual(stock.parseProject(JSON.stringify(project)).communication,project.communication);assert.deepEqual(stock.parseProject(JSON.stringify(project)).digital,project.digital);const legacy={...project};delete legacy.digital;assert.equal(stock.parseProject(JSON.stringify(legacy)).digital.gates[0].type,'DFF');
 const digital={ok:true,engine:'fixture/ideal',version:'fixture',summary:{tickS:.1},wires:['clock','d'],trace:[{tick:0,t:0,values:{clock:false,d:true}},{tick:1,t:.1,values:{clock:true,d:false}}],events:[{tick:1,t:.1,wire:'clock',from:false,to:true,cause:'clock'}]};assert.equal(replay.replayResult('digital',digital),digital);const digitalCSV=transport.digitalCSV(digital);assert.ok(digitalCSV.includes('unit=boolean'));assert.ok(digitalCSV.includes('1,0.1,1,0'));assert.throws(()=>replay.replayResult('digital',{...digital,trace:[{tick:0,t:0,values:{clock:'1',d:true}}]}));
 const rate=8000,count=64,waveform=Array.from({length:count},(_,index)=>({t:index/rate,tx:Math.cos(2*Math.PI*8*index/count),txQ:Math.sin(2*Math.PI*8*index/count),rx:Math.cos(2*Math.PI*8*index/count),q:Math.sin(2*Math.PI*8*index/count)})),radio={ok:true,engine:'fixture/complex',version:'fixture',summary:{sampleRateHz:rate,seed:42,modulation:'QPSK',lineCode:'NRZ'},ber:0,interval:{lower:0,upper:.1},waveform,constellation:[],eye:[]};assert.equal(replay.replayResult('communications',radio),radio);assert.throws(()=>replay.replayResult('communications',{...radio,waveform:[{...waveform[0],q:Infinity}]}));const csv=transport.radioCSV(radio);assert.ok(csv.includes('raw_samples=true'));assert.ok(csv.includes('time_s,tx_I,tx_Q,rx_I,rx_Q'));assert.equal(csv.split('\r\n').length,count+2);assert.ok(plot.radioPlot(radio,true).traces.every(trace=>trace.name.endsWith('Q')));const spectrum=plot.spectrum(radio);assert.ok(spectrum.xmin<0);assert.equal(spectrum.points,count);assert.ok(spectrum.measurementLabel.includes('not PSD'));
 assert.throws(()=>replay.replayResult('communications',{...radio,lineWaveform:{t:0,value:1}}),/line-code/);assert.throws(()=>replay.replayResult('communications',{...radio,lineWaveform:[{t:0,value:Infinity}]}),/line-code/);assert.throws(()=>replay.replayResult('communications',{...radio,lineWaveform:Array.from({length:2049},(_,index)=>({t:index,value:1}))}),/line-code/);assert.throws(()=>replay.replayResult('communications',{...radio,idealConstellation:[{i:0,q:NaN}]}),/constellation/);assert.throws(()=>replay.replayResult('communications',{...radio,idealConstellation:Array.from({length:5},()=>({i:0,q:0}))}),/constellation/);
 assert.throws(()=>replay.replayResult('communications',{...radio,waterfall:{rows:[],frames:0,bins:0,minimumDb:-100,maximumDb:0}}),/spectrogram/);assert.throws(()=>replay.replayResult('communications',{...radio,sweep:{cells:[],values:[],secondaryValues:[]}}),/scan/);
 const replayRequest={schema:'ocv.signals/1',op:'communications',bits:'10',seed:42,ebN0Db:8,samplesPerSymbol:8,sampleRateHz:8000,crc:'CRC-8',modulation:'BPSK',lineCode:'NRZ',timingOffsetSymbols:0,frequencyOffsetHz:0,noiseless:true},frame='1000001110',replaySummary={...replayRequest,sigma:0,symbolRateHz:1000,durationS:.01,symbols:10};delete replaySummary.schema;delete replaySummary.op;delete replaySummary.bits;
 const replayRadio={ok:true,engine:'CE2/rust-frame',version:'1.1.0',summary:replaySummary,payloadBits:'10',decodedBits:'10',txBits:frame,rxBits:frame,payloadLength:2,frameLength:10,crcValid:true,bitErrors:0,frameBitErrors:0,ber:0,interval:{lower:0,upper:.6576},waveform:Array.from({length:80},(_,index)=>({t:index/8000,tx:frame[Math.floor(index/8)]==='1'?1/Math.sqrt(8):-1/Math.sqrt(8),txQ:0,rx:0,q:0})),constellation:Array.from({length:10},(_,index)=>({i:frame[index]==='1'?1:-1,q:0,bit:Number(frame[index]),index})),eye:[]};
 const replayEnvelope={schema:'ocv.signals-replay/1',kind:'communications',request:replayRequest,result:replayRadio,sampling:replaySummary,modelVersion:'1.1.0',units:{time:'s',amplitude:'normalized',frequency:'Hz'}};assert.equal(replay.replayRecord(replayEnvelope,'communications',replayRequest),replayRadio);
 assert.throws(()=>replay.replayRecord(replayEnvelope,'communications',{...replayRequest,bits:'01'}),/editable project/);
 assert.throws(()=>replay.replayRecord({...replayEnvelope,request:{...replayRequest,bits:'01'}},'communications',{...replayRequest,bits:'01'}),/frame differs/);
 assert.throws(()=>replay.replayRecord({...replayEnvelope,request:{...replayRequest,sampleRateHz:4000}},'communications',{...replayRequest,sampleRateHz:4000}),/sampleRateHz/);
 const wrongTimes=structuredClone(replayEnvelope);wrongTimes.result.waveform.forEach(row=>row.t*=2);assert.throws(()=>replay.replayRecord(wrongTimes,'communications',replayRequest),/sample times/);
 for(const change of [{modelVersion:'wrong'},{units:{time:'ms',amplitude:'normalized',frequency:'Hz'}},{sampling:{...replaySummary,sampleRateHz:1}}])assert.throws(()=>replay.replayRecord({...replayEnvelope,...change},'communications',replayRequest));
 const legacyReplay=structuredClone(replayEnvelope);for(const key of ['lineCode','timingOffsetSymbols','frequencyOffsetHz','symbols','durationS'])delete legacyReplay.result.summary[key];legacyReplay.sampling=structuredClone(legacyReplay.result.summary);for(const key of ['lineCode','timingOffsetSymbols','frequencyOffsetHz'])delete legacyReplay.request[key];assert.equal(replay.replayRecord(legacyReplay,'communications',replayRequest),legacyReplay.result);
 const digitalRequest={schema:'ocv.signals/1',op:'digital',inputs:{d:true},patterns:{d:'10'},gates:[{id:'q',type:'DFF',inputs:['d'],initial:false}],ticks:2,clockPeriodTicks:2,tickS:.1},digitalSummary={ticks:2,clockPeriodTicks:2,tickS:.1,durationS:.2,model:'ideal synchronous'},digitalRecord={ok:true,engine:'CE2/rust-frame',version:'1.1.0',summary:digitalSummary,wires:['clock','d','q'],trace:[{tick:0,t:0,values:{clock:false,d:true,q:false}},{tick:1,t:.1,values:{clock:true,d:false,q:false}}],events:[]},digitalEnvelope={schema:'ocv.signals-replay/1',kind:'digital',request:digitalRequest,result:digitalRecord,sampling:digitalSummary,modelVersion:'1.1.0',units:{time:'s',wire:'boolean'}};assert.equal(replay.replayRecord(digitalEnvelope,'digital',digitalRequest),digitalRecord);
 assert.throws(()=>replay.replayRecord({...digitalEnvelope,request:{...digitalRequest,tickS:.2}},'digital',{...digitalRequest,tickS:.2}),/acquisition/);
 const changedDigital={...digitalRequest,patterns:{d:'01'}};assert.throws(()=>replay.replayRecord({...digitalEnvelope,request:changedDigital},'digital',changedDigital),/digital input/);
 const controller=await readFile(join(root,'config/apps/ng/config2/Inventory2.ts'),'utf8'),method=controller.match(/ sweepPreset\(name:string\)\{([^\n]+)\}/)?.[1];assert.ok(method);const apply=new Function('name',method);for(const [sampleRateHz,samplesPerSymbol]of [[8000,8],[8000,32],[1,32]]){const fixture={project:()=>({communication:{sampleRateHz,samplesPerSymbol}}),message:{set:()=>{}},mutate:update=>{const project={communication:{sampleRateHz,samplesPerSymbol}};update(project);fixture.sweep=project.communication.sweep}};apply.call(fixture,'Carrier / timing');const values=fixture.sweep.values;assert.equal(values.length,5);assert.ok(values.every((value,index)=>Math.abs(value)<=sampleRateHz/samplesPerSymbol*.25&&(!index||value>values[index-1])))}
 console.log(JSON.stringify({ok:true,scope:'pure frontend/domain fixtures; not native or browser proof',templates:3,projectRoundtrip:true,legacyLoad:true,digitalAndIQExports:true,boundedReplayValidation:true,replayRequestAndSamplingIdentity:true,complexSpectrum:true}));
}finally{const inside=relative(temporaryRoot,resolve(scratch));if(!inside||inside.startsWith('..')||isAbsolute(inside)||!inside.startsWith('signals-phase14-ui-'))throw Error('Unexpected fixture directory');await rm(scratch,{recursive:true,force:true})}
