import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {resolve,join} from 'node:path';
import {composeCall,dockerCall} from '../../scripts/docker-child.mjs';

const mode=process.env.OCV_SIGNALS_NATIVE_MODE||'container',container=process.env.OCV_SIGNALS_NATIVE_CONTAINER;
function native(input){const request=JSON.stringify({schema:'ocv.signals/1',...input}),options={input:request,timeout:20000,maxBuffer:8*1024*1024};let output;
 if(mode==='binary'){if(!process.env.OCV_RUST_BINARY)throw Error('Explicit OCV_RUST_BINARY required');output=spawnSync(process.env.OCV_RUST_BINARY,[],{...options,encoding:'utf8',windowsHide:true})}
 else output=container?dockerCall(['exec','-i',container,'/opt/ocv/ocv-communications'],options):composeCall(['exec','-T','signals-native','/opt/ocv/ocv-communications'],options);
 if(output.error||output.status)throw Error(output.error?.message||output.stderr||`Native exit ${output.status}`);return JSON.parse(output.stdout);
}
let binary;
async function wasm(input){binary??=readFile(join(resolve(process.env.OCV_SIGNALS_WASM_DIR||'config/apps/portal/public/signals/engines'),'communications.wasm')).then(bytes=>WebAssembly.instantiate(bytes,{})).then(result=>result.instance.exports);const module=await binary,bytes=new TextEncoder().encode(JSON.stringify({schema:'ocv.signals/1',...input})+'\0'),pointer=module.ocv_alloc(bytes.length);assert.ok(pointer);try{new Uint8Array(module.memory.buffer,pointer,bytes.length).set(bytes);const output=module.ocv_run(pointer),memory=new Uint8Array(module.memory.buffer);let end=output;while(end<memory.length&&memory[end]&&end-output<8*1024*1024)end++;assert.ok(output&&end<memory.length&&end-output<8*1024*1024);return JSON.parse(new TextDecoder().decode(memory.subarray(output,end)))}finally{module.ocv_dealloc(pointer,bytes.length)}}
const close=(a,b,tolerance=1e-10)=>assert.ok(Math.abs(a-b)<=tolerance*Math.max(1,Math.abs(b)),`${a} differs from ${b}`);
function crc(bits,width){let value=width===16?0xffff:0,polynomial=width===16?0x1021:0x07,mask=width===16?0xffff:0xff;for(const bit of bits){const top=((value>>(width-1))&1)^Number(bit);value=(value<<1)&mask;if(top)value^=polynomial}return value.toString(2).padStart(width,'0')}

test('All twelve modulation / line / CRC combinations use native and Wasm engines',async()=>{
 const bits='1011000100110';for(const modulation of ['BPSK','QPSK','BFSK'])for(const lineCode of ['NRZ','Manchester'])for(const check of ['CRC-8','CRC-16']){const input={op:'communications',bits,modulation,lineCode,crc:check,noiseless:true,samplesPerSymbol:8},a=native(input),b=await wasm(input);for(const result of [a,b]){assert.equal(result.ok,true);assert.equal(result.decodedBits,bits);assert.equal(result.txBits,bits+crc(bits,check==='CRC-16'?16:8));assert.equal(result.crcValid,true);assert.equal(result.bitErrors,0);assert.equal(result.summary.lineCode,lineCode);assert.equal(result.summary.modulation,modulation);assert.equal(result.eye.at(-1).phase,((result.waveform.length-1)%16)/8);assert.ok(result.interval.upper>0)}assert.equal(a.txBits,b.txBits);for(let i=0;i<Math.min(32,a.waveform.length);i++)for(const field of ['tx','txQ','rx','q'])close(a.waveform[i][field],b.waveform[i][field]);}
});
test('CRC catalogue check values are independently generated from ASCII input',()=>{const bits=Array.from(Buffer.from('123456789'),byte=>byte.toString(2).padStart(8,'0')).join('');assert.equal(parseInt(crc(bits,8),2),0xf4);assert.equal(parseInt(crc(bits,16),2),0x29b1);for(const width of [8,16])assert.equal(native({op:'communications',bits,crc:width===8?'CRC-8':'CRC-16',noiseless:true}).txBits.slice(-width),crc(bits,width))});
test('Manchester emits real complementary chips and preserves bit energy',()=>{for(const modulation of ['BPSK','QPSK','BFSK']){const result=native({op:'communications',bits:'101011001',modulation,lineCode:'Manchester',crc:'CRC-16',noiseless:true});assert.equal(result.ok,true);assert.equal(result.encodedBits,Array.from(result.txBits,bit=>bit+(bit==='0'?'1':'0')).join(''));const energy=result.waveform.reduce((total,sample)=>total+sample.tx**2+sample.txQ**2,0);close(energy,result.frameLength);assert.equal(result.summary.lineCodeViolations,0)}});
test('Fixed seeded channel, offsets and finite-sample scans are reproducible',async()=>{const input={op:'communications',bits:'010110101001'.repeat(16),modulation:'QPSK',lineCode:'NRZ',crc:'CRC-16',seed:29,ebN0Db:2,timingOffsetSymbols:.125,frequencyOffsetHz:25,sweep:{axis:'ebN0Db',values:[-2,2,6],secondaryAxis:'timingOffsetSymbols',secondaryValues:[-.25,0,.25]}},a=native(input),b=native(input),w=await wasm(input);assert.deepEqual(a,b);assert.equal(a.ok,true);assert.equal(a.sweep.executed,true);assert.equal(a.sweep.cases,9);assert.equal(w.sweep.cases,9);for(const cell of a.sweep.cells){close(cell.ber,cell.bitErrors/cell.payloadLength);assert.ok(cell.interval.lower<=cell.ber&&cell.interval.upper>=cell.ber);const candidate=native({...input,sweep:undefined,ebN0Db:cell.x,timingOffsetSymbols:cell.y});assert.equal(cell.bitErrors,candidate.bitErrors);assert.equal(cell.crcValid,candidate.crcValid)}assert.ok(a.waterfall.rows.every(row=>Number.isFinite(row.powerDb)));assert.equal(a.waterfall.rows.length,a.waterfall.frames*a.waterfall.bins);});
test('AWGN is actually active and the matched BPSK realization retains prior behavior',()=>{const result=native({op:'communications',bits:'1011000110001010'.repeat(64),seed:55,ebN0Db:0});assert.equal(result.ok,true);assert.ok(result.bitErrors>0&&result.ber<.25);close(result.summary.sigma,Math.sqrt(.5));assert.ok(result.waveform.some(sample=>sample.rx!==sample.tx));assert.equal(result.frameLength,result.payloadLength+8)});
test('Complex spectral waterfall is the independent sampled Hann DFT',()=>{const result=native({op:'communications',bits:'0011001100110011',modulation:'BFSK',noiseless:true});const first=result.waterfall.rows.filter(row=>row.frame===0),N=result.waterfall.bins,fs=result.summary.sampleRateHz,center=first[0].t*fs,start=Math.round(center-N/2);for(const cell of first.slice(0,6)){const bin=cell.bin-Math.floor(N/2);let re=0,im=0;for(let index=0;index<N;index++){const sample=result.waveform[start+index],window=.5-.5*Math.cos(2*Math.PI*index/(N-1)),angle=2*Math.PI*bin*index/N;re+=window*(sample.rx*Math.cos(angle)+sample.q*Math.sin(angle));im+=window*(sample.q*Math.cos(angle)-sample.rx*Math.sin(angle))}close(cell.powerDb,10*Math.log10(Math.max(1e-14,(re*re+im*im)/(N*N))),1e-9)}});
test('Bounded channel and sweep inputs reject unsupported or excessive work',()=>{for(const input of [{modulation:'OFDM'},{timingOffsetSymbols:.46},{frequencyOffsetHz:251},{modulation:'BFSK',samplesPerSymbol:2},{sweep:{axis:'ebN0Db',values:[0,0]}},{sweep:{axis:'ebN0Db',values:Array.from({length:8},(_,i)=>i)}},{bits:'1'.repeat(4096),samplesPerSymbol:32},{bits:'0'.repeat(1024),samplesPerSymbol:16,sweep:{axis:'ebN0Db',values:[0,4]}}])assert.equal(native({op:'communications',...input}).ok,false)});
test('JK and DFF latch the same prior state and actual cyclic source events',async()=>{const input={op:'digital',inputs:{one:true,d:false},patterns:{d:'00110000'},gates:[{id:'q',type:'JKFF',inputs:['one','one']},{id:'r',type:'DFF',inputs:['q']},{id:'sample',type:'DFF',inputs:['d']}],clockPeriodTicks:4,ticks:12,tickS:.01},a=native(input),b=await wasm(input);assert.deepEqual(a,b);assert.equal(a.ok,true);assert.equal(a.trace[2].values.q,true);assert.equal(a.trace[2].values.r,false);assert.equal(a.trace[6].values.q,false);assert.equal(a.trace[6].values.r,true);assert.equal(a.trace[2].values.sample,true);assert.equal(a.trace[6].values.sample,false);close(a.trace[10].t,.1);assert.ok(a.events.some(event=>event.wire==='sample'&&event.cause==='rising-edge register'));});
test('Digital cycles and trace growth return explicit diagnostics',()=>{const cycle=native({op:'digital',inputs:{},gates:[{id:'a',type:'NOT',inputs:['b']},{id:'b',type:'NOT',inputs:['a']}]});assert.equal(cycle.ok,false);assert.equal(cycle.diagnostics[0].code,'DIGITAL_CYCLE');assert.equal(native({op:'digital',inputs:{d:false},patterns:{missing:'10'},gates:[]}).ok,false);assert.equal(native({op:'digital',inputs:Object.fromEntries(Array.from({length:32},(_,i)=>['x'+i,false])),gates:[],ticks:4096}).diagnostics[0].code,'LIMIT')});
