import {features,snapshot,mutate,loadDesk,watchDesk,reloadDesk,clean} from './state.mjs';
import {searchFeatures} from '../main1/catalogue.mjs';
const root=document.querySelector('[data-desk-page]'),picker=document.querySelector('.q9-picker');
const status=document.querySelector('[data-desk-status]');let target='favorite',folder='all',filter='',dragging=null;
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n;};
const button=(text,fn)=>{const n=el('button',text,{type:'button'});n.onclick=fn;return n;};
function recent(){try{const rows=JSON.parse(localStorage.getItem('ocv.desk.recent')||'[]');return Array.isArray(rows)?rows.filter(r=>features.has(r.id)&&Number.isFinite(r.time)).slice(0,24):[];}catch{return [];}}
function favorite(id){mutate(s=>{if(s.favorites.some(r=>r.id===id))return;if(s.favorites.length>=60){status.textContent='最多 60 项';return;}s.favorites.push({id,folder:features.get(id)?.url.startsWith('/functions/')?'tools':'pages'});});}
function preview(row){for(const [key,value] of Object.entries({title:row.title,url:row.url,group:row.group}))document.querySelector('[data-preview-'+key+']').textContent=value;const a=document.querySelector('[data-preview-open]');a.href=row.url;a.hidden=false;}
function paint(){const s=snapshot();document.querySelectorAll('[data-desk-total]').forEach(n=>n.textContent=String(s.favorites.length));
 const pins=document.querySelector('[data-desk-pins]');if(pins){pins.replaceChildren(...s.pinned.map(id=>{const r=features.get(id),n=el('div',undefined,{class:'q9-pin'});n.append(el('a',r.title,{href:r.url}),button('×',()=>mutate(s=>s.pinned=s.pinned.filter(n=>n!==id))));return n;}));if(!s.pinned.length)pins.append(el('span','—'));}
 const table=document.querySelector('[data-desk-recent]');if(table){table.replaceChildren(...recent().map(row=>{const r=features.get(row.id),tr=el('tr');const a=el('td');a.append(el('a',r.title,{href:r.url}));const star=el('td');star.append(button(s.favorites.some(n=>n.id===r.id)?'★':'☆',()=>favorite(r.id)));tr.append(a,el('td',new Date(row.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),el('td',r.url),star);return tr;}));if(!table.children.length){const tr=el('tr');tr.append(el('td','—',{colspan:'4'}));table.append(tr);}}
 const note=document.querySelector('[data-desk-note]');if(note&&document.activeElement!==note)note.value=s.note;const length=document.querySelector('[data-note-length]');if(length)length.textContent=(note?.value.length||0)+' / 1200';
 for(const list of document.querySelectorAll('[data-favorite-list]')){const column=list.closest('[data-folder-column]');column.hidden=folder!=='all'&&folder!==list.dataset.favoriteList;const rows=s.favorites.filter(row=>row.folder===list.dataset.favoriteList&&(!filter||(features.get(row.id).title+' '+features.get(row.id).url).toLowerCase().includes(filter)));list.replaceChildren(...rows.map(row=>{const r=features.get(row.id),card=el('article',undefined,{class:'q9-bookmark','data-favorite-id':row.id});const title=button(r.title,()=>preview(r));title.className='q9-bookmark-title';card.append(title,el('a',r.url,{href:r.url}));const foot=el('footer'),select=el('select',undefined,{'aria-label':'分组'});for(const [id,label] of [['default','未分类'],['tools','工具'],['pages','页面']]){const opt=el('option',label,{value:id});opt.selected=id===row.folder;select.append(opt);}select.onchange=()=>mutate(s=>{s.favorites.find(r=>r.id===row.id).folder=select.value;});foot.append(select,button('↑',()=>mutate(s=>{const i=s.favorites.findIndex(r=>r.id===row.id);if(i>0)[s.favorites[i-1],s.favorites[i]]=[s.favorites[i],s.favorites[i-1]];})),button('☆',()=>mutate(s=>{if(!s.pinned.includes(row.id)&&s.pinned.length<8)s.pinned.push(row.id);})),button('×',()=>mutate(s=>s.favorites=s.favorites.filter(r=>r.id!==row.id))));card.append(foot);return card;}));if(!rows.length)list.append(el('div',undefined,{class:'q9-empty-shelf'}));}}
function options(value=''){const list=picker.querySelector('[data-picker-list]'),s=snapshot(),items=value?searchFeatures(value):[...features.values()].filter(r=>r.group==='日常'||r.group==='开发'||r.id==='research').slice(0,35);list.replaceChildren(...items.filter(r=>r.available).map(r=>{const b=button(r.title,()=>{if(target==='pin'){if(snapshot().pinned.length>=8){status.textContent='最多 8 项';return;}mutate(s=>{if(!s.pinned.includes(r.id))s.pinned.push(r.id);});}else favorite(r.id);options(picker.querySelector('input').value);});b.append(el('small',(target==='pin'?s.pinned.includes(r.id):s.favorites.some(n=>n.id===r.id))?'✓':r.group));return b;}));}
document.querySelectorAll('[data-picker]').forEach(b=>b.onclick=()=>{target=b.dataset.picker;picker.hidden=false;options();picker.querySelector('input').focus();});document.querySelector('[data-picker-close]').onclick=()=>picker.hidden=true;document.querySelector('[data-picker-search]').oninput=e=>options(e.target.value);
document.querySelector('[data-note-save]')?.addEventListener('click',()=>{mutate(s=>s.note=document.querySelector('[data-desk-note]').value);document.dispatchEvent(new CustomEvent('ocv:site-action',{detail:{kind:'note'}}));});document.querySelector('[data-desk-note]')?.addEventListener('input',e=>document.querySelector('[data-note-length]').textContent=e.target.value.length+' / 1200');
document.querySelector('[data-recent-clear]')?.addEventListener('click',()=>{try{localStorage.setItem('ocv.desk.recent','[]');}catch{}paint();});
document.querySelectorAll('[data-folder-view]').forEach(b=>b.onclick=()=>{folder=b.dataset.folderView;paint();});document.querySelector('[data-favorite-filter]')?.addEventListener('input',e=>{filter=e.target.value.toLowerCase();paint();});
function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,...clean(snapshot())},null,2)],{type:'application/json'}));const a=el('a',undefined,{href:url,download:'favorites.json'});a.click();document.dispatchEvent(new CustomEvent('ocv:site-action',{detail:{kind:'export'}}));setTimeout(()=>URL.revokeObjectURL(url),1500);}
document.querySelector('[data-favorite-export]')?.addEventListener('click',exportData);document.querySelector('[data-favorite-import]')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file||file.size>32768)throw Error('文件限 32 KiB');const value=JSON.parse(await file.text());if(value.version!==1)throw Error('文件版本不匹配');const imported=clean(value);mutate(s=>Object.assign(s,imported));}catch(err){status.textContent=err.message;}finally{e.target.value='';}});
document.querySelectorAll('[data-desk-close]').forEach(b=>b.onclick=()=>b.closest('[data-desk-window]').hidden=true);
for(const handle of document.querySelectorAll('[data-desk-handle]')){const panel=handle.closest('[data-desk-window]');handle.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;handle.setPointerCapture(e.pointerId);dragging={panel,x:e.clientX,y:e.clientY,dx:Number(panel.dataset.dx||0),dy:Number(panel.dataset.dy||0)};});handle.addEventListener('pointermove',e=>{if(!dragging||dragging.panel!==panel)return;const dx=Math.max(-1200,Math.min(1200,dragging.dx+e.clientX-dragging.x)),dy=Math.max(-1000,Math.min(1000,dragging.dy+e.clientY-dragging.y));panel.dataset.dx=String(dx);panel.dataset.dy=String(dy);panel.style.translate=dx+'px '+dy+'px';});for(const name of ['pointerup','pointercancel'])handle.addEventListener(name,()=>dragging=null);}
const reload=button('重新读取',()=>void reloadDesk());reload.className='q9-reload';status.after(reload);
document.addEventListener('q9:desk',e=>{paint();document.querySelectorAll('[data-desk-storage]').forEach(n=>n.textContent=e.detail.storage==='postgresql'?'已连接':'本地');if(e.detail.message)status.textContent=e.detail.message;});paint();await loadDesk();paint();watchDesk();
