import {snapshot} from './state.mjs';
const root=document.querySelector('[data-desk-page="profile"]');if(root){
 const session=snapshot().session,key='ocv.profile.v1',form=root.querySelector('[data-profile-form]'),message=root.querySelector('[data-profile-message]'),life=new AbortController();let profile={session,nickname:'',bio:'',avatar:'',twoFactor:false},uploading=false,busy=false;
 const privateLabels={email:'禁止输入邮箱',phone:'禁止输入手机号',old:'禁止输入密码',new:'禁止输入密码'};for(const input of root.querySelectorAll('[data-private]'))input.addEventListener('input',()=>{const note=input.parentElement.querySelector('[data-private-note]');note.textContent=privateLabels[input.dataset.private];note.hidden=input.value.length===0;},{signal:life.signal});
 const scrub=v=>String(v).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'…').replace(/(?:\+?\d[\s().-]*){7,}/g,'…').replace(/[\x00-\x1f\x7f]/g,' ').trim();
 function persist(){try{localStorage.setItem(key,JSON.stringify(profile));}catch{}}
 function paint(){root.querySelector('[data-profile-avatar]').src=profile.avatar?'data:image/png;base64,'+profile.avatar:'/favicon.svg';root.querySelector('[data-profile-name]').textContent=profile.nickname||'guest';root.querySelector('[data-profile-intro]').textContent=profile.bio||'—';form.elements.nickname.value=profile.nickname;form.elements.bio.value=profile.bio;root.querySelector('[data-two-factor]').checked=profile.twoFactor;}
 async function api(action,data){const r=await fetch('/api/q8/profile/'+action,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify({session,...data}),signal:AbortSignal.any([life.signal,AbortSignal.timeout(5500)])});if(!r.ok)throw Error('后台未连接');return r.json();}
 try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old?.session===session&&typeof old.nickname==='string'&&old.nickname.length<=32&&typeof old.bio==='string'&&old.bio.length<=500&&typeof old.avatar==='string'&&old.avatar.length<=87384)profile={session,nickname:scrub(old.nickname),bio:scrub(old.bio),avatar:old.avatar,twoFactor:old.twoFactor===true};}catch{}paint();
 async function save(){if(busy||uploading)return;busy=true;const value={nickname:scrub(form.elements.nickname.value).slice(0,32),bio:scrub(form.elements.bio.value).slice(0,500),avatar:profile.avatar};profile={...profile,...value};persist();paint();for(const [kind,value]of [['nickname',profile.nickname],['bio',profile.bio],['avatar',profile.avatar]])if(value)document.dispatchEvent(new CustomEvent('ocv:site-action',{detail:{kind}}));try{const saved=await api('write',value);profile={...profile,nickname:saved.nickname,bio:saved.bio,avatar:saved.avatar};persist();root.querySelector('[data-profile-store]').textContent='已存档';message.textContent='已保存';}catch{message.textContent='未连接；资料在本地';}finally{busy=false;}}
 form.addEventListener('submit',e=>{e.preventDefault();void save();},{signal:life.signal});root.querySelector('[data-avatar-clear]').onclick=()=>{profile.avatar='';void save();};
 root.querySelector('[data-avatar-file]').addEventListener('change',async e=>{let image;try{const file=e.target.files[0];if(!file||file.size>8*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('PNG / JPG / WebP，限 8 MiB');uploading=true;image=await createImageBitmap(file);if(image.width*image.height>32000000)throw Error('图片过大');const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),size=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,128,128);const value=c.toDataURL('image/png').split(',')[1];if(value.length>87384)throw Error('缩略图过大');profile.avatar=value;uploading=false;await save();}catch(err){message.textContent=err.message;}finally{image?.close();uploading=false;e.target.value='';}},{signal:life.signal});
 async function slip(kind,enabled,go=false){if(busy)return;busy=true;try{const receipt=await api('slip',{kind,...(enabled===undefined?{}:{enabled})});root.querySelector('[data-profile-receipt]').textContent=receipt.id.slice(0,8);if(kind==='two-factor'){profile.twoFactor=receipt.enabled;persist();}if(go&&/^\/maze\/[a-z0-9/_-]*\/$/.test(receipt.route))location.assign(receipt.route);}catch{root.querySelector('[data-two-factor]').checked=profile.twoFactor;message.textContent='后台未连接';if(go)location.assign('/maze/approval/');}finally{busy=false;}}
 for(const f of root.querySelectorAll('[data-profile-slip]'))f.addEventListener('submit',e=>{e.preventDefault();for(const input of f.querySelectorAll('input'))input.value='';for(const note of f.querySelectorAll('[data-private-note]'))note.hidden=true;void slip(f.dataset.profileSlip,undefined,f.dataset.profileSlip!=='password');},{signal:life.signal});root.querySelector('[data-two-factor]').onchange=e=>{void slip('two-factor',e.target.checked);};root.querySelector('[data-two-factor-code]').onclick=()=>void slip('two-factor',profile.twoFactor,true);
 let edited=false;root.addEventListener('input',()=>edited=true,{signal:life.signal});api('read',{}).then(data=>{if(edited||busy||uploading)return;if(data.nickname||data.bio||data.avatar||data.twoFactor){profile={session,nickname:scrub(data.nickname),bio:scrub(data.bio),avatar:data.avatar,twoFactor:data.twoFactor===true};persist();paint();}root.querySelector('[data-profile-store]').textContent='已连接';}).catch(()=>{});
 window.addEventListener('pagehide',e=>{for(const f of root.querySelectorAll('[data-profile-slip]'))f.reset();for(const note of root.querySelectorAll('[data-private-note]'))note.hidden=true;if(!e.persisted)life.abort();},{signal:life.signal});
}
