import './s1.css';
import {SITE_AWARDS,createSiteAwards} from './s0.mjs';
export function ensureSiteAwards(){
 if(/^\/(research|identity)(\/|$)/.test(location.pathname)||location.pathname.startsWith('/functions/3d-world'))return null;if(window.__ocvSiteAwards)return window.__ocvSiteAwards;
 const life=new AbortController(),on=(n,k,f,options={})=>n?.addEventListener(k,f,{...options,signal:life.signal}),active=new Map(),queue=[],titles=new Map(SITE_AWARDS.map(a=>[a.id,a.title]));let serial=0,drag=null;let storage;try{storage=localStorage;}catch{}
 const intro=()=>document.body.classList.contains('luminous-home')&&scrollY<innerHeight*.72;
 function remove(id){const row=active.get(id);if(!row)return;clearTimeout(row.timer);row.node.remove();active.delete(id);drain();}
 function drain(){if(document.hidden||intro())return;while(queue.length&&active.size<3){const id=queue.shift(),n=serial++,box=document.createElement('aside');box.className='s1-award';box.dataset.siteAward=id;box.dataset.form=String((SITE_AWARDS.findIndex(a=>a.id===id)+n)%8);box.setAttribute('role','status');box.setAttribute('aria-live','polite');box.style.left=Math.max(8,innerWidth-270-(n%3)*68)+'px';box.style.top=(90+(n%3)*152)+'px';const header=document.createElement('header'),label=document.createElement('span'),close=document.createElement('button'),text=document.createElement('strong'),footer=document.createElement('small');label.textContent=['成就','ACHIEVEMENT','取得','NOTICE'][n%4];close.textContent='×';close.setAttribute('aria-label','关闭成就提示');text.textContent=titles.get(id);footer.textContent='◆ / '+id;header.append(label,close);box.append(header,text,footer);document.body.append(box);close.onclick=()=>remove(id);header.onpointerdown=e=>{if(e.target.closest('button'))return;header.setPointerCapture(e.pointerId);drag={box,x:e.clientX,y:e.clientY,left:parseFloat(box.style.left),top:parseFloat(box.style.top)};};header.onpointermove=e=>{if(drag?.box!==box)return;box.style.left=Math.max(-200,Math.min(innerWidth-16,drag.left+e.clientX-drag.x))+'px';box.style.top=Math.max(-100,Math.min(innerHeight-16,drag.top+e.clientY-drag.y))+'px';};header.onpointerup=header.onpointercancel=()=>drag=null;active.set(id,{node:box,timer:setTimeout(()=>remove(id),4800+(n%3)*800)});}}
 const store=createSiteAwards(storage,ids=>{for(const id of ids)if(!active.has(id)&&!queue.includes(id)&&queue.length<SITE_AWARDS.length)queue.push(id);document.dispatchEvent(new CustomEvent('ocv:site-awards'));drain();});window.__ocvSiteAwards=store;
 store.visit(location.pathname);on(document,'ocv:tool-success',e=>store.tool(e.detail?.id));on(document,'ocv:site-action',e=>{if(['export','nickname','bio','avatar','note','search','contact','media'].includes(e.detail?.kind))store.add(e.detail.kind);});
 on(document,'q9:desk',e=>{const d=e.detail||{};store.set('favorites',d.favorites);store.set('pins',d.pins);store.set('noteLength',d.noteLength);});on(document,'q8:progress',e=>store.set('hunt',e.detail?.count));
 on(document,'click',e=>{if(e.target.closest?.('.s1-award'))return;const node=e.target.closest?.('button');if(!node)return;if(node.matches('[data-n3-close],[data-desk-close],[data-p2-close],[data-help-close]'))store.add('closed');if(node.matches('[data-author-open]'))store.add('contact');});
 let moving=null;on(document,'pointerdown',e=>{const handle=e.target.closest?.('[data-n3-handle],[data-desk-handle],[data-p2-handle]');if(handle&&(!e.target.closest('button')||e.target.closest('button')===handle))moving={id:e.pointerId,x:e.clientX,y:e.clientY};});on(document,'pointerup',e=>{if(moving?.id===e.pointerId&&Math.hypot(e.clientX-moving.x,e.clientY-moving.y)>12)store.add('dragged');moving=null;});on(document,'pointercancel',()=>moving=null);
 on(document,'play',e=>{if(e.target instanceof HTMLMediaElement)store.add('media');},{capture:true});
 on(window,'scroll',drain);on(document,'visibilitychange',drain);on(window,'pagehide',e=>{for(const {node,timer}of active.values()){clearTimeout(timer);node.remove();}active.clear();queue.length=0;drag=null;if(!e.persisted){life.abort();delete window.__ocvSiteAwards;}});return store;
}
ensureSiteAwards();
