import * as T from 'three';
for(const root of document.querySelectorAll('[data-q9-scene]')){
 const canvas=root.querySelector('canvas');let renderer;try{renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true});}catch{root.dataset.render='unavailable';continue;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0xffffff,0);renderer.outputColorSpace=T.SRGBColorSpace;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100),group=new T.Group();scene.add(group);camera.position.set(0,2.6,12);camera.lookAt(0,0,0);
 scene.add(new T.HemisphereLight(0xfaffff,0x466ba0,2.3));const key=new T.DirectionalLight(0xffffff,3.2);key.position.set(-3,5,4);scene.add(key);const blueLight=new T.PointLight(0x1685ff,22,25);blueLight.position.set(4,0,3);scene.add(blueLight);
 const glass=new T.MeshPhysicalMaterial({color:0xbedfff,metalness:.45,roughness:.16,transparent:true,opacity:.73,clearcoat:1,side:T.DoubleSide}),blue=new T.MeshStandardMaterial({color:0x164dff,metalness:.65,roughness:.25}),wire=new T.LineBasicMaterial({color:0x6198e6,transparent:true,opacity:.5});
 const pieces=[],ray=new T.Raycaster(),pointer=new T.Vector2(5,5),base=new T.Vector3(),mode=root.dataset.q9Scene;let pulse=0,hover=null,disposed=false,raf=0,last=0;
 function piece(geo,mat,x,y,z,index){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.userData={home:new T.Vector3(x,y,z),kick:0,index};group.add(m);pieces.push(m);return m;}
 if(mode==='desk'){
  const geo=new T.BoxGeometry(1.2,.16,.8);for(let i=0;i<54;i++){const m=piece(geo,i%7===0?blue:glass,(i%6-2.5)*1.08,Math.floor(i/18)*.87,(Math.floor(i/6)%3-1)*1.02,i);m.rotation.z=i%11===0?.2:0;}
  const rack=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(7,3.7,4.1)),wire);group.add(rack);rack.position.y=.7;group.rotation.set(.25,-.42,0);
 }else if(mode==='saved'){
  for(let i=0;i<5;i++){const ring=piece(new T.TorusGeometry(2+i*.17,.025,6,96),i===3?blue:glass,0,0,-i*.28,i);ring.rotation.set(.32+i*.18,.43+i*.12,.2);}
  const geo=new T.BoxGeometry(.85,1.15,.08);for(let i=0;i<32;i++){const a=i*.71,m=piece(geo,i%5===0?blue:glass,Math.cos(a)*(2.5+i%3*.21),Math.sin(a)*1.5,Math.sin(i*.37)*2,i+5);m.rotation.set(.15,a*.2,i%4===0?.13:0);}group.rotation.y=.28;
 }else{
  const profile=[new T.Vector2(0,-2.1),new T.Vector2(1.85,-1.9),new T.Vector2(1.3,-1.45),new T.Vector2(.55,-.65),new T.Vector2(.43,-.3),new T.Vector2(.95,.1),new T.Vector2(1.1,.9),new T.Vector2(.85,1.8),new T.Vector2(.3,2.1),new T.Vector2(0,2.13)];
  piece(new T.LatheGeometry(profile,80),glass,0,0,0,0);for(let i=0;i<12;i++){const m=piece(new T.TorusGeometry(1.5+i*.1,.018,6,72),i%4?glass:blue,0,-1.9+i*.35,-.1,i+1);m.rotation.x=Math.PI/2+i*.065;}for(let i=0;i<18;i++){const a=i*.9;piece(new T.IcosahedronGeometry(.08+i%3*.05),blue,Math.cos(a)*3,Math.sin(i*.7)*2.7,Math.sin(a)*2,i+13);}
 }
 const coords=new Float32Array(240*3);for(let i=0;i<coords.length;i++)coords[i]=(Math.sin(i*129.1)*.5)*13;const pointGeo=new T.BufferGeometry();pointGeo.setAttribute('position',new T.BufferAttribute(coords,3));const dots=new T.Points(pointGeo,new T.PointsMaterial({color:0x3988dd,size:.026,transparent:true,opacity:.8}));scene.add(dots);
 const life=new AbortController();const move=e=>{const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);};canvas.addEventListener('pointermove',move,{signal:life.signal});canvas.addEventListener('pointerleave',()=>pointer.set(5,5),{signal:life.signal});canvas.addEventListener('pointerdown',e=>{move(e);pulse=1;ray.setFromCamera(pointer,camera);const picked=ray.intersectObjects(pieces)[0]?.object;if(picked){picked.userData.kick=1;root.dataset.clicks=String(Number(root.dataset.clicks||0)+1);}else pieces.forEach((m,i)=>{if(i%3===0)m.userData.kick=1;});},{signal:life.signal});canvas.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pulse=1;pieces.forEach(m=>m.userData.kick=1);}},{signal:life.signal});
 const resize=new ResizeObserver(()=>{const r=root.getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}});resize.observe(root);
 function draw(time){if(disposed)return;raf=requestAnimationFrame(draw);if(document.hidden)return;const dt=Math.min(.05,(time-last)/1000||0);last=time;pulse=Math.max(0,pulse-dt*.7);ray.setFromCamera(pointer,camera);hover=ray.intersectObjects(pieces)[0]?.object;root.dataset.hover=hover?'true':'false';for(const m of pieces){const d=m.userData;d.kick=Math.max(0,d.kick-dt*.65);m.position.copy(d.home);m.position.y+=Math.sin(time*.0007+d.index)*.045+d.kick*Math.sin((1-d.kick)*16)*.6+(m===hover?.32:0);m.position.x+=d.kick*Math.sin(d.index*3.3)*.4;if(mode==='saved')m.rotation.y+=dt*.025*(d.index%2?1:-1);}blueLight.intensity=22+pulse*35;dots.rotation.y=time*.000015;renderer.render(scene,camera);root.dataset.render='ready';}raf=requestAnimationFrame(draw);
 function stop(){disposed=true;cancelAnimationFrame(raf);resize.disconnect();life.abort();const geos=new Set(),mats=new Set();scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);});for(const g of geos)g.dispose();for(const m of mats)m.dispose();renderer.dispose();}
 window.addEventListener('pagehide',e=>{if(!e.persisted)stop();},{signal:life.signal});
}
