import {catalogue} from '../main1/catalogue.mjs';
import {projectEvents} from '../site1/projection.mjs';
const key='ocv.desk.v1';
export const features=new Map(catalogue.filter(r=>r.available).map(r=>[r.id,r]));
const initial={session:crypto.randomUUID(),revision:0,favorites:[{id:'json',folder:'tools'},{id:'calculator',folder:'tools'},{id:'media',folder:'pages'},{id:'research',folder:'pages'},{id:'music-studio',folder:'default'}],pinned:['json','csv','research'],note:'',dirty:false};
let state=initial,ready=false,saving=false,again=false,conflict=false,life=new AbortController(),source,favoriteChanges=[];
export function clean(data){if(!data||typeof data!=='object'||!Array.isArray(data.favorites)||data.favorites.length>60||!Array.isArray(data.pinned)||data.pinned.length>8||typeof data.note!=='string'||data.note.length>1200)throw Error('文件格式不匹配');const seen=new Set();return {favorites:data.favorites.filter(r=>r&&features.has(r.id)&&['default','tools','pages'].includes(r.folder)&&!seen.has(r.id)&&seen.add(r.id)).map(r=>({id:r.id,folder:r.folder})),pinned:[...new Set(data.pinned.filter(id=>features.has(id)))],note:data.note};}
try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old&&/^[a-f0-9-]{36}$/.test(old.session)&&Number.isInteger(old.revision)&&old.revision>=0)state={...initial,...clean(old),session:old.session,revision:old.revision,dirty:old.dirty===true};}catch{}
export function snapshot(){return {...state,favorites:state.favorites.map(r=>({...r})),pinned:[...state.pinned]};}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function signal(storage='local',message=''){document.dispatchEvent(new CustomEvent('q9:desk',{detail:{storage,message,favorites:state.favorites.length,pins:state.pinned.length,noteLength:state.note.length}}));}
async function api(path,body){const r=await fetch('/api/q8/desk/'+path,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify(body),signal:AbortSignal.any([life.signal,AbortSignal.timeout(5000)])});if(!r.ok){const e=Error('storage');e.status=r.status;throw e;}return r.json();}
export async function loadDesk(){if(ready)return snapshot();ready=true;try{const remote=await api('read',{session:state.session});if(!state.dirty){if(remote.revision>0)state={...state,...clean(remote),revision:remote.revision};else state.revision=0;}else if(remote.revision!==state.revision){conflict=true;signal('local','版本有变化；导出本地内容后可重新读取');return snapshot();}persist();signal('postgresql');}catch{signal('local','未连接；保存在本机');}return snapshot();}
export async function writeDesk(){if(saving){again=true;return;}if(conflict){signal('local','版本有变化；导出本地内容后可重新读取');return;}saving=true;try{await loadDesk();if(conflict)return;const payload={session:state.session,revision:state.revision,...clean(state)},projectionBatch=favoriteChanges.slice(),remote=await api('write',payload);state.revision=remote.revision;if(JSON.stringify(clean(state))===JSON.stringify(clean(payload)))state.dirty=false;persist();signal('postgresql','已保存');if(remote.storage==='postgresql'&&projectionBatch.length){const ids=new Set(projectionBatch.map(event=>event.id));favoriteChanges=favoriteChanges.filter(event=>!ids.has(event.id));void projectEvents(projectionBatch,{profileSession:state.session,signal:life.signal});}}catch(e){if(e.status===409)conflict=true;signal('local',conflict?'版本有变化；导出后重新读取':'未连接；保存在本机');}finally{saving=false;if(again&&!life.signal.aborted){again=false;void writeDesk();}}}
export function mutate(fn){const previous=state.favorites.map(row=>({...row}));fn(state);Object.assign(state,clean(state));const before=new Map(previous.map(row=>[row.id,row.folder])),after=new Map(state.favorites.map(row=>[row.id,row.folder]));for(const row of previous)if(!after.has(row.id))favoriteChanges.push({id:crypto.randomUUID(),kind:'favorite',data:{id:row.id,folder:row.folder,action:'remove'}});for(const row of state.favorites)if(!before.has(row.id)||before.get(row.id)!==row.folder)favoriteChanges.push({id:crypto.randomUUID(),kind:'favorite',data:{id:row.id,folder:row.folder,action:before.has(row.id)?'move':'add'}});if(favoriteChanges.length>120)favoriteChanges=favoriteChanges.slice(-120);state.dirty=true;persist();signal();void writeDesk();}
export async function reloadDesk(){try{const remote=await api('read',{session:state.session});state={...state,...clean(remote),revision:remote.revision,dirty:false};conflict=false;favoriteChanges=[];persist();signal('postgresql','已读取');}catch{signal('local','未连接');}}
export function watchDesk(){if(source||!ready)return;source=new EventSource('/api/q8/events/'+state.session);source.onmessage=e=>{try{const p=JSON.parse(e.data);if(p.phase==='desk')signal('postgresql');}catch{}};source.onerror=()=>source.close();}
window.addEventListener('pagehide',e=>{source?.close();source=undefined;if(!e.persisted)life.abort();});
window.addEventListener('pageshow',e=>{if(e.persisted)watchDesk();});
persist();
