import {Component,OnDestroy,AfterViewInit,signal,computed,ElementRef,ViewChild} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {PARTS,Part,PartKind,Pin,Terminal,Project,Wire,AnalysisSettings,RadioSettings,RFLinkSettings,DEFAULT_RF_LINK,RF_RANGES,validateRFLink,clone,endpoint,pinsFor,engineering,defaultProject,netlist,parseProject,template,terminalKey} from './stock';
import {LocalComputer,api,JobResponse,EngineResult,CircuitResult,CircuitRow,RadioResult,DigitalResult,download,circuitCSV,radioCSV,digitalCSV} from './transport';
import {Plot,circuitPlot,radioPlot,spectrum,pathOf,circuitCursorIndex,plotSeries} from './plot';
import {NetworkKind,NetworkNode,NetworkLink,Network,NetworkResult,Flight,NETWORK_KINDS,networkTemplate,flightsFrom} from './packet';
import {Measurement,circuitMeasurements,measurementCSV} from './metrology';
import {networkAudit,networkAuditCSV} from './network-audit';
import {DigitalSettings,GateKind,GATE_KINDS,digitalTemplate,digitalLayout,validateDigital} from './clock2';
import {replayRecord} from './replay2';
type RunKind='circuit'|'communications'|'network'|'digital';
interface NativeLaunch {kind:RunKind;origin:Project;source:Project;request:object;sequence:number}
interface NativeCache extends NativeLaunch {result:EngineResult;analysis?:Record<string,unknown>}

@Component({selector:'signals-app',standalone:true,imports:[FormsModule],templateUrl:'./receipt.html'})
export class Inventory2 implements OnDestroy,AfterViewInit {
 @ViewChild('schematic') schematic?:ElementRef<SVGSVGElement>;
 @ViewChild('networkBoard') networkBoard?:ElementRef<SVGSVGElement>;
 readonly parts=PARTS;readonly engineering=engineering;readonly pinsFor=pinsFor;readonly labels=['DC','AC','TRANSIENT'];
 readonly gridXTicks=[100,300,500,700,900,1100];readonly gridYTicks=[100,200,300,400,500];
 private initialProject(){const project=defaultProject();project.communication.rf={...DEFAULT_RF_LINK};return project}
 readonly project=signal<Project>(this.initialProject());readonly selected=signal('R1');readonly armed=signal<PartKind|null>(null);readonly lead=signal<Terminal|null>(null);
 readonly wirePointer=signal<{x:number;y:number}|null>(null);readonly hoverTerminal=signal<Terminal|null>(null);
 readonly engineeringPrefixes=[{label:'p',factor:1e-12},{label:'n',factor:1e-9},{label:'µ',factor:1e-6},{label:'m',factor:1e-3},{label:'',factor:1},{label:'k',factor:1e3},{label:'M',factor:1e6},{label:'G',factor:1e9}];
 private prefixOverride=signal<{part:string;factor:number}|null>(null);
 readonly message=signal('Ready');readonly circuit=signal<CircuitResult|null>(null);readonly radio=signal<RadioResult|null>(null);readonly analysisCheck=signal<Record<string,unknown>|null>(null);
 readonly circuitSource=signal<Project|null>(null);readonly radioSource=signal<Project|null>(null);readonly networkSource=signal<Project|null>(null);
 readonly circuitAnalysis=signal<Record<string,unknown>|null>(null);readonly radioAnalysis=signal<Record<string,unknown>|null>(null);
 readonly localBusy=signal(false);readonly backendBusy=signal(false);readonly job=signal<JobResponse|null>(null);readonly serverProject=signal<{id:string;ticket:string;revision?:number;digest?:string}|null>(null);
 readonly nativeResults=signal<Partial<Record<RunKind,NativeCache>>>({});readonly runningNativeKind=signal<RunKind|null>(null);readonly queuedNativeKind=signal<RunKind|null>(null);readonly backgroundMessage=signal('');
 readonly analysisChecks=computed(()=>{const rows=this.analysisCheck()?.['checks'];return Array.isArray(rows)?rows.filter((row):row is Record<string,unknown>=>!!row&&typeof row==='object').slice(0,128):[]});
 readonly analysisSummary=computed(()=>{const report=this.analysisCheck(),summary=report?.['summary'] as Record<string,unknown>|undefined;return report?{state:String(report['verification']||'—'),checks:Number(summary?.['checks']??this.analysisChecks().length),failed:Number(summary?.['failed']??0),warnings:Number(summary?.['warnings']??0)}:null});
 readonly analysisReferencePlot=computed(()=>{const report=this.analysisCheck(),reference=report?.['reference'] as Record<string,unknown>|undefined,rows=reference?.['rows'];if(!reference?.['supported']||!Array.isArray(rows))return null;const kind=report?.['kind'];if(kind==='communication'){const theory=rows.filter(row=>Number.isFinite(row.ebN0Db)&&Number.isFinite(row.ber)&&row.ber>0).map(row=>({x:Number(row.ebN0Db),y:Math.log10(Number(row.ber))}));const support=report?.['support'] as Record<string,unknown>|undefined,ber=Number(reference['empiricalBER']),snr=Number(support?.['ebN0Db']);const traces=[{name:'Theory',points:theory,color:'#3776cf'}];if(ber>0&&Number.isFinite(snr))traces.push({name:'Measured',points:[{x:snr,y:Math.log10(ber)}],color:'#11a895'});return theory.length>1?plotSeries(traces,'Eb/N₀ / dB','log₁₀ BER'):null}if(kind==='circuit'){const samples=rows.filter(row=>Number.isFinite(row.absoluteErrorV)&&Number.isFinite(row.limitV));if(samples.length<2)return null;const ac=samples[0].frequencyHz!==undefined;return plotSeries([{name:'Absolute residual',points:samples.map((row,index)=>({x:Number(ac?row.frequencyHz:row.t??index),y:Number(row.absoluteErrorV)})),color:'#176de1'},{name:'Tolerance',points:samples.map((row,index)=>({x:Number(ac?row.frequencyHz:row.t??index),y:Number(row.limitV)})),color:'#0b9f93'}],ac?'Frequency / Hz':'Time / s','Residual / V')}return null});
 readonly referenceMeasuredPoint=computed(()=>{const report=this.analysisCheck(),plot=this.analysisReferencePlot(),reference=report?.['reference'] as Record<string,unknown>|undefined,support=report?.['support'] as Record<string,unknown>|undefined,ber=Number(reference?.['empiricalBER']),snr=Number(support?.['ebN0Db']);return report?.['kind']==='communication'&&plot&&ber>0&&Number.isFinite(snr)?{x:32+(snr-plot.xmin)*836/Math.max(1e-15,plot.xmax-plot.xmin),y:248-(Math.log10(ber)-plot.ymin)*216/Math.max(1e-15,plot.ymax-plot.ymin),ber}:null});
 readonly selectedPart=computed(()=>this.project().drawing.components.find(p=>p.id===this.selected()));
 readonly selectedValueFactor=computed(()=>{const part=this.selectedPart(),override=this.prefixOverride();if(!part)return 1;if(override?.part===part.id)return override.factor;const value=Math.abs(part.value);return [...this.engineeringPrefixes].reverse().find(prefix=>value>=prefix.factor)?.factor||1});
 readonly nodes=computed(()=>{try{return netlist(this.project()).nodes}catch{return new Map<string,string>()}});
 readonly measuredTerminals=computed(()=>{try{const source=this.circuitSource();return source?netlist(source).nodes:new Map<string,string>()}catch{return new Map<string,string>()}});
 readonly wirePreview=computed(()=>{const start=this.lead(),cursor=this.wirePointer();if(!start||!cursor)return '';const part=this.project().drawing.components.find(item=>item.id===start.component);if(!part)return '';const target=this.hoverTerminal();if(target&&terminalKey(target)!==terminalKey(start))return this.wirePath({id:'preview',from:start,to:target});const a=endpoint(part,start.pin),u=this.pinDirection(part,start.pin),p={x:a.x+u.x*16,y:a.y+u.y*16};return `M${a.x} ${a.y}L${p.x} ${p.y}${u.x?'H'+cursor.x+'V'+cursor.y:'V'+cursor.y+'H'+cursor.x}`});
 readonly nodeNames=computed(()=>Array.from(new Set(this.nodes().values())).filter(node=>node!=='0'));
 readonly voltagePlot=computed(()=>{const result=this.circuit();return result?.ok?circuitPlot(result,this.project().instruments.probe,false,this.project().instruments.cursor):null});
 readonly phasePlot=computed(()=>{const result=this.circuit();return result?.ok&&result.rows.some(row=>row.frequencyHz!==undefined)?circuitPlot(result,this.project().instruments.probe,true):null});
 readonly radioQuadrature=signal(false);
 readonly communicationPlot=computed(()=>this.radio()?.ok?radioPlot(this.radio()!,this.radioQuadrature()):null);
 readonly spectrumPlot=computed(()=>this.radio()?.ok?spectrum(this.radio()!):null);
 readonly linePlot=computed(()=>this.radio()?.ok?plotSeries([{name:'Coded line',color:'#136ce0',points:(this.radio()?.lineWaveform||[]).map(row=>({x:row.t,y:row.value}))}],'Time / s','Encoded ±1 chips'):null);
 readonly gateKinds=GATE_KINDS;readonly digitalSettings=computed(()=>this.project().digital||digitalTemplate());readonly digital=signal<DigitalResult|null>(null);readonly digitalSource=signal<Project|null>(null);readonly digitalAnalysis=signal<Record<string,unknown>|null>(null);
 readonly digitalCursor=signal(0);readonly selectedGate=signal('q0');readonly digitalDrawing=computed(()=>digitalLayout(this.digitalSettings()));readonly digitalGate=computed(()=>this.digitalSettings().gates.find(gate=>gate.id===this.selectedGate()));
 readonly digitalInputs=computed(()=>Object.entries(this.digitalSettings().inputs).map(([id,value])=>({id,value,pattern:this.digitalSettings().patterns[id]||''})));readonly digitalWires=computed(()=>['clock',...Object.keys(this.digitalSettings().inputs),...this.digitalSettings().gates.map(gate=>gate.id)]);
 readonly digitalRows=computed(()=>{const result=this.digital();if(!result?.ok)return [];const rows=result.trace,wires=result.wires.slice(0,16),maximum=Math.max(1,rows.length-1);return wires.map((wire,index)=>{const top=23+index*28;let path='';rows.forEach((row,tick)=>{const x=106+tick/maximum*660,y=top+(row.values[wire]?0:14);if(tick===0)path=`M${x} ${y}`;else path+=`H${x}V${y}`});return {wire,path,y:top+11}})});
 readonly digitalValues=computed(()=>{const result=this.digital();return result?.trace[Math.max(0,Math.min(result.trace.length-1,this.digitalCursor()))]?.values||{}});
 readonly scanPlot=computed(()=>{const sweep=this.radio()?.sweep;if(!sweep?.cells.length)return null;return plotSeries(sweep.secondaryValues.map((value,row)=>({name:sweep.secondaryAxis?`${sweep.secondaryAxis} ${value}`:'BER',color:['#176bd2','#0ca5a6','#775bc7','#c77e21','#687caf','#ab5a98','#46856b'][row],points:sweep.cells.filter(cell=>cell.row===row).map(cell=>({x:cell.x,y:cell.ber}))})),sweep.axis,'Empirical BER')});
 readonly measurementNode=signal('out');readonly measurementReference=signal('n1');
 readonly measuredNodeNames=computed(()=>Object.keys(this.circuit()?.rows?.[0]?.values||{}));
 readonly measurementProbe=computed(()=>{const nodes=this.measuredNodeNames(),selected=this.measurementNode();return nodes.includes(selected)?selected:nodes.find(node=>node!=='0')||nodes[0]||''});
 readonly measurementRef=computed(()=>{const nodes=this.measuredNodeNames(),selected=this.measurementReference();return nodes.includes(selected)?selected:nodes.find(node=>node!=='0'&&node!==this.measurementProbe())||nodes[0]||''});
 readonly measurements=computed(()=>{const result=this.circuit(),source=this.circuitSource();return result&&source?circuitMeasurements(result,source,this.measurementProbe(),this.measurementRef()):null});
 readonly rfFields:{key:keyof RFLinkSettings;label:string}[]=[{key:'frequencyMHz',label:'Carrier / MHz'},{key:'distanceKm',label:'Distance / km'},{key:'txPowerDbm',label:'TX power / dBm'},{key:'txGainDbi',label:'TX gain / dBi'},{key:'rxGainDbi',label:'RX gain / dBi'},{key:'lossDb',label:'Other loss / dB'},{key:'bandwidthHz',label:'Noise BW / Hz'},{key:'bitRateBps',label:'Bit rate / bit·s⁻¹'},{key:'noiseFigureDb',label:'Noise figure / dB'},{key:'requiredEbN0Db',label:'Required Eb/N₀ / dB'}];
 readonly rfRanges=RF_RANGES;readonly budget=computed(()=>this.radio()?.ok?this.radio()?.linkBudget:null);
 readonly budgetReadings=computed(()=>{const result=this.budget();return result?[{label:'Free-space path loss',value:result.freeSpaceLossDb,unit:'dB'},{label:'EIRP',value:result.eirpDbm,unit:'dBm'},{label:'Received power',value:result.receivedDbm,unit:'dBm'},{label:'Receiver noise',value:result.noiseDbm,unit:'dBm'},{label:'SNR',value:result.snrDb,unit:'dB'},{label:'Eb/N₀',value:result.ebN0Db,unit:'dB'},{label:'Shannon capacity bound',value:result.capacityBps,unit:'bit/s'},{label:'Link margin',value:result.marginDb,unit:'dB'},{label:'First Fresnel radius / midpoint',value:result.fresnelRadiusM,unit:'m'}]:[]});
 readonly probeRow=computed<CircuitRow|undefined>(()=>{const rows=this.circuit()?.rows||[];return rows[Math.max(0,Math.min(rows.length-1,this.project().instruments.cursor))]});
 readonly dcReadings=computed(()=>{const row=this.probeRow();return row?Object.entries(row.values).map(([node,value])=>({node,value:typeof value==='number'?value:value.magnitude})):[]});
 readonly cursorPosition=computed(()=>this.voltagePlot()?.cursor?.x??32);
 readonly view=signal({x:0,y:0,width:1100,height:560});readonly viewBox=computed(()=>{const v=this.view();return `${v.x} ${v.y} ${v.width} ${v.height}`});
 readonly undoCount=signal(0);readonly redoCount=signal(0);readonly activeTab=signal('network');readonly showNetlist=signal(false);readonly showRaw=signal(false);
 readonly networkKinds=NETWORK_KINDS;readonly networkResult=signal<NetworkResult|null>(null);readonly networkSelected=signal('');readonly networkLead=signal<string|null>(null);readonly networkLinkMode=signal(false);readonly networkArmed=signal<NetworkKind|null>(null);
 readonly hoveredNode=signal('');readonly hoveredLink=signal('');readonly selectedFlow=signal('');readonly hoveredFlow=signal('');
 readonly activeRoute=computed(()=>{const id=this.hoveredFlow()||this.selectedFlow();return this.networkResult()?.routes.find(route=>route.flow===id)});
 readonly activeRouteLinks=computed(()=>new Set(this.activeRoute()?.links||[]));
 readonly currentActivity=computed(()=>{const map=new Map<string,{tx:number;rx:number;drop:number}>(),time=this.simulationTime();for(const event of this.networkResult()?.events||[]){if(event.tMs>time)continue;const id=event.kind==='send'?event.from:event.to;if(!id)continue;const count=map.get(id)||{tx:0,rx:0,drop:0};if(event.kind==='send')count.tx++;else if(event.kind==='arrive')count.rx++;else if(event.kind==='drop')count.drop++;map.set(id,count)}return map});
 readonly recentActivity=computed(()=>{const set=new Set<string>(),time=this.simulationTime();for(const event of this.networkResult()?.events||[])if(event.tMs<=time&&event.tMs>time-180){if(event.kind==='send')set.add(event.from);if(event.kind==='arrive'||event.kind==='delivered')set.add(event.to)}return set});
 readonly networkNode=computed(()=>this.project().network.nodes.find(node=>node.id===this.networkSelected()));readonly networkLink=computed(()=>this.project().network.links.find(link=>link.id===this.networkSelected()));
 readonly simulationTime=signal(0);readonly playing=signal(false);readonly playbackSpeed=signal(1);readonly flights=signal<Flight[]>([]);
 readonly playbackDuration=computed(()=>this.networkSource()?.network.durationMs??this.project().network.durationMs);
 readonly visiblePackets=computed(()=>{const t=this.simulationTime();return this.flights().filter(p=>p.start<=t&&p.end>t).slice(0,128)});
 readonly currentDrops=computed(()=>{const t=this.simulationTime();return (this.networkResult()?.events||[]).filter(e=>e.kind==='drop'&&e.tMs<=t&&e.tMs>t-400).slice(-20)});
 readonly deliveredNow=computed(()=>{const t=this.simulationTime();return(this.networkResult()?.events||[]).filter(e=>e.kind==='delivered'&&e.tMs<=t).length});
 readonly recentEvents=computed(()=>{const t=this.simulationTime();return(this.networkResult()?.events||[]).filter(e=>e.tMs<=t).slice(-12).reverse()});
 readonly auditPacket=signal('');readonly auditLink=signal('');
 readonly networkInspection=computed(()=>{const result=this.networkResult(),source=this.networkSource();return result?.ok&&source?networkAudit(result,source.network,this.auditPacket()||undefined):null});
 readonly inspectedLink=computed(()=>{const links=this.networkInspection()?.links||[];return links.find(link=>link.key===this.auditLink())||links[0]||null});
 readonly latencyPlot=computed(()=>{const flows=this.networkInspection()?.flows||[],flow=flows.find(item=>item.id===this.selectedFlow())||flows[0];return flow?.latencySeries.length?plotSeries([{name:flow.id,points:flow.latencySeries.map(point=>({x:point.tMs,y:point.latencyMs})),color:'#126de0'}],'Injection time / ms','Delivered latency / ms'):null});
 readonly queuePlot=computed(()=>{const link=this.inspectedLink();return link?.queueSeries.length?plotSeries([{name:link.from+' → '+link.to,points:link.queueSeries.map(point=>({x:point.tMs,y:point.queueMs})),color:'#168b9b'}],'Serialization start / ms','Reconstructed queue wait / ms'):null});
 private computer=new LocalComputer();private undoStack:Project[]=[];private redoStack:Project[]=[];private dragging?:{id:string;dx:number;dy:number};private resizeObserver?:ResizeObserver;
 private polling?:ReturnType<typeof setTimeout>;private requestAbort?:AbortController;private number=10;private jobGeneration=0;private jobDeadline=0;private readonly pollLifetime=7*86400000;
 private localGeneration=0;private disposed=false;
 private heightFrame=0;private publishedHeight=0;
 private publishHeight=()=>{if(this.heightFrame)return;this.heightFrame=requestAnimationFrame(()=>{this.heightFrame=0;const bench=document.querySelector<HTMLElement>('.bench');if(!bench)return;const height=Math.ceil(Math.max(bench.getBoundingClientRect().height,bench.scrollHeight));if(height===this.publishedHeight)return;this.publishedHeight=height;parent.postMessage({type:'OCV_SIGNALS_HEIGHT',height},location.origin)})};
 private sharedContext=()=>{const p=this.serverProject(),job=this.job();parent.postMessage({type:'OCV_SHARED_CONTEXT',domain:'signals',project:p?{...p,domain:'signals'}:null,projectData:this.project(),job:job?.ticket?{id:job.id,ticket:job.ticket}:null},location.origin)};
 private heightRequest=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==parent)return;const d=event.data;if(d?.type==='OCV_SIGNALS_MEASURE'){this.publishedHeight=0;this.publishHeight();this.sharedContext()}else if(d?.type==='OCV_SHARED_MEASURE')this.sharedContext();else if(['OCV_SHARED_REFRESH','OCV_SHARED_OPEN_BRANCH','OCV_SHARED_APPLY_PROJECT'].includes(d?.type)){const p=d.project||this.serverProject();if(p&&typeof p.id==='string'&&/^[a-f0-9-]{36}$/.test(p.id)&&typeof p.ticket==='string'&&/^[a-f0-9]{64}$/.test(p.ticket)){this.serverProject.set(p);void this.reopenProject()}}};
 private networkDragging?:{id:string;dx:number;dy:number};private animation=0;private lastAnimation=0;private frameCarry=0;
 private activeNative?:NativeLaunch;private queuedNative?:NativeLaunch;
 private presentationGeneration=0;private nativeSequence=0;private wantedNative:Partial<Record<RunKind,number>>={};
 private keyListener=(event:KeyboardEvent)=>{
  if((event.target as HTMLElement)?.matches('input,textarea,select'))return;
  if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?this.redo():this.undo();}
  else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();this.activeTab()==='network'?this.removeNetwork():this.remove();}
  else if(event.key.toLowerCase()==='r')this.rotate(event.shiftKey?-1:1);else if(event.key==='Escape'){this.armed.set(null);this.lead.set(null);this.selected.set('');this.hoverTerminal.set(null);}
 };
 private pointerMove=(event:PointerEvent)=>{if(this.networkDragging){const point=this.networkPoint(event);if(!point)return;const drag=this.networkDragging;this.mutate(project=>{const node=project.network.nodes.find(n=>n.id===drag.id);if(node){node.x=this.snap(point.x-drag.dx,70,1030);node.y=this.snap(point.y-drag.dy,70,560)}});return}if(!this.dragging)return;const point=this.toPoint(event);if(!point)return;const drag=this.dragging;this.mutate(project=>{const p=project.drawing.components.find(p=>p.id===drag.id);if(p){p.x=this.snap(point.x-drag.dx,70,1030);p.y=this.snap(point.y-drag.dy,70,490)}})};
 private pointerUp=()=>{this.dragging=undefined;this.networkDragging=undefined};
 ngAfterViewInit(){
  document.addEventListener('keydown',this.keyListener);document.addEventListener('pointermove',this.pointerMove);document.addEventListener('pointerup',this.pointerUp);
  this.resizeObserver=new ResizeObserver(this.publishHeight);this.resizeObserver.observe(document.querySelector('.bench')!);document.addEventListener('load',this.publishHeight,true);window.addEventListener('message',this.heightRequest);this.publishHeight();
  try{const saved=localStorage.getItem('ocv.signals.project-ticket.v1');if(saved){const item=JSON.parse(saved);if(typeof item.id==='string'&&typeof item.ticket==='string')this.serverProject.set(item)}}catch{}
  void this.initialExamples();
 }
 ngOnDestroy(){this.disposed=true;++this.localGeneration;++this.jobGeneration;this.queuedNative=undefined;this.computer.cancel();this.requestAbort?.abort();clearTimeout(this.polling);cancelAnimationFrame(this.animation);cancelAnimationFrame(this.heightFrame);this.resizeObserver?.disconnect();document.removeEventListener('load',this.publishHeight,true);window.removeEventListener('message',this.heightRequest);document.removeEventListener('keydown',this.keyListener);document.removeEventListener('pointermove',this.pointerMove);document.removeEventListener('pointerup',this.pointerUp)}
 private async initialExamples(){const generation=this.localGeneration+1,presentation=this.presentationGeneration+1;await this.preview('network');if(!this.disposed&&this.localGeneration===generation&&this.presentationGeneration===presentation)await this.preview('communications')}
 private snap(value:number,min:number,max:number){return Math.max(min,Math.min(max,Math.round(value/10)*10))}
 private nextId(prefix:string){const p=this.project(),ids=new Set([...p.drawing.components,...p.drawing.wires,...p.network.nodes,...p.network.links,...p.network.flows].map(item=>item.id));let id;do{id=`${prefix}${++this.number}`}while(ids.has(id));return id}
 private invalidateAnalysis(clearCache=true){++this.presentationGeneration;this.analysisCheck.set(null);if(clearCache){this.nativeResults.set({});this.wantedNative={}}this.frameCarry=0}
 private mutate(action:(project:Project)=>void,changesInput=true){const next=clone(this.project());action(next);this.project.set(next);if(changesInput)this.invalidateAnalysis()}
 private inputIdentity(project:Project){const snapshot=clone(project);snapshot.instruments.cursor=0;return JSON.stringify(snapshot)}
 private remember(){this.undoStack.push(clone(this.project()));if(this.undoStack.length>80)this.undoStack.shift();this.redoStack=[];this.updateHistory()}
 private updateHistory(){this.undoCount.set(this.undoStack.length);this.redoCount.set(this.redoStack.length)}
 undo(){const prior=this.undoStack.pop();if(!prior)return;this.redoStack.push(clone(this.project()));this.project.set(prior);this.invalidateAnalysis();this.updateHistory();this.message.set('Undo')}
 redo(){const next=this.redoStack.pop();if(!next)return;this.undoStack.push(clone(this.project()));this.project.set(next);this.invalidateAnalysis();this.updateHistory();this.message.set('Redo')}
 setTemplate(name:string){this.remember();this.mutate(project=>{project.drawing=template(name);project.analysis.kind=['Divider','Potentiometer','VCVS'].includes(name)?'dc':name==='RLC'?'ac':'transient';project.analysis.durationS=name==='RL'?.00005:.01;project.analysis.stepS=name==='RL'?.0000002:.000025;project.instruments.probe='out'});this.activeTab.set('schematic');this.selected.set(this.project().drawing.components.some(part=>part.id==='R1')?'R1':this.project().drawing.components.find(part=>part.kind==='POT')?.id||this.project().drawing.components.find(part=>part.kind!=='GND')?.id||'');this.lead.set(null);this.circuit.set(null);this.message.set(`${name} loaded`)}
 clearDrawing(){if(!confirm('清空画板？'))return;this.remember();this.mutate(project=>project.drawing={components:[],wires:[]});this.circuit.set(null);this.selected.set('')}
 rename(value:string){this.mutate(project=>project.name=value.slice(0,80))}
 arm(kind:PartKind){this.activeTab.set('schematic');this.armed.set(this.armed()===kind?null:kind);this.lead.set(null);this.message.set(`Place ${kind} · click drawing`)}
 boardClick(event:MouseEvent){
  if(!(event.target as SVGElement).hasAttribute('data-board'))return;
  const kind=this.armed(),point=this.toPoint(event);if(!kind||!point){this.selected.set('');return}
  if(this.project().drawing.components.length>=64){this.message.set('64-component editor limit');return}
  this.remember();const id=this.nextId(kind==='GND'?'G':kind),definition=PARTS.find(p=>p.kind===kind)!;
  this.mutate(project=>project.drawing.components.push({id,kind,x:this.snap(point.x,70,1030),y:this.snap(point.y,70,490),rotation:0,value:definition.value,...(kind==='S'?{closed:true}:{}),...(kind==='POT'?{wiper:.5}:{}),...(kind==='SPDT'?{throw:'b' as const}:{})}));this.selected.set(id);this.armed.set(null);this.message.set(id);
 }
 private toPoint(event:MouseEvent|PointerEvent):{x:number;y:number}|null {const svg=this.schematic?.nativeElement,matrix=svg?.getScreenCTM();if(!svg||!matrix)return null;const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const result=p.matrixTransform(matrix.inverse());return {x:result.x,y:result.y}}
 beginDrag(event:PointerEvent,part:Part){if((event.target as Element).closest('[data-pin]'))return;this.activeTab.set('schematic');event.stopPropagation();event.preventDefault();this.selected.set(part.id);const point=this.toPoint(event);if(!point)return;this.remember();this.dragging={id:part.id,dx:point.x-part.x,dy:point.y-part.y}}
 selectComponent(id:string){if(id&&!this.project().drawing.components.some(part=>part.id===id))return;this.activeTab.set('schematic');this.selected.set(id);this.armed.set(null);this.lead.set(null)}
 selectWire(event:MouseEvent,wire:Wire){event.stopPropagation();this.activeTab.set('schematic');this.selected.set(wire.id);this.message.set('Wire selected · Delete removes')}
 pinClick(event:MouseEvent,part:Part,pin:Pin){
  event.stopPropagation();this.activeTab.set('schematic');this.armed.set(null);const terminal={component:part.id,pin},start=this.lead();
  if(!start){this.lead.set(terminal);this.message.set('Select another terminal');return}
  this.lead.set(null);if(terminalKey(start)===terminalKey(terminal))return;
  if(this.project().drawing.wires.length>=256){this.message.set('256-wire editor limit');return}
  const exists=this.project().drawing.wires.some(w=>(terminalKey(w.from)===terminalKey(start)&&terminalKey(w.to)===terminalKey(terminal))||(terminalKey(w.to)===terminalKey(start)&&terminalKey(w.from)===terminalKey(terminal)));
  if(exists)return;this.remember();const id=this.nextId('w');this.mutate(project=>project.drawing.wires.push({id,from:start,to:terminal}));this.message.set('Connected')
 }
 private pinDirection(part:Part,pin:Pin){const local=part.kind==='GND'?{x:0,y:-1}:pin==='a'?{x:-1,y:0}:pin==='b'?{x:1,y:0}:{x:0,y:1},angle=part.rotation*Math.PI/180,c=Math.round(Math.cos(angle)),s=Math.round(Math.sin(angle));return {x:local.x*c-local.y*s,y:local.x*s+local.y*c}}
 wirePath(wire:Wire){const parts=this.project().drawing.components,from=parts.find(p=>p.id===wire.from.component),to=parts.find(p=>p.id===wire.to.component);if(!from||!to)return '';const a=endpoint(from,wire.from.pin),b=endpoint(to,wire.to.pin),u=this.pinDirection(from,wire.from.pin),v=this.pinDirection(to,wire.to.pin),p={x:a.x+u.x*16,y:a.y+u.y*16},q={x:b.x+v.x*16,y:b.y+v.y*16};let between;if(u.x&&v.x){const x=Math.round((p.x+q.x)/20)*10;between=`H${x} V${q.y} H${q.x}`}else if(u.y&&v.y){const y=Math.round((p.y+q.y)/20)*10;between=`V${y} H${q.x} V${q.y}`}else if(u.x){between=`H${q.x} V${q.y}`}else{between=`V${q.y} H${q.x}`}return `M${a.x},${a.y} L${p.x},${p.y} ${between} L${b.x},${b.y}`}
 localTerminal(part:Part,pin:Pin){return endpoint({...part,x:0,y:0,rotation:0},pin)}
 terminalAnnotation(part:Part,pin:Pin){const p=endpoint(part,pin),u=this.pinDirection(part,pin);return {x:p.x+u.x*12,y:p.y+u.y*12+3,anchor:u.x<0?'end':u.x>0?'start':'middle'}}
 selectionHeight(part:Part){return ['E','G'].includes(part.kind)?111:['POT','SPDT'].includes(part.kind)?95:56}
 boardHover(event:PointerEvent){if(!this.lead())return;const point=this.toPoint(event);if(point)this.wirePointer.set({x:this.snap(point.x,0,1100),y:this.snap(point.y,0,560)})}
 pinHover(part:Part,pin:Pin,inside:boolean){this.hoverTerminal.set(inside?{component:part.id,pin}:null);if(inside)this.wirePointer.set(endpoint(part,pin))}
 potentiometerArm(part:Part){const x=((part.wiper??.5)-.5)*52;return `M0 48V32H${x}V12M${x-5} 18L${x} 12L${x+5} 18`}
 partTransform(part:Part){return `translate(${part.x} ${part.y}) rotate(${part.rotation})`}
 labelTransform(part:Part){const vertical=part.rotation===90||part.rotation===270||part.kind==='GND';return vertical?`translate(${part.x+34} ${part.y-8})`:`translate(${part.x} ${part.y-26})`}
 labelAnchor(part:Part){return part.rotation===90||part.rotation===270||part.kind==='GND'?'start':'middle'}
 valueLabelY(part:Part){return part.rotation===90||part.rotation===270||part.kind==='GND'?19:['E','G'].includes(part.kind)?130:['POT','SPDT'].includes(part.kind)?103:53}
 partUnit(part:Part){return PARTS.find(p=>p.kind===part.kind)?.unit||''}
 quantity(value:number,unit:string){const valueText=engineering(value),match=valueText.match(/^([-+\d.e]+)([GMkmunµp])$/);return match?`${match[1]} ${match[2]}${unit}`:`${valueText} ${unit}`}
 cursorLabel(label:string|undefined){return (label||'').replace(/([-+\d.e]+)([GMkmunµp]) (s|V|Hz)/g,'$1 $2$3')}
 probeAxisQuantity(){const row=this.probeRow();return row?.frequencyHz!==undefined?this.quantity(row.frequencyHz,'Hz'):row?.t!==undefined?this.quantity(row.t,'s'):'DC'}
 node(part:Part,pin:Pin){return this.nodes().get(`${part.id}:${pin}`)||'—'}
 nodesEntries(){return Object.fromEntries(this.nodes())}
 activePin(part:Part,pin:Pin){const lead=this.lead();return !!lead&&lead.component===part.id&&lead.pin===pin}
 pinProbe(event:MouseEvent,part:Part,pin:Pin){event.stopPropagation();const name=this.node(part,pin);if(name==='—')return;this.probe(name);this.lead.set(null);this.message.set(`Probe ${name}`)}
 pinValue(part:Part,pin:Pin){if(!this.circuit()?.ok)return '';const node=this.measuredTerminals().get(`${part.id}:${pin}`)||'',value=this.probeRow()?.values[node];return value===undefined?'':typeof value==='number'?this.quantity(value,'V'):`${this.quantity(value.magnitude,'V')} ∠ ${value.phaseDeg.toFixed(1)}°`}
 wireNode(wire:Wire){const part=this.project().drawing.components.find(p=>p.id===wire.from.component);return part?this.node(part,wire.from.pin):'—'}
 rotate(direction=1){const id=this.selectedPart()?.id;if(!id)return;this.remember();this.mutate(project=>{const p=project.drawing.components.find(p=>p.id===id)!;p.rotation=(p.rotation+direction*90+360)%360});this.message.set(`${id} rotated ${direction<0?'left':'right'} · ${this.selectedPart()?.rotation}°`)}
 duplicate(){const part=this.selectedPart();if(!part||this.project().drawing.components.length>=64)return;this.remember();const id=this.nextId(part.kind==='GND'?'G':part.kind);this.mutate(project=>project.drawing.components.push({...part,id,x:this.snap(part.x+90,70,1030),y:this.snap(part.y+70,70,490)}));this.selected.set(id)}
 remove(){const id=this.selected();if(!id)return;this.remember();this.mutate(project=>{project.drawing.components=project.drawing.components.filter(p=>p.id!==id);project.drawing.wires=project.drawing.wires.filter(w=>w.id!==id&&w.from.component!==id&&w.to.component!==id)});this.selected.set('')}
 partValue(value:number){const part=this.selectedPart();if(!part||['GND','AM'].includes(part.kind))return;if(!Number.isFinite(value)||Math.abs(value)>1e12||(['R','C','L','S','POT','SPDT','VM'].includes(part.kind)&&value<1e-18)){this.message.set('Value is outside the component model range.');return}this.remember();this.mutate(project=>project.drawing.components.find(p=>p.id===part.id)!.value=value)}
 partPrefix(factor:number){const part=this.selectedPart();if(part&&this.engineeringPrefixes.some(prefix=>prefix.factor===factor))this.prefixOverride.set({part:part.id,factor})}
 scaledPartValue(value:number){this.partValue(value*this.selectedValueFactor())}
 partParameter(key:'phaseDeg'|'initial'|'wiper',value:number){const part=this.selectedPart();if(!part||!Number.isFinite(value))return;const limits=key==='phaseDeg'?360:1e9;if(key==='wiper'?(value<.01||value>.99):Math.abs(value)>limits){this.message.set(`Invalid ${key} parameter`);return}if(key==='phaseDeg'&&!['V','I'].includes(part.kind)||key==='initial'&&!['C','L'].includes(part.kind)||key==='wiper'&&part.kind!=='POT')return;this.remember();this.mutate(project=>project.drawing.components.find(p=>p.id===part.id)![key]=value)}
 switchThrow(value:'b'|'w'){const part=this.selectedPart();if(part?.kind!=='SPDT'||!['b','w'].includes(value))return;this.remember();this.mutate(project=>project.drawing.components.find(p=>p.id===part.id)!.throw=value)}
 componentParameterLabel(part:Part){return part.kind==='VM'?'Input resistance':part.kind==='POT'?'Total resistance':['S','SPDT'].includes(part.kind)?'On resistance':part.kind==='E'?'Voltage gain':part.kind==='G'?'Transconductance':'Value'}
 meterReading(part:Part){const row=this.probeRow(),source=this.circuitSource();if(!this.circuit()?.ok||!row||!source?.drawing.components.some(item=>item.id===part.id&&item.kind===part.kind))return 'Unavailable';if(part.kind==='AM'){const value=row.branches[part.id];return typeof value==='number'?this.quantity(value,'A'):value?`${this.quantity(value.magnitude,'A')} ∠ ${value.phaseDeg.toFixed(1)}°`:'Unavailable'}const map=this.measuredTerminals(),a=row.values[map.get(`${part.id}:a`)||''],b=row.values[map.get(`${part.id}:b`)||''];if(a===undefined||b===undefined)return 'Unavailable';const re=(typeof a==='number'?a:a.re)-(typeof b==='number'?b:b.re),im=(typeof a==='number'?0:a.im)-(typeof b==='number'?0:b.im);return typeof a==='number'&&typeof b==='number'?this.quantity(re,'V'):`${this.quantity(Math.hypot(re,im),'V')} ∠ ${(Math.atan2(im,re)*180/Math.PI).toFixed(1)}°`}
 switchState(value:boolean){const id=this.selectedPart()?.id;if(!id)return;this.remember();this.mutate(project=>project.drawing.components.find(p=>p.id===id)!.closed=value)}
 setting<K extends keyof AnalysisSettings>(key:K,value:AnalysisSettings[K]){this.mutate(project=>project.analysis[key]=value)}
 radioSetting<K extends keyof RadioSettings>(key:K,value:RadioSettings[K]){this.mutate(project=>project.communication[key]=value)}
 radioPreset(name:string){this.remember();this.mutate(project=>{const settings=project.communication;settings.crc=name==='BPSK'?'CRC-8':'CRC-16';settings.modulation=name==='BFSK'?'BFSK':name==='QPSK'?'QPSK':'BPSK';settings.lineCode=name==='Manchester'?'Manchester':'NRZ';settings.ebN0Db=name==='BFSK'?10:6;settings.frequencyOffsetHz=0;settings.timingOffsetSymbols=0;settings.noiseless=false;delete settings.sweep});this.radioQuadrature.set(false);this.message.set('Loaded')}
 radioSweep(enabled:boolean){this.mutate(project=>{if(enabled)project.communication.sweep={axis:'ebN0Db',values:[-2,0,2,4,6,8],secondaryAxis:'timingOffsetSymbols',secondaryValues:[-.25,0,.25]};else delete project.communication.sweep})}
 sweepPreset(name:string){const settings=this.project().communication,limit=Math.min(100,settings.sampleRateHz/settings.samplesPerSymbol*.25);if(!Number.isFinite(limit)||limit<=0){this.message.set('Set a valid sample/symbol rate first');return}this.mutate(project=>project.communication.sweep=name==='Carrier / timing'?{axis:'frequencyOffsetHz',values:[-limit,-limit/2,0,limit/2,limit],secondaryAxis:'timingOffsetSymbols',secondaryValues:[-.25,0,.25]}:name==='SNR'?{axis:'ebN0Db',values:[-2,0,2,4,6,8,10]}:{axis:'ebN0Db',values:[-2,0,2,4,6,8],secondaryAxis:'timingOffsetSymbols',secondaryValues:[-.25,0,.25]})}
 sweepValues(secondary:boolean,text:string){const values=text.split(',').map(part=>Number(part.trim()));if(values.length<1||values.length>7||!values.every(Number.isFinite)||values.some((value,index)=>index>0&&value<=values[index-1])){this.message.set('Scan: 1–7 increasing numbers per axis');return}this.mutate(project=>{const sweep=project.communication.sweep;if(sweep){if(secondary)sweep.secondaryValues=values;else sweep.values=values}})}
 scanColor(ber:number){const value=Math.max(0,Math.min(1,Math.sqrt(ber)));return `hsl(${214-value*176} 80% ${93-value*44}%)`}
 waterfallColor(power:number){const report=this.radio()?.waterfall,span=Math.max(1,(report?.maximumDb??0)-(report?.minimumDb??-140)),value=Math.max(0,Math.min(1,(power-(report?.minimumDb??-140))/span));return `hsl(${218-value*46} ${30+value*57}% ${97-value*66}%)`}
 digitalPreset(name:string){this.remember();this.mutate(project=>project.digital=digitalTemplate(name));this.selectedGate.set(this.digitalSettings().gates[0]?.id||'');this.digitalCursor.set(0);this.message.set('Loaded')}
 digitalSetting<K extends keyof DigitalSettings>(key:K,value:DigitalSettings[K]){this.mutate(project=>{project.digital={...this.digitalSettings(),[key]:value}})}
 digitalPattern(id:string,value:string){if(value&&!/^[01]{1,4096}$/.test(value)){this.message.set('Pattern: binary digits');return}this.mutate(project=>{const settings=project.digital||digitalTemplate();if(value)settings.patterns[id]=value;else delete settings.patterns[id];project.digital=settings})}
 digitalInput(id:string,value:boolean){this.mutate(project=>{const settings=project.digital||digitalTemplate();settings.inputs[id]=value;project.digital=settings})}
 addDigitalInput(){const settings=this.digitalSettings();if(Object.keys(settings.inputs).length>=16){this.message.set('Editor: 16 sources');return}let number=1;while(this.digitalWires().includes('in'+number))number++;this.mutate(project=>{const settings=project.digital||digitalTemplate();settings.inputs['in'+number]=false;project.digital=settings})}
 addGate(kind:GateKind){if(this.digitalSettings().gates.length>=24){this.message.set('Editor: 24 gates');return}let number=1;while(this.digitalWires().includes('g'+number))number++;const id='g'+number,source=Object.keys(this.digitalSettings().inputs)[0]||'clock';this.remember();this.mutate(project=>{const settings=project.digital||digitalTemplate();settings.gates.push({id,type:kind,inputs:Array(['NOT','BUFFER','DFF'].includes(kind)?1:2).fill(source),...(['DFF','JKFF'].includes(kind)?{initial:false}:{})});project.digital=settings});this.selectedGate.set(id)}
 gateType(kind:GateKind){const id=this.selectedGate();this.remember();this.mutate(project=>{const gate=project.digital?.gates.find(gate=>gate.id===id);if(!gate)return;gate.type=kind;const count=['NOT','BUFFER','DFF'].includes(kind)?1:2;gate.inputs=Array.from({length:count},(_,index)=>gate.inputs[index]||Object.keys(project.digital!.inputs)[0]||'clock');if(['DFF','JKFF'].includes(kind))gate.initial=false;else delete gate.initial})}
 gateInput(index:number,wire:string){this.mutate(project=>{const gate=project.digital?.gates.find(gate=>gate.id===this.selectedGate());if(gate&&this.digitalWires().includes(wire))gate.inputs[index]=wire})}
 gateInitial(value:boolean){this.mutate(project=>{const gate=project.digital?.gates.find(gate=>gate.id===this.selectedGate());if(gate&&['DFF','JKFF'].includes(gate.type))gate.initial=value})}
 removeGate(){const id=this.selectedGate();if(this.digitalSettings().gates.some(gate=>gate.id!==id&&gate.inputs.includes(id))){this.message.set('Reconnect dependent pins before deleting');return}this.remember();this.mutate(project=>{if(project.digital)project.digital.gates=project.digital.gates.filter(gate=>gate.id!==id)});this.selectedGate.set(this.digitalSettings().gates[0]?.id||'')}
 logicCursor(event:MouseEvent){const result=this.digital();if(!result?.ok)return;const rect=(event.currentTarget as SVGElement).getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*800;this.digitalCursor.set(Math.max(0,Math.min(result.trace.length-1,Math.round((x-106)/660*(result.trace.length-1)))))}
 exportRadioTable(kind:'waterfall'|'scan'){const result=this.radio();if(!result?.ok)return;const quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const metadata=`# engine=${result.engine};version=${result.version};seed=${result.summary['seed']};fs_Hz=${result.summary['sampleRateHz']};model=${result.summary['modulation']}/${result.summary['lineCode']}`;const rows:unknown[][]=kind==='waterfall'?[['window','frequency_Hz','time_s','Hann_DFT_power_dB'],...(result.waterfall?.rows||[]).map(row=>[row.frame,row.frequencyHz,row.t,row.powerDb])]:[['row','column',result.sweep?.axis||'x',result.sweep?.secondaryAxis||'secondary','errors','payload_bits','BER','Wilson95_lower','Wilson95_upper','CRC_pass'],...(result.sweep?.cells||[]).map(cell=>[cell.row,cell.column,cell.x,cell.y,cell.bitErrors,cell.payloadLength,cell.ber,cell.interval.lower,cell.interval.upper,cell.crcValid])];download(`signals-${kind}.csv`,[metadata,...rows.map(row=>row.map(quote).join(','))].join('\r\n'),'text/csv;charset=utf-8')}
 exportVisual(id:string){const element=document.getElementById(id);if(!(element instanceof SVGSVGElement))return;const copy=element.cloneNode(true) as SVGSVGElement;copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width',element.viewBox.baseVal.width.toString());copy.setAttribute('height',element.viewBox.baseVal.height.toString());const metadata=document.createElementNS('http://www.w3.org/2000/svg','metadata');metadata.textContent=JSON.stringify({schema:'ocv.signals-figure/1',kind:id,project:id.startsWith('logic')?this.digitalSource():this.radioSource(),engine:id.startsWith('logic')?this.digital()?.engine:this.radio()?.engine,version:id.startsWith('logic')?this.digital()?.version:this.radio()?.version,model:id.startsWith('logic')?this.digital()?.summary:this.radio()?.summary,units:id==='spectrum-waterfall'?{x:'Hz',y:'s',color:'Hann DFT dB; not PSD'}:{x:'ticks or scan input',y:'boolean or finite-sample BER'},dataDerived:true});copy.prepend(metadata);const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font:10px monospace;fill:#345d8b}.logic-wire,.logic-trace,.trace{fill:none;stroke:#176bce;stroke-width:1.5}.plot-grid{fill:none;stroke:#d4e3f4}.logic-gate{fill:white;stroke:#6b9ccc}.logic-node.on .logic-gate{fill:#e5f1ff}.ideal-point{fill:white;stroke:#557faf}.plot-minor-grid{fill:none;stroke:#eaf1f8}.plot-zero{fill:none;stroke:#9ab9df}';copy.prepend(style);download(`signals-${id}.svg`,new XMLSerializer().serializeToString(copy),'image/svg+xml')}
 exportReplay(kind:'communications'|'digital'){const result=kind==='digital'?this.digital():this.radio(),project=kind==='digital'?this.digitalSource():this.radioSource();if(!result?.ok||!project)return;download(`signals-${kind}-replay.json`,JSON.stringify({schema:'ocv.signals-replay/1',kind,project,request:this.request(kind,project),result,sampling:result.summary,modelVersion:result.version,units:kind==='digital'?{time:'s',wire:'boolean'}:{time:'s',amplitude:'normalized',frequency:'Hz'},view:{cursor:kind==='digital'?this.digitalCursor():0,quadrature:this.radioQuadrature()}},null,2),'application/json')}
 rfEnabled(enabled:boolean){this.remember();this.mutate(project=>{if(enabled)project.communication.rf={...DEFAULT_RF_LINK};else delete project.communication.rf});this.message.set(enabled?'RF enabled':'RF disabled')}
 rfPreset(name:'terrestrial'|'leo'){this.remember();this.mutate(project=>project.communication.rf=name==='leo'?{...DEFAULT_RF_LINK,frequencyMHz:2200,distanceKm:1200,txPowerDbm:30,txGainDbi:12,rxGainDbi:30,lossDb:3,bandwidthHz:2e6,bitRateBps:1e6,noiseFigureDb:3}: {...DEFAULT_RF_LINK});this.message.set(name==='leo'?'LEO loaded':'Terrestrial loaded')}
 rfSetting(key:keyof RFLinkSettings,value:number){if(!Number.isFinite(value))return;this.mutate(project=>{if(project.communication.rf)project.communication.rf[key]=value})}
 adoptBudget(){const value=this.budget()?.ebN0Db;if(value===undefined||!Number.isFinite(value))return;const adopted=Math.max(-10,Math.min(40,value));this.radioSetting('ebN0Db',adopted);this.message.set(`AWGN Eb/N₀ set to ${adopted.toFixed(3)} dB${adopted!==value?' (clamped to −10…40 dB)':''}; run again to apply.`)}
 readingText(value:number|null|undefined,unit:string){if(value===null||value===undefined||!Number.isFinite(value))return 'Unavailable';return unit==='dB'||unit==='dBm'||unit==='deg'?`${Number(value.toPrecision(5))} ${unit==='deg'?'°':unit}`:this.quantity(value,unit)}
 measurementText(item:Measurement){return this.readingText(item.value,item.unit)}
 exportMeasurements(){const report=this.measurements();if(report)download('signals-circuit-measurements.csv',measurementCSV(report),'text/csv;charset=utf-8')}
 exportBudget(){const budget=this.budget(),source=this.radioSource();if(!budget||!source?.communication.rf)return;const rows=[['source_project','kind','name','value','unit'],...this.rfFields.map(field=>[source.name,'input',field.key,source.communication.rf![field.key],field.label.split(' / ')[1]||'']),...this.budgetReadings().map(item=>[source.name,'result',item.label,item.value,item.unit])];download('signals-rf-link-budget.csv',rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 probe(value:string){this.mutate(project=>project.instruments.probe=value)}
 setCursor(event:MouseEvent){const result=this.circuit();if(!result?.rows?.length)return;const rect=(event.currentTarget as SVGElement).getBoundingClientRect(),fraction=((event.clientX-rect.left)/rect.width*900-32)/836,index=circuitCursorIndex(result,this.project().instruments.probe,fraction);if(index!==this.project().instruments.cursor)this.mutate(project=>project.instruments.cursor=index,false)}
 zoom(factor:number){const v=this.view(),width=Math.min(1400,Math.max(450,v.width*factor)),height=width*560/1100;this.view.set({x:(1100-width)/2,y:(560-height)/2,width,height})}
 resetView(){this.view.set({x:0,y:0,width:1100,height:560})}
 scrollTo(id:string){this.activeTab.set(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
 request(kind:RunKind,project=this.project()):Record<string,unknown>{
  if(kind==='network'){const network=project.network;return {schema:'ocv.signals/1',op:'network',...network};}
  if(kind==='circuit')return netlist(project).request as unknown as Record<string,unknown>;
  if(kind==='digital')return {schema:'ocv.signals/1',op:'digital',...validateDigital(project.digital||digitalTemplate())};
  const settings=project.communication;
  if(!/^[01]{1,256}$/.test(settings.bits))throw Error('Bits: 1–256 binary digits');
  if(!Number.isFinite(settings.seed)||settings.seed<0||settings.seed>4294967295)throw Error('Seed: unsigned 32-bit integer');
  if(!Number.isFinite(settings.ebN0Db)||settings.ebN0Db< -10||settings.ebN0Db>40)throw Error('Eb/N₀: −10…40 dB');
  if(!Number.isFinite(settings.sampleRateHz)||settings.sampleRateHz<=0)throw Error('Sample rate must be positive');
  if(settings.rf)validateRFLink(settings.rf);
  return {schema:'ocv.signals/1',op:'communications',...settings,seed:Math.floor(settings.seed),samplesPerSymbol:Math.round(settings.samplesPerSymbol),crc:settings.crc||'CRC-8',modulation:settings.modulation||'BPSK',lineCode:settings.lineCode||'NRZ'};
 }
 private accept(result:EngineResult,source:Project,verification?:Record<string,unknown>){
  if(!result.ok){const errors=result.diagnostics?.map(d=>`${d.code}: ${d.message}`).join(' · ')||'Calculation failed';this.message.set(errors);if('rows'in result)this.circuit.set(result as CircuitResult);return}
  if('trace'in result){this.digitalSource.set(source);this.digitalAnalysis.set(verification||null);this.digital.set(result as DigitalResult);this.digitalCursor.set(0)}else if('events'in result){this.networkSource.set(source);this.networkResult.set(result as NetworkResult);this.selectedFlow.set((result as NetworkResult).routes[0]?.flow||'');this.flights.set(flightsFrom(result as NetworkResult,source.network));this.simulationTime.set(0);this.playing.set(false);this.togglePlayback()}else if('rows'in result){this.circuitSource.set(source);this.circuitAnalysis.set(verification||null);this.circuit.set(result as CircuitResult)}else{this.radioSource.set(source);this.radioAnalysis.set(verification||null);this.radio.set(result as RadioResult)};
  this.message.set('Complete')
 }
 run(kind:RunKind){
  if(this.disposed)return;
  try{const origin=clone(this.project()),request=this.request(kind,origin),source=this.refineProject(kind,origin),nativeRequest=this.request(kind,source);this.invalidateAnalysis(false);const presentation=this.presentationGeneration,sequence=++this.nativeSequence;this.wantedNative[kind]=sequence;this.nativeResults.update(cache=>{const next={...cache};delete next[kind];return next});void this.preview(kind,origin,request,presentation);this.enqueueNative({kind,origin,source,request:nativeRequest,sequence})}catch(error){this.message.set((error as Error).message)}
 }
 private refineProject(kind:RunKind,origin:Project){
  const source=clone(origin);if(kind!=='circuit')return source;const settings=source.analysis,compiled=netlist(source),nodeCount=new Set([...compiled.nodes.values()].filter(node=>node!=='0')).size,components=compiled.request.components,unknowns=nodeCount+components.filter(part=>['V','E','L'].includes(part.type)||settings.kind==='transient'&&part.type==='C').length,workLimit=Math.floor(300000000/Math.max(1,unknowns)**3),cellLimit=Math.floor(1048576/(nodeCount+components.length+1));
  if(settings.kind==='ac'&&Number.isFinite(settings.points)){const target=Math.min(128,workLimit,Math.max(2,Math.round(settings.points))*2);if(target>settings.points)settings.points=target}
  if(settings.kind==='transient'&&Number.isFinite(settings.stepS)&&Number.isFinite(settings.durationS)&&settings.stepS>=1e-9&&settings.durationS>0){const steps=Math.ceil(settings.durationS/settings.stepS),limit=Math.min(2048,workLimit-1,cellLimit-1,262143);if(steps<limit)settings.stepS=Math.max(1e-9,settings.stepS/2,settings.durationS/limit)}return source;
 }
 async preview(kind:RunKind,source=clone(this.project()),request?:object,presentation?:number){
  if(this.disposed)return;const generation=++this.localGeneration;
  if(this.localBusy())this.computer.cancel();if(presentation===undefined){this.invalidateAnalysis();presentation=this.presentationGeneration}const expected=presentation;this.localBusy.set(true);this.message.set('Calculating…');
  try{const result=await this.computer.run(request||this.request(kind,source));if(!this.disposed&&generation===this.localGeneration&&expected===this.presentationGeneration)this.accept(result,source)}catch(error){if(!this.disposed&&generation===this.localGeneration&&expected===this.presentationGeneration)this.message.set(String((error as Error).message))}finally{if(generation===this.localGeneration)this.localBusy.set(false)}
 }
 cancelLocal(){++this.localGeneration;this.invalidateAnalysis(false);this.computer.cancel();this.localBusy.set(false);this.message.set('Stopped')}
 private enqueueNative(launch:NativeLaunch){
  if(this.disposed)return;
  if(this.backendBusy()){this.queuedNative=launch;this.queuedNativeKind.set(launch.kind);this.backgroundMessage.set('待复核');return}
  void this.submitNative(launch);
 }
 private finishBackground(){
  this.backendBusy.set(false);this.runningNativeKind.set(null);const next=this.queuedNative;this.queuedNative=undefined;this.queuedNativeKind.set(null);if(next&&!this.disposed)this.enqueueNative(next);
 }
 async saveProject(){
  if(this.backendBusy())return;this.backendBusy.set(true);this.message.set('Saving…');
  try{const result=await this.persistProject();if(!this.disposed)this.message.set('Saved')}catch(error){if(!this.disposed)this.message.set((error as Error).message)}finally{this.finishBackground()}
 }
 private async persistProject(project=clone(this.project()),signal?:AbortSignal){const current=this.serverProject(),result=await api<{id:string;ticket:string;revision?:number;digest?:string}>('/projects',{project,...(current?{id:current.id,ticket:current.ticket,expectedRevision:current.revision}:{})},signal);if(this.disposed)return result;this.serverProject.set(result);try{localStorage.setItem('ocv.signals.project-ticket.v1',JSON.stringify(result))}catch{}this.sharedContext();return result}
 async reopenProject(){
  const project=this.serverProject();if(!project||this.backendBusy())return;this.backendBusy.set(true);
  try{const result=await api<{project?:Project;revision?:number;digest?:string}>(`/projects/${encodeURIComponent(project.id)}/read`,{ticket:project.ticket});if(this.disposed)return;if(!result.project)throw Error('Project snapshot missing');const parsed=parseProject(JSON.stringify(result.project)),updated={...project,...(result.revision!==undefined?{revision:result.revision}:{}),...(result.digest?{digest:result.digest}:{})};this.serverProject.set(updated);try{localStorage.setItem('ocv.signals.project-ticket.v1',JSON.stringify(updated))}catch{}this.remember();this.project.set(parsed);this.invalidateAnalysis();this.message.set('Restored');this.sharedContext()}catch(error){if(!this.disposed)this.message.set((error as Error).message)}finally{this.finishBackground()}
 }
 private async submitNative(launch:NativeLaunch){
  this.backendBusy.set(true);this.runningNativeKind.set(launch.kind);this.job.set(null);this.backgroundMessage.set('复核中…');const generation=++this.jobGeneration,controller=new AbortController();this.requestAbort=controller;this.activeNative=launch;this.jobDeadline=Date.now()+this.pollLifetime;
  try{const project=await this.persistProject(launch.source,controller.signal);if(this.disposed||generation!==this.jobGeneration)return;const job=await api<JobResponse>('/jobs',{request:launch.request,project:project.id,projectTicket:project.ticket},controller.signal);if(this.disposed||generation!==this.jobGeneration)return;if(!job.ticket)throw Error('Job access ticket missing');this.job.set(job);this.sharedContext();this.backgroundMessage.set(`复核 / ${job.state}`);void this.pollJob(job.id,job.ticket,generation,this.jobDeadline)}catch(error){if(!this.disposed&&generation===this.jobGeneration){this.backgroundMessage.set((error as Error).message);this.finishBackground()}}
 }
 private async pollJob(id:string,ticket:string,generation:number,deadline:number,attempt=0){
  if(this.disposed||generation!==this.jobGeneration||this.requestAbort?.signal.aborted)return;
  if(Date.now()>=deadline){this.backgroundMessage.set('自动复核等待已结束');this.finishBackground();return}
  try{const result=await api<JobResponse>(`/jobs/${encodeURIComponent(id)}/read`,{ticket},this.requestAbort?.signal);if(this.disposed||generation!==this.jobGeneration||this.requestAbort?.signal.aborted)return;this.job.set({...result,ticket});this.backgroundMessage.set(`复核 / ${result.state}`);
   if(['done','complete','completed','succeeded','failed','cancelled','canceled','timeout','timed_out'].includes(result.state)){
    const launch=this.activeNative;if(['done','complete','completed','succeeded'].includes(result.state)&&result.result?.engine&&launch){if(this.wantedNative[launch.kind]===launch.sequence&&this.inputIdentity(launch.origin)===this.inputIdentity(this.project())){this.nativeResults.update(cache=>({...cache,[launch.kind]:{...launch,result:result.result!.engine,analysis:result.result!.analysis}}));this.backgroundMessage.set('复核结果已就绪')}else this.backgroundMessage.set('复核完成 / 历史记录')}else{const error=result.error?(typeof result.error==='string'?result.error:JSON.stringify(result.error)):'';this.backgroundMessage.set(`复核 ${result.state}${error?' · '+error:''}`)}this.finishBackground();return;
   }
   this.polling=setTimeout(()=>void this.pollJob(id,ticket,generation,deadline,attempt+1),Math.max(0,Math.min(attempt<119?1200:15000,deadline-Date.now())));
  }catch(error){if(this.disposed||generation!==this.jobGeneration||this.requestAbort?.signal.aborted)return;const status=Number((error as Error&{status?:number}).status);if(status===403||status===404){this.backgroundMessage.set('复核记录已过期');this.finishBackground();return}if(Date.now()>=deadline){this.backgroundMessage.set('自动复核等待已结束');this.finishBackground();return}this.backgroundMessage.set('复核连接等待中');this.polling=setTimeout(()=>void this.pollJob(id,ticket,generation,deadline,attempt+1),Math.min(15000,deadline-Date.now()))}
 }
 canViewNative(kind:RunKind){const cache=this.nativeResults()[kind];return !!cache&&cache.sequence===this.wantedNative[kind]&&this.inputIdentity(cache.origin)===this.inputIdentity(this.project())}
 viewNative(kind:RunKind){const cache=this.nativeResults()[kind];if(!cache||!this.canViewNative(kind))return;++this.localGeneration;this.computer.cancel();this.localBusy.set(false);this.invalidateAnalysis(false);this.analysisCheck.set(cache.analysis||null);this.accept(cache.result,cache.source,cache.analysis);if(cache.result.ok)this.message.set('复核结果')}
 async refreshJob(){const job=this.job();if(!job?.ticket||this.backendBusy())return;this.backendBusy.set(true);this.runningNativeKind.set(this.activeNative?.kind||null);this.requestAbort=new AbortController();void this.pollJob(job.id,job.ticket,++this.jobGeneration,this.jobDeadline||Date.now()+this.pollLifetime)}
 async cancelJob(){const job=this.job();if(!job?.ticket)return;clearTimeout(this.polling);++this.jobGeneration;this.queuedNative=undefined;this.queuedNativeKind.set(null);this.invalidateAnalysis();this.requestAbort?.abort();this.backendBusy.set(true);try{const result=await api<JobResponse>(`/jobs/${encodeURIComponent(job.id)}/cancel`,{ticket:job.ticket});if(!this.disposed){this.job.set({...result,ticket:job.ticket});this.backgroundMessage.set('已请求取消')}}catch(error){if(!this.disposed)this.backgroundMessage.set((error as Error).message)}finally{this.finishBackground()}}
 checkMetrics(check:Record<string,unknown>){return Object.entries(check).filter(([key,value])=>!['code','status','message'].includes(key)&&(typeof value==='boolean'||typeof value==='number'&&Number.isFinite(value))).slice(0,5).map(([key,value])=>`${key} ${typeof value==='number'?Number(value.toPrecision(5)):value}`).join(' · ')}
 exportAnalysis(){const report=this.analysisCheck();if(!report)return;const quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`,rows=[['check','status','metrics'],...this.analysisChecks().map(check=>[check['code'],check['status'],JSON.stringify(Object.fromEntries(Object.entries(check).filter(([key])=>!['code','status','message'].includes(key))))])];download('signals-verification.csv',rows.map(row=>row.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 exportAnalysisJSON(){const report=this.analysisCheck();if(report)download('signals-verification.json',JSON.stringify(report,null,2),'application/json')}
 exportProject(){download('signals-project.json',JSON.stringify(this.project(),null,2),'application/json')}
 exportResults(kind:'circuit'|'communications'|'digital') {const result=kind==='circuit'?this.circuit():kind==='digital'?this.digital():this.radio(),project=kind==='circuit'?this.circuitSource():kind==='digital'?this.digitalSource():this.radioSource(),analysis=kind==='circuit'?this.circuitAnalysis():kind==='digital'?this.digitalAnalysis():this.radioAnalysis();if(!result||!project)return;download(`signals-${kind}-result.json`,JSON.stringify({schema:'ocv.signals-result/1',project,request:this.request(kind,project),result,analysis},null,2),'application/json')}
 exportCSV(kind:'circuit'|'communications'|'digital'){const result=kind==='circuit'?this.circuit():kind==='digital'?this.digital():this.radio();if(!result?.ok)return;download(`signals-${kind}.csv`,kind==='circuit'?circuitCSV(result as CircuitResult):kind==='digital'?digitalCSV(result as DigitalResult):radioCSV(result as RadioResult),'text/csv;charset=utf-8')}
 exportSVG(){const svg=this.schematic?.nativeElement;if(!svg)return;const copy=svg.cloneNode(true) as SVGSVGElement;copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width','1100');copy.setAttribute('height','560');copy.setAttribute('viewBox','0 0 1100 560');copy.querySelectorAll('.selection-box,.terminal-hit,.wire-hit,.wire-back,.wire-preview').forEach(node=>node.remove());copy.querySelectorAll('.part').forEach(p=>{p.setAttribute('stroke','#164474');p.setAttribute('fill','white')});copy.querySelectorAll('.wire').forEach(p=>{p.setAttribute('stroke','#2878cb');p.setAttribute('fill','none');p.setAttribute('stroke-width','2')});copy.querySelectorAll('text').forEach(p=>{p.setAttribute('fill','#174276');p.setAttribute('font-family','monospace');p.setAttribute('font-size','14')});copy.querySelectorAll('.terminal-name').forEach(p=>{p.setAttribute('font-size','9');p.setAttribute('fill','#7899b4')});copy.querySelectorAll('.meter-mark,.control-mark').forEach(p=>{p.setAttribute('stroke','none');p.setAttribute('font-family','Arial');p.setAttribute('font-size',p.classList.contains('meter-mark')?'18':'12')});copy.querySelectorAll('.terminal').forEach(p=>{p.setAttribute('fill','white');p.setAttribute('stroke','#005eff')});download('signals-schematic.svg',new XMLSerializer().serializeToString(copy),'image/svg+xml')}
 async importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>8388608)throw Error('Import exceeds 8 MiB');const text=await file.text(),record=JSON.parse(text);if(record?.schema==='ocv.signals-replay/1'){if(!['communications','digital'].includes(record.kind))throw Error('Unsupported replay kind');const project=parseProject(JSON.stringify(record.project)),kind=record.kind as 'communications'|'digital',result=replayRecord(record,kind,this.request(kind,project));this.remember();this.project.set(project);this.invalidateAnalysis();this.accept(result,project);if(kind==='digital')this.digitalCursor.set(Math.max(0,Math.min((result as DigitalResult).trace.length-1,Math.floor(Number(record.view?.cursor)||0))));this.radioQuadrature.set(record.view?.quadrature===true);this.message.set('Loaded replay / recorded data')}else{if(file.size>524288)throw Error('Project exceeds 512 KiB');const project=parseProject(text);this.remember();this.project.set(project);this.invalidateAnalysis();this.selected.set('');this.message.set(`Imported ${file.name}`)}}catch(error){this.message.set((error as Error).message)}finally{(event.target as HTMLInputElement).value=''}}
 json(value:unknown){return JSON.stringify(value,null,2)}
 constellationX(i:number){return Math.max(14,Math.min(426,220+i*75))}constellationY(q:number){return Math.max(12,Math.min(208,110-q*75))}
 eyeX(phase:number){return 20+phase*200}eyeY(value:number){return Math.max(12,Math.min(208,110-value*52))}
 setNetworkTemplate(name:string){this.remember();this.mutate(project=>project.network=networkTemplate(name));this.networkResult.set(null);this.networkSource.set(null);this.flights.set([]);this.pausePlayback();this.simulationTime.set(0);this.networkSelected.set('');this.message.set(`${name} topology loaded`)}
 private networkPoint(event:MouseEvent|PointerEvent):{x:number;y:number}|null {const svg=this.networkBoard?.nativeElement,matrix=svg?.getScreenCTM();if(!svg||!matrix)return null;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const p=point.matrixTransform(matrix.inverse());return {x:p.x,y:p.y}}
 armNetwork(type:NetworkKind){this.networkArmed.set(this.networkArmed()===type?null:type);this.networkLinkMode.set(false)}
 networkBoardClick(event:MouseEvent){if(!(event.target as Element).hasAttribute('data-network-board'))return;const type=this.networkArmed(),point=this.networkPoint(event);if(!type||!point){this.networkSelected.set('');return}if(this.project().network.nodes.length>=64){this.message.set('64-node limit');return}this.remember();const id=this.nextId('N');this.mutate(project=>project.network.nodes.push({id,type,x:this.snap(point.x,70,1030),y:this.snap(point.y,70,560)}));this.networkArmed.set(null);this.networkSelected.set(id)}
 beginNetworkDrag(event:PointerEvent,node:NetworkNode){this.activeTab.set('network');if(this.networkLinkMode())return;event.preventDefault();event.stopPropagation();this.networkSelected.set(node.id);const p=this.networkPoint(event);if(!p)return;this.remember();this.networkDragging={id:node.id,dx:p.x-node.x,dy:p.y-node.y}}
 networkNodeClick(event:MouseEvent,node:NetworkNode){event.stopPropagation();this.networkSelected.set(node.id);if(!this.networkLinkMode())return;const start=this.networkLead();if(!start){this.networkLead.set(start||node.id);this.message.set('Choose destination node');return}this.networkLead.set(null);if(start===node.id)return;if(this.project().network.links.length>=128){this.message.set('128-link limit');return}if(this.project().network.links.some(link=>(link.a===start&&link.b===node.id)||(link.b===start&&link.a===node.id)))return;this.remember();const id=this.nextId('L');this.mutate(project=>project.network.links.push({id,a:start,b:node.id,rateMbps:20,delayMs:10,loss:0,enabled:true}));this.networkSelected.set(id)}
 toggleLinkMode(){this.networkLinkMode.set(!this.networkLinkMode());this.networkLead.set(null);this.networkArmed.set(null)}
 selectNetworkLink(event:MouseEvent,link:NetworkLink){event.stopPropagation();this.networkSelected.set(link.id)}
 removeNetwork(){const id=this.networkSelected();if(!id)return;this.remember();this.mutate(project=>{project.network.nodes=project.network.nodes.filter(n=>n.id!==id);project.network.links=project.network.links.filter(link=>link.id!==id&&link.a!==id&&link.b!==id);project.network.flows=project.network.flows.filter(flow=>flow.source!==id&&flow.target!==id)});this.networkSelected.set('')}
 linkEnd(link:NetworkLink,side:'a'|'b'){return this.project().network.nodes.find(node=>node.id===link[side])||{id:'',type:'router' as NetworkKind,x:0,y:0}}
 networkLinkColor(link:NetworkLink){if(!link.enabled)return '#bac5d2';const types=[this.linkEnd(link,'a').type,this.linkEnd(link,'b').type];return types.includes('satellite')?'#1a95cb':types.includes('ue')?'#57aa73':'#497ceb'}
 linkLabel(link:NetworkLink){const a=this.linkEnd(link,'a'),b=this.linkEnd(link,'b'),dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1;return {x:(a.x+b.x)/2-dy/length*15,y:(a.y+b.y)/2+dx/length*15}}
 linkDirection(link:NetworkLink){const a=this.linkEnd(link,'a'),b=this.linkEnd(link,'b'),x=(a.x+b.x)/2,y=(a.y+b.y)/2,angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;return `translate(${x} ${y}) rotate(${angle})`}
 nodeActivity(id:string){return this.currentActivity().get(id)||{tx:0,rx:0,drop:0}}
 flowColor(id:string){const index=Math.max(0,(this.networkSource()?.network.flows||this.project().network.flows).findIndex(flow=>flow.id===id));return ['#0868fa','#00a6b6','#7b60d1','#278b67'][index%4]}
 linkSetting(key:'rateMbps'|'delayMs'|'loss'|'enabled',value:number|boolean){const id=this.networkLink()?.id;if(!id)return;this.remember();this.mutate(project=>{const link=project.network.links.find(l=>l.id===id)!;if(key==='enabled')link.enabled=!!value;else if(typeof value==='number'&&Number.isFinite(value))link[key]=value})}
 networkSetting(key:'seed'|'durationMs',value:number){if(!Number.isFinite(value))return;this.mutate(project=>project.network[key]=value)}
 flowSetting(id:string,key:'source'|'target'|'packets'|'bytes'|'startMs'|'intervalMs',value:string|number){this.mutate(project=>{const flow=project.network.flows.find(f=>f.id===id);if(!flow)return;if(key==='source'||key==='target')flow[key]=String(value);else if(typeof value==='number'&&Number.isFinite(value))flow[key]=value})}
 addFlow(){const network=this.project().network;if(network.flows.length>=16||network.nodes.length<2)return;this.remember();const id=this.nextId('F');this.mutate(project=>project.network.flows.push({id,source:network.nodes[0].id,target:network.nodes[network.nodes.length-1].id,packets:16,bytes:1200,startMs:0,intervalMs:100}))}
 removeFlow(id:string){this.remember();this.mutate(project=>project.network.flows=project.network.flows.filter(f=>f.id!==id))}
 packetPosition(flight:Flight){const a=this.project().network.nodes.find(n=>n.id===flight.from),b=this.project().network.nodes.find(n=>n.id===flight.to);if(!a||!b)return {x:0,y:0};const progress=Math.max(0,Math.min(1,(this.simulationTime()-flight.start)/(flight.end-flight.start||1)));return {x:a.x+(b.x-a.x)*progress,y:a.y+(b.y-a.y)*progress}}
 eventNode(id:string){return this.project().network.nodes.find(n=>n.id===id)||{x:0,y:0}}
 pausePlayback(){this.playing.set(false);cancelAnimationFrame(this.animation);this.lastAnimation=0;this.frameCarry=0}
 togglePlayback(){if(this.playing()){this.pausePlayback();return}if(!this.networkResult()?.ok)return;if(this.simulationTime()>=this.playbackDuration())this.simulationTime.set(0);this.playing.set(true);this.lastAnimation=0;this.frameCarry=0;const tick=(time:number)=>{if(!this.playing())return;const elapsed=this.lastAnimation?Math.min(100,time-this.lastAnimation):0;this.lastAnimation=time;this.frameCarry+=elapsed;if(this.frameCarry>0){this.simulationTime.set(Math.min(this.playbackDuration(),this.simulationTime()+this.frameCarry*this.playbackSpeed()));this.frameCarry=0;}if(this.simulationTime()>=this.playbackDuration()){this.pausePlayback();return}this.animation=requestAnimationFrame(tick)};this.animation=requestAnimationFrame(tick)}
 seek(value:number){this.simulationTime.set(value)}
 resetPlayback(){this.pausePlayback();this.simulationTime.set(0)}
 exportNetwork(){const result=this.networkResult(),source=this.networkSource();if(!result||!source)return;download('network-events.json',JSON.stringify({schema:'ocv.signals-network-result/1',network:source.network,request:this.request('network',source),result},null,2),'application/json')}
 exportNetworkCSV(){const result=this.networkResult();if(!result)return;const rows=['time_ms,event,packet,flow,from,to,link,reason',...result.events.map(e=>[e.tMs,e.kind,e.packet,e.flow,e.from,e.to,e.link,e.reason||''].map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(','))];download('network-events.csv',rows.join('\r\n'),'text/csv;charset=utf-8')}
 exportNetworkAudit(){const report=this.networkInspection();if(report)download('signals-network-diagnostics.csv',networkAuditCSV(report),'text/csv;charset=utf-8')}
 private cabal312512(value:number){return Number.isFinite(value)?value:0}
}

