export const PLACES = Object.freeze([
  {
    id: "la-palma",
    en: "La Palma",
    zh: "拉帕尔马",
    latitude: 28.76,
    longitude: -17.89,
    elevation: 2300,
  },
  {
    id: "atacama",
    en: "Atacama",
    zh: "阿塔卡马",
    latitude: -24.63,
    longitude: -70.4,
    elevation: 2400,
  },
  {
    id: "reykjavik",
    en: "Reykjavík",
    zh: "雷克雅未克",
    latitude: 64.1466,
    longitude: -21.9426,
    elevation: 20,
  },
  {
    id: "shanghai",
    en: "Shanghai",
    zh: "上海",
    latitude: 31.2304,
    longitude: 121.4737,
    elevation: 4,
  },
  {
    id: "sydney",
    en: "Sydney",
    zh: "悉尼",
    latitude: -33.8688,
    longitude: 151.2093,
    elevation: 50,
  },
  {
    id: "tokyo",
    en: "Tokyo",
    zh: "东京",
    latitude: 35.6762,
    longitude: 139.6503,
    elevation: 40,
  },
]);

export const PLANETS = Object.freeze([
  { id: "sun", en: "Sun", zh: "太阳", radius: "695,700 km" },
  { id: "mercury", en: "Mercury", zh: "水星", radius: "2,440 km" },
  { id: "venus", en: "Venus", zh: "金星", radius: "6,052 km" },
  { id: "earth", en: "Earth", zh: "地球", radius: "6,371 km" },
  { id: "moon", en: "Moon", zh: "月球", radius: "1,737 km" },
  { id: "mars", en: "Mars", zh: "火星", radius: "3,390 km" },
  { id: "jupiter", en: "Jupiter", zh: "木星", radius: "69,911 km" },
  { id: "saturn", en: "Saturn", zh: "土星", radius: "58,232 km" },
  { id: "uranus", en: "Uranus", zh: "天王星", radius: "25,362 km" },
  { id: "neptune", en: "Neptune", zh: "海王星", radius: "24,622 km" },
]);

export const EVENTS = Object.freeze([
  {
    id: "solar-2024-dallas",
    kind: "solar",
    en: "Total solar eclipse",
    zh: "日全食",
    date: "2024 · 04 · 08",
    placeEn: "Dallas",
    placeZh: "达拉斯",
  },
  {
    id: "lunar-2025-dallas",
    kind: "lunar",
    en: "Total lunar eclipse",
    zh: "月全食",
    date: "2025 · 03 · 14",
    placeEn: "Dallas",
    placeZh: "达拉斯",
  },
]);

export const EXPERIENCES = Object.freeze([
  {
    id: "meteors",
    group: "nightSky",
    en: "Meteor shower",
    zh: "流星雨",
    icon: "meteor",
  },
  {
    id: "trails",
    group: "nightSky",
    en: "Star trails",
    zh: "星轨",
    icon: "trails",
  },
  { id: "moon", group: "lunar", en: "Moon phases", zh: "月相", icon: "moon" },
  {
    id: "shadow",
    group: "lunar",
    en: "Shadow theatre",
    zh: "影锥剧场",
    icon: "shadow",
  },
  {
    id: "orbits",
    group: "dynamics",
    en: "Orbit explorer",
    zh: "轨道探索",
    icon: "orbits",
  },
  ...EVENTS.map((event) => ({
    ...event,
    group: "celestialEvents",
    icon: event.kind === "solar" ? "sun" : "moon",
  })),
]);

export const MOON_PHASES = Object.freeze([
  { en: "New moon", zh: "新月", day: 0 },
  { en: "Waxing crescent", zh: "娥眉月", day: 3.69 },
  { en: "First quarter", zh: "上弦月", day: 7.38 },
  { en: "Waxing gibbous", zh: "盈凸月", day: 11.07 },
  { en: "Full moon", zh: "满月", day: 14.77 },
  { en: "Waning gibbous", zh: "亏凸月", day: 18.46 },
  { en: "Last quarter", zh: "下弦月", day: 22.15 },
  { en: "Waning crescent", zh: "残月", day: 25.84 },
]);

export const COPY = Object.freeze({
  en: {
    title: "PLANETARIUM",
    loading: "Opening the sky",
    sky: "Sky",
    solar: "Solar system",
    eclipses: "Eclipses",
    experiences: "Experiences",
    nightSky: "NIGHT SKY",
    lunar: "LUNAR",
    dynamics: "ORBITS",
    celestialEvents: "CELESTIAL EVENTS",
    replay: "Replay",
    music: "Music",
    musicOn: "Mute music",
    musicOff: "Play music",
    volume: "Volume",
    constellation: "Constellation",
    help: "Controls",
    reset: "Reset view",
    azimuthShort: "AZ",
    altitudeShort: "ALT",
    rollShort: "ROLL",
    dragGuide: "Look around",
    moveGuide: "Move the camera",
    forwardGuide: "Forward / backward",
    strafeGuide: "Sideways / up / down",
    rollGuide: "Roll the sky",
    ringsGuide: "Direction rings",
    ringsKeys: "Drag a handle · AZ / ALT / ROLL · Arrow keys",
    zoomGuide: "Zoom",
    focusGuide: "Approach selection",
    pauseGuide: "Play / pause time",
    pauseExperienceGuide: "Play / pause experience",
    canvasSky: "Drag to explore the sky. Scroll to zoom. Space to play or pause.",
    canvasSolar: "Left drag to look around. Right drag to move. Scroll to move forward or backward.",
    timeSpeed: "Time speed",
    eclipseTime: "Eclipse time",
    source: "Source ↗",
    license: " · License",
    leftDrag: "Left drag",
    rightDrag: "Right drag",
    wheel: "Scroll / pinch",
    deviceMotion: "Phone motion",
    motionHttps: "Phone motion needs HTTPS.",
    motionDenied: "Motion access was not granted.",
    motionUnavailable: "No motion sensor is available.",
    motionTimeout: "No sensor data received. Try again.",
    objects: "Celestial objects",
    famousStars: "Bright stars",
    settings: "Display",
    location: "Location",
    constellations: "Constellations",
    coordinates: "Coordinates",
    latitude: "Latitude",
    longitude: "Longitude",
    apply: "Apply",
    photographic: "Long exposure",
    atmosphere: "Horizon & atmosphere",
    orbits: "Orbit lines",
    quality: "Quality",
    balanced: "Balanced",
    high: "High",
    credits: "Sources & credits",
    allCredits: "All credits ↗",
    focus: "Approach",
    now: "Now",
    tour: "Tour",
    dateTime: "Date & time · UTC",
    displayScale: "Display scale",
    star: "Star",
    planet: "Planet",
    satellite: "Natural satellite",
    radius: "Radius",
    magnitude: "Magnitude",
    altitude: "Altitude",
    search: "Find a star or planet",
    close: "Close",
    play: "Play",
    pause: "Pause",
    fullscreen: "Fullscreen",
    reverse: "Reverse time",
    day: "1 day/s",
    month: "30 days/s",
    custom: "Custom location",
    partial: "Partial",
    total: "Totality",
    penumbral: "Penumbral",
    ready: "Ready",
    error: "The sky could not be loaded. Reload to try again.",
    invalidDate: "Choose a date between 1600 and 2400.",
    unavailable: "This view needs WebGL 2.",
    contextLost: "Graphics paused. Reload to continue.",
    overview: "Overview",
    position: "Coordinates",
    eclipseDate: "Eclipse",
    language: "Switch to Chinese",
  },
  zh: {
    title: "天象仪",
    loading: "正在开启天幕",
    sky: "天幕",
    solar: "太阳系",
    eclipses: "日月食",
    experiences: "观赏模式",
    nightSky: "夜空",
    lunar: "月球",
    dynamics: "轨道",
    celestialEvents: "天象回放",
    replay: "重播",
    music: "音乐",
    musicOn: "关闭音乐",
    musicOff: "播放音乐",
    volume: "音量",
    constellation: "星座",
    help: "操作",
    reset: "复位视角",
    azimuthShort: "方位",
    altitudeShort: "仰角",
    rollShort: "侧倾",
    dragGuide: "自由转动",
    moveGuide: "平移镜头",
    forwardGuide: "前进 / 后退",
    strafeGuide: "左右 / 上下",
    rollGuide: "旋转天幕",
    ringsGuide: "方向控制环",
    ringsKeys: "拖动环柄 · 方位 / 高度 / 横滚 · 方向键",
    zoomGuide: "缩放",
    focusGuide: "靠近选中天体",
    pauseGuide: "播放 / 暂停时间",
    pauseExperienceGuide: "播放 / 暂停体验",
    canvasSky: "拖动探索天幕，滚轮缩放，空格播放或暂停。",
    canvasSolar: "左键拖动转向，右键拖动平移，滚轮前进或后退。",
    timeSpeed: "时间倍率",
    eclipseTime: "食相时间",
    source: "来源 ↗",
    license: " · 许可",
    leftDrag: "左键拖动",
    rightDrag: "右键拖动",
    wheel: "滚轮 / 双指缩放",
    deviceMotion: "手机陀螺仪",
    motionHttps: "陀螺仪需要通过 HTTPS 打开。",
    motionDenied: "未获得动作传感器权限。",
    motionUnavailable: "当前设备没有可用的动作传感器。",
    motionTimeout: "尚未收到传感器数据，请重试。",
    objects: "天体",
    famousStars: "亮星",
    settings: "显示",
    location: "地点",
    constellations: "星座",
    coordinates: "坐标",
    latitude: "纬度",
    longitude: "经度",
    apply: "应用",
    photographic: "高曝光星空",
    atmosphere: "地平线与大气",
    orbits: "轨道",
    quality: "画质",
    balanced: "均衡",
    high: "高",
    credits: "来源与署名",
    allCredits: "完整声明 ↗",
    focus: "靠近",
    now: "现在",
    tour: "巡游",
    dateTime: "日期与时间 · UTC",
    displayScale: "展示比例",
    star: "恒星",
    planet: "行星",
    satellite: "天然卫星",
    radius: "半径",
    magnitude: "星等",
    altitude: "高度角",
    search: "寻找恒星或行星",
    close: "关闭",
    play: "播放",
    pause: "暂停",
    fullscreen: "全屏",
    reverse: "时间倒流",
    day: "每天 / 秒",
    month: "30 天 / 秒",
    custom: "自定义地点",
    partial: "偏食",
    total: "全食",
    penumbral: "半影食",
    ready: "就绪",
    error: "天幕加载失败，请刷新重试。",
    invalidDate: "请选择 1600 至 2400 年之间的日期。",
    unavailable: "此视图需要 WebGL 2。",
    contextLost: "图形已暂停，请刷新继续。",
    overview: "总览",
    position: "坐标",
    eclipseDate: "食相",
    language: "Switch to English",
  },
});
