import {queueLimit,queueTtlSeconds,expireTasksSql,terminalLimit,trimTerminalSql} from '../a1/capacity';
import {BadRequestException,Body,Controller,Headers,HttpException,Inject,Injectable,OnModuleDestroy,Param,Post,ServiceUnavailableException} from '@nestjs/common';
import {Pool,PoolClient} from 'pg';
import {randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {canonicalInvoice,hashInvoice,hexTicket,uuidInvoice,objectInvoice,keysInvoice} from './1';
import {validateWorkshopProject,validateWorkshopRequest} from './stock3';

@Injectable()
export class ReturnOrder implements OnModuleDestroy {
 private pool?:Pool;private readers=0;
 private db(){if(!process.env.DATABASE_URL)throw new ServiceUnavailableException('PostgreSQL is required for server engineering projects');if(!this.pool){this.pool=new Pool({connectionString:process.env.DATABASE_URL,max:1,connectionTimeoutMillis:1500,statement_timeout:3000});this.pool.on('error',()=>{});}return this.pool;}
 private parse<T>(fn:()=>T){try{return fn();}catch(e){throw new BadRequestException((e as Error).message);}}
 private receipt(id:string,input:unknown,allowed=['ticket']){return this.parse(()=>{const p=objectInvoice(input);keysInvoice(p,allowed);if(!uuidInvoice.test(id)||typeof p.ticket!=='string'||!hexTicket.test(p.ticket))throw Error('Invalid capability');return p;});}
 private lease(key:string|undefined){const expected=process.env.OCV_RUNNER_KEY;if(!key||!expected||!hexTicket.test(key)||!timingSafeEqual(Buffer.from(hashInvoice(key)),Buffer.from(hashInvoice(expected))))throw new HttpException('Unavailable endpoint',404);}
 private revision(v:unknown){if(!Number.isInteger(v)||Number(v)<1||Number(v)>2147483647)throw new BadRequestException('Invalid revision');return Number(v);}
 private async open<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db().connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(312512,81)');const out=await fn(c);await c.query('SELECT ocv_signals.trim_catalog()');await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 private async source(c:PoolClient,id:string,ticket:string,revision?:unknown){if(revision!==undefined)this.revision(revision);const r=revision===undefined?await c.query('SELECT p.id,s.name,p.revision AS head_revision,s.revision,s.snapshot,s.digest,s.invoice_text,s.operation,s.parent_snapshot,s.source_snapshot FROM ocv_workshop.return_orders s JOIN ocv_signals.catalog_stock p ON p.id=s.id WHERE p.id=$1 AND p.ticket_sha=$2 FOR UPDATE OF p',[id,hashInvoice(ticket)]):await c.query('SELECT p.id,p.name,p.revision AS head_revision,h.revision,h.id AS snapshot,h.digest,h.invoice_text,h.operation,h.parent_snapshot,h.source_snapshot FROM ocv_signals.catalog_stock p JOIN ocv_signals.price_history h ON h.project_id=p.id AND h.revision=$3 WHERE p.id=$1 AND p.ticket_sha=$2 AND p.domain=\'workshop\' FOR UPDATE OF p',[id,hashInvoice(ticket),revision]);if(!r.rows.length)throw new HttpException('Project or revision expired or inaccessible',404);const row=r.rows[0];if(hashInvoice(row.invoice_text)!==row.digest)throw new ServiceUnavailableException('Snapshot checksum mismatch');return row;}
 private async write(c:PoolClient,id:string,revision:number,parsed:ReturnType<typeof validateWorkshopProject>,operation='save',parent:string|null=null,source:string|null=null){const snapshot=randomUUID();await c.query('INSERT INTO ocv_signals.price_history(id,project_id,revision,digest,invoice_text,operation,parent_snapshot,source_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[snapshot,id,revision,parsed.digest,parsed.text,operation,parent,source]);return {id,revision,digest:parsed.digest,snapshot,parentSnapshot:parent,sourceSnapshot:source,operation,storage:'PostgreSQL',contract:'ocv.workshop-project/1'};}
 async save(input:unknown){const p=this.parse(()=>{const o=objectInvoice(input);keysInvoice(o,['project','id','ticket','expectedRevision']);return o;}),parsed=this.parse(()=>validateWorkshopProject(p.project)),editing=p.id!==undefined;if(editing)this.receipt(String(p.id),{ticket:p.ticket});else if(p.ticket!==undefined||p.expectedRevision!==undefined)throw new BadRequestException('New projects do not accept a previous capability');const id=editing?String(p.id):randomUUID(),ticket=editing?String(p.ticket):randomBytes(32).toString('hex');return this.open(async c=>{let revision=1,parent=null;if(editing){const previous=await this.source(c,id,ticket);if(this.revision(p.expectedRevision)!==previous.head_revision)throw new HttpException('Revision conflict; reload the saved project',409);revision=previous.head_revision+1;parent=previous.snapshot;await c.query('UPDATE ocv_signals.catalog_stock SET name=$2,revision=$3,updated_at=now() WHERE id=$1',[id,parsed.name,revision]);}else await c.query('INSERT INTO ocv_signals.catalog_stock(id,ticket_sha,name,domain) VALUES($1,$2,$3,\'workshop\')',[id,hashInvoice(ticket),parsed.name]);return {...await this.write(c,id,revision,parsed,'save',parent),ticket};});}
 async read(id:string,input:unknown){const p=this.receipt(id,input,['ticket','revision']);const c=await this.db().connect();try{const row=await this.source(c,id,String(p.ticket),p.revision);return {...row,invoice_text:undefined,project:JSON.parse(row.invoice_text),storage:'PostgreSQL'};}finally{c.release();}}
 async versions(id:string,input:unknown){const p=this.receipt(id,input);const r=await this.db().query('SELECT h.revision,h.id AS snapshot,h.digest,h.operation,h.parent_snapshot,h.source_snapshot,h.created_at FROM ocv_signals.price_history h JOIN ocv_signals.catalog_stock p ON p.id=h.project_id WHERE p.id=$1 AND p.ticket_sha=$2 AND p.domain=\'workshop\' ORDER BY h.revision DESC LIMIT 12',[id,hashInvoice(String(p.ticket))]);if(!r.rows.length)throw new HttpException('Project expired or inaccessible',404);return{id,versions:r.rows,storage:'PostgreSQL'};}
 async branch(id:string,input:unknown){const p=this.receipt(id,input,['ticket','revision','name']);return this.open(async c=>{const origin=await this.source(c,id,String(p.ticket),p.revision),project=JSON.parse(origin.invoice_text);if(p.name!==undefined)project.name=p.name;const parsed=this.parse(()=>validateWorkshopProject(project)),next=randomUUID(),ticket=randomBytes(32).toString('hex');await c.query('INSERT INTO ocv_signals.catalog_stock(id,ticket_sha,name,domain) VALUES($1,$2,$3,\'workshop\')',[next,hashInvoice(ticket),parsed.name]);return{...await this.write(c,next,1,parsed,'branch',null,origin.snapshot),ticket,sourceProject:id};});}
 async rollback(id:string,input:unknown){const p=this.receipt(id,input,['ticket','revision','expectedRevision']);this.revision(p.revision);return this.open(async c=>{const head=await this.source(c,id,String(p.ticket));if(this.revision(p.expectedRevision)!==head.head_revision)throw new HttpException('Revision conflict; reload the saved project',409);const chosen=await this.source(c,id,String(p.ticket),p.revision),parsed=this.parse(()=>validateWorkshopProject(JSON.parse(chosen.invoice_text))),revision=head.head_revision+1;await c.query('UPDATE ocv_signals.catalog_stock SET name=$2,revision=$3,updated_at=now() WHERE id=$1',[id,parsed.name,revision]);return{...await this.write(c,id,revision,parsed,'rollback',head.snapshot,chosen.snapshot),ticket:p.ticket};});}
 async submit(input:unknown){const p=this.parse(()=>{const o=objectInvoice(input);keysInvoice(o,['request','project','projectTicket']);return o;}),request=this.parse(()=>validateWorkshopRequest(p.request));if(p.project===undefined&&p.projectTicket!==undefined)throw new BadRequestException('A saved project is required for its capability');const id=randomUUID(),ticket=randomBytes(32).toString('hex'),digest=hashInvoice(canonicalInvoice(request));const c=await this.db().connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(312512,52)');await c.query('SELECT pg_advisory_xact_lock(312512,81)');await c.query(expireTasksSql,[queueTtlSeconds()]);const count=await c.query("SELECT count(*) FROM ocv_after.jobs WHERE state='queued'");if(queueLimit()>0&&Number(count.rows[0].count)>=queueLimit())throw new HttpException('Workshop queue occupied; local preview remains available',429);let snapshot=null;if(p.project!==undefined){const cap=this.receipt(String(p.project),{ticket:p.projectTicket}),origin=await this.source(c,String(p.project),String(cap.ticket));snapshot=origin.snapshot;}await c.query("INSERT INTO ocv_after.jobs(id,run_id,ticket_sha,family,feature,digest) VALUES($1,$1,$2,'mechanical','workshop',$3)",[id,hashInvoice(ticket),digest]);await c.query('INSERT INTO ocv_workshop.order_items(id,project_id,snapshot_id,request) VALUES($1,$2,$3,$4::jsonb)',[id,p.project??null,snapshot,JSON.stringify(request)]);await c.query('UPDATE ocv_shared1.task_books SET owner_bucket=$2 WHERE job_id=$1',[id,p.project??'unsaved:'+'engineering']);await c.query(trimTerminalSql,[terminalLimit()]);await c.query('COMMIT');return{id,ticket,state:'queued',dispatcherConfigured:!!process.env.OCV_RUNNER_KEY,storage:'PostgreSQL'};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async job(id:string,input:unknown){const p=this.receipt(id,input);if(this.readers>=8)throw new HttpException('Read capacity reached',429);this.readers++;try{const r=await this.db().query('SELECT j.id,j.state,j.phase,j.result,j.created_at,j.updated_at,n.engine_result,n.stock_manifest,n.review_result,n.cancelled FROM ocv_after.jobs j JOIN ocv_workshop.order_items n ON n.id=j.id WHERE j.id=$1 AND j.ticket_sha=$2',[id,hashInvoice(String(p.ticket))]);if(!r.rows.length)throw new HttpException('Job expired or inaccessible',404);const row=r.rows[0];return{...row,engine_result:undefined,stock_manifest:undefined,review_result:undefined,result:{...row.result,engine:row.engine_result,manifest:row.stock_manifest,analysis:row.review_result},error:row.state==='failed'?row.result.reason:undefined,storage:'PostgreSQL'};}finally{this.readers--;}}
 async cancel(id:string,input:unknown){const p=this.receipt(id,input);const c=await this.db().connect();try{await c.query('BEGIN');const r=await c.query("UPDATE ocv_after.jobs SET state='cancelled',result='{\"reason\":\"cancelled by owner\"}',updated_at=now() WHERE id=$1 AND ticket_sha=$2 AND family='mechanical' AND state IN('queued','starting','running') RETURNING id",[id,hashInvoice(String(p.ticket))]);if(r.rows.length)await c.query('UPDATE ocv_workshop.order_items SET cancelled=true WHERE id=$1',[id]);await c.query('COMMIT');return{id,cancelled:!!r.rows.length};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async internal(key:string|undefined,input:unknown){this.lease(key);const p=this.parse(()=>{const o=objectInvoice(input);keysInvoice(o,['action','id','worker','engine','manifest','analysis']);if(!uuidInvoice.test(String(o.id))||!uuidInvoice.test(String(o.worker))||!['input','engine','manifest','analysis','status'].includes(String(o.action)))throw Error('Invalid worker command');return o;});const c=await this.db().connect();try{await c.query('BEGIN');const r=await c.query("SELECT n.request,n.project_id,n.snapshot_id,n.cancelled,n.engine_result,n.stock_manifest,n.review_result,j.state,j.digest AS request_digest,h.invoice_text,h.digest,h.revision FROM ocv_workshop.order_items n JOIN ocv_after.jobs j ON j.id=n.id LEFT JOIN ocv_signals.price_history h ON h.id=n.snapshot_id WHERE n.id=$1 AND j.family='mechanical' AND EXISTS(SELECT 1 FROM ocv_after.worker WHERE id=1 AND owner=$2 AND lease_until>now()) FOR UPDATE OF n",[p.id,p.worker]);if(!r.rows.length)throw new HttpException('Worker lease or job unavailable',409);const row=r.rows[0];if(p.action==='status'){await c.query('COMMIT');return{id:p.id,state:row.state,cancelled:row.cancelled};}if(row.cancelled||!['starting','running'].includes(row.state))throw new HttpException('Task is no longer active',409);if(p.action!=='input'){const field=p.action==='engine'?'engine_result':p.action==='manifest'?'stock_manifest':'review_result',result=p.action==='engine'?p.engine:p.action==='manifest'?p.manifest:p.analysis;this.parse(()=>objectInvoice(result));const text=JSON.stringify(result);if(Buffer.byteLength(text)>(p.action==='engine'?4194304:1048576))throw new BadRequestException('Result exceeds byte limit');await c.query(`UPDATE ocv_workshop.order_items SET ${field}=$2::jsonb WHERE id=$1`,[p.id,text]);}await c.query('COMMIT');return{...row,storage:'PostgreSQL'};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async onModuleDestroy(){await this.pool?.end();}
}
@Controller('api/workshop')
export class ReturnController {
 constructor(@Inject(ReturnOrder)private readonly stock:ReturnOrder){}
 @Post('projects') save(@Body()p:unknown){return this.stock.save(p);}
 @Post('projects/:id/read') read(@Param('id')id:string,@Body()p:unknown){return this.stock.read(id,p);}
 @Post('projects/:id/versions') versions(@Param('id')id:string,@Body()p:unknown){return this.stock.versions(id,p);}
 @Post('projects/:id/branch') branch(@Param('id')id:string,@Body()p:unknown){return this.stock.branch(id,p);}
 @Post('projects/:id/rollback') rollback(@Param('id')id:string,@Body()p:unknown){return this.stock.rollback(id,p);}
 @Post('jobs') submit(@Body()p:unknown){return this.stock.submit(p);}
 @Post('jobs/:id/read') job(@Param('id')id:string,@Body()p:unknown){return this.stock.job(id,p);}
 @Post('jobs/:id/cancel') cancel(@Param('id')id:string,@Body()p:unknown){return this.stock.cancel(id,p);}
 @Post('internal') internal(@Headers('x-ocv-runner')key:string|undefined,@Body()p:unknown){return this.stock.internal(key,p);}
}
