import {canonicalInvoice,finiteInvoice,hashInvoice,keysInvoice,objectInvoice} from './1';

const docket=/^[A-Za-z0-9_-]{1,32}$/;
function sku(v:unknown){if(typeof v!=='string'||!docket.test(v))throw Error('Invalid engineering identifier');return v;}
function small(v:unknown,max=64){if(typeof v!=='string'||v.length>max||/[\x00-\x1f]/.test(v))throw Error('Invalid engineering label');return v;}
function integer(v:unknown,a:number,b:number){const n=finiteInvoice(v,a,b);if(!Number.isInteger(n))throw Error('Integer required');return n;}
function price(o:Record<string,unknown>,k:string,a:number,b:number){if(o[k]!==undefined)finiteInvoice(o[k],a,b);}
function boxed(v:unknown,depth=0){if(depth>10)throw Error('Engineering object too deep');if(Array.isArray(v)){if(v.length>256)throw Error('Engineering array too large');v.forEach(x=>boxed(x,depth+1));}else if(v&&typeof v==='object'){if(Object.keys(v).length>40)throw Error('Engineering object has too many fields');for(const[k,x]of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k)||/password|email|phone|token|secret/i.test(k))throw Error('Account fields are not accepted');boxed(x,depth+1);}}else if(typeof v==='number'&&!Number.isFinite(v))throw Error('Finite engineering values required');else if(typeof v==='string'&&v.length>4096)throw Error('Engineering string too long');}
function listing(v:unknown,max:number){if(!Array.isArray(v)||v.length>max)throw Error('Engineering collection exceeds its limit');return v;}
function unique(rows:unknown[],allowed:string[]){const seen=new Set<string>();return rows.map(item=>{const p=objectInvoice(item);keysInvoice(p,allowed);const id=sku(p.id);if(seen.has(id))throw Error('Duplicate engineering identifier');seen.add(id);return p;});}
export function worldStock(value:unknown){
 const p=objectInvoice(value);keysInvoice(p,['gravityX','gravityY','stepS','durationS','sampleEvery','seed','bodies','joints','motors','controls']);
 price(p,'gravityX',-100,100);price(p,'gravityY',-100,100);const step=finiteInvoice(p.stepS??1/120,1/240,1/30),duration=finiteInvoice(p.durationS??8,.05,20),sample=integer(p.sampleEvery??8,1,4800);integer(p.seed??1,0,4294967295);
 const ticks=Math.ceil(duration/step);if(ticks>4800)throw Error('Engineering simulation or frame limit exceeded');
 const bodies=unique(listing(p.bodies,64),['id','kind','mode','x','y','angle','width','height','radius','mass','friction','restitution','linearDamping','angularDamping','vx','vy','omega','layer','group','label','colour']);if(!bodies.length)throw Error('At least one mechanical body is required');const ids=new Set(bodies.map(b=>String(b.id)));
 for(const b of bodies){if(!['ball','box','track','wheel','link','slider','gear','pulley'].includes(String(b.kind)))throw Error('Unsupported mechanical part');if(b.mode!==undefined&&!['dynamic','fixed'].includes(String(b.mode)))throw Error('Unsupported body mode');for(const k of ['x','y','vx','vy'])price(b,k,-100,100);price(b,'angle',-1000,1000);for(const k of ['width','height','radius'])price(b,k,.01,50);price(b,'mass',.001,10000);price(b,'friction',0,2);price(b,'restitution',0,1);for(const k of ['linearDamping','angularDamping'])price(b,k,0,100);price(b,'omega',-200,200);if(b.layer!==undefined)integer(b.layer,0,32);if(b.group!==undefined){small(b.group);if(Buffer.byteLength(String(b.group))>64)throw Error('Group exceeds 64 UTF-8 bytes');}if(b.label!==undefined){small(b.label);if(Buffer.byteLength(String(b.label))>64)throw Error('Part label exceeds 64 UTF-8 bytes');}if(b.colour!==undefined&&(typeof b.colour!=='string'||!/^#[a-fA-F0-9]{6}$/.test(b.colour)))throw Error('Colour must be a six-digit hex value');}
 const joints=unique(listing(p.joints??[],64),['id','kind','a','b','anchorX','anchorY','axisX','axisY','restLength','stiffness','damping','ratio','min','max']);
 for(const j of joints){if(!['hinge','slider','spring','rod','fixed','gear','belt'].includes(String(j.kind)))throw Error('Unsupported mechanical joint');if(!ids.has(sku(j.a))||!ids.has(sku(j.b))||j.a===j.b)throw Error('Joint must connect two existing bodies');for(const k of ['anchorX','anchorY','axisX','axisY','min','max'])price(j,k,-100,100);price(j,'restLength',.001,100);price(j,'stiffness',0,10000);price(j,'damping',0,10000);if(j.ratio!==undefined){const ratio=finiteInvoice(j.ratio,-20,20);if(Math.abs(ratio)<.01)throw Error('Joint ratio is too small');}if(j.kind==='slider'&&Number(j.axisX??1)**2+Number(j.axisY??0)**2<=1e-10)throw Error('Slider axis must be nonzero');if(Number(j.min??-10)>Number(j.max??10))throw Error('Joint interval is reversed');}
 const motors=unique(listing(p.motors??[],8),['id','body','targetSpeed','maxTorque','enabled']);const motorIds=new Set(motors.map(m=>String(m.id)));for(const m of motors){if(!ids.has(sku(m.body)))throw Error('Motor body does not exist');if(bodies.find(b=>b.id===m.body)?.mode==='fixed')throw Error('Motor body must be dynamic');price(m,'targetSpeed',-100,100);price(m,'maxTorque',.001,10000);if(m.enabled!==undefined&&typeof m.enabled!=='boolean')throw Error('Motor enabled must be boolean');}
 const controls=unique(listing(p.controls??[],16),['id','kind','body','target','threshold','action','motor','maxFirings','inputs','logic']);const packets=new Set<string>();
 for(const c of controls){
  if(!['timer','contact','distance','count','logic'].includes(String(c.kind))||!['start','stop','reverse','signal'].includes(String(c.action)))throw Error('Unsupported control');
  if(c.action!=='signal'&&!motorIds.has(sku(c.motor)))throw Error('Controlled motor does not exist');
  if(c.action==='signal'&&c.motor!==undefined&&c.motor!==''&&!motorIds.has(sku(c.motor)))throw Error('Signal motor reference does not exist');
  if(['contact','distance','count'].includes(String(c.kind))&&!c.body)throw Error('Control body required');if(['contact','distance'].includes(String(c.kind))&&!c.target)throw Error('Control target required');
  if(c.body!==undefined&&c.body!==''&&!ids.has(sku(c.body)))throw Error('Control body does not exist');if(c.target!==undefined&&c.target!==''&&!ids.has(sku(c.target)))throw Error('Control target does not exist');
  const inputs=listing(c.inputs??[],4);if(new Set(inputs).size!==inputs.length||inputs.some(v=>!packets.has(sku(v))))throw Error('Control inputs must reference earlier distinct controls');
  if(c.logic!==undefined&&!['all','any','not'].includes(String(c.logic)))throw Error('Unsupported logical condition');if(c.kind==='logic'&&(inputs.length<1||(c.logic==='not'&&inputs.length!==1)))throw Error('Logical gate input count');
  if(c.kind!=='logic'&&(inputs.length>0||(c.logic!==undefined&&c.logic!=='all')))throw Error('Only logical controls accept input signals');
  price(c,'threshold',0,10000);if(c.maxFirings!==undefined)integer(c.maxFirings,1,32);packets.add(String(c.id));
 }
 return p;
}
function challengeStock(value:unknown,world:Record<string,unknown>){
 const c=objectInvoice(value);keysInvoice(c,['id','kind','body','targetX','targetY','tolerance','minTime','targets','maxParts']);sku(c.id);if(!['delivery','steady','routing','crossing'].includes(String(c.kind)))throw Error('Unsupported challenge');
 const bodies=world.bodies as Record<string,unknown>[];if(!bodies.some(b=>b.id===sku(c.body)))throw Error('Challenge body missing');price(c,'targetX',-100,100);price(c,'targetY',-100,100);price(c,'tolerance',.001,50);price(c,'minTime',0,20);
 const targets=listing(c.targets??[],8),seen=new Set<string>();for(const value of targets){const target=objectInvoice(value);keysInvoice(target,['body','targetX','targetY','tolerance']);const id=sku(target.body);if(seen.has(id)||!bodies.some(b=>b.id===id&&b.mode!=='fixed'))throw Error('Challenge target body must be an existing distinct dynamic body');seen.add(id);finiteInvoice(target.targetX,-100,100);finiteInvoice(target.targetY,-100,100);finiteInvoice(target.tolerance,.001,50);}
 if(c.kind==='routing'&&(targets.length<2||!seen.has(String(c.body))))throw Error('Routing challenge requires distinct destinations including its primary body');if(c.kind!=='routing'&&targets.length>0)throw Error('Only routing challenges accept destinations');
 if(c.maxParts!==undefined)integer(c.maxParts,0,64);if(c.kind==='crossing'){integer(c.maxParts,1,64);const body=bodies.find(b=>b.id===c.body);if(body?.mode==='fixed'||Number(body?.x??0)>=Number(c.targetX??0)-Number(c.tolerance??.25))throw Error('Crossing challenge must start behind the destination');}else if(Number(c.maxParts??0)!==0)throw Error('Part budgets require a crossing challenge');
 if(c.kind==='steady'&&!(world.motors as Record<string,unknown>[]|undefined)?.some(m=>m.body===c.body))throw Error('Steady challenge requires a drive');return c;
}
export function validateWorkshopRequest(value:unknown){const p=objectInvoice(value);boxed(p);keysInvoice(p,['schema','op','world','challenge','scan']);if(p.schema!=='ocv.workshop-run/1'||!['simulate','scan'].includes(String(p.op)))throw Error('Unsupported workshop request');const world=worldStock(p.world);if(p.challenge!==undefined)challengeStock(p.challenge,world);if(p.op==='scan'){const s=objectInvoice(p.scan);keysInvoice(s,['parameter','targetId','values','trials']);if(!['motorSpeed','gravityY','restitution'].includes(String(s.parameter)))throw Error('Unsupported scan parameter');const values=listing(s.values,9);if(!values.length)throw Error('Scan values required');const limits=s.parameter==='restitution'?[0,1]:[-100,100];values.forEach(v=>finiteInvoice(v,limits[0],limits[1]));integer(s.trials??1,1,3);if(s.parameter!=='gravityY'){const candidates=s.parameter==='motorSpeed'?world.motors:world.bodies;if(!(candidates as Record<string,unknown>[]|undefined)?.some(b=>b.id===sku(s.targetId)))throw Error('Scan target missing');}else if(s.targetId!==undefined&&s.targetId!=='')sku(s.targetId);}else if(p.scan!==undefined)throw Error('Scan parameters require a scan operation');if(Buffer.byteLength(canonicalInvoice(p))>131072)throw Error('Workshop request exceeds 128 KiB');return p;}
export function validateWorkshopProject(value:unknown){const p=objectInvoice(value);boxed(p);keysInvoice(p,['schema','name','world','appearance','challenge']);if(p.schema!=='ocv.workshop-project/1')throw Error('Unsupported workshop project');const name=small(p.name,80).trim();if(!name)throw Error('Project name required');worldStock(p.world);if(p.challenge!==undefined)challengeStock(p.challenge,objectInvoice(p.world));if(p.appearance!==undefined){const a=objectInvoice(p.appearance);keysInvoice(a,['depth','material','background','wireframe']);price(a,'depth',.01,5);if(a.material!==undefined&&!['alloy','polymer','glass'].includes(String(a.material)))throw Error('Invalid material');if(a.background!==undefined&&!['white','sky'].includes(String(a.background)))throw Error('Invalid background');if(a.wireframe!==undefined&&typeof a.wireframe!=='boolean')throw Error('Wireframe must be boolean');}const text=canonicalInvoice({...p,name});if(Buffer.byteLength(text)>131072)throw Error('Workshop project exceeds 128 KiB');return{name,text,digest:hashInvoice(text),project:JSON.parse(text)};}
